### ISSUE TITLE
<attRef> needs better documentation

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1196]
As pointed out during the thread starting here on TEI-L:

http://listserv.brown.edu/archives/cgi-bin/wa?A2=ind1306&L=TEI-L&F=&S=&P=86274

the `<attRef>` element is never mentioned in chapter 22. There are also only two examples for it, which are identical. The use-case discussed in the thread might provide possible examples.

Original comment by: @martindholmes

**Comment by martindholmes** [comment]
Added a new section to chapter 22 in commit dfd756e. It's at the end of 22.2. Council can examine and edit/approve/reject at the FtF.

**Comment by martindholmes** [comment]
Council 2015-10-28: Replace @source example because it now makes no sense with global @source. If/when there is prose about the namespace/anyXML issue, point to it. 

Change "many elements many need to be deleted" to "many attributes may need to be deleted."

Investigate whether @include and @exclude attribute on attribute classes work, and if so, recommend that approach instead. If it doesn't work, raise a ticket to make it work on the Stylesheets.

**Comment by martindholmes** [comment]
Fixed the prose in 2ca8a5f..760b022. Thing about include/exclude remains to be done.

**Comment by martindholmes** [comment]
Dropped the ball on this; will pick up now. Apologies.

**Comment by martindholmes** [comment]
I confirm that `classRef/@include` and `classRef/@except` are working in schema generation.

**Comment by sydb** [comment]
Yay! Thank you, Martin. So now this is a documentation issue.

**Comment by martindholmes** [comment]
I confirm that `<attRef>` is also working as intended.

**Comment by martindholmes** [comment]
Added new prose and examples in TD chapter, TD.html#TDbuild, and fixed a couple of moduleRef key="teiheader" (should be "header") instances in there too. Will leave the ticket open until the build has gone through and Council have checked my additions.

**Comment by ebeshero** [comment]
TEI Councillors:
I’m in Krakow a few days early for the DH 2016 conference and I’m working at the Jagiellonian Library, where I’ve secured myself a library card (not really necessary, but it provides me an alternative internet access to eduroam and to the conference wifi). I have just inquired about whether we can arrange for a room to hold a special teleconference meeting for Council while a bunch of us are here, and the very helpful librarian (who speaks good English) tells me a) she is not optimistic about being able to organize such a thing on such short notice, but b) that she will try to do what she can.

I do have edu-roam working (and can test the special library access tomorrow when it kicks on)—internet seems good and strong on campus, and the only thing I think we need to figure out is where on campus we might work. I think I’ll write the conference organizers to inquire if they have any suggestions for us at this late moment. We’ll figure something out—but I do think that campus is probably the best internet access for us, rather than hotel wifi, etc. 

Speaking of which, for those of you who are arriving soon to Krakow, feel free to ping me by e-mail (or text my phone at +1 724-732-5279) when you arrive. I’m staying pretty close to campus in a little rented apartment in a historic building—(probably too small for us as a meeting space and no lobby downstairs to work in, though there *are* giant landings on the old staircase). My address is Józefa Piłsudskiego 6, 33-332 Kraków, Poland. Here’s a Google map of it: you’ll see the starred pin labelled “Józefa Piłsudskiego 6”—that’s me:
 https://goo.gl/maps/xNGj18YbWUR2 <https://goo.gl/maps/xNGj18YbWUR2>

I’m actually not playing tourist very much yet because I'm working on a book chapter draft due today/tomorrow-ish and my presentation(s) in two things that happen just ahead of the conference on Monday and Tuesday. (That’s why I’m haunting the library.) Maybe we should aim for our Krakow meeting sometime between Tues. evening and Fri. evening next week? 

Best, 
Elisa
-- 
Elisa Beshero-Bondar, PhD
Director, Center for the Digital Text | Associate Professor of English
University of Pittsburgh at Greensburg | Humanities Division
150 Finoli Drive
Greensburg, PA  15601  USA
E-mail: ebb8@pitt.edu <mailto:ebb8@pitt.edu>
Development site: http://newtfire.org <http://newtfire.org/>

**Comment by lb42** [comment]
Checked new material from MH; will review in the context of #1082, so closing for now
