### ISSUE TITLE
"TEI-conformable" is meaningless

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1243]
This previous bug:

http://sourceforge.net/p/tei/bugs/582/

dealt with some inconsistencies in usage and formatting of "TEI-conformant" and "TEI-conformable", but it did not address the elephant in the room: "TEI-conformable", as it is defined, is meaningless:

"A document is said to be TEI Conformable if it is a well-formed XML document which can be transformed algorithmically and automatically into a TEI Conformant document as defined above without loss of information."

This applies to any XML document. Even extreme cases of documents containing no TEI-like information at all, any information can be represented using e.g. feature structures. I suggest we remove this phrase from the Guidelines, and thus substantially simplify the USE chapter.

Original comment by: @martindholmes

**Comment by lb42** [comment]
"TEI conformable" extirpated passim et seriatim.

**Comment by bansp** [comment]
Thanks :-)

**Comment by sydb** [comment]
I would just like to register my objection. I may eventually be convinced otherwise, but I think Martin was simply incorrect in the original classification of “conformable” as “meaningless”. It is not, it is quite useful. 
Take, e.g., an input document that does not record sufficient metadata for a minimal TEI header. It cannot be conformable. And although most any XML document could be transformed into a TEI feature structure, that does not mean that the resulting document is a TEI document. (In order to be a TEI document it not only has to be a valid TEI feature structure, but it must also meet the TEI abstract model — which, IIRC, includes the concept that features for which an encoding is available in TEI are encoded using the TEI encoding, not a generic feature structure.)
One can easily come across an HTML document which is not conformable because two different TEI concepts (say, verse and an inscription) are encoded exactly alike. The ambiguity means the HTML document is not conformable. (Because translation to TEI would require human intervention to resolve the ambiguity.) [Note that this is not entirely true — one could encode both an <lg> and a <quote> that each had an @exclude that pointed to the other ... hmmm ... does *anyone* even know anyone who uses the @exclude attribute?]

**Comment by PFSchaffner** [comment]
My feeling all along was that the notion of 'conformable' was not only useful but one that we implicitly resorted to constantly, especially in creating interim coding/capture stages, or in dealing with legacy data or data which we were not responsible for creating. But also that it was a notion so hard -- perhaps impossible -- to define precisely that it was not tenable as part of the guidelines. Even if one arrived at a precise definition, that definition would probably be unacceptably narrow. For in actual use, conformable describes a comfort zone that reflects not only the technical feasability but the elegance possible in doing so and our skills at achieving it.  You could say that it means 'conformity to the abstract model' if you like, but what you reallly mean might be 'encoded according to a sensibility that is recognizably within the spirit of TEI and can therefore be expressed in conformant TEI.' Or even, 'this is something that I can imagine myself converting to conformant P5 without divine intervention.'

**Comment by hcayless** [comment]
@sydb: I use `@exclude` all the time :-). It's very useful for encoding transpositions in an apparatus, where different sources disagree on where (e.g.) a line is to be located. The different possibilities are mutually exclusive.

I agree with @PFSchaffner. "Conformable" as written has an oddly restrictive definition, and I don't think it's useful at all. "Can I turn this thing into a proper TEI document?" is a useful question, but not one I think we need to be too bothered with in the Guidelines, because it's arbitrarily complex. And who really cares if I have to side-load some metadata in order to generate a TEI header from some input document? Is a solution that stores its metadata separately from its text but which can combine them to produce a TEI output not ipso facto conformable?

It's not a useless *idea*: the question of the compatibility of other formats with TEI, or of TEI-based formats that have been extended (or cut down) to the point that they can't be called TEI anymore is a valid one. But I don't think what we have addresses that question adequately. It just muddies the waters, which are already muddy enough.

**Comment by martindholmes** [comment]
Hi Syd. Your example of a document without enough information to create a conformant TEI document doesn't work for me. This is a conformant TEI document, and it has no info in it at all, surely:

~~~~~
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml"
	schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
      <fileDesc>
         <titleStmt>
            <title>Title</title>
         </titleStmt>
         <publicationStmt>
            <p>Publication Information</p>
         </publicationStmt>
         <sourceDesc>
            <p>Information about the source</p>
         </sourceDesc>
      </fileDesc>
  </teiHeader>
  <text>
      <body>
         <p>Some text here.</p>
      </body>
  </text>
</TEI>
~~~~~

And we do use the @exclude attribute in real life; we use it to provide two distinct interpretations of a historical date when we cannot tell whether the original author was using a calendar in which the first day of the year was January 1 or March 25:

~~~~~
<birth when-custom="1491" datingMethod="#julian"><date xml:id="d38803e608_julianJan" exclude="d38803e608_julianMar" notBefore="1491-01-10" notAfter="1492-01-09"/><date xml:id="d38803e608_julianMar" exclude="d38803e608_julianJan" notBefore="1491-04-03" notAfter="1492-04-02"/></birth>
~~~~~

Cheers,
Martin

**Comment by sydb** [comment]
@martindholmes : Well, I'm quite glad to see that you (and @hcayless) have a real use case for `@exclude`. (But those attrs are missing the initial sharp sign. :-)  But more importantly, while the document you posted ~5 hours ago indeed has no information, and indeed is valid against a TEI schema, it is *not* a TEI-conformant document. The element `<publicationStmt>` does not contain a publication statement, and the element `<sourceDesc>` does not contain a source description. These bits of information are not optional: they are required by the TEI abstract model. (Just as an `<l>` cannot be used for a typographic line, a `<sourceDesc>` cannot be used to hold an epigraph or even a placeholder for a source description.)
But even though I am unconvinced that “conformable” is *meaningless*, @hcayless brings up a valid point: it may not be all that *useful*. But I’m not sure I’m in a position to say. The idea was to have a mechanism to say (e.g., to your funding agency) “while these files are not actually TEI-conformant as they sit now, we could easily make them so *without loss of information*”. My guess is that is still a useful thing to be able to say.

**Comment by martindholmes** [comment]
@sydb: Yep, we were missing hashes there -- fixed in the XSLT now. But I think the broader point is this: "conformable" would be useful if it were definable, but it's not. How on earth do you judge whether the information I have can be turned into a valid sourceDesc or not? What constitutes a satisfactory publication statement? Presumably I can create a TEI file in which I choose not to designate any person or organization as publisher, and for which I elect not to apply a licence or claim any kind of copyright; there's nothing wrong with that. Lots of born-digital TEI files have no source; how do you judge (other than completely subjectively) whether the absence of anything that looks to you like a source description is a violation of conformability or a reasonable representation of the truth? What if I write XSLT that converts the absence of any source information into this:

~~~~~
<sourceDesc>
  <p>No source information is known for this document.</p>
</sourceDesc>
~~~~~

Have I conformed it? I certainly made it TEI without loss of information.

**Comment by PFSchaffner** [comment]
Is a plain old TEI P3 document conformable to P5? Largely yes. But what about those multi-value @lang attributes? Is there any reasonable place to put that information, short of feature structures, in a P5 instance? Is an ordinary MARC record conformable to a TEI header? Well, maybe, but only by storing lots of binary coded data in an uncomfortable form in the header: there is no easy 1:1 match of granularity or field. Converting any bibliographic record form, in fact, poses difficulties of mismatched concepts (as I learned once by trying to capture a thousand idiosyncratic bibliographies to a single format.) Each such question involves so many hedges and qualifications and acceptable sacrifices that 'conformable' ceases to be a single thing. And the lack of a defined 'conformability' standard in the guidelines should not stand in your way when arguing that your use of some other data format to store information (e.g., in our case, MARC) has virtues of its own, and is not inconsistent with a TEI-conformant derivative, either a lossless one or a one with certain specified but acceptable losses of information.
