### ISSUE TITLE
TEILIte example shows cit/quote, but quote is not allowed

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1266]
The TEILite documentation for `<cit>`:

http://www.tei-c.org/release/doc/tei-p5-exemplars/html/tei_lite.doc.html#cit

includes an example showing `<quote>` as a child of `<cit>`, but `<quote>` is apparently not available in TEILite. This should be changed to `<q>` instead.

Original comment by: @martindholmes

**Comment by lb42** [comment]
I changed a couple of the examples in ``&lt;cit>`` to use q rather than quote. I fear however that there must be plenty of other cases where an example in the Lite documentation uses elements not defined by Lite. Finding and fixing them all at this late stage seems a waste of effort, so I am closing this ticket.
