### ISSUE TITLE
TEILite has @calendar, but no `<calendar>` element it can point to

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1267]
`@calendar` in TEILite is a pointer, but it's not clear what it could be pointing to, because the `<calendar>` element is absent from TEILite. There should at least be some guidance on how to use the attribute if it is retained; otherwise it should be removed. 

Original comment by: @martindholmes

**Comment by lb42** [comment]
Have removed @calendar from ODD for TEI Lite. Presumably the next buuild will regenerate schema files accordingly.

**Comment by martindholmes** [comment]
This does not seem to have worked; @calendar is still there in 3.0.0:

http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_lite.rng

**Comment by lb42** [comment]
This is very mysterious. The change was definitely made on 25 oct commit 020aa6b as it says above. I can't find any subsequent commit that overwrote it. But the 3.0.0. release version of the file doesn't have the change in it. So something is presumably going wrong during the build.  Anyway, I've now committed the change again (2938aa6) ...

**Comment by lb42** [comment]
The problem seems to be in the process that updates the website when we make a new release. The repo is up to date, but the data at http://www.tei-c.org/release/xml/tei/custom/ does not reflect it. I suspect that the release procedure doesnt even regenerate new schemas, since (for example) there is no copy of tei_odds.rnc here.

**Comment by lb42** [comment]
This is clearly something in the release process not working as expected. I've checked that if I generate a schema from the current ODD source, the @calendar attribute is not present. Since we don't keep schema files in the Exemplars/ directory in the repo, I assume they must be generated on release. Someone who knows more than I do about the release process needs to follow this up.

**Comment by hcayless** [comment]
Looks like this was accidentally stomped on in the switchover to the dev branch 4e7a718522387b642b27081b7504e32c8e6121db. Closing.
