### ISSUE TITLE
sequence of declaration info is lost when making an ODD

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1276]
Consider model.physDescPart_sequenceOptional. In TEI_All, this has the declaration  
  objectDesc?,
  handDesc?,
  typeDesc?,
  scriptDesc?,
  musicNotation?,
  decoDesc?,
  additions?,
  bindingDesc?,
  sealDesc?,
  accMat?

i.e., the members of the class are listed in a specific order, which is that of their declaration in P5. 

Now see what happens when you delete some of them from your ODD (whether by not prouiding an &lt;elementRef> for them, by using `@exclude`, or by using `@include`)

The declaration for that same pattern in your generated schema now reorders them alphabetically, like this:

model.physDescPart_sequenceOptional =
  accMat?,
  additions?,
  bindingDesc?,
  decoDesc?,
  handDesc?,
  objectDesc?,
  typeDesc?

so a document which is ualid against TEI-ALL will not be ualid against your generated schema.

This cannot be right, but I am not sure what should be done to fix it.

Original comment by: @lb42

**Comment by lb42** [comment]
There doesn't seem to be any right solution to this, other than to improve the documentation for oddbyexample We should probably add a warning against using just elementRefs (rather than moduleRefs with @include or @exclude) if we think this is a serious problem. From memory there are only about two elements in which the order of child elements is significant, so it's a pretty recondite issue all round.

**Comment by lb42** [comment]
Council agrees.
