### ISSUE TITLE
part of the "Title" clipped by Roma, in a somewhat sneaky fashion

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1295]
When I input the following into the "Title" window in the "Customize" tab in Roma:

TEI Lite customization for Twardowski's "O czynnościach i wytworach"

and press "save", the part enclosed in quotes vanishes, so the saved XML only contains

~~~~~

<title>TEI Lite customization for Twardowski's </title>

~~~~~

However, one can be easily mislead into thinking that everything is good (like when you have filled the "Description" window, and you click on "Save" and move on the e.g. the "Modules" or "Save.." tabs), because the full string is still displayed in the upper right corner, This is illustrated by the attached screenshot.

Original comment by: @bansp

**Comment by martindholmes** [comment]
After some confusion figuring out where Roma actually is on tei-c (there are lots of copies), I've deployed the new version and asked Ian to give us a symlink at http://www.tei-c.org/Roma-4.18/ so that we can test it out. If it tests OK, we can change the existing symlink to make it live. Then we can adopt and document a standard approach to updating Roma on the server.

**Comment by martindholmes** [comment]
Council confirms this is the way to proceed, and suggests moving this bug to the TEIC/Roma repo.

**Comment by peterstadler** [comment]
Already closed per https://github.com/TEIC/Roma/issues/8
