### ISSUE TITLE
<app> is phrase-level

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1322]
&lt;app> is considered a phrase-level element, which is just plain WRONG and makes no sense whatsoever. &lt;app> should be allowed to be at the very least paragraph-level. In fact, to reflect reality, &lt;app> should have the same content model as &lt;div>s, i.e. allowed to contain several paragraphs, or even divisions. 
There are enough problems with the encoding of critical editions without shooting ourselves in the foot with this nonsensical, self-imposed constraint of the content model of &lt;app>. This has been a plague to critical editors engaging with TEI for ages. I really couldn't care less if abolishing this constraint would make the processing of digital editions trickier. As it is, it makes the encoding of critical editions absurd, which is definitely a bigger problem for the TEI. 
Please have mercy on editors and do something! 

Original comment by: mburghart

**Comment by hcayless** [comment]
Fixed in c39236ff46d54725bb5cac51e125c56db366bb7b.

**Comment by ebeshero** [comment]
@hcayless

**Comment by jamescummings** [comment]
Have you updated your version of the TEI framework in oxygen?

**Comment by ebeshero** [comment]
Aha! That takes care of the problem--thank you, @jamescummings (and thanks for the clear and current instructions on that posted http://blogs.it.ox.ac.uk/jamesc/2014/04/02/auto-update-your-tei-framework-in-oxygen/ )

**Comment by jamescummings** [comment]
Those instructions are a bit dated, but the general idea is the same.

**Comment by ebeshero** [comment]
THey're from 2014, but they work. My 17.1 installation of oXygen lacked the relevant update line from our TEI at Sourceforge, so that's the part that counts for me! 

I notice though, that an `<lg>` must still contain an `<l>` child as a sibling of `<app>` (and similarly the `<body>` element expects at least one `<lg>` in the presence of a child `<app>`. I can imagine a scenario in which an entire poem is encoded in `<app>` elements showing alternate versions of lines, so I'm wondering why we still mandate the sibling relationship of `<app>` to `<l>` and `<lg>` ?

**Comment by hcayless** [comment]
@ebeshero This doesn't really have anything to do with `<app>` per se, but it is related to #1419. The content model of `<lg>` needs some re-thinking I believe. I'm going to close this again and reference it over there.
