### ISSUE TITLE
Specification for @match in att.scoping is confusing

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1330]
The definition of `@match` in att.scoping says this:

>supplies an arbitrary XPath expression using the syntax defined in Kay (ed.) (2007) which identifies a set of nodes, selected within the context identified by the target attribute if this is supplied, or within the context of the element bearing this attribute if it is not.

whereas the remark at the bottom says this:

>The expression of certainty applies to the nodeset identified by the value of the target attribute, possibly modified additionally by the value of the match attribute. If neither attribute is present, the expression of certainty applies to the context of the certainty element itself, i.e. its parent element.

The one seems to mean that `<certainty>` (for instance) is the default XPath context, while the other means that `<certainty>`'s parent is the default context. But in fact it's more subtly confusing than that; the one refers to the `@match` attribute, while the other refers to the expression of uncertainty itself. This is such a potential source of error that I think it needs to be reviewed, and it should also be illustrated with more examples. Finally, I think we should strongly suggest that `@target` be used, to avoid this concern.

Original comment by: @martindholmes

**Comment by hcayless** [comment]
The wording is confusing, but I think the intent is clear: if `@match` and `@target` are not supplied, then `<certainty/>` (e.g.) applies to its parent element. I suggest we just say that.

**Comment by martindholmes** [comment]
Don't we also have to specify what the XPath in @match is relative to if it appears? Is it relative to itself (child of certainty), to its parent certainty, or to the parent element of certainty?

**Comment by hcayless** [comment]
It’s relative to the element bearing the @match. If there is no match, then the default behavior is to assume @match=".." (i.e. the parent of the element bearing the @match).

**Comment by frederik-elwert** [comment]
I am afraid currently the guidelines contradict themselves. Especially, the [prose text](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CE.html) and the examples contained therein are not in line with the definition in att.scoping.

Examples in the prose text:

    <div>
     <certainty locus="name" degree="0.3"
      match=".//persName"/>
    </div>

or

    <u who="#A">Have you heard the election results?<certainty
      match="@who" locus="value"
      degree="0.5"/>
    </u>

Versus example in the definition:

    <gap reason="cancelled">
     <certainty match="parent::gap/@reason"
      locus="value" cert="low"/>
    </gap>

There are four possible cases, three of which are quite clear I think:

1. Both `@target` and `@match` are given. Then `@target` selects an element, and the XPath expression in `@match` is evaluated in the context of that element.
2. Neither are given. Then the `<certainty>` element refers to its parent.
3. Only `@target` is given. Then the `<certainty>` element refers to the selected element.
4. Only `@match` is given. This case is problematic, since there are two interpretations: The prose text of the guidelines assumes that then the XPath expression is evaluated in the context of the *parent* of `<certainty>`, while the definition in att.scoping states that it is evaluated in the context of `<certainty>` itself.

I think that it is necessary to align the prose text and the definition. I will make an argument why I think the prose text is correct and the definition should be updated:

If neither `@target` nor `@match` are given, `<certainty>` refers to its parent. This could be interpreted as `@match=".."`. But if we assume that `@match` has an implicit default value of "..", then this can only be true of `@target` is empty, otherwise we would implicitly select the parent of any element selected via `@target`. To me, the idea that the default value of `@match` changes from "`..`" to "`.`" when `@target` is not empty seems counter-intuitive.

However, the fact that `<certainty>` refers to its parent when both `@target` and `@match` are absent could also be interpreted as `@target` having a default value of the parent element, i.e. "`#xpath(..)`". Then, the default value for `@match` would always be "`.`". When `@target` is given, `@match` is evaluated in the context of the selected element, when `@target` is absent, `@match` is evaluated in the context of the parent element.

In this interpretation, the examples in the prose text of the guidelines would be correct, while the definition would have to be updated. And to me, the examples in the text look much more natural than the `parent::*`-style examples in the definition.

**Comment by jamescummings** [comment]
The prose is correct for #4 but needs to be spelled out in reference pages. For all, if there is no target then it is in the context of the parent.

**Comment by sydb** [comment]
So we need a table, it seems, to concisely express F-E's 4 cases, which Council sub-group agrees is a correct analysis. We also need to fix #4, and the consensus seems to be that for case #4 the context should be parent::*.

**Comment by hcayless** [comment]
Reassigned to Martina. The to-do, as I see it, is to check through the members of att.scoping and make sure examples where there is a `@match` but no `@target` assume that the XPath in `@match` is starting from the parent. Consider adding notes to at least `<certainty>` and `<precision>` that make it clear what `@match` without a `@target` means.

**Comment by martinascholger** [comment]
(1) Is there an agreement that the spec for @match should be rephrased:

"[...] or within the context of the element bearing this attribute if it is not."

to 

"[...] or within the context of the parent element if it is not."

and correct the examples like this:  

```
<gap reason="cancelled">
 <certainty match="parent::gap/@reason"
  locus="value" cert="low"/>
</gap>
```

to

```
<gap reason="cancelled">
 <certainty match="@reason"
  locus="value" cert="low"/>
</gap>
```

(2) For the att.scoping spec, I would summarize the notes of @target and @match in one note, like this:

The expression of certainty applies to the nodeset identified by the value of the @target attribute, possibly modified additionally by the value of the @match attribute. If more than one identifier is given, the implication is that all elements (or nodesets) are intended. The @match attribute may also be used as a means of identifying groups of elements. 

-  If @target and @match are present, @target selects an element and the XPath expression in @match is evaluated in the context of that element. 
- If neither attribute is present, the expression applies to its parent element.
- If only @target is given, the expression refers to the selected element or nodeset.
- If only @match is given, the XPath expression is evaluated in the context of the parent element of the bearing element.  

Note that the value of the @target attribute may include an XPointer expression including an XPath expression (see 16.2.4 TEI XPointer Schemes).

(3) do we need to spell out the same description in the spec for `<precision>` and `<certainty>` as well? 

(4) the definition of att.scoping says "att.scoping provides attributes for selecting particular 
 elements within a document by means of XPath." Since @target contains a data pointer, should this be rephrased more generally? "[...] provides attributes for selecting particular elements within a document".

**Comment by jamescummings** [comment]
1) Agreed
2) Agreed
3) I don't think it necessarily needs changes of description on those, but ensure nothing in those specs conflicts with the above.  They get these attributes via the att.scoping class so the note really belongs there.  Also, of course, check their examples.
4) Agreed.

**Comment by martinascholger** [comment]
I wonder if it makes sense to put the note (see 2) as a separate row in the att.scoping table, since it applies to all the possible attributes of this element. However, it would essentially not be a note about the att.scoping itself, but it's attributes. If I just put the note below match in the attibutes cell, at first glance, it looks at if it only applies to that attribute. Any recommandations on this?

**Comment by martinascholger** [comment]
implemented as outlined above
