### ISSUE TITLE
French Header chapter needs significant updating

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1341]
The French HD chapter was lacking the link to p5.nvdl, and therefore validity problems were not showing up. When I added the schema link, it revealed that the chapter is badly in need of work; it's still full of entity references instead of XIncludes. Since the structure of the English version may have changed a bit, someone will have to painstakingly work through the two and align the French one, pulling in the relevant bits.

Original comment by: @martindholmes

**Comment by stefaniegehrke** [comment]
The French HD chapter is not used for building the french version of the guidelines (only the spec files are used).

**Comment by martindholmes** [comment]
Options are:
1. Accept that this translation of the prose will never be completed, mark it obsolete and move on.
2. Accept that it's not likely to be completed, but for reasons of hygiene, fix the validity issues.
3. Try to get the translation finished and updated.

**Comment by stefaniegehrke** [comment]
LB agrees to make it valid

**Comment by sydb** [comment]
At Council face-to-face in Lyon it was asserted that we can no longer build the Guidelines using non-English (i.e., French) versions of the chapters. I volunteered to check into whether or not there was a trivial fix for this.

The pre-ANT build process used a DOCUMENTATIONLANGUAGE variable to do this work. The (relatively) new ANT-based build process ignores this variable. If I tweak the antbuildweb.xml file manually (using "fr" instead of each of the 4 occurrences of "@{long}" what gets generated is (correctly) in the output fr/ directory and (correctly) uses French glosses and descriptions, but still doesn't get the French chapter HD, and has no CSS.

So my conclusion is while there may be a fix for this, it is at least non-trivial, if not hard.

**Comment by lb42** [comment]
Have made a start by converting entity refs to xincludes. lots of work remains however.

**Comment by jamescummings** [comment]
As @lb42 notes, lots of work remains, the file is currently valid against TEI. There is a question of whether we should update all the prose since it is also so out of date. How important or valuable will this be given we currently do not release this chapter and it is the only chapter translation we have.

**Comment by sydb** [comment]
Council decides to make GREEN for @lb42 to finish making valid (almost there!), but after that to close ticket with no further work. Should more translation cycles become available, we will gladly accept them and work on incorporation.

**Comment by lb42** [comment]
File is now valid.
