### ISSUE TITLE
problem with the description of att.global.facs

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1362]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Specs/att.global.facs.xml#L12

<quote>
groups elements corresponding with all or part of an image, because they contain an
    alternative representation of it, typically but not necessarily a transcription of it.
</quote>

This is just wrong, I think, since the function of an attribute class isn't to group elements but to provide sets of attributes: Compare the wording of any of the other att.global classes. (By the way, since @ana is the only member of att.global.analytic, its definition should probably say "provides the @ana attribute for associating specific analyses or interpretations with appropriate portions of a text" rather than "provides additional global attributes for associating specific analyses or interpretations with appropriate portions of a text.") That should maybe be another ticket, I know.

**Comment by lb42** [comment]
There are in fact six attribute classes which use the formulation "groups elements which.,.." rather than "provides attributes which..." ; clearly consistency would be desirable

**Comment by raffazizzi** [comment]
> the function of an attribute class isn't to group elements but to provide sets of attributes

This is very true, so I'd support a rewording across the board.

**Comment by lb42** [comment]
There are in fact rather more than six classes which don't say "provides attributes ..." though only six say anything about grouping elements. I propose to revise the &lt;desc>s for the following so that all use the same formula.
att.fragmentable, att.pointing, att.pointing.group, att.readFrom, att.styleDef, att.enjamb, att.entryLike, att.lexicographic, att.global.facs, att.coordinated, att.rdgPart, att.textCritical, att.global.linking, att.global.analytic.

**Comment by peterstadler** [comment]
Hmm, I don't know whether it's that easy. Yes, there are no free-standing attributes so attribute classes technically provide those. But isn't a semantic grouping mechanism involved, as well?
I mean, we could (technically) provide all attributes via one class. We don't, because it's more clear (and makes customizing easier, etc) to group them accordingly.

**Comment by lb42** [comment]
I take your point but the argument here is just for consistency of wording. The majority of descs define attribute classes by what they do rather than by their semantics.

**Comment by lb42** [comment]
Reworded descs to consistently use "provides attributes/an attribute which..."
