### ISSUE TITLE
Problematic use of the word "change" in several places in PH-changes

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1392]
At 
https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L2808
https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L2814
and
https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L2821

~~~~~
<q>
 <item>a system to assign phenomena to a particular change</item>
            <item>a way to characterize a change, in itself and in relation to other changes.</item>
</q>
~~~~~
~~~~~
<q>
It may contain a
            <gi>listChange</gi> element which contains a number of <gi>change</gi> elements, one for
         each identified change:
</q>
~~~~~
~~~~~
<q>
In the following example an editor has identified four distinct changes:
</q>
~~~~~
In each of the quoted passages "change" seems to have been a substituted for what was "stage" in an earlier draft version. The problem is that whereas "stage" implies a grouping of individual phenomena "change" suggests an individual phenomenon itself. The definition of &lt;change> finesses this problem by using the phrase "a change or set of changes," a solution that I would adapt to each of the above instances.

Suggested revisions: 

~~~~~	
	<item>a system to assign phenomena to a particular change or set of changes</item>
            <item>a way to characterize a change or set of changes, in itself and in relation to other changes.</item>
~~~~~
~~~~~      
It may contain a
            <gi>listChange</gi> element which contains a number of <gi>change</gi> elements, one for
         each identified change or set of changes:  
      
In the following example an editor has identified four distinct sets of changes:
~~~~~

**Comment by lb42** [comment]
This element name was one of the most bitterly fought over in the entire history of the TEI. Let's not revisit that struggle. The element change is used to refer to an "identified change", which may in fact comprise several modifications (changes with a small c if you like). Your proposed rewording risks confusing that essential point, by allowing for groups of changes (are they groups of identified changes?)

**Comment by raffazizzi** [comment]
I agree with @lb42. A change may be made of several modifications. "Stage" certainly reflects the field's terminology better, but those different stages are the result of changes. Since TEI already has mechanisms to describe changes, it makes sense to conflate all into one system and reduce redundancy.

**Comment by lb42** [comment]
The problem with "stage" (and as I said, let's please not revisit that debate again) is that it doesn't reflect the point of view of those wishing to uncouple this notion from any kind of chronology. A stage is a step you go through on a defined path. That's a step too far for some. Or so I am told.

**Comment by hcayless** [comment]
It seems like we're leaning towards rejecting this. Any objections?

**Comment by brettttt** [comment]
I'm certainly not trying to revisit the debate over the name of the element. 

> Your proposed rewording risks confusing that essential point, by allowing for groups of changes (are they groups of identified changes?)

No, I'm trying to point out that the definition of &lt;gi&gt;change&lt;/gi&gt; **already** allows for groups of changes: "documents a change or set of changes made during the production of a source document, or during the revision of an electronic file." 

What I see as a problem is that "change" is a very common, seemingly transparent, non-specialized, garden-variety word to most native English speakers, and if we intend for it to have a special meaning in all the instances in which it occurs in PH-PrimarySources we need to signal that unambiguously. As it is, in a sentence such as "In the following example an editor has identified four distinct changes," wherein the word "change" isn't being used as an element name, how are readers to know that it's being used in this specialized way? After all, the word "change" occurs a great many times throughout the Guidelines outside chapter 11, and in almost none of those occurrences does it carry this special meaning. 

There are several places in PH-PrimarySources where the problem is smoothed over by glossing the word with less ambiguous synonyms, and I think those work fine. (I note, by the way, that "stages" is one of those synonyms, so it's not as though we've banished the term just because the element was named "change.") Examples: 

- "through three states or changes" 
- "A nested &lt;gi>listChange&lt;/gi> elements is also useful to indicate a <emph>partial</emph> ordering of revision campaigns" [sic]
- "In addition to the possibility of ordering text stages in relation to each other, &lt;gi>change&lt;/gi> elements may . . . ."

**Comment by lb42** [comment]
I apologise for misunderstanding the point you were trying to make: it's true that if we use "change" as a term of art, then we need to be careful to do so in a marked way.  I propose the following revisions:

1. For "An editor may wish to  assign a set of alterations (deletions, additions, substitutions, transpositions, etc.) or any other act of writing to a particular change, to indicate... "
I propose
"An editor may wish to  regard a particular set of alterations (deletions, additions, substitutions, transpositions, etc.) or  any other act of writing as a single object for which we use the general term "change", to indicate.... 

2. I think with this definition right at the start of the section, we remove the need for your revisions to the items in the list, but to make sure, I suggest the following:
~~~~
To document this we need: <list>
       <item>a system to assign phenomena to a particular 
                  <soCalled>change</soCalled> as defined above</item>
        <item>a way to characterize each such change, in itself and in relation to others.</item>
         </list></p>
~~~~

3. Similarly, for "It may contain a  &lt;gi>listChange&lt;'/gi> element which contains a number of &lt;gi>change&lt;/gi> elements, one for  each identified change:"

I propose :

"It may contain a  &lt;gi>listChange&lt;/gi> element which contains a number of &lt;gi>change&lt;/gi> elements, one for  each set of alterations identified"

and (likewise) "the editor has identified four distinct sets of alterations" rather than "the editor has identified four distinct sets of changes"

I've now made these changes, and a number of others aimed at avoiding the imprecision of the word "change".

See commit  44f29d1
