### ISSUE TITLE
Allow <expan> to be less than a complete word or phrase

### ISSUE THREAD

**Issue by adunning** [TEIC/TEI#1403]
The [guidelines for `<expan>`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-expan.html) indicate, 'The content of this element should usually be a complete word or phrase.' I would suggest that that this line be changed to 'This element should contain a complete abbreviation.'

[Many of the examples provided](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/examples-expan.html) do not follow this rule, and there are cases in which it is more meaningful to use `<expan>` to mark only what one considers to be the abbreviation. In premodern manuscripts, one needs to approach abbreviations on a modular level, since something like 'bꝫ' (bus) or '⁊' (et) can be combined with many different words, and one will find them as separate entries in a reference work such as Capelli.

Take this example, from Oxford, Bodleian Library, Bodley 860, fol. 96r:

![Oxford, Bodleian Library, Bodley 860, fol. 96r](https://cloud.githubusercontent.com/assets/1084407/11073121/0be23692-87b7-11e5-89c7-fa8c12a98a1c.jpeg)

What you’re seeing here is the word ‘ciuitatem’, but it started out as ‘circu-‘. The guidelines imply that this is to be encoded as:

```xml
<expan>c<subst><del rend="erased"><am>&#x365;</am><ex>ir</ex>c</del><add place="overstrike">i</add></subst>uitatem</expan>
```

But this would be better:

```xml
c<subst><del rend="erased"><expan><am>&#x365;</am><ex>ir</ex></expan>c</del><add place="overstrike">i</add></subst>uitatem
```

This is more helpful on a few levels:

1. The word is only abbreviated before correction.
2. If one were generating a database of abbreviations from this text, it's most helpful to understand that a superscript 'i' in this context can expand to 'ir'.
3. This is much easier to type, since one can set `.ir` as a text expansion to be used in any context and receive `<expan><am>&#x365;</am><ex>ir</ex></expan>` without having to play around with tags any further.

**Comment by hcayless** [comment]
I think this is pretty uncontroversial. Perhaps we should add a note to the effect that wrapping the whole word will make it easier for you to tabulate lists of abbreviations (if you care about that sort of thing).

**Comment by lb42** [comment]
i am unconvinced by this, sorry. If &lt;expan> contains an abbreviation, what is &lt;abbr> for? But certainly we should review the current uses of &lt;expan> in examples in the Guidelines : on a quick glance several should clearly now be using &lt;ex>

**Comment by hcayless** [comment]
Andrew's case is a complex one, but I don't think it's all that weird. `<expan>` here does contain an abbreviation plus its expansion. The difference is that, as Andrew rightly notes, it probably shouldn't contain the whole word in this case, as only the uncorrected version contains an abbreviation. 

I'm not sure about the suggested wording though. It doesn't work for the use of `<expan>` opposite `<abbr>` inside a `<choice>`. This is in an explanatory note, so maybe something like:

"The content of this element should be the expanded abbreviation, usually (but not always) a complete word or phrase."

Looking back through the guidance on abbreviations, I see that [EpiDoc style](http://www.stoa.org/epidoc/gl/latest/trans-abbrevfully.html) isn't really represented at all. I think it should be (because it's better), but that's probably another ticket. That whole section needs work.

**Comment by alavrentev** [comment]
I can add a use cas for having multiple <abbr> + <expan> within a word. In this fragment from Ms. Paris, Bnf, lat. 12943, f. 97
![compluribus](https://cloud.githubusercontent.com/assets/13948078/13645117/a2d8ecd2-e629-11e5-96c5-3a11b8b5ac53.jpg)
we have 3 independent abbreviations in the word-form "co(m)pl(ur)ib(us)". I am working on a palaeography project that needs to count the abbreviations and to provide a list of corresponding expansions. If we followed the recommendation of the Guidelines, we would have to introduce an extension element.
However, I agree that in many cases having one abbreviation/expansion tag for an entire word is practical (e.g. for tokenisation), so I like Hugh's re-wording proposal.

**Comment by lb42** [comment]
Why is three abbreviations rather than three abbreviation markers? If you expanded one of the abbreviated parts but not the other two, the word as a whole would still be an abbreviation, surely?

**Comment by alavrentev** [comment]
Because, in my opinion, abbreviation marker, abbreviation and abbreviated word are three distinct phenomena. For instance, in 
lanc̅. = Lanc(elot) ([Queste del saint Graal, col. 160a](http://txm.bfm-corpus.org/?command=edition&path=/GRAAL&textid=qgraal_cm&editions=diplomatique,fac-similaire&pageid=160a&wordids=w_106_000100)), there is one abbreviation (the entire word) and two abbreviation markers (tilde and dot).
You may have an abbreviation without an abbreviation marker (e.g. "etc" without dot).
In the example I gave before, there is one abbreviated word, three abbreviations (o with tilde above, superscript ur and "b;" for "b(us)") and three abbreviation markers (the tilde, the superscript ur and the semicolon).
The entire word is an abbreviation when the abbreviation marker cannot be resolved by itself (as is the case for tironian "7" (= et) or "9" (= cum)) or by association with one or several letters (like nasality tildes over vowels).
I understand that these distinctions are very tiny and I don't think that the Guidelines should impose them but I don't understand why the Guidelines should impose an encoding that does not allow to make these potentially useful distinctions.

**Comment by lb42** [comment]
You seem to be drawing a distinction between an abbreviation which happens to be lexical when expanded and a smaller unit which is a combination of an abbreviation mark with some other letter. Let's call the first an A1, and the second an A2. So, o is a letter, tilde is an abbreviation mark, and the combination of the two is an A2. Or "w" is a letter, "ch-superscripted" is an abbreviation mark, and the two combined are either an A2 (if for example followed by "ever") or an A1, if nothing follows. Have I understood correctly? If so, is this really a useful distinction, and what does it facilitate?

**Comment by jamescummings** [comment]
For the record, I'd encode @alavrentev's word as: 
```xml
<choice>
    <abbr>co<am><g ref="#abbr-macron"/></am>pl<am><g ref="#abbr-barredl"/></am>ib<am><g ref="#abbr-us"/></am></abbr>
     <expan>co<ex>m</ex>pl<ex>ur</ex>ib<ex>us</ex></expan>
</choice>
```
and don't quite see why (even when counting abbreviations) that doesn't suffice? 

One could break this up as:
```xml
<w>co<choice>
             <am><g ref="#abbr-macron"/></am>
             <ex>m</ex>
           </choice>pl<choice>
             <am><g ref="#abbr-barredl"/></am>
             <ex>ur</ex>
           </choice>ib<choice>
             <am><g ref="#abbr-us"/></am>
             <ex>us</ex>
           </choice>
      </w>
```
Though frankly I think that is silly.  Yes, the previous way has a bit of redundancy in non-expanded characters, but I think the clarity is worth it.

This issue has noted that there are some examples using `<expan>` where we would now recommend to use `<ex>` and for reasons of backwards compatibility we won't mandate against doing so, but I'm going to put in an bug issue to correct any examples to use `<expan>` as a full word. We shouldn't exemplify what we've previously agreed is sub-optimal practice where possible. We certainly agreed when `<ex>` was created that it was the preferred way.

The idea of embedding `<am>` inside `<expan>` seems wrong to me because of an editorial stance where I don't believe that, say, a superscript 'r' made into a full character and indicating the presence of a preceding 'u' is indeed the same 'r' when it is expanded. Unicode define these as different character points, and I define them as different characters. Even if there wasn't a physical difference (though no example jumps to mind), I feel the character indicating the abbreviation is somehow no longer the same once the word has been expanded.  But the TEI allows you to hold the opposite view if you want. 

I'm not against Hugh's suggested rephrasing.

**Comment by PFSchaffner** [comment]
FWIW, I'd do the same as James--probably because our 
approach is directly descended from the original TEI
(SGML) approach, wherein the brevigraphs that James 
represents as `<g>` elements we represented as entities 
(entity abus = brevigraph for 'us', etc.). --Except that we distinguish
between the generic -us brevigraph and the distinctive -bus
brevigraph.

`<abbr>co&ab-macron;p&barred-l;i&abbus;</abbr>`

And the original `@expan` attribute (`@expan="compluribus"`)
migrates more or less directly into a `<choice><expan>`
structure, such as James provides.

**Comment by alavrentev** [comment]
Well, if everybody is OK with Hugh's rephrasing, the discussion may end here.

For the record:

1. I don't think there is a "barred l" but rather an "l" followed by a "superscript ur round r form" according to MUFI  terminology. But this is a palaeographic detail irrelevant for the current discussion. 
2. The are not 2 but at least 3 abbreviation types: the 2 mentioned by Lou and the 3d one where the abbreviation mark can be resolved without association with other letters of the word.
3. In most cases these fine differences are irrelevant, and the encoding (option 1) proposed by James is OK. However, if a project involves palaeogrpahic analaysis of letters, punctuation and abbreviation marks (as is the case in [Oriflamms](http://oriflamms.hypotheses.org/)), a more precise encoding may be necessary. For instance, we need to be able to tokenize the transcriptions at character level and to associate every individual abbreviation with its expansion. This task would be very complicated with multiple <am> in <abbr> and multiple <ex> in <expan>.

**Comment by jamescummings** [comment]
Hi @alavrentev 
In response to 3. I would note that you are already able to tokenise at the character level using `<c>` inside `<abbr>` and `<expan>`. However, it is interesting to note that you are not able to do so inside `<am>` or `<ex>`. (The former possibly being defensible since this is a marker).  

These allow inside them:
am:
core: add corr del orig reg sic unclear
gaiji: g
transcr: damage handShift mod redo restore retrace secl supplied surplus undo

and ex only: 
gaiji: g

This difference is defensible... In editorially-supplied expanded text you can't have these transcription related elements.  However, one could argue that an expansion containing multiple characters, in a document where you have tokensized by character that 'am' and 'ex' should allow 'c' and 'pc' inside them.  I'd support that inside 'ex' at least.

**Comment by martinascholger** [comment]
F2F subgroup C suggests to correct the examples to
`<choice>
<abbr>Aug<am>g</am>
</abbr>
<expan>
Aug
 <ex>ustorum duo</ex>
</expan>
</choice>`

Change specification followign Hugh's suggestion "The content of this element should be the expanded abbreviation, usually (but not always) a complete word or phrase."

Add example to ref-am
`<abbr>eu<am>
  <g ref="#b-er"/>
 </am>y</abbr>
<abbr>
 <am>
  <g ref="#b-per"/>
 </am>sone
</abbr> ...`

**Comment by martinascholger** [comment]
changed examples and note
