### ISSUE TITLE
Differentiate <ex> and <expan> more clearly

### ISSUE THREAD

**Issue by adunning** [TEIC/TEI#1404]
[Several of the examples for `<expan>` in the guidelines](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/examples-expan.html) are using the tag in place of `<ex>`, to indicate letters added by an editor. For example, `Apringi ep<expan>iscop</expan>i Pacensis eccl<expan>esi</expan>e` should be `Apringi ep<ex>iscop</ex>i Pacensis eccl<ex>esi</ex>e`.

The definition of `<ex>` is clear ('contains a sequence of letters added by an editor or transcriber when expanding an abbreviation'), but I can see how it could be confused with `<expan>` ('contains the expansion of an abbreviation'). A clearer definition for the latter might be 'contains the expanded form of an abbreviation', but I imagine that there's a better way of phrasing this.

One could also go further and adopt EpiDoc's rule that `<expan>` must always include `<ex>`. It doesn't seem especially useful to indicate that a word has been expanded without indicating which letters have been added.

**Comment by jamescummings** [comment]
This is primarily for legacy reasons. Previously `<expan>` did double-duty as both the expanded word and some people used it for just the expanded text.  In my mind we should move to a system as you suggest where `<expan>` is used for expanded words as a whole and only `<ex>` is the only things used for the expanded text. We can do this with no schema changes or backwards compatibility issues by merely changing the prose and examples.

Enforcing the use of an `<ex>` inside `<expan>` is one I'm less comfortable with. Even when the expansion letters are retained e.g. NATO / North Atlantic Treaty Organization to require that encoders mark the expanded bits seems a bit heavy handed from a TEI perspective.  (Seems like a great idea for consistency in a project setting.)

**Comment by lb42** [comment]
Sometimes letters are suppressed as well as added when an appreviation is expanded, e.g. "pp" for "pages".  Using &lt;ex> in such situations is hardly useful. But I agree that we need to review urgently current usage of these two tags in the Guidelines examples, which is inconsistent.

**Comment by adunning** [comment]
Perhaps I am missing your point, but I would mark up something like 'pp' as `<expan>p<am>p</am><ex>ages</ex></expan>`. Makes the relationship between what appears on the page and its interpretation absolutely clear.

**Comment by lb42** [comment]
Of course. I am being stupid.

**Comment by adunning** [comment]
Hardly; I still don't entirely understand what the guidelines envision for this.

**Comment by jamescummings** [comment]
These days I would only use expan around a word or phrase and never use it to indicate the expanded text which I'd mark with ex.  I think it is possible to have expan without any ex elements (see the NATO example above, if 'North Atlantic Treaty Organization' is the original text, and you are editorially making that abbreviated to 'NATO' then the abbr is the new thing, not the expan).

**Comment by adunning** [comment]
Wouldn't you technically need to put that inside a `<choice><sic/><corr/></choice>` structure? But, yes, HTML shows us that there is a place for marking abbreviations as such without necessarily giving their expanded form.

I'm increasingly wondering whether we need to clarify the relationship between `<abbr>` and `<expan>` as much as `<expan>` and `<ex>`. (At least we don't have to worry about `<am>`!)

**Comment by jamescummings** [comment]
I don't think I'd need to embed it in a sic and corr.

The problem is with the assumption by some that:
```
<choice>
<expan>North Atlantic Treaty Organization</expan>
<abbr>NATO</abbr>
</choice>
```

means that the original had 'NATO' and the expanded form is being provided. This is not necessarily true, it could be the reverse. abbr and expan is the one exception to knowing which is in the document. With corr/sic you know which is the correction and which the document-provided apparent error. With orig/reg you know which is regularisation and which is the document-provided original reading.  With abbr/expan you have no such knowledge (you may indicate through things like `@type` I suppose).  

Except in cases such as this, though, I'd never have an expan without an ex, and I'd only wrap abbr and expan around whole words or phrases, not parts of words,  but I'd not necessarily have an am inside my abbr.

**Comment by PFSchaffner** [comment]
I'm a little skeptical about the 'no expan without an ex' sentiment. Probably because I've used it so seldom, I've always been a bit confused about `<ex>`, especially as to whether to count as 'added' letters that are present in some form in the original abbreviated form. E.g. "LaP" can be an abbreviation for "Ladyship"; in expanding it I change the case of "P" to "p"; does "p" belong in the `<ex>`? Or if the original (as often) has a superscripted letter, or the degraded or corrupted form of a superscripted letter, as in the familiar 'pri' and 'qui' and 'qua' abbreviations with superscripted 'i' and 'a'. Are the i and a being added in expansion, or merely recognized? In the even more familiar 'ye' and 'yt' (the / that) abbreviations, 'h' and 'ha' belong in `<ex>` tags, but do 'e' and 't'? And what about the 'y'? Arguably, though historically thorn, by the time of print the 'y' is simply a glyph variant of 'th'. Does it go in `<ex>`? When the chi-rho is used as an abbreviation for "Christus" the "Ch" and the "r" are surely present in some sense, as is the "r" in the 'recipe' brevigraph -- even when said brevigraph is used to abbreviate a wholly different word in r- (which is common). Brevigraphs in general are problematic, because they may contain letters, or the vestigial forms of letters, and it is not clear, to me at least, whether the `<ex>` system allows one to acknowledge the different degrees of suppletion involved when the encoder supplies expansion. "hz" contains an 'h' and an 'et-brevigraph'; when expanding "hz" to "habet", what should go in `<ex>`? 'ab' to be sure, but also 'et'? 'a' and 'b' are fully supplied; 'et' is simply (as it were) recognized.

**Comment by adunning** [comment]
That bothered me for quite awhile as well. I have tended to put something in `<ex>` if it has a different Unicode code point; so, for your first example, `<expan>La<am>P</am><ex>dyship</ex></expan>`.

**Comment by jamescummings** [comment]
I would equally never put an `<am>`into an `<expan>` unless I really wanted to show that the abbreviation marker preserved.  To me Andrew's markup in his last post above means that the expanded text is LaPdyship... which seems wrong.

I'd mark this up as:
```
<choice>
<abbr>La<am>P</am></abbr>
<expan>La<ex>dyship</ex></expan>
</choice>
```
To answer Paul's questions, with superscripted letters it all depends if you view the superscripted letter as the same letter as in the expansion.  If so, then you could mark it as an 'am' as Andrew suggests, or not and just as a letter which remains (which I would do). But honestly I view a letter standing in as an abbreviation marker and a similar looking (but full-sized) letter as different ones, so the new letter becomes part of the 'ex' expanded text.  For yat with a superscript t expanding to that I would encode as:
```
<choice>
<abbr>ya<am rend="sup">t</am></abbr>
<expan>tha<ex>t</ex></expan>
</choice>
```
precisely because, as you say, the y is just another form of th, not an expansion. With hz I'd put all of 'abet' into an 'ex' element because the et-breivgraph is a form of abbreviation marker (while I don't think the 'y') is.

In all these cases I think it comes down to your editorial perspective, tradition, and reasons for encoding. I think the TEI's job in this area is to enable all of those possibilities but clarify that `<expan>` should be for the word/phrase that has been expanded and `<ex>` is for the supplied text.

**Comment by hcayless** [comment]
We're seeing the collision between "choice-style" and "EpiDoc-style" abbreviation handling here. I would do pretty much as Andrew does, `<expan><abbr>La<am>P</am></abbr><ex>dyship</ex></expan>`, and in my rendering of that I would display the `<am>` if I wanted the unexpanded version and the `<ex>` if I wanted the expanded version. I like it better because it doesn't involve repeating yourself.

**Comment by raffazizzi** [comment]
The breakout group thinks that when providing both and abbreviation and an expansion, a `<choice>` should be provided. Putting and abbreviation mark inside an expansion would be confusing. 

Regarding the original comment, we suggest that only `<ex>` should be used to identify content provided for the expansion, not `<expan>`. More discussion to follow.

**Comment by ebeshero** [comment]
See #1403

**Comment by jamescummings** [comment]
I agree with @raffazizzi's comment above.

**Comment by emylonas** [comment]
Look through examples, and make sure that `<ex>` is identifying the expansion and not `<expan>`
.

**Comment by sydb** [comment]
Council leaves GREEN for asignee to go through GLs and find examples of `<ex>` or `<expan>` and normalize them so that the latter is used for complete words and the former to identify content provided for the expansion.

**Comment by martinascholger** [comment]
Changed examples

**Comment by ebeshero** [comment]
Oops-- my push was referencing the wrong ticket...I meant #1414!

**Comment by ebeshero** [comment]
Fortunately this one is already closed.
