### ISSUE TITLE
<title> should be in att.datable

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1410]
Titles should be datable:
```xml
 <bibl>
   <title level="j" from="1986-01" to="2014-12-02">Literary &amp; Linguistic Computing</title>
   <title level="j" from="2014-12-03">Digital Scholarship in the Humanities</title>
   <publisher>Oxford University Press</publisher>
 </bibl>
```

In my mind `<title>` is roughly equivalent to `<name type="book">` (or `<bookName>`). Since `<name>` and its ilk are in `att.datable`, so too should `<title>` be, no?

**Comment by lb42** [comment]
I see the logic, but this seems a really unusual edgecase. In practice, I think the only time where you might conceivably need to do this would be when citing a serial title, since when citing anything else you will presumably want to refer to the title as it was when the work cited was produced; anything else would be very confusing. And wouldn't the same logic apply also to other kinds of information in the citation? e.g. names of publishers change over time, as do their addresses.

**Comment by martindholmes** [comment]
You can also put empty `<date>` elements into the `<title>` element and use their attributes, so there is an available method of encoding the info.

**Comment by ebeshero** [comment]
Subgroup at F2F agrees that titles should be datable.

**Comment by sydb** [comment]
Done in commit 62839e1, push 62839e1.
