### ISSUE TITLE
Build/release scripts, branches and Jenkinses

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1411]
tei-intall.sh, which is run during the release process of a new version of P5, has hard-coded links to old Jenkins URIs:

Jenkins=http://bits.nsms.ox.ac.uk:8080/job
jenkinsdir=${Jenkins}/${package}/lastSuccessfulBuild/artifact/P5

and so on. These will need to be updated to the new jenkins.tei-c.org URLs, but there is a further issue that has to be solved first: presumably we wish to release from the master branch, but the Jenkinses are (naturally) building the dev branch. Do we need to add new jobs on Jenkins which build from master?

**Comment by peterstadler** [comment]
> Do we need to add new jobs on Jenkins which build from master?

Yes, I do believe so. Both for the Stylesheets and the Guidelines. It wouldn't be that expensive since the build will only be triggered by a change to master (which will only occur through a release) but we should restrict the amount of build artifacts to only 1 or 2 to save disk space (and since we are keeping a history of binary files in the GitHub releases). (I believe we talked about this issue briefly during the f2f?!)

**Comment by hcayless** [comment]
I think there has to be a build-from-master job for both. Releasing won't be safe otherwise. Making this green.

**Comment by hcayless** [comment]
We should also add temporary jobs to build from the release branch, or maybe temporarily switch over to build that rather than dev while we're in the run-up to a release. We still need to have a build from master, as that's the final stopgap, but we also want to pick up errors in the release. Need to discuss this.
