### ISSUE TITLE
Make @select a bit more generalized

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1418]
The note on the `@select` attribute at <http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.linking.html> says 
>This attribute should be placed on an element which is superordinate to all of the alternants from which the selection is being made. 

It would be useful, however, to be able to use `@select` as the converse of `@exclude`. Specifically, it would be nice to be able to use it in a critical apparatus for variant words which are linked, but separated by non-varying words. This is particularly common in Latin, e.g., where case agreement means non-contiguous words may vary in tandem. 

For example, 
> aspice me quanto rapiat fortuna periclo

and in the app. crit.:
> *quanta...procella* Markland

It would be nice to be able to do:
~~~~~
aspice me <app>
  <lem xml:id="lem1" select="#lem2">quanto</lem>
  <rdg source="#Markland" xml:id="rdg1" select="#rdg2">quanta</rdg>
</app> rapiat fortuna <app>
  <lem xml:id="lem2" select="#lem1">periclo</lem>
  <rdg source="#Markland" xml:id="rdg2" select="#rdg1">procella</rdg>
</app>
~~~~~
and so use `@select` to show that the lemma of the first app implies the lemma of the second, and the reading of the first implies the reading of the second (and vice versa). The only thing that prevents this usage now is the note, which requires that the attribute be on an ancestor of the selected element. I suggest the note simply be removed.

**Comment by lb42** [comment]
Unless I misunderstand, this is not  what @select is for. It's for choosing amongst a bunch of subordinate alternates, not for indicating that one choice implies another.

**Comment by hcayless** [comment]
My question is: could `@select` be used in this way? It would be nice to have a attribute that does the opposite of `@exclude`. Or do I need to propose one? The thing is, `@select` in my example *is* "select[ing] one or more alternants." They're just alternants in a different structure. The only missing bit is the selecting element isn't a parent of the selected.

**Comment by hcayless** [comment]
Assigning to Raff for more input.

**Comment by raffazizzi** [comment]
I think `@select` requires that the pointed elements are somehow in alternation. In your use case (very interesting, btw) the words are not in alternation, rather they may alternate _as a pair_ with other readings, so I think you want to establish that co-dependence (possibly with a subordinate order). In other words `@select` is not adequate because it assumes that "quanta" and "procella" are alternatives to each other, but they're not.

`@corresp` might do it for the time being, but it won't strongly express the co-dependence and the order (i.e. the variant "procella" is what determine the change of case in "quanta" - I think).

So maybe a new attribute may be needed here - let's talk about it at the F2F.

**Comment by raffazizzi** [comment]
From F2F: `@require` (or `@imply`) might be a possible attribute that is opposite of `@select`.

It may be added to `att.global.linking` or perhaps `att.global.linking` should be re-organized into multiple more semantic classes.

**Comment by sydb** [comment]
At F2F Council is leaning towards adding `@require` (or `@imply`) to only `<rdg>` and `<lem>` (and maybe (`<rdgGrp>`), rather than global.

**Comment by raffazizzi** [comment]
Note to self: do not add the new attribute to `att.global.linking`: the approach is to gradually extend it to other elements when/if required; create new calls instead.

Possible elements already suggested by @martinascholger that may be affected are `<subst>`, `<add>`, `<del>`. 

Also look if there a class that already affects these elements together.

**Comment by raffazizzi** [comment]
Adding `@require` to `<rdg>` and `<lem>` (that is, to `att.witnessed`), but not to other elements yet. I noted that @martinascholger  suggested other elements like `<subst>`, `<add>`, `<del>`, and possibly other members of `att.transcriptional`, but I would recommend opening a new ticket for that, so that we can introduce `@require` more gradually, as discussed at the F2F.
