### ISSUE TITLE
Inconsistent handling of <idno>?

### ISSUE THREAD

**Issue by StefanDumont** [TEIC/TEI#1424]
It seems to me that `<idno>` is handled a little inconsistently in the structured elements `<place>`, `<person>`, `<bibl>` and `<org>`. In all these elements except `<place>` I can encode idno on any child position (first, last ...). In `<place>` I cannot place it as a first child. Is this behaviour intended?

**Comment by lb42** [comment]
The content models of these elements are all long overdue for a reappraisal. However, as I read it the content model for &lt;place> does permit you to put &lt;idno first, so long as you don't want to put an member of model.placeStatelike in as well --  which seems unlikely. 

&lt;person> and &lt;org> get &lt;idno> via model.nameLike, but &lt;place> seems to avoid that, presumably because it would permit personal names inside place information, which seems wrong.

This is all invented metadata of course which doesn't need to follow any source constraints. So why do you care about the order?

And why is &lt;bibl> in your list? It's not really the same kind of beast is it?

**Comment by StefanDumont** [comment]
Thx for your feedback! When I worked in Oxygen XML 17.1 I got a validation error for this example: 
```
<listPlace>
 <place>
  <idno type="uri">http://www.geonames.org/2761369</idno>
  <placeName>Wien</placeName>
 </place>
</listPlace>
```
Tested also with the TEI-all schema directly (without TEI oXygen framework). 
But perhaps I overlooked something?

It's not a big problem, that's right. I just wondered why the first position for idno is not allowed in place. We're using listPerson, listPlace, listBibl for indexes of persons, places and works in digital scholarly editions. Our scholars work with these files and we're using idno in all indexes for VIAF, GeoNames etc. and I usually try to order the elements in the same order (i.e. idno at at the first place, then the name etc.).

**Comment by lb42** [comment]
You're quite right: you can't put &lt;idno> before &lt;placeName>, because the latter is in model.placeStateLike, which appears in the content model before &lt;idno>. And I agree that this seems silly. 

The current model is
~~~~
<content>
 <sequence>
  <classRef key="model.headLike"
   minOccurs="0" maxOccurs="unbounded"/>
  <alternate>
   <classRef key="model.pLike"
    minOccurs="0" maxOccurs="unbounded"/>
   <alternate minOccurs="0"
    maxOccurs="unbounded">
    <classRef key="model.labelLike"/>
    <classRef key="model.placeStateLike"/>
    <classRef key="model.eventLike"/>
   </alternate>
  </alternate>
  <alternate minOccurs="0"
   maxOccurs="unbounded">
   <classRef key="model.noteLike"/>
   <classRef key="model.biblLike"/>
   <elementRef key="idno"/>
   <elementRef key="linkGrp"/>
   <elementRef key="link"/>
  </alternate>
  <alternate minOccurs="0"
   maxOccurs="unbounded">
   <classRef key="model.placeLike"/>
   <elementRef key="listPlace"/>
  </alternate>
 </sequence>
</content>
~~~

If we want to fix this, we would either have to move idno explicitly into the second alternation in the content model or (perhaps) add it to model.labelLike and remove the explicit reference to it. Either way will probably break something somewhere else :-(

**Comment by jamescummings** [comment]
I'd agree that this would be desirable. I don't think we should impose any ordered structure inside person/place/org/etc.

But yes, might break something somewhere.  The current content model seems barking to me.  Why can't all these just be in alternation with each other rather than in a specific order?

**Comment by emylonas** [comment]
There are several tickets related to this: #1414, #667 perhaps others - Group A thinks that that `<idno>` should appear in all the -ography elements, including `<nym>` and `<event>` and `<place>` etc. and its position should not be constrained. this will require more reconciliation of elements.

**Comment by sydb** [comment]
Council decided to close this ticket, and fold it into #367. However, the rationalization of those element should *all* permit `<idno>` as a 1st child (and perhaps elsewhere).
