### ISSUE TITLE
Restructure chapter 11

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1427]
The presentation of information should follow a logical, cumulative order. Two key changes are needed: 1)  The chapter should discuss transcription of primary sources before discussing how to combine facsimile and transcription. 2) Since the chapter relies on a basic distinction between text-focused and document-focused transcriptions, it would be most logical to structure the discussion of the various transcriptional elements accordingly. This could, however, turn out to be difficult, as almost all of the elements of the trascr module are allowed within either &lt;text> or &lt;sourceDoc>—the only exception seems to be &lt;subst>. A possible solution would be to treat elements twice, once in each context. 

Also, several aspects of the chapter (presumably unintentionally) bias naive encoders toward document-focused transcriptions. For one thing, "11.2 Combining Transcription with Facsimile" implies that one must choose between &lt;text> and &lt;sourceDoc>. Second, expressions such as "finished text" and "creative process" are used in place of the terms "text-focused" and "document-focused"—which were used in the [release notes of v2.0](http://www.tei-c.org/Vault/P5/current/doc/tei-p5-doc/readme-2.0.html). and which seem more precise and neutral.

**Comment by gerritbruening** [comment]
Would it help to break this issue down into smaller sub-issues that we can refer to from here?

**Comment by raffazizzi** [comment]
Some thoughts:
> 1) The chapter should discuss transcription of primary sources before discussing how to combine facsimile and transcription.

I think it's beyond the scope of the Guidelines to generally discuss the transcription of primary sources. Rather than creating a dedicated section to this, it may be sufficient to improve and extend the opening of 11.2 Combining Transcription with Facsimile, which leads to the following issue:

> For one thing, "11.2 Combining Transcription with Facsimile" implies that one must choose between <text> and <sourceDoc>

I disagree: the opening clearly specifies that both can be used "in parallel", so one does not exclude the other: "the recommended practice is to use the text element to contain such a structured representation, and to present it in parallel." Perhaps this can be made clearer. I'd also like to revisit the opening to immediately introduce the concept of "text-focused" and "document-focused". I agree with @brettttt that these terms are precise and neutral. This will help encoders to figure out whether they need to use `<text>`, `<sourceDoc>`, or both.

> the chapter relies on a basic distinction between text-focused and document-focused transcriptions
> A possible solution would be to treat elements twice, once in each context.

I think the chapter should focused exclusively on document-focused transcription; text-focused transcription is covered elsewhere (i.e. pretty much the rest of the TEI Guidelines). It should be sufficient to adjust the language to make this crystal clear.

**Comment by lb42** [comment]
FWIW, I agree with Raff's analysis and suggestions.

**Comment by gerritbruening** [comment]
> I think the chapter should focused exclusively on document-focused transcription; text-focused transcription is covered elsewhere (i.e. pretty much the rest of the TEI Guidelines).

@raffazizzi , do you mean that the chapter should solely be about the `sourceDoc` approach? I think this is what "document-focused" refers to.

**Comment by ebeshero** [comment]
In group ticket session at F2F (2016-04-25): suggestion to add a gentle paragraph to the start of section 11.2 that explains a distinction between document-based and text-based transcription.

**Comment by sydb** [comment]
Council as a whole thinks sub-group has it right.

**Comment by gerritbruening** [comment]
OK, great to hear that. @ebeshero , [do you mean](https://github.com/TEIC/TEI/issues/1427#issuecomment-214392305) the second paragraph of the whole chapter or rather of [section 11.2](https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L395)?

**Comment by ebeshero** [comment]
@gerritbruening We were concentrating on the second paragraph of section 11.2, yes. I noted that the second paragraph of the chapter indicates a range of use-cases relevant to the chapter contents--in a general way it sets up the idea of multiple approaches. I find the hyphenated "text-focused" and "text-based" language only in this ticket and I am not sure either phrasing is needed in the chapter itself, where I find only the hyphenated "text-critical" in use. We were also really not contemplating a general overhaul of the chapter.

**Comment by peterrobinson** [comment]
Good to see a discussion on this issue. I have been saying, for some time, that there are serious problems with this chapter. Because the chapter is titled "transcription of primary sources", and because it focusses almost exclusively on "document based" transcription, the effect of the chapter is to suggest that transcription, in the TEI world, should follow the model suggested in this chapter. This puts the chapter at odds with the practice of many editorial projects and encourages the creation of narrowly-based transcriptions which present individual pages (not even whole documents) with great detail, but at the cost of limiting other uses of the transcripts.  Try, for example, to compare any paragraph in the 1818 and 1831 versions of Frankenstein with the manuscript transcripts in the online Shelley/Godwin archive. So, good to see that others in the TEI community are uneasy about this chapter.

However, there is a problem with the opposition "text-focussed" and "document-focussed".  Of course, this leads us into the murky waters of the meaning of the terms "text" "document" "work", and this chapter is not going to settle the exact meaning of these terms and their relationship with each other, where generations of textual scholars etc have failed (ok, you can look at [my article in Ecdotica]([url]https://www.academia.edu/9575974/The_Concept_of_the_Work_in_the_Digital_Age_published_version_(url)) on this). I think you can present the choices in an introductory paragraph in terms of the opposition between transcripts which choose as their primary hierarchy the intellectual structure of the communication present in the document text  (typically by div elements representing book/chapter/paragraph etc) and transcripts which choose as their primary hierarchy the physical disposition of the document text upon the page (as in sourceDoc etc). A useful introductory section would acknowledge the virtues and deficiencies of each approach, stressing that both are valid, and both have limitations. (Peter Robinson, University of Saskatchewan)

**Comment by gerritbruening** [comment]
@ebeshero Thanks for your feedback. It is true that neither of the two terms "text-focussed" and "document-focussed" appears in the chapter. But [Brett](https://github.com/TEIC/TEI/issues/1427#issue-129268825) did not invent him by himself, they were used in the [release notes of verion 2.0](http://www.tei-c.org/Vault/P5/current/doc/tei-p5-doc/readme-2.0.html).

**Comment by raffazizzi** [comment]
@gerritbruening, @ebeshero, and @peterrobinson thank you very much for your comments.

It sounds to me that there a few important things to address:
  1. Clarify that this chapter does not describe the **only** way of transcribing primary sources, but just a specific approach;
  2. Adopt the _text-focused_ and _document-focused_ terminology as identifying encoding methods, and related:
  3. Clarify that the encoding methods do not necessarily correspond 1-to-1 with any theoretical framework, which is left to textual scholars to define and discuss.

Suggested plan of action:
  1. I'll take a first stab at revising the text -- expect relatively small adjustments, and a few new sentences (or a paragraph or two max) in key places to clarify prose.
  2. Will circulate the draft (in the form of a GitHub Pull Request) to the council as well as the participants on this ticket
  3. If there is sufficient agreement, we'll proceed. If we still feel that substantial revisions are needed, we'll look into involving the MS SIG for more substantial revisions.

**Comment by peterrobinson** [comment]
I do suggest you drop the opposition "document focussed" and "text focussed". This is misleading, and simply wrong.  Instead you might highlight the choice faced by encoders: treat the physical disposition of the text on the page as the primary hierarchy (as current 11 has it) or treat the intellectual divisions of the act of communication as the primary hierarchy (as in the P3-P4 versions, etc). As for point 3: no need to specify what textual scholars might make of this. Good luck.

**Comment by peterrobinson** [comment]
A note on my last post. From looking at the history of the terms 'document/text focussed' in the context of this discussion, it's clear that they arise from the distinct content models of <document> and <text> in the TEI universe. One might retain the terms, as part of a discussion of the encoding choices: in the TEI world, the two terms crystallize the distinction (which is really problematic and a prime exhibit in the argument that TEI has to move past XML) between the alternative encodings. Hence, a chapter which started along the lines that "The TEI offers two distinct methods of encoding the texts of primary source materials.." I guess the point I am making is that you should beware any kind of statement which might be read as saying that there is some distinction between text and document which exists outside the TEI world. Many of us will leap on you from a great height if you try and argue that.  The reality is that the uni-hierarchical model of XML forces you to choose a primary hierarchy, in phenomena which actually have multiple hierarchies, as all do know.

**Comment by raffazizzi** [comment]
@peterrobinson yes, it is my intention to characterize the terms as identifying encoding approaches not ontological considerations. I see how it could be confusing, however, so I might also try to use a paraphrase instead. In your previous post you said:

> treat the physical disposition of the text on the page as the primary hierarchy (as current 11 has it) or treat the intellectual divisions of the act of communication as the primary hierarchy (as in the P3-P4 versions, etc)

This is the precisely the distinction that the chapter needs to clarify.

**Comment by peterrobinson** [comment]
That makes excellent sense. Stay out of the ontological weeds.. as far as you can

**Comment by brettttt** [comment]
This discussion has gotten a bit long before I've been able to devote my attention back to it, so I'm going to try to respond to the comments in sequence. 

Raffaele wrote:

>> For one thing, "11.2 Combining Transcription with Facsimile" implies that one must choose between <text> and <sourceDoc>
> I disagree: the opening clearly specifies that both can be used "in parallel", so one does not exclude the other: "the recommended practice is to use the text element to contain such a structured representation, and to present it in parallel."
What it says is that the transcription may be "supplied in parallel **with a &lt;gi&gt;facsimile&lt;/gi&gt;**" (not thot o transcription in &lt;gi&gt;text&lt;/gi&gt; may be supplied in parallel with &lt;gi&gt;sourceDoc&lt;/gi&gt;. It's true that a careful reading of the paragraph in 11.1 "Either of the &lt;gi&gt;facsimile&lt;/gi&gt; or &lt;gi&gt;sourceDoc&lt;/gi&gt; elements may be used . . . " conveys the correct information that "facsimile" &#2260; &lt;gi&gt;facsimile&lt;/gi&gt;, but between that paragraph and 11.2 is a rather long discussion of &lt;gi&gt;facsimile&lt;/gi&gt;. And the impression that, in 11.2, facsimile = &lt;facsimile&gt; is of course reinforced by the fact that the text mistakenly actually uses "&lt;gi&gt;facsimile&lt;/gi&gt;," confusing the element for the general term. If the Council, as writers of the guidelines, had at this point confounded the two, I think it's fair to assume that a lot of readers are likely to follow suit.

**Comment by brettttt** [comment]
Elisa wrote:

>We do cover basically the distinction between document vs. text transcription in the 2nd paragraph of the whole chapter (near the top) . . .

and 

> I noted that the second paragraph of the chapter indicates a range of use-cases relevant to the chapter contents--in a general way it sets up the idea of multiple approaches.

Hmmm. That paragraph ("Although this chapter . . . ") does, indeed, suggest that much of the chapter is applicable to a wide range of use-cases, not just to the manuscript material that it takes for most of its examples. So it suggests that most of the suggestions and examples can be extrapolated, without undue contortions, to encoding **different kinds of materials**. That's a very different thing than discussing the different **approaches/methods one might use for encoding something (whether it be a manuscript, a printed pamphlet, or a monumental inscription).

**Comment by brettttt** [comment]
Peter wrote:

>Because the chapter is titled "transcription of primary sources", and because it focusses almost exclusively on "document based" transcription, the effect of the chapter is to suggest that transcription, in the TEI world, should follow the model suggested in this chapter.

Raffaele wrote:

>It sounds to me that there a few important things to address:

>Clarify that this chapter does not describe the **only** way of transcribing primary sources, but just a specific approach;

Having used the pre-P5 version of this chapter and having also spent rather a lot of time over the past year and a half or so reading over the current version multiple times, I want to argue that this chapter, in its current incarnation, does **not** "focus almost exclusively on 'document-based' transcription." Rather, I think, several aspects of the way that it's written tend toward the impression that it does (e.g., the ordering of topics, the use of examples, the biased language). So I very much **don't** want this chapter to become a discussion of just one "specific approach" (i.e., document-focused). Instead, I'd like it to treat both approaches in more equal and agnostic terms.

That said, I can get behind the plan of action that Raffaele has outlined above--and the goal to ground the discussion in a choice between foregrounding physical or intellectual hierarchies and explicitly not in a choice among the various editorial theories.

**Comment by gerritbruening** [comment]
> I think the chapter should focused exclusively on document-focused transcription; text-focused transcription is covered elsewhere (i.e. pretty much the rest of the TEI Guidelines).

I was a little bit stunned when I read this, and I fully share the opinion that both approaches should be presented in one and the same chapter, and in a neutral, balanced way.
At the same time I see how one can think that the text-focused is 'covered elsewhere'. If we consider the upper part of the hierarchy of a text-focused transcription, we fill find that it's elements are from the `core` module, whereas the document-focused transcription is build upon the `transcr` module throughout:

|        | text-focused  | document-focused       |
|--------|---------------|------------------------|
| top    | `core` | `transcr` |
| chunk  | `core` (`<p>`and the like) | `transcr` (`<line>`) |
| phrase | `transcr` (`<subst>`) | `transcr` (`<mod>`) |

(I am aware that the terms top, chunk and phrase-level do not fully apply to `surface`, `zone`, `line`, and its children)

However, when we look on the characteristic features of an ambitious text-focused transcription, it is indeed the phrase-level. Because it is mainly on that level where it is possible to record the textual development by means `<subst>` and its children. So 'text-focused' is not only about what Peter calls the 'intellectual divisions' of a text.

**Comment by ebeshero** [comment]
Well, here's yet another complicating factor: Chapter 11 is about transcriptions of primary documents. Last weekend I was just advising on a new TEI project that involves transcriptions of speech from a set of interviews, and introducing some friends to the TEI by means of [Chapter 8](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TS.html). There's another application of transcriptions from primary sources, taken down with `<u>` and other elements in the spoken — Transcriptions of Speech module.

The reason I bring this up is because we *do* cover different kinds of transcription from different kinds of primary source materials and contexts in other chapters. Perhaps Chapter 11 might begin with a survey of distinct approaches for what we call "transcription"? @gerritbruening , I like your table of modules as a helpful overview, but while we're at it, perhaps we ought to be discussing the concept of transcription more fully, since there are even more modules at work here than we're presenting in this binary division of "text-focused" vs. "document-focused."

**Comment by ebeshero** [comment]
@raffazizzi MS-SIG would be happy to review your revision(s) as you're working on this. (Send to MS-SIG list.)

**Comment by ebeshero** [comment]
@raffazizzi Suggestion from @Martin-de-la-Iglesia in the Text and Graphics SIG that we include the `<graphic>` element in the list of elements in 11.1 "available to represent components of a digital facsimile":  (to include it with facsimile, sourceDoc, surface, surfaceGrp, zone, etc.) .

**Comment by lb42** [comment]
It's at a lower structural level so doesn't appear in this list. You can't use it outside one of the others.

**Comment by ebeshero** [comment]
@martinascholger and I are at the Text and Graphics SIG together, and we note that 3.9's explanation of graphic should be directing the reader to Ch. 11 for more information on graphic used for facsimiles.

**Comment by raffazizzi** [comment]
@brettttt and @gerritbruening we just sent a [PR](https://github.com/TEIC/TEI/pull/2014) addressing this issue, we welcome your feedback from you and others!

**Comment by holfordm** [comment]
Is the phrase "primary source materials" helpful? For most people a modern edition of a medieval charter would still be a primary source but that is not what the chapter is about. The new summary of the chapter in `div xml:id="PHOV"` is very helpful, and I wonder the first sentence (lines 14-15) could say something like 'this chapter provides guidelines for the encoding of materials where issues such as layout,  transcription, or combining text and fascimile require more complex markup than is provided by core elements'.

**Comment by peterstadler** [comment]
This is merged, right? So can this be closed @raffazizzi ?

**Comment by raffazizzi** [comment]
Closing the issue as it's been addressed by PR #2014.
