### ISSUE TITLE
Allow <msPart> before <history> etc.

### ISSUE THREAD

**Issue by adunning** [TEIC/TEI#1430]
At present, if `<msPart>` is present, other manuscript description elements cannot be entered outside this. This does not reflect the actual practice of cataloguing: often it is the author of the description that is first making the argument that the manuscript can be divided into booklets, and one needs to be able to talk about the object as a whole as well as its parts. I would thus ask that `<physDesc>`, `<history>`, and `<additional>` be allowed in parallel with `<msPart>`. (On the other hand, I can't think of a reason to have `<msContents>` outside of `<msPart>`.)

**Comment by hcayless** [comment]
I'm pretty sure you can have these already, they just have to occur before
the msPart(s).

**Comment by adunning** [comment]
Yes, quite right; thanks for pointing that out. It would still make life easier if `<msPart>` could occur earlier, though I would be interested to know if there is a reason for the current behaviour.

**Comment by lb42** [comment]
The order of child elements within &lt;msDesc> is generally fixed. There are several reasons for this:
- the order can be entirely arbitrary since these elements do not generally need to follow a pre-existing original artefact
- however software development (and schema specifications) are a LOT easier to manage if the order is the same in all instances
- hence for the most part, a specific (though arbitrary) order is proposed

**Comment by adunning** [comment]
You don't give yourself enough credit: the order of the elements is really quite logical. If the position of `<msPart>` was in fact a specific part of the design, I'll just deal with it. Thanks for the explanation!
