### ISSUE TITLE
add <schemaSpec> to att.docStatus

### ISSUE THREAD

**Issue by peterstadler** [TEIC/TEI#1433]
Until version 2.9 the attribute `@status` was a member of `att.identified`, hence an e.g. `<schemaSpec status="unstable">` was perfectly valid. I think that's still sensible and propose to make `<schemaSpec>` a member of the class `att.docStatus` to inherit the attribute  `@status`.
For a real world example have a look at the [CMIF ODD](https://github.com/TEI-Correspondence-SIG/CMIF/blob/master/odd/cmi-customization.xml).

**Comment by jamescummings** [comment]
I've looked into why this happened. @martindholmes removed it from att.identified because we had deprecated it and the time had run out. (I don't remember why...) but yes, schemaSpec got its `@status` from att.identified so when that was deprecated it vanished from there in the 2.9.0 release. We were probably rationalising class models... he may remember more.

Specifically, with this commit:
https://github.com/TEIC/TEI/commit/5f51363839793c9c4a246ad000f7ac47e77fd75a 

Since we've removed `@status` from att.identified, I see no objection to having schemaSpec claim membership in att.docStatus and thus get its status attribute back.

**Comment by lb42** [comment]
Not a lot to discuss here: it looks like a corrigible error, so I've corrected it. 

I suppose one might agonise over the possibility of the @status on the parent &lt;TEI> element being different from that of the &lt;schemaSpec> and what that might mean. But it's quite feasible that you'd have a stable schemaSpec before you'd finalised the documentation as a whole (or vice versa)
