### ISSUE TITLE
the future of the Debian packages

### ISSUE THREAD

**Issue by lddubeau** [TEIC/TEI#1441]
I found that the Debian packages available on http://tei.oucs.ox.ac.uk/teideb/ have not been updated since 2.8.0. If I were to venture a guess, I'd guess that Sebastian was the driving force keeping these packages updated, and now that he has passed there's no one keeping them up to date.

Is there any intention to bring them up to date with the latest release?

The issue is broader than just this repository. [Roma](https://github.com/TEIC/Roma), to take the first example that comes to mind, is also affected.

**Comment by jamescummings** [comment]
Hi @lddubeau 

What you surmise is true. There has been some investigation into setting these up ourselves and I believe the intention is to produce some .debs for 3.0.0 soon. We're also looking into moving it to a more canonical hosting hanging off a subdomain of tei-c.org.  One of the questions we've had is how dependent people are on the debian packages and how much work we should put into maintaining them. We have a face to face meeting at the end of April where this will definitely be discussed.

**Comment by stuartyeates** [comment]
In the medium to long run, it may be worth considering moving to debian-on-docker as a platform.

**Comment by martindholmes** [comment]
@stuartyeates : could you explain exactly what you're proposing?

**Comment by stuartyeates** [comment]
Docker https://docs.docker.com/ is a next-generation paradigm for virtualisation. Rather than dealing in virtual machines, it deals in recipes for virtual machines and diffs between recipes for virtual machines. 

So a recipe for a Roma machine might be defined in terms of the current debian + a hand full of prerequisite packages + the git clone of https://github.com/TEIC/Roma/ + starting the webserver. When running on a debian machine, no additional OS is downloaded nor stored on the disk (running on Ubuntu, redhat or MS Windows a docker downloads and stores a single copy of the minimal Debian install across the entire ecosystem). 

Moving TEI development to docker would probably involve writing recipes for (a) a machine which builds the TEI standard itself; (b) a machine which runs jenkins for TEI; (c) a machine that builds / runs Roma; (d) a machine that builds debian / ubuntu packages; (e) a machine that builds / runs OxGarage; and maybe others. I forget the exact details of the dependencies between these systems, but some of the machines would be defined in terms of others.

This would allow people to build the TEI on MS windows 7+ as well as MacOS machines.

Since I don't have time to support the TEI Council myself, I'm not suggesting that we move immediately.

**Comment by martindholmes** [comment]
Actually I know about docker; I just don't really understand how this will help us solve this particular problem, since our entire website is running on shared hosting on a CentOS machine. I don't think we have any option for running docker instances on tei-c.org.

**Comment by raffazizzi** [comment]
@smjwsk is working on it, this should be green

**Comment by peterstadler** [comment]
Council decided during f2f in Providence that we want to maintain Debian packages in the future. We'll be looking for a subdomain e.g. packages.tei-c.org and provide the deb packages there. @smjwsk is working on the signing process and how to integrate this into the release process. 

BTW, the (unsigned) packages are regularly built by the Jenkins servers, see http://jenkins.tei-c.org/job/TEIP5/lastSuccessfulBuild/artifact/P5/

**Comment by emylonas** [comment]
Is there anything to report on this @smjwsk ?

**Comment by martindholmes** [comment]
I've investigated further, by actually trying to install some of the unsigned packages on my local system.

teu-p5-schema, tei-p5-doc, tei-p5-exemplars and tei-p5-test all install.

tei-p5-source depends on tei-xsl.

The tei-xsl package would not install because it had a dependency on "saxon". I assume that it's the saxon package that was originally distributed by Sebastian:

http://tei.oucs.ox.ac.uk/teideb/

After looking into this package, it seems to me that it does no more than install saxon9he.jar and set it up, so I figured that this dependency could be replaced with libsaxon-java. I tried this by changing the control file locally and building the package; I was able to install the result, and following that I was able to install tei-p5-source. Everything basically seems to work, although calling a transformation such as teitorng fails to find the local P5 source where it's been installed, and instead uses the Vault copy. Not sure if that's what should happen or not.

Anyway, I've changed the control file in the Stylesheets deb build to depend on libsaxon-java instead of "saxon".

tei-p5-database is supposed to install a bunch of XQuery and stuff into an existing eXist xmldb instance, but the included PERL scripts assume that eXist is running under Cocoon (nobody does that any more, and in fact I think it's impossible to build eXist to work that way). I didn't test it because I have various eXist instances locally that I don't want to risk. I'm not sure whether there's any point in keeping this package.

If anyone knows more than me about any of this stuff, please pipe up and correct me.

I've been looking into the possibility of creating a deb package repo on the Jenkins server itself, and doing the package signing there. That would make me the distributor of the packages (it has to be a person with an email address, and all the setup should be done when logged onto the hosting server itself, I think). It would be doable, but I do think it would be preferable to have the tei user on tei-c.org do this, with an email address that can be monitored by multiple people and the capability for anyone able to log on as tei to do a package release. It can be done:

http://troubleshootingrange.blogspot.ca/2012/09/hosting-simple-apt-repository-on-centos.html

and contrary to what I believed before, I think a script could simply pull the latest built packages from Jenkins and sign them locally.

**Comment by martindholmes** [comment]
I've tried to contact @smjwsk directly about this and had no response at all. I found this apparently abandoned repo too: 

https://github.com/smjwsk/tei-package-repo

I think we have to conclude that @smjwsk is no longer active on this ticket (he doesn't seem to have been active at all on Github for a while, under that user name at least), and assign the ticket to someone else.

**Comment by lddubeau** [comment]
On Wed, 2016-11-30 at 17:03 -0800, Martin Holmes wrote:
> After looking into this package, it seems to me that it does no more
> than install saxon9he.jar and set it up, so I figured that this
> dependency could be replaced with libsaxon-java.

That's also what I would have done. However, when I look at the version
numbers I see libsaxon-java at 6.5.5 whereas Sebastian's saxon package
is at 9.4.0.4. I'd expect 9.x to be able to do things that earlier
versions did not support. Unfortunately, the issue may not be revealed
by running stock TEI stylesheets. I don't know any reason why Sebastian
had version 9.x packaged.

> Everything basically seems to work, although calling a transformation
> such as teitorng fails to find the local P5 source where it's been
> installed, and instead uses the Vault copy. Not sure if that's what
> should happen or not.

It really depends on the command you were giving at the command line,
but could this be a manifestation of this problem: 

https://github.com/TEIC/Roma/issues/12

I'll point out that the report there started with an issue in `roma`
but the issue is in fact present in all the tools that are supposed to
replace it: `teitornc` and `teitorng` are also afflicted.

> tei-p5-database is supposed to install a bunch of XQuery and stuff
> into an existing eXist xmldb instance, but the included PERL scripts
> assume that eXist is running under Cocoon (nobody does that any more,
> and in fact I think it's impossible to build eXist to work that way).
> I didn't test it because I have various eXist instances locally that
> I don't want to risk. I'm not sure whether there's any point in
> keeping this package.

I sure don't depend on it.

**Comment by martindholmes** [comment]
You're right about libsaxon-java; I should have added libsaxonhe-java instead. I'll do that now...

**Comment by martindholmes** [comment]
I've pushed the libsaxonhe-java fix into dev; since we're not currently releasing packages, I don't see a need to push it into the release branch, but if anyone disagrees, please do that. It's commit d0b11bd.

**Comment by martindholmes** [comment]
@lddubeau I think the most reliable approach to building schemas locally is to ignore the deb packages completely (for the moment at least); I would clone the Stylesheets repos on your local machine, and use the bin/teitornc etc. commands in the Stylesheets repo to do conversions, passing the location of whatever TEI source you would prefer to use (a release version on the tei-c site, or a development build from the Jenkins server). The mismatch between the actual Stylesheets code in the last-released deb package, and the current P5 release that it uses by default on the TEI site, is so significant now that I don't think it's a good idea to use the debs at all.

**Comment by peterstadler** [comment]
Taking over from @smjwsk and here's the plan:

* create a subdomain `packages.tei-c.org` and a directory `deb` for the debian packages
* sign the repo with a new key (the passphrase will be given to the release technicians)
* (slightly) update the build process of the debian packages with new maintainer and dependencies (i.e. get rid of most dependencies)
* only keep and support packages `tei-p5-doc`, `tei-p5-schema`, `tei-p5-source`, `tei-xsl`, and `rnv`

**Comment by martindholmes** [comment]
Good to see this moving ahead! For tei-xsl, I think we'll need to address this:

https://github.com/TEIC/Stylesheets/issues/234

because it amounts to a non-free dependency. If there's anything that needs changing on Jenkins let me know.

**Comment by peterstadler** [comment]
### achieved:

* sneak preview of the debian packages is up at https://packages.tei-c.org/deb/ (Thanks to Ian Rifkin for setting up the subdomain!)
*  created a GitHub for my ANT build script at https://github.com/peterstadler/TEI-apt-repo which sets up the APT repo.

### still open

* the script relies on `dpkg-scanpackages` which is unavailable on CentOS (what the tei-c.org server runs on). Since it should be possible to install this on a CentOS machine (see http://superuser.com/questions/159310/bash-line-7-dpkg-command-not-found-said-centos), I've asked Ian – answer pending
* the XSL deb package needs tweaking of its metadata

**Comment by martindholmes** [comment]
Would it be helpful to test these now, or should we wait until the metadata is working?

**Comment by peterstadler** [comment]
Yes, it should be stable enough for testing (= repo URL and key should be stable).

The current package metadata reads:
```
Package: tei-xsl
Priority: optional
Section: web
Installed-Size: 146707
Maintainer: Sebastian Rahtz <sebastian.rahtz@it.ox.ac.uk>
Architecture: all
Version: 7.42.0
Replaces: tei-p5-xsl, tei-p5-xsl2, tei-p5-xslprofiles, tei-xsl-common
Depends: ant, ant-contrib, libsaxon-java
Conflicts: tei-p5-xsl, tei-p5-xsl2, tei-p5-xslprofiles, tei-xsl-common
Filename: ./tei-xsl_7.42.0_all.deb
Size: 9730438
MD5sum: 821aea605441b63c29037e3b3d1fad8c
SHA1: e59b9edca8a858d3609b7aa570d7daad4ea34431
SHA256: c8efce182c39aecf1a5e5ead06b062f0ea3f629056a285ba3df0197445390efb
SHA512: d1250026c2ab541f033189aac6459a5391a8a5306efb4d15eb887b7353dc30f9124bd7f80141208d67d43bfaf73b0dce91d471dae27bc5b64e54e60c56a55bad
Description: Text Encoding Initiative XSLT (2.0) stylesheets (P5)
 Stylesheets (XSLT 2.0) for TEI P5
```

I think we should update the Maintainer to `TEI Council <council@tei-c.org>` as in the other packages and check whether some of the other fields (`Replaces`, `Conflicts`, or `Depends`) are obsolete or need adjustments?

**Comment by martindholmes** [comment]
We definitely need `replaces`, because anyone who has not upgraded for a while (= most people) may have a lot of obsolete packages on their machines. It's not still signed with Sebastian's key, is it?

**Comment by peterstadler** [comment]
No, the individual packages are unsigned, only the repo (i.e. the Release file) is signed.

**Comment by martindholmes** [comment]
On Ubuntu 16.10, after adding the repo and the key, I get this error on apt-get update:

W: Invalid 'Date' entry in Release file /var/lib/apt/lists/packages.tei-c.org_deb_binary_._Release

The date looks like this:

Date: Mon, 27 Feb 2017 11:45:36 +0100

Other working packages look like this:

Date: Thu, 16 Feb 2017 21:44:49 UTC
Date: Wed, 22 Feb 2017 21:18:58 +0000

I wonder if they always supposed to be dated UTC?

**Comment by jamescummings** [comment]
I get:

````
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/packages.tei-c.org_deb_binary_._Release
````

This needs to be provided in UTC I believe.

Questions:

1) Why does tei-p5-doc depend on tei-p5-schema? Can't I just (say) get the documentation?
2) Why does tei-p5-source depend on tei-xsl? (Can't I just (say) get the source without wanting to build it?)
3) Is another option to installing dpkg-scanpackages on CentOS having a VM image somewhere which does the creation and the copies it to packages.tei-c.org? 

My test installation of these said I already had a couple installed and then I realised that I had first tried from your test server elsewhere so already have those... but then I did --reinstall (having cleared the cache first) and everything downloaded and installed properly.

**Comment by jamescummings** [comment]
(Sorry, @martindholmes's comment was there when I started typing, but then I went and installed things multiple times. ;-) )  

My reading elsewhere leads me to believe that the date must be in UTC.

**Comment by peterstadler** [comment]
Fixed the timezone issue per [bf7af75](https://github.com/peterstadler/TEI-apt-repo/commit/bf7af75fe1befd01f80f44a4f19c7d3ff06832bf) and updated the Release file in the APT repo.

Re James' questions

> Why does tei-p5-doc depend on tei-p5-schema? Can't I just (say) get the documentation?

I'd vote for removing the dependency

> Why does tei-p5-source depend on tei-xsl? (Can't I just (say) get the source without wanting to build it?)

I'd vote for removing the dependency

> Is another option to installing dpkg-scanpackages on CentOS having a VM image somewhere which does the creation and the copies it to packages.tei-c.org?

It's really a simple thing, but I find rather inelegant to implement. A few options come to my mind:

* integrate into the default build of the debian packages. (We already rely on Debian specific tools here, e.g. `debclean`). Would be the best short-term solution?
* create a docker container (or a VM) for the whole creation of the debian packages. (Actually, @hcayless created a docker image for the Guidelines build already …)
 That seems to make more sense in the long run, but I have no idea how to integrate into Jenkins?

**Comment by peterstadler** [comment]
wrong button …

**Comment by jamescummings** [comment]
Removing the dependencies: Agreed, +1

Integrating as much as possible into the build of the debian packages sounds good to me.  I've nothing against docker but am always nervous to through another level of complexity into things.

**Comment by martindholmes** [comment]
They now install for me with no problem and seem to work well. Nice job!

One thing I noticed was the standard message:

WARNING: No localsource set. Will get a copy from http://www.tei-c.org/Vault/P5/.

I wonder if, given that you've gone to the trouble to install the packages which come with a local P5 source, that should be the default? Does that make sense?

**Comment by jamescummings** [comment]
I'm not against pre-setting localsource for people who have installed the packages.  Though I suspect it is people like us who will suffer (who might be pointing to a dev localsource and not remembered to put it on the commandline).  However I think that:
a) This should only happen for those who have downloaded/installed the packages not for ppl getting the stylesheets some other way
b) That we should ensure that when using localsource it tells us. Even better if it tells us what version of the TEI it is using.  (I think it does say where it is getting it, but not what version even when grabbing from vault.)

**Comment by peterstadler** [comment]
Current status regarding TEI release 3.2.0:

No more changes to the TEI sources needed—but I'm still hoping for Ian to install the package `dpkg-dev` ("Debian package development tools") on the CentOS server so I can use the command `dpkg-scansources`. Once this is done, my little ANT script from https://github.com/peterstadler/TEI-apt-repo should do all the work. The release technicians will still need the passphrase for the PGP key which I happily share with them via any secure channel :)

**Comment by peterstadler** [comment]
Ian installed the missing package – many thanks! – so everything is in place now.
I updated the documentation at http://teic.github.io/TCW/tcw22.html, finally closing this ticket (while I am prepared that there might be issues during/after the next release, sigh)
