### ISSUE TITLE
Xenodata oddities

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1465]
A couple of minor things I just noticed when looking at the current spec for xenodata (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-xenoData.html)

1. "outside" isn't a very good translation for "xeno". "Alien" or perhaps "Externallydefined" ? Or dont supply a gloss at all.

2. The spec says this is an empty element, but the content model says it can contain text or anyXML.

3. Shouldnt the content model have a maxOccurs=unlimited on its alternation? or is that something to do with that weird anyXML macro we have to replace?

**Comment by hcayless** [comment]
1. Agree. "non-TEI metadata"?
2. Think this may be a Stylesheets bug. I notice the spec for egXML says the same.
3. Might be. The anyXML macro permits any number of non-TEI elements, so specifying maxOccurs would be redundant I guess. Might that make for a nondeterministic content model in schema?

**Comment by sydb** [comment]
1. IMHO it absolutely needs a gloss, but I am not sold on any of the options (outside, alien, externally defined).
2. By "spec" do you mean the "May contain" line in the tagdoc? If so, yes, I think this is a stylesheet bug. And furthermore, Hugh has already fixed it.
3. It is not the intent of this content model to permit text nodes intermingled with XML elements, but rather to allow either XML or, because people other than I insisted, JSON or some other non-XML blob. So no, I don't think there should be a `maxOccurs=unbounded` on the `<alternation>`. But other people may disaree.

**Comment by hcayless** [comment]
Changed the gloss to "non-TEI metadata."

**Comment by emylonas** [comment]
1. fixed
2. fixed
3. won't fix
see discussion of #1373
