### ISSUE TITLE
Deprecated attribute @render discussion needs revision

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1475]
The attribute @render on `<tagUsage>` is slated for removal in less than 6 months time. The discussion at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/HD.html#HD57-1 needs some extensive revision before that time.

**Comment by ebeshero** [comment]
See https://sourceforge.net/p/tei/feature-requests/520/

**Comment by ebeshero** [comment]
@martindholmes @sydb @jamescummings @lb42 I spent some time simplifying the examples in http://www.tei-c.org/release/doc/tei-p5-doc/en/html/HD.html#HD57-1 to eliminate the examples with `@render` on `<tagUsage>`. Since this is the first intensive revision I've attempted to make with the language of the Guidelines I'd appreciate it if you'd take a look and let me know if I need to alter anything further. Martin, I'm alerting you because I think you wrote some of the examples that we needed to revise.

**Comment by martindholmes** [comment]
@ebeshero This looks good to me, although I'd like to see a completed build to read it in context. When we get to that stage, if everyone's happy, do remove the commented-out bits.

**Comment by ebeshero** [comment]
Removed commented-out bits, per Council recommendation, so marking this closed.

**Comment by martindholmes** [comment]
I'm reopening this because the prose of the French Header chapter (Guidelines/fr/HD-Header.xml) still contains a reference to this attribute which needs to be fixed:

~~~~~
<p>Cette proposition autorise l’encodeur à saisir une description informelle de
restitution, ou style, sous forme de prose suivie libre uniquement. Il est compris que la
restitution s’applique, par défaut, à toutes les occurrences d’un élément qui nomme son
identifiant comme étant la valeur de l’attribut <att>render</att> de l’élément <gi>tagUsage
</gi> en question. Dans le cas d’occurrences d’un élément auxquelles la restitution par
défaut ne s’applique pas, l’encodeur devrait en donner une description précise et
explicite en utilisant l’attribut global <att>rend</att> pour les éléments en question.</p>
~~~~~

**Comment by martindholmes** [comment]
There's this egXML too:

~~~~~
<egXML xmlns="http://www.tei-c.org/ns/Examples"><tagsDecl>
   <rendition xml:id="style1">   
      ... description d’une restitution par défaut…
   </rendition>
   <rendition xml:id="style2">   
      ... description d’une autre restitution par défaut…
   </rendition>
   <namespace name="http://www.tei-c.org/ns/1.0">
   <tagUsage gi="p" render="#style1"> ... </tagUsage>
   <tagUsage gi="hi" render="#style2"> ... </tagUsage>
   </namespace>
</tagsDecl></egXML>
~~~~~

**Comment by ebeshero** [comment]
I self-assigned this ticket a while back when we were rewriting the explanation and examples in English. Is anyone else more confident than I am about editing the French version?

**Comment by lb42** [comment]
There are many many things that need revision in the Fr version!

**Comment by ebeshero** [comment]
@lb42 I'm looking at this ticket in the weekend before a refrigeration (prior to July 1 freeze before next release)...I could make a miserable attempt at translating my amended language into French, but something tells me you could do this faster than I could...Would you be willing to help with just this piece? You can see my revisions in this commit: https://github.com/TEIC/TEI/commit/fc92136e73fb29054b62f1171e5f40d313bb64dd

**Comment by ebeshero** [comment]
@martindholmes noted two areas to be fixed in the French Header chapter (Guidelines/fr/HD-Header.xml) and an egXML. Bet you could fix these in 5 minutes!

**Comment by sydb** [comment]
Since when do we keep a ticket (sorry, issue) open to reflect a change in another language? I don’t think (off the top of my head) we have **ever** done that before. Translation is a different problem, and we are well aware that the only entire chapter translated into a non-English language is somewhat behind.

**Comment by ebeshero** [comment]
Well, Martin reopened it because he thought the misdirection in the French version needed to be addressed. Perhaps this issue sets a precedent, though it seems generally we are turning more attention to translation maintenance in the Guidelines. I don't think this would be difficult to address for the TEI experts I know who are more fluent en Francais que moi.

**Comment by ebeshero** [comment]
When someone of us points out a specific passage or two that could be rendered accurate and up to date in non-English versions of Guidelines that we supposedly maintain, should we not try diligently to update them?

**Comment by lb42** [comment]
It all depends what level of maintenance is aimed at for the non-English parts. For example, I would have thought that maintaining  the non-English parts of the tagdocs should have a much higher priority than maintaining the text of a translated chapter,  since oXygen (for example) actually uses them. Yet I'm not aware that anyone ever thinks to update a non-English &lt;desc> or check a non-English &lt;exemplum> when updating their English equivalents. Why does this obscure part of a barely visible chapter merit special attention, especially when there are plenty of far more significant changes to the chapter which are not reflected in it? Cf #1341

**Comment by ebeshero** [comment]
I've carefully edited the parts of the French Header chapter that @martindholmes brought to light, to remove the deprecated use of `@render` on tagusage and updated the examples. Note: I tried to keep my edits to the prose minimal, but updated the examples to look more like those we now have in the English Guidelines.
