### ISSUE TITLE
Allow figure elements only in TEI/text/body

### ISSUE THREAD

**Issue by polypunkt** [TEIC/TEI#1485]
The schema doesn't allow a body containing only figure elements. In my case the TEI document should represent an image collection only. 
Of course, I could add an auxiliary div container but the schema would be much more consistent when figures were allowed as main body content as well. It would be definitely at least as useful as some of the tei_model.common elements that are allowed as body main content at the moment.

In my view a body containing only figure elements should be as well allowed as a body that contains only bibl elements (which is possible).
Integrating this feature would be no problem in respect to downwards compatiblity either, so perhaps the feature might be considered.

**Comment by lb42** [comment]
As far as I can see,  &lt;figure> is already permitted within &lt;body>. Did you perhaps forget to include the figures module in your schema?

**Comment by polypunkt** [comment]
I'm using the tei_allPlus.rng where figures are included, aren't they?
And figure is generally allowed in body that is true. But is it not allowed that body contains nothing else than figure elements.

**Comment by lb42** [comment]
Ah. Apologies, I didn't look closely enough. You are right: although &lt;body> can have a sequence of &lt;figure> elements, it requires this to be followed by at least one div or div1 like element. This is probably to avoid ambiguity. I will see if we can fix this. Meanwhile, may I ask what sort of a document it is that you are encoding that only has figures in it?

**Comment by polypunkt** [comment]
In this special case it is a part of a book containing only figures with their heads. This part is printed separately from the rest of the book and also set into a new file by the typesetters. For reasons of automated processing we convert this image part separately and later merge it into the rest of the main book.
And as I said, I can create an auxiliary div (did that now), but in respect to the other allowed common elements it would do no harm to allow that case. (We're trying to stay close to the original P5 schema and only added some additional attributes to be maximal compatible to other TEI workflows. So we do not want too extend the schema for that purpose).
So thanks for your open ear.

**Comment by lb42** [comment]
If it's "part of a book" why not put it inside a &lt;div> ?

**Comment by polypunkt** [comment]
We generate divs only when real headings exists. But as I said it is no problem to workaround this issue for us. The question is more a principal one: if elements like lists are allowed in body only, why not figures.

**Comment by lb42** [comment]
Ironically enough, the root cause of this apparent anomaly seems to be that &lt;figure> is a member of model.global, so as to permit it to appear anywhere in a content model. But the content model for body (and possibly other elements too) is carefully constructed to require the presence of at least one non-global element.  We should probably review the case for making figure global, rather than review the requirement that body etc have at least one non-global element.

**Comment by ebeshero** [comment]
Lou-- I'd have thought the other way, that figure remain global but that the restriction on body be lifted--but I am likely missing something important here. What problems do we face if body doesn't have to have a non-global element? I guess it seems less drastic to change figure than it does to change body and its ilk...Is that the idea?

Elisa

Typeset by hand on my iPad

**Comment by martindholmes** [comment]
I think removing `<figure>` from `model.global` will have horrible ramifications for other content models; to avoid backwards compatibility issues, I imagine we'd have to redefine a lot of existing content models in ways that make them far more ugly and complicated.

Is it a terrible imposition to require a `<div>` as the immediate child of `<body>` in this scenario? It seems a fairly benign constraint.

**Comment by lb42** [comment]
And if you remove the constraint that there must be at least one non global element, the content model becomes non deterministic. So a bit of an impasse really.

**Comment by ebeshero** [comment]
Reviewing our discussion of this, it seems pretty clear that `<body>` needs to contain one non-global element, and that `<figure>` needs to remain a member of `model.global`. The only solutions that seem feasible for the use-case of a TEI document whose body contains only `<figure>` elements would require a project-specific ODD redefinition of one or the other element, or the adding a `<div>`. And since the `<div>` poses problems for consistency in the project schema, I think the solution here needs to be to modify the project schema--If the project needs for `<figure>` elements to behave like list elements, the project could apply an ODD rule to reassign figure to `model.listLike`. Is that a fair recommendation?

**Comment by polypunkt** [comment]
Thank you for reviewing the issue.

I will talk to my colleagues whether to change our project's ODD  rules, but I guess we will keep the solution of the auxiliary container div in these cases, instead of changing our project's schmema. Thanks for considering changes, we just wanted to improve the general TEI schema.

**Comment by lb42** [comment]
Thanks for provoking this useful discussion! It shows that the thinking behind the TEI content models is not always straightforward, especially for complex things like &lt;body>. BTW I would certainly not recommend @beshero 's suggestion above, since (if I understand it correctly)  it would make your documents non-conformant. OK if you want to add your own element (&lt;my:figure>) in your own namespace of course, but that's different.
