### ISSUE TITLE
datatype of prefixDef/@ident

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1489]
`@ident` of `<prefixDef>` is formally defined as teidata.name, and in prose as “supplies a name which functions as the prefix for an abbreviated pointing scheme such as a private URI scheme. The prefix constitutes the text preceding the first colon.”

```
teidata.name = xsd:Name = (Letter | '_' | ':') ( Letter | Digit | '.' | '-' | '_' | ':' | CombiningChar | Extender )*
teidata.xmlName = xsd:NCName = (Letter | '_' ) ( Letter | Digit | '.' | '-' | '_' | CombiningChar | Extender )*
URI scheme = [a-z0-9+.-]+
```

If we are thinking of these as just a TEI shortcut, then the formal definition should be `teidata.xmlName`, so that a colon can’t creep in. If we are thinking of these as private URI schemes that TEI users get to use as shortcuts, then we should make up a special-purpose datatype just for this use. (Not because URI schemes allow ‘+’ and `teidata.xmlName` does not — that’s no big deal IMHO; but rather because `teidata.xmlName` allows ‘Θ’, ‘ሴ’, ‘䌡’, ‘A’, and ‘_’, which URI schemes do not.)

My instinct is that
1. These are shortcuts, so `teidata.xmlName` would do.
2. We would do well to add prose pointing out that if you actually want your shortcut URI to be valid as a URI, you should only use `[a-z0-9.-]+`.

**Comment by martindholmes** [comment]
Very good point. I believe we should stick to the strict definition and create a datatype based on the definition and regex defined here:

https://tools.ietf.org/html/rfc3986#section-3.1

**Comment by hcayless** [comment]
I agree with Martin.

**Comment by martindholmes** [comment]
I would propose this as the regex:

`[a-z][a-z\d\+\.\-]+`

Per the RFC, "Scheme names consist of a sequence of characters beginning with a letter and followed by any combination of letters, digits, plus ("+"), period ("."), or hyphen ("-").  Although schemes are case-insensitive, the canonical form is lowercase and documents that specify schemes must do so with lowercase letters." So I think it's reasonable to constrain it to lower-case letters in our case.

This would be a backwards-incompatible change, since it would disallow a range of characters including those unlikely to have been used (as in Syd's examples) and some which may well have been used (upper-case letters), so I believe we would need to use something like a deprecation mechanism; we could begin by introducing the constraint as a Schematron warning, and then progress to a full datatype constraint.

I'm not 100% sure whether non-ascii letters are allowed in the scheme, but I think not; there are no examples of non-ascii schemes that I can find, and RFC 3986 refers for its definition of ALPHA to RFC 2234, which specifies this: "ALPHA          =  %x41-5A / %x61-7A   ; A-Z / a-z".

The other question is whether this needs to be a datatype, or whether we'll never need it in any other context. For the moment, we should probably make it specific to this attribute definition, but make a note in the spec that it could be generalized if another usage context appears.

**Comment by emylonas** [comment]
fix  using Martin's regex. call the datatype teidata.prefix

**Comment by sydb** [comment]
OK. Changed as a corrigible error (i.e., no deprecation) at daf3258. But the regexp I used is
~~~~~
[a-z][a-z0-9\+\.\-]*
~~~~~
(Note the `*` instead of `+` at the end, there) because my reading of [the RFC](https://tools.ietf.org/html/rfc3986#section-3.1) is that a lone single letter **is** permitted.

For those who are interested in these things, note also that I left Martin’s backslashes in there. My reading of the [XML datatypes spec](http://www.w3.org/TR/xmlschema-2/) says that they are not needed. My validators say that only the one in front of the hyphen is required. But both say they are allowed, so it seems like leaving them is the more cautious way to go.
