### ISSUE TITLE
Clarify modelGrp semantics

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1494]
Re-reading the PM stuff with an implementor's perspective, and a lot of things are unclear...

Are modelGrp's children mutually exclusive? Is just the first matching model to be processed or all matching models? This should be made clear.
1. What is going on with the example in http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TD.html#TDPMMC? Are all the models in each group being processed, since they have no predicates? Or just the first one? 
2. "The child model elements of a modelGrp are always processed independently." What does "independently" mean? Are models ever processed any other way? They can't be pipelined (i.e. the output of one piped into another) can they?

**Comment by hcayless** [comment]
I suggest we adopt a rule like:

> A "matching" model is one where the element to be processed satisfies the XPath in the `@predicate` attribute of the model or modelSequence and the current output method matches the method specified in the `@output` attribute of the model, modelSequence, or a containing modelGrp. A model or modelSequence without a `@predicate` always matches the element to be processed. A model, modelGrp, or modelSequence without an `@output` attribute matches any output method.

>Processing Model implementations must execute only the first matching model or modelSequence in document order.

**Comment by jamescummings** [comment]
Answers:

1)  Erm. You are right, that example makes no sense to me. I mean it would make sense if they had predicate, otherwise I would expect only the first rule to fire.

2) That seems reasonable to me and the way I understood independently.  Independent I think is a poor choice of words -- they are processed separately not as a whole sequence to be processed. I think the reluctance on whether to legislate that it should be the 'first' or 'most specific' is because for an XSLT-type implementation it is easier to (basically) copy them to output and let the XSLT parser determine priority.  I think it would be fine for us to say the 'first matching model' and the modelSequence items should be applied in the order they appear in the odd.

**Comment by lb42** [comment]
Maybe that example should be using modelSequence?

**Comment by lb42** [comment]
Also, James, don't forget that "the order in which they are defined in an odd" is not an easily defined concept, since odds can contain multiple declaration s, and be chained together.

**Comment by jamescummings** [comment]
@lb42 You are right. And I guess what I mean there is the document order inside that specific modelSequence with any declarations resolved in the order they appear, and ignoring any chained together results.  (that is, that modelSequence should be treated as one individual object).  I think you probably know what I mean but I recognise I'm not very clear at expressing it.

**Comment by tuurma** [comment]
modelGrp was conceived as a convenient way of avoiding repeating certain attributes over and over again on model elements, specifically the output. It serves just as a shortcut or visual aid for the ODD writer. Such grouping or lack thereof must be of no significance to processing (bar the need to expand models with the attribute specified on modelGrp). Example thus needs to be rewritten as @jamescummings suggested to make any sense.

**Comment by tuurma** [comment]
Sorry, only now noticed that @jamescummings already did rewrite that unfortunate example with his c44738f4598350e999d45bd58644820ae9370ec6 commit. Since the way of choosing the model to apply was discussed in #1497 and during f2f in Vienna (not to mention it has nothing to do with modelGrp semantics) I take it we can remove 'needs discussion' label here and only action left is to substitute the 'processed independently' in http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TD.html#TDPMIP with something clearer.

It was:
> Individual model elements are processed independently, except when they appear within a  modelSequence

I'd suggest
> Only one of the `model`s is to be applied for a particular instance of the element, except when they appear  within a modelSequence

followed by discussion how to select the one matching model.
