### ISSUE TITLE
Use of `@next/@prev` versus `<join>` with `@scope/@result` and `@exclude` needs clarification

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1505]
This thread on TEI-L:

https://listserv.brown.edu/archives/cgi-bin/wa?A2=ind1609&L=TEI-L&F=&S=&X=6712D504851EFC4274&Y=mholmes%40uvic.ca&P=23954

reveals the need for some discussion and subsequent updates to the Guidelines, and possibly the specs, on how these features should be used in various contexts, specifically:

Should `@next/@prev` be recommended or allowed for linking different elements, or should they be restricted to elements with the same name?
When `<join>` is used to create a result elements from two or more components, how exactly should `@scope` function, and should we recommend and exemplify the use of `@exclude` to show how the constructed element should replace or mask the original components from which it's constructed.

**Comment by adiel-mittmann** [comment]
I have used `@next` more than once to link an `<l>` to a `<signed>`, as in the following example:
```xml
      <lg n="4">
        <l n="1">Eu só encontro no primor de rima</l>
        <l n="2">A justa oferta, a jóia que te exprima</l>
        <l next="#mano-augusto" n="3">O amor fraterno do teu mano</l>
      </lg>
      <closer>
        <signed xml:id="mano-augusto">Augusto.</signed>
        <dateline>Em 28 de abril de 1901</dateline>
      </closer>
```

Without linking the elements, the verse line would be metrically incomplete.  As discussed in the mailing list, a more semantically accurate alternative would be something like:

```xml
   <lg n="4">
        <l n="1">Eu só encontro no primor de rima</l>
        <l n="2">A justa oferta, a jóia que te exprima</l>
        <l xml:id="line4.3" n="3" exclude="#line4.3extended">O amor fraterno do teu mano</l>
        <join xml:id="line4.3extended" exclude="#line4.3" result="l" target="#line4.3 #mano-augusto" scope="branches"/>
      </lg>
      <closer>
        <signed xml:id="mano-augusto">Augusto.</signed>
        <dateline>Em 28 de abril de 1901</dateline>
      </closer>
```

However, the first example is less verbose, easier to read and, in my scenario (an automatic scansion tool), easier to process.

So, at least in my case, it would be simpler if I could just link elements of different names with `@next`.

**Comment by lb42** [comment]
I strongly feel that we should not use @next and @prev in this way. We should introduce a constraint that they must always point to elements of the same type, since the resulting element is of the same type. We should specify how their attributes are combined in the Guidelines.

**Comment by peterstadler** [comment]
Council subgroup agrees during Vienna F2F that the use of ```@next``` in the example given by @adiel-mittmann  is unusual, but not forbidden by the Guidelines.
We think we shouldn’t change the current practice but the current suggested practice by Guidelines and examples is to be preferred. 

No need seen for additional clarification of ```join/@scope``` unless someone produces a concrete proposal.

**Comment by hcayless** [comment]
@peterstadler Does this mean the ticket can be closed?

**Comment by peterstadler** [comment]
I can't remember whether we talked about this ticket with the whole Council or whether the minutes just reflect the subgroup's opinion. My personal opinion is to close the ticket since there is no concrete proposal on the table.

**Comment by lb42** [comment]
The proposal is to revise the wording so a s tomakeclearer that some combinations of attribute values make very little sense and are not recommended. I am happy to propose some text if necessary.

**Comment by hcayless** [comment]
@lb42 Please do!

**Comment by sydb** [comment]
The WWP applies 6 constraints above and beyond TEI’s to the values of `@next` and `@prev`:

1. each must not have internal whitespace (which are allowed in xs:anyURI, but make it look like there are multiple values, and could be encoded using, e.g., %20)
2. each must point to a local element (i.e., cannot point to a different file)
3. neither can point to the element upon which it is specified
4. each must point to an element of the same element type as the one it occurs on (the subject of this ticket)
5. `@next` must point to an element that occurs **later** in the file
6. `@prev` must point to an element that occurs **earlier** in the file

@martindholmes  and I agree that:

- 1 & 3 should be in the _Guidelines_
- 2, 5, & 6 should **not** be in the _Guidelines_, they are project-specific
- 4 needs further discussion by Council.

The sub-group that addressed this in Vienna seems to think 4 should **not** be in the _Guidelines_. I feel that if it were not for the backward-compatibility issue, we should put this constraint in the _Guidelines_. @martindholmes leans towards including this constraint, but only if we can figure out some sort of deprecation method (e.g., write the rule, and make it a warning for the first 18 months, then switch it to an error).

**Comment by lb42** [comment]
(1) surely applies to any attribute which has a value of (a single) anyURI; nothing special about @next or @prev in this respect. 
(2) (5) and (6) seem unduly restrictive to me and shouldnt go into the Guidelines
(3) and (4) seem like they need to be spelled out more clearly in the prose, since introducing a formal constraint to implement (4) might raise backwards compatibility concerns. 
FWIW, I think the OP's proposed encoding is just plain wrong :  it says that an element which is not tagged as a (partial) metrical line is to be considered as if it was one. This is because &lt;l> isn't permitted inside &lt;closer> I assume. But why not wrap the &lt;signature> inside a free standing partial &lt;l> if that's what it is?

**Comment by sydb** [comment]
Yes, `<l>` is not allowed in `<closer>`, and I think @lb42 ’s last suggestion is what I would recommend, too.

**Comment by adiel-mittmann** [comment]
I don't want to argue too much in favor of the encoding I described, but I do want to explain the reasoning behind it.

In my case, the poem is processed by two separate pieces of software: a stylesheet and a scansion tool.  Encoding the poem for just one of them is straightforward.  For the stylesheet, `<l>` would encode all poetic lines, except for the final word of the last verse, which would be encoded with the `<signed>` element; the idea is that this last word would be displayed as a regular signature and it's up to the reader to figure out that it's actually the last word of the last verse.  For the scansion tool, the last `<l>` element would simply contain the whole line, including the last word, and that would be it.

I used `@next` to be able to encode the poem for processing with both the stylesheet and the scansion tool, while keeping verbosity and complexity to a minimum.  The original suggestion to fix this (shown in my first reply) is way too complicated.

I could place the `<signed>` within a free-standing `<l>`, but this would confuse the stylesheet, because it expects this kind of material to be contained within a `<closer>`.  On the other hand, next to nothing would change for the scansion tool.  This would still be better than the original suggestion, though.

**Comment by hcayless** [comment]
Closed with 8c2f895  (which referenced the wrong issue)

**Comment by emylonas** [comment]
@lb42 to go ahead with his suggestion to spell out usage and constraints for items 3 and 4 in guidelines.  Also to add constraints to this effect in the schema.

**Comment by sydb** [comment]
Note on above: Council decided constraint does not need deprecation.
@lb42 — I have Schematron code for this already. I can send it to you, post it here, put it on the TEI wiki, or insert it directty into att.global.linking.xml. Whatever you prefer.

**Comment by lb42** [comment]
Have added recommendation in the classSpec and in the text of the Guidelines.
