### ISSUE TITLE
pb, lb, cb, gb 'beginning' 

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1529]
The gloss for pb, lb, cb, gb, elements all say 'page break' (or similar) while Council has previously said that it is good practice to put these at the beginning of each page, line, whatever. This might be encouraged if the glosses were changed to 'page beginning' (or similar). 

(This suggestion came from a student in a workshop I was teaching.)

**Comment by tuurma** [comment]
Support, this is actually how I teach it for quite a while

**Comment by lb42** [comment]
I thought we'd already made that change ... Certainly it's what the description says

**Comment by hcayless** [comment]
I think do it. Making it green.

**Comment by martinascholger** [comment]
In this context I'd suggest to harmonize the descriptions, starting with "marks the beginning of...". This would make internationalizations easier.

**Comment by martindholmes** [comment]
Really good idea.

**Comment by PFSchaffner** [comment]
"Beginning" seems to me ambiguous, and potentially misleading. I use the 'break' tags to mark the point at which the text moves onto another page/column/etc.  This may or may not be the 'beginning' of the page (if that means the top), since the text may travel onto the same page more than once, and at more than one physical point: each journey onto that page, regardless of where on the page it occurs, marks a new 'beginning' or 'start.' In other words, I take 'beginning' or 'start' to mark a point in a (reading) process, not a physical point, and the same page may contain more than one such beginning. (1) Do others do the same? (2) If not, how do you mark movement of the text sequence onto a new page at a point other than the physical 'start'?

**Comment by schassan** [comment]
Combined answer to the ambiguity and question (2): "Beginning" might not be ambiguous if you think about the serialisation ("linearisation"?) that takes place during the representation of text in XML: Ideally, you first have to pass the "breaking point" in order to arrive at the new page, column, line, whatever. And the text might be geographically placed wherever but as a stream of text it just goes on. This is my idea behind the expression "beginning".
Besides, text usually starts only once on a new page, line, etc wherever the beginning (geographically) is. There might be line or column breaks all over the page but once you've reached the end of that "division", a break will take you to the next one of the same kind. Thus, if a text starts twice on the same page, you would end up with two page breaks but you wouldn't interpret it as two columns with column breaks then, right?
Example: Parallel versions of bible texts in different languages, where each language runs separately in its own column across the pages. One would have two or more page breaks but no column break since the text doesn't break from one language to the other but only from one page to the next?

**Comment by jamescummings** [comment]
Check the glosses.

James

--
Dr James Cummings, Academic IT Services, University of Oxford

On 28 Oct 2016 12:19 p.m., Lou <notifications@github.com> wrote:

I thought we'd already made that change ... Certainly it's what the description says

**Comment by jamescummings** [comment]
Currently the glosses and descriptions of these are:


1. `<pb>` (page break) marks the start of a new page in a paginated document
2. `<lb>` (line break) marks the start of a new (typographic) line in some edition or version of a text.
3. `<cb>` (column break) marks the beginning of a new column of a text on a multi-column page.
4. `<gb>` (gathering begins) marks the point in a transcribed codex at which a new gathering or quire begins.

The current proposal would changes this to:

1. `<pb>` (page **beginning**) marks the **beginning** of a new page in a paginated document.
2. `<lb>` (line **beginning**) marks the **beginning** of a new (typographic) line in some edition or version of a text.
3. `<cb>` (column **beginning**) marks the beginning of a new column of a text on a multi-column page.
4. `<gb>` (gathering **beginning**) marks the **beginning of a new gathering or quire in a transcribed codex**.

A. If you agree with this proposal please add a 'thumbs up' vote (click on the + smiley face on the right-hand side and select thumbs up). 

B. If you disagree with this proposal please add a 'thumbs down' and comment on what change would make you accept it.

Thanks!

**Comment by PFSchaffner** [comment]
No worse and a little better than what's been there hitherto. Better not just because it is more consistent but because by being more explicitly verbal, it at least allows interpretation as representing an event in the transcription process rather than a spot on the page (as per my demurrals above : this is the point at which you start transcribing from a different page/column/line). It does not, of course, address the commonest question (sequence of tags when a page (break) beginning coincides with a structural (break) beginning), but I suppose it wasn't intended to.
