### ISSUE TITLE
move sample values from description of gap/@reason to <valList>

### ISSUE THREAD

**Issue by peterstadler** [TEIC/TEI#1534]
In the description of ```gap/@reason``` several sample values are named: 

```
<desc versionDate="2008-10-03" xml:lang="en">gives the reason for omission. Sample values include <val>sampling</val>,
        <val>inaudible</val>, <val>irrelevant</val>, <val>cancelled</val>.</desc>
```

I propose to move these to an open <valList> instead (and use the translations as glosses of the values).

**Comment by sydb** [comment]
Done at 0d1fd50, assuming Mr. Jenkins approves. BUT:

1. I was unable to create glosses for ko, zh-TW, and ja
2. Native speakers of de, es, fr, and it should check those glosses
3. We added "deleted" as a value because @emylonas asserted we used it in an example; I don’t think we do. See list below.
4. I added "editorial" (as the description mentions this situation)
5. There are several uses of `@reason` on `<gap>` in the _Guidelines_ (almost certainly in examples) that probably need to be changed.

Here is a list of `@reason` on `<gap>` in the _Guidelines_:

  13 gap/@reason=illegible
   5 gap/@reason=sampling
   2 gap/@reason=cancelled
   2 gap/@reason=lost&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;# not in list
   1 gap/@reason=inDéchiffrable&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;# not in list
   1 gap/@reason=overwriting illegible&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;# ½ not in list; and wouldn’t "overwriting" be `@agent`?
   1 gap/@reason=passing-truck&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;# should be `@agent`, I think (`@reason` should be "inaudible"
   1 gap/@reason=抽樣
   1 gap/@reason=無法識讀

**Comment by emylonas** [comment]
@sydb No idea what I was thinking. I withdraw my support for `deleted` as a value.
