### ISSUE TITLE
no schema error when using `@ed` with a pointer

### ISSUE THREAD

**Issue by jeffreycwitt** [TEIC/TEI#1537]
Recently, we learned (see our issue here: https://github.com/lombardpress/lombardpress-schema/issues/76) that our use of `@ed` with a pointer (for example on a line break) is out of sync with the TEI guidelines, which says `@ed` should not take a pointer (see http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.edition.html). Apparently, we should be using `@edRef`.

But since I've been using a pointer (e.g. `ed="#something"`) for five or so years and never received a validation error from Oxygen, I wonder if this is a rule that is not being correctly enforced by the general TEI schema. (Or should I not be expecting the TEI schema to enforce rules at this level). 

I'm going to write my own schematron rule to enforce this in our work, but I was curious why the general TEI schema is not already enforcing this. Could this be a possible bug in the general schema.?

Thanks for your help.

**Comment by lb42** [comment]
@ed is defined in the schema with a datatype of teidata.word. This datatype permits more or less any sequence of unicode characters, including # . So you could say ed="####!" or ed="*#jkl" or ed="f¥¶√•▓oo" for that matter. The only thing not permitted in a teidata.word value is spaces. (However, since the attribute is defined as permitting *one or more* such values, you can also say ed="foo bar" ... but this is processed as meaning two values "foo" and "bar", rather than a single value "foo bar". If you care.)  To answer your question: the presence of a # at the start of the value does not necessarily imply a pointer! In a similarly annoying way, the *absence* of a # at the start of a value for @edRef is not necessarily an error, since "foo" is a perfectly valid (though probably wrong) way of pointing to a resource.

**Comment by jeffreycwitt** [comment]
@lb42 many thanks. This is a very helpful explanation.
