### ISSUE TITLE
Modify remarks in <relatedItem>, <set> and <profileDesc>

### ISSUE THREAD

**Issue by martinascholger** [TEIC/TEI#1541]
The remark of `<relatedItem>`  says "If the target attribute is used to reference the related bibliographic item, the element should be empty." Actually, if the target attribute is used the element must be empty. I suggest to change "should" to "must".

`<set>`: "...This element should not be used outside the front matter". 
There is an example providing the `<set>` element within the back matter as well. I suggest to change the remark to "front or back matter".

`<profileDesc>`: "Although the content model permits it, it is rarely meaningful to supply multiple occurrences for any of the child elements of profileDesc unless these are documenting multiple texts. In earlier versions of these Guidelines, it was required that the creation element appear first."
I suggest to remove the second sentence, since I think that referring to outdated variants is not relevant and potentially confusing.

**Comment by sydb** [comment]
1. [On `<relatedItem>`]: I agree, should just be changed as corrigible error IMHO.
1. [On `<set>`]: I agree, but would prefer more informative wording. How about “This element should be used within the front or back matter; for similar contextual descriptions within the body of the text, use the <gi>stage</gi> element.”?
1. [On `<profileDesc>`]: I would to know more about this before we nuke that sentence. What previous versions are being referred to? In P4 the order of all child elements was strictly spelled out, not just `<creation>`.

**Comment by lb42** [comment]
On (3) the purpose of that sentence was presumably to warn that earlier versions of the Guidelines did specify a particular order for the children of profileDesc, but that now (since the introduction of the class model.profileDescPart) they can appear in any order.I agree with Martina that the sentence is unimportant  it's not as if previously valid documents become invalid as a result of a change. Rather the reverse in fact.

**Comment by sydb** [comment]
@lb42 : While I think in the big picture you’re right, it is **not** the case that “since the introduction of _model.profileDescPart_ they can appear in any order”. I’m not sure exactly when _model.profileDescPart_ was introduced, but it was before the release of P5 1.0.0. The content model of `<profileDesc>` required `<creation>` first from P5 1.0.0 up to 1.6.0; in 1.7.0 `<creation>` got added to _model.profileDescPart_ and thus was no longer required first. (And presumably, this note was added.) But why did we think it important to have `<creation>` first? I just don’t remember.

**Comment by martinascholger** [comment]
On (2): That's exactly what we currently have in the Guidelines. It wasn't my intention to delete the second part of the sentence. 

I take (1) and (2) as a "Go", what about (3)? @sydb do you want to keep track on this, before I delete the sentence or can I go ahead?

**Comment by martinascholger** [comment]
Closed with 0e9a482
