### ISSUE TITLE
Should default for @maxOccurs be unbounded?

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1544]
At present the default value for @maxOccurs is 1 which leads to a contradictory situation if @minOccurs is supplied with a value greater than 1. Clearly if I say @minOccurs=3 I am expecting at least 3 occurrences, and maybe more, whatever the notional default for @maxOccurs might be. Possible solutions might be (a) some clever schematron rule (b) abolish default value (c) set default value to unbounded. I prefer the last, I think.

**Comment by sydb** [comment]
Can’t just have (c) a default `@maxOccurs` of `"unbounded"`, because then a simple reference like
~~~~~xml
<elementRef key="body"/>
~~~~~
or
~~~~~xml
<datatype><dataRef key="teidata.count"/><datatype>
~~~~~
would allow an infinite number of `<body>`s or integers.

**Comment by sydb** [comment]
Would be quite reasonable, IMHO to have 
d) a rule that if `@minOccurs` is specified, then `@maxOccurs` must be specified. (This might be the same as Lou’s (a), not sure.)
e) an explanation that the default value of `@maxOccurs` is 1 **unless** `@minOccurs` is greater than 1, in which case the default value is `unbounded`.
f) an explanation that the default value of `@maxOccurs` is 1 **unless** `@minOccurs` is greater than 1, in which case the default value is the same as the value specified for `@minOccurs`.

I like the proposals in order (best to least favorite): (d), (e), (b), (f), (c). At least for now. :-)

In all of these cases a rule that says `@maxOccurs` must be ≥ `@minOccurs` (whether specified or defaulted) is a good idea.

**Comment by sydb** [comment]
P.S. — I’m not sure this is a release blocker. It has been broken for a really long time, hasn’t it?

**Comment by lb42** [comment]
Default values. They are almost as much of a pain as namespaces. Anyway, yes, Syd is right : we can't make maxOccurs default to unbounded. So, I now vote for option (d). Which indeed can be expressed in ODD, and which our current stylesheets seem to process correctly to relaxng at least, as far as I've tested it.

**Comment by lb42** [comment]
[See also Martin's comment reminding us about 
https://github.com/TEIC/Stylesheets/issues/190]

**Comment by ebeshero** [comment]
My read of this favors option d): IF `@minOccurs` is specified THEN `@maxOccurs` must be specified too. It seems the most flexible and adaptable solution, since you can set minOccurs as some specific value and maxOccurs as unbounded as needed. Or you can tightly control things and set minOccurs to zero and maxOccurs to 1.
Option e) sets a couple of conditions for the default value of maxOccurs, and does nothing with minOccurs: Is that an issue in itself? (Is there currently a default on @minOccurs?)

**Comment by sydb** [comment]
Another possible solution, (g): do what W3C does for XSD:
- use defaults of `1`
- accept the consequences thereof:
1. if `@minOccurs` is ≥ 2, then `@maxOccurs` is required
1. if `@minOccurs` is **not** specified and `@maxOccurs` is, then it must be ≥ 1 (i.e. 0 is invalid)
1. if `@maxOccurs` is **not** specified and `@minOccurs` is, then it must be set to 0 or 1

See [this list post](http://lists.lists.tei-c.org/pipermail/tei-council/2016/023767.html), the [stack overflow answer I found](http://stackoverflow.com/questions/4821477/xml-schema-minoccurs-maxoccurs-default-values), and [XML Schema itself](http://www.w3.org/TR/xmlschema-0/#OccurrenceConstraints).

**Comment by raffazizzi** [comment]
I think d) is perfectly reasonable, though g) may be more comprehensive, but more work to implement.

**Comment by emylonas** [comment]
d) seems to be the simplest and most explicit. agree with Raf that g) is
more comprehensive, but requires more rules as well as more understanding
on the part of the human.

[Elli Mylonas
 Senior Digital Humanities Librarian
 and
 Center for Digital Scholarship
 University Library
 Brown University
 library.brown.edu/cds]

**Comment by hcayless** [comment]
The XSD rules all fall out from there being default values for these attributes. If we don't do default values, then both are required, right? d) means there's a default value for `@minOccurs` (presumably 1?) and none for `@maxOccurs`. That seems inconsistent. I think we probably ought to either do what XSD does or just make them both required.

**Comment by lb42** [comment]
Making them both required is a major pain for the 90℅ case of 1 for both.

**Comment by sydb** [comment]
Sorry for the delay … meetings all morning.

After a minor epiphany when I awoke this morning, I am now convinced that (g) is the way to go.

1. Mimics what W3C does, and thus what some folks are familiar with.
1. Does not require a change in long-standing TEI documented values.
1. Not particularly hard to code, I don’t think (this was part of the epiphany).
1. My big concern for (d) or (g) was that the stylesheets would still have to contend with odd combinations of these attrs, because errors in encoding them are likely to slip by validation. BUT there is an easy way around this. No matter what the values of `@minOcurrs` and `@maxOccurs` are, the stylesheets should produce output as though `@minOccurs` were `min( $minOccurs, $maxOccurs)` and `@maxOccurs` were `max( $minOccurs, $maxOccurs )`. (Where the definitions of these functions are a bit funky, because they have to deal with `"unboudned"`, too.)

Unless there is serious objection quite soon, I’ll probably start working on this tonight — both the constraint end and the stylesheet end.

P.S. @lb42 — when I tried to get the snippet of nested `<attList>`s above to generate something like
~~~~~
  ( @maxOccurs ) | ( @minOccurs, @maxOccurs )
~~~~~
it didn’t work _at all_. Can you post a sample that does work? Maybe I’m doing something wrong.

**Comment by lb42** [comment]
I think we're making this overly complicated. Let's not forget that we don't have to validate document instances; we just have to ensure that the schema we generate from our ODD declaration is valid  in the target schema language and at least approximates in its effect what the ODD says. We also have the luxury of being able to decide what the schema says irrespective of what the ODD says, which is particularly  handy in the  presence of default values.

 I suggest that we solve this problem by always supplying a value for both attributes if either is specified in the ODD, rather than relying on the @default behaviour.

- if both @min and @max are already present : do the right thing (ideally, pass the values on to XSD; generate some suitable pattern for RNG, eytc). We could decide that any value for @max greater than say 10 is to be traeated as  unbounded. We could add a schematreon check that @max is > @min.
- if only @max is specified, treat as if @min were 1
- if only @min is specified,
   if @min > 1, treat as if @max were unbounded. 
[Though I can  also see an argument for saying that @max should be set to @min in this case]
– if @min <1,  set @max to 1

I'm working on the attlist thing, but am currently stumped by a bizarre but I think unrelated schematron error.

**Comment by jamescummings** [comment]
That sounds reasonable to me.  
My general feeling is that `@min` should always be 1 unless specified.  `@max` should always be 'unbounded' unless specified.  So I'm a little confused by the very last option there, but otherwise I think your suggestions match my intuition about how it should work.

**Comment by lb42** [comment]
You're forgetting (as I did) the most common case where neither is specified. Which does NOT mean 1 to unbounded, but 1 to 1..

**Comment by jamescummings** [comment]
Ah. I suppose that makes sense. Though if you told me that if you don't specify then it is unbounded I could also have lived with that ... but meaning 1 matches what I understand in schema languages.

**Comment by sydb** [comment]
Sorry, @lb42 , I think maybe we’re talking at cross-purposes. I have never suggested (or at least, never meant to suggest) that it matters a whit what default value for either `@minOccurs` or `@maxOccurs` is actually supplied by a schema against which an ODD is validated. I am only talking about a) how we document them, and thus how the user should think of ’em, and b) what the stylesheet should do when one or the other is not specified. (We all agree, I think, that it should do 1 and only 1 if neither is specified.)

So I reiterate that (g) is the right solution for the documentation. If we do that, the stylesheets need to DTRT whenever the input is valid: i.e., when `@maxOccurs` ≥ `@minOccurs`. What the stylesheets do when the input is invalid (which I wasted a lot of my previous post on) is not really all that important.

Note that (g) is very much like @lb42 ’s suggestion of ~21:23Z. The only real difference is that specifying only `@minOccurs` as > 1 is an error.

Until you have the `<attList>` thing working, I’ll presume that we’re using `<constraintSpec>` for this.

**Comment by ebeshero** [comment]
My head is spinning, looking at option g). Can we please take another look at it? @sydb wrote:

Another possible solution, (g): do what W3C does for XSD:

use defaults of 1
accept the consequences thereof:
if @minOccurs is ≥ 2, then @maxOccurs is required
if @minOccurs is not specified and @maxOccurs is, then it must be ≥ 1 (i.e. 0 is invalid)
if @maxOccurs is not specified and @minOccurs is, then it must be set to 0 or 1

Everything except the *last* if statement looks right to me when I go and look at the XML schema. But I don't understand the last bit: if @maxOccurs is not specified, and @minOccurs is, then it must be set to 0 or 1? Is that a typo or something? Why would you set @maxOccurs to 0 or 1 in this case? Why wouldn't it be 1 or unbounded?

**Comment by lb42** [comment]
Now I'm confused! We're certainly not talking about how an *ODD* is validated! We're talking about how it is processed, so as to generate a schema, against which document instances will be validated. Fortunately though, we seem to be in vigorous agreement about what we expect to happen for each of the following cases
  - neither @min nor @max is present (schema will assume both are 1
  - both @min and @max are present  (schema will believe what it says
  - only @max (schema assumes @min = 1 

 We disagree on what we expect to happen if only @min is supplied
 - ODD processor flags an error and refuses to continue (I don't like that at all)
 - generated schema will assume @max of unbounded if min >1, or 1 otherwise  (my fave)
 - generated schema will assume @max same as @min (could live with it)

**Comment by sydb** [comment]
Comited ~6 hours ago at 7edb48e. It worked fine on my local build, but since the TEIP5-dev build on Jenkins is already broken for some other reason (looks like letex/PDF stuff), it’s hard to be sure Mr. Jenkins would be happy.

**Comment by sydb** [comment]
(In response to @lb42 of just under an hour ago)

Sure, we care about how an ODD is validated! Seems pretty important to me. (After all, this ticket is in the TEI tree, not the Stylesheets tree; that was on purpose, IIRC.) And, in fact, the commit mentioned above improves the validation of ODDs just so.

As for the Stylesheets, yes, the only point of concern now is what to do if only `@minOccurs` is supplied. Right now they assume `@maxOccurs` is the same as `@minOccurs`. I have no significant objection to changing that behavior. As I said, I don’t think we should fret about invalid input all that much.

**Comment by sydb** [comment]
(In reponse to @ebeshero of ~12 hrs ago)

I think I must not have expressed that very well, then. Let me try from the other angle. (And remember, we’re talking about validation here — what a user is and is not allowed to put in her ODD. Given that it’s you I’m talking to, I should probably talk in Schematron. In fact, you should take a look at the Schematron in [att.repeatable](http://jenkins.tei-c.org/view/TEI%20dev/job/TEIP5-dev/lastBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-att.repeatable.html).)

Basically, there are two rules:
1. the default value is 1
2. `@minOccurs` cannot be more than `@maxOccurs`

That’s all. So if you don’t have a `@maxOccurs` then it is 1, and `@minOccurs` better not be more than 1, or the combination is invalid.

`@minOccurs` | `@maxOccurs` | valid? | result 
-----|-----|-----|-----
absent | absent | yes | 1
absent | 0 | NO | ?
absent | 1 | yes | 1
absent | 2 | yes | 1–2
absent | unbounded | yes | 1–∞
0 | absent | yes | 0–1
0 | 0 | yes | 0
0 | 1 | yes | 0–1
0 | 2 | yes | 0–2
0 | unbounded | yes | 0–∞
1 | absent | yes | 1
1 | 0 | NO | ?
1 | 1 | yes | 1
1 | 2 | yes | 1–2
1 | unbounded | yes | 1–∞
2 | absent | NO | ?
2 | 0 | NO | ?
2 | 1 | NO | ?
2 | 2 | yes | 2
2 | unbounded | yes | 2–∞

(For any row of the table you can replace all the “2”s with “7” or “17” or whatever you want.)

And to re-state my position: if I were designing the system from scratch I would probably go with (e) above, because I agree with @lb42 that it is a natural way to go — it is what a user who has not read the documentation might expect. But we have several years of history in which we have explicitly stated the default values are 1, and these attributes are based on a well-established system (the W3C’s) that uses this approach (g).

**Comment by lb42** [comment]
There must be an upper limit to the values of @maxOccurs and @minOccurs which the stylesheets can plausibly support when generating equivalent RELAX NG patterns, surely? 
~~~~
<elementRef key="foo" minOccurs="42" maxOccurs="57"/> 
~~~~
is not going to turn into a pattern with 42 foos I hope...

**Comment by martindholmes** [comment]
@lb42: From long experience writing desktop applications, I would say that whenever you arbitrarily decide on a limit which is "big enough for any real-world scenario that would arise", some user comes along and wants it to be bigger. We once had someone complain that our arbitrary limit of 100 answers to a multiple-choice question was too small, because he needed 140. It's far simpler in the long run to go with truly unbounded.

**Comment by lb42** [comment]
@martindholmes yes, that's my experience too.  But the ODD language permits such things, so the stylesheets have to decide how to convert them to RELAXNG. If the number of repetitions is manageable, I think Syd's policy is to generate a pattern such as ((a,a,a), a?, a?) for a @min of 3 and a @max of 5. But for some value of @max, it must be better to say ((a,a,a), a*). I am wondering what that value is.

**Comment by sydb** [comment]
I don't know what that number should be, either. It is currently the `maxint` parameter to teiodds.xsl, with a default value of 42.

**Comment by hcayless** [comment]
My inclination is to say that if you write nutty ODDs, you'll get nutty schemas and leave it at that. If someone wants between 500 and 503 occurrences of something, who are we to say they can't have it?

**Comment by hcayless** [comment]
@sydb where are we with this one? It's the last remaining issue in the milestone now.

**Comment by sydb** [comment]
Looking at it now, @hcayless .

**Comment by lb42** [comment]
Still seems broken to me. I just tried generating relaxng and dtd from testerrmav.odd using current builds of P5 and Stylesheets. The definition of abbr in the ODD has a child hi with a @minOccurs of 3 (but no @maxOccurs).  This generates a RelaxNG model of (hi,hi,hi) which is not wrong, but not entirely right either. The DTD it generates is syntactically invalid, which is definitely wrong, imffho.

**Comment by sydb** [comment]
Short answer: I think this issue is finished. I've implemented (g), and as far as I can tell, it has been pulled into dev and works.

However, I implemented (g) without full consensus, so you might want to give people a(nother) chance to object.

It seems people still want to debate what should happen when the stylesheets get invalid input (e.g., a `@minOccurs` that is greater than `@maxOccurs`, which happens when `@minOccurs` is set to 2 and `@maxOccurs` is not specified), and what the default value of $maxint should be (if any). But those (IMHO) are not release blockers, and belong on a ticket in the Stylesheets repo, to boot.

**Comment by sydb** [comment]
All that said, I’m a bit worried that the Stylesheets are still generating invalid DTD and XSD. Will check into that in an hour or so.

**Comment by lb42** [comment]
Generating invalid DTD/XSD  is more than a bit worrying. It is release blocking. Especially because the ODD processor gives no indication at all that something has gone wrong.

**Comment by sydb** [comment]
Agreed, but it’s not this ticket. And I could swear I fixed it and had it working. Did I check it in incorrectly? Looking around my HD now …

**Comment by lb42** [comment]
Also a content model like this 
~~~~
       <elementRef key="name" minOccurs="2" maxOccurs="4"/>
~~~~
generates the following DTD content
~~~~
(((title)?,(name,name,name,name)+))
~~~~
which is valid but wrong!

**Comment by sydb** [comment]
Right, that’s messed up, and I can reproduce that problem. But it‘s not this ticket.

**Comment by hcayless** [comment]
Can we close this now?

**Comment by lb42** [comment]
Not until the doc is updated to clearly express what each possible combination of @minOccurs and @maxOccurs is intended to mean

**Comment by sydb** [comment]
You don’t think it is clear already? What combination do you think is undocumented?

**Comment by lb42** [comment]
I've added &lt;remarks> element containing (more or less) the text that was in the &lt;desc> of the constraintSpec. I also removed the XML comments which were cluttering up the generated HTML. So now, I think this can be closed.

**Comment by lb42** [comment]
I'm trying to update the doc, but Mr GitHub won't let me. Hang on.

**Comment by hcayless** [comment]
I had done the same thing :-). Yours is probably better!

**Comment by lb42** [comment]
OK, have now added new remarks, I hope satisfactory.
