### ISSUE TITLE
encoding in descriptions inconsistent

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1549]
We are completely inconsistent as to whether or not an element name inside a `<desc>` is encoded as a `<gi>` or not. Here is the list of the elements I found whose `<desc>` (probably) needs a `<gi>` just by searching for the word “element”.

- TEI
- teiCorpus
- metSym — either “symbol element” should be just “symbol”, or “`<metSym>` element”, no?
- castGroup
- joinGrp
- iff
- fLib — maybe “feature elements” should be “`<f>` elements”?
- eTree — also needs “the” added, IMHO
- triangle??
- eLeaf
- modelGrp
- modelSequence

**Comment by ebeshero** [comment]
Signal Martina when done re how to deal with the German implementation. Also update https://github.com/TEIC/Documentation/tree/master/TCW to say that we should use use both `<gi>` (or `<att>`) and “element” (or “attribute”). Also to use “a” or “an” in front of an attribute name based on its name, not on the “@” :-)

**Comment by scstanley7** [comment]
Two questions before I close this one:
* should I change to "feature" to `<f>` element on fLib, or is this not understandable enough? Is it appropriate to say something like "<f> (feature) elements"?
* should triangle's desc be changed to "embedded tree" rather than `<gi>eTree</gi>` It seems to be referring to the thing that is being encoded rather than the `<eTree>` element itself.
