### ISSUE TITLE
<listRelation> as child element of <body>

### ISSUE THREAD

**Issue by jze** [TEIC/TEI#1552]
The `<listRelation>` element should be allowed as child element of `<body>`. 

On page 880 of the guidelines (revision 89ba24e) only these elements from the "namesdates" module are allowed: `listEvent listNym listOrg listPerson listPlace`. However, `listRelation` is missing.

**Comment by martindholmes** [comment]
To clarify: it's not that specific revision which introduced the change.

**Comment by martinascholger** [comment]
The example in the specs [listRelation](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-listRelation.html) is not valid, since `listRelation` has to be a child of `listPerson`, `listPlace` etc.

**Comment by ebeshero** [comment]
F2F subgroup recommends we add listRelation to model.listLike, so it may be a sibling of listPerson, listPlace, etc.

**Comment by martinascholger** [comment]
We made no final decision at the F2F in Prague, since we ended up with the discussion on "linked data block". 
I can probably see a necessity to have the <`listRelation`> as sibling of <`listPerson`>, <`listPlace`>, etc. to indicate cross-references among these elements. But the relations can currently be expressed as child of eg. <`listPerson`>. What would be the actual benefit of <`listRelation`> as a sibling or the disadvantage in keeping it as it is?

**Comment by StefanDumont** [comment]
I don't know the discussion on "linked data block", but I think it would be helpful, if `<listRelation>` could be used "stand alone" in a TEI document. We consider to develop a feature in our digital working environment for encoding relations between different types of entities with the help of the TEI element `<listRelation>`. At the moment we plan to store these relations in a seperate TEI file - that's why I would appreciate if `<listRelation>` would be member of `model.listLike`.

**Comment by ebeshero** [comment]
I remember we discussed this in context with linked open data, but don't remember a "block" or a concept of blockage. Indeed, in my own projects I keep multiple lists of different kinds of named entities (people, places, organizations, books, artworks, plants, animals. In applying listRelation in such an environment, relationships might be described as initiated in terms of any of these named kinds of entities, so I'd like to "free" listRelation from having to be a child of any single list. It should be free-standing, and a member of model.listLike. 

On this topic, I just took a terrific course on RDF and LOD at the Digital Humanities Summer Institute, and discussed with the instructor (as the TEI-head in the room to someone who'd worked on the Shelley-Godwin Archive) the matter of how TEI can best contribute to LOD. Listrelation by itself is not going to suffice, but it can be a starting point for mapping to RDF vocabularies. I'd like to see some serious work on this to model some examples to the TEI community (with input from various projects), and I'd like to see the Ontologies SIG activated on it...anyway, I intend to be working on it in my projects.

**Comment by martinascholger** [comment]
Sounds convincing to me. If there are no strong objections until Saturday, I set this to green an implement it.

**Comment by martinascholger** [comment]
I suggest to add this example: 

```
<listPerson>
    <person xml:id="pp1">
        <!-- data about person pp1 -->
    </person>
    <person xml:id="pp2">
        <!-- data about person pp2 -->
    </person>
    <!-- more person (pp2, pp3) elements here -->
</listPerson>

<listPlace>
    <place xml:id="pl1">
        <!-- data about place pl1 -->
    </place>
    <!-- more place (pl2, pl3) elements here -->
</listPlace>

<listRelation>
    <relation name="residence" active="#pp1 #pp2" passive="#pl2"/>
</listRelation>
```
The persons with identifiers pp1 and pp2 live in pl1.

**Comment by martinascholger** [comment]
Implemented with f46e110. Mr. Jenkins didn't complain, but how can I make sure that `<listRelation>` can really be a child of `<body>` now?

**Comment by sydb** [comment]
I just tested (by building locally and validating a tiny test doc), and `<listRelation>` is allowed inside `<body>` (and `<title>`; and also `<p>` and `<l>` and `<rendition>` and `<u>` and `<damage>`).

**Comment by martinascholger** [comment]
Thank you, @sydb!

**Comment by martindholmes** [comment]
You can also create a new XML document linked to:

http://jenkins.tei-c.org/job/TEIP5-dev/2906/artifact/P5/release/xml/tei/custom/schema/relaxng/tei_all.rng

**Comment by martinascholger** [comment]
Thank you @martindholmes! I used the wrong link. It works now.
