### ISSUE TITLE
teidata.namespaceOrName is not restrictive enough

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1570]
The new teidata.namespaceOrName says it “defines attribute values which contain either a namespace URI or an XML name”.
Besides the fact that the description says it defines attribute values (it can be used to define element content just as easily), the datatype permits an xs:Name (in addition to a namespace), but both places it is used (anyElement/@except and schemaSpec/@defaultExceptions) say “prefixed element names”. So it would be more appropriate if the datatype only permitted an xs:QName, or, equivalently, restricted the xs:Name to those that contain one and only one colon, not in the last position.

**Comment by hcayless** [comment]
Yeah, that's a fair point. It should technically be a QName. It's all a bit academic, because namespace is AnyURI (a superset of Name/QName) and so we can't actually restrict the value in any useful way. Any QName could equally well be a URI after all.  I'd say this is pretty low-priority, but we can fix it in the next release.

**Comment by Conal-Tuohy** [comment]
I would say the [`teidata.namespace`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-teidata.namespace.html) data type shouldn't be declared to be `xsd:anyURI`; it should be restricted to absolute URIs. See https://www.w3.org/2000/09/xppa


https://www.w3.org/TR/xpath-30/#doc-xpath30-BracedURILiteral

**Comment by martindholmes** [comment]
There's an example here: https://www.w3.org/TR/1999/REC-xml-names-19990114/#ns-expnames  showing an ns value of:

xmlns='urn:com:books-r-us'

So I think the idea of a single-colon restriction must be wrong.

**Comment by Conal-Tuohy** [comment]
I know the EAC-CPF schema actually does use the namespace `urn:isbn:1-931666-33-4`

**Comment by hcayless** [comment]
Yeah, the single colon idea is a non-starter, though Syd didn't suggest that as a restriction for the Namespace part, just the Name. Namespaces can be any absolute URI, and that's all there is to it. I only created the type because Lou argued that just making it teidata.namespace (which is xsd:anyURI) wasn't clear enough. Syd is right that it can properly be any namespace or any QName, but there isn't a QName XSD datatype, and it seemed a little extravagant to create a QName TEI dataype just so it could participate in this frankendataype. And in any case, making it more restrictive does nothing for validation, because any QName could (lexically) be a URI. Like I said above, I'm happy to correct it (because it is technically incorrect), but the actual impact is going to be precisely zero.

**Comment by Conal-Tuohy** [comment]
Have I understood it correctly that an `NCName` is currently allowed (by the `xsd:anyURI` production)? Because it seems to me it should not be (I understood this case to be what was concerning @sydb above). It should be either a `QName` or an absolute URI (not just any URI); in either case it should contain one (or more) `:` characters.

**Comment by hcayless** [comment]
xsd:anyURI does not have to be an absolute URI afaik, so things that could lexically be NCNames are perfectly legal. We could define a TEI datatype for absolute URIs, which are defined as 
````
absolute-URI  = scheme ":" hier-part [ "?" query ]
````
in https://tools.ietf.org/html/rfc3986#section-3.1 (again, a QName would match this production perfectly :-)). I think we've tended to fall back on the XSD dataypes and not get more specialized than that, but it might be useful to create such a TEI dataype.

**Comment by Conal-Tuohy** [comment]
So is agreed that changing `teidata.namespace` from `xsd:anyURI` to rfc3896's `absolute-URI` is the solution to the issue?

**Comment by ebeshero** [comment]
Council agrees that Syd should constrain to absolute URI or Qname, with a simple regex to exclude a relative URI (no `/` before a colon).

**Comment by sydb** [comment]
Done at  3f6a2c3, standing by for Mr. Jenkin’s approval. Note that I have **not** yet added a test for this.
