### ISSUE TITLE
New Problem with Installing TEI Framework Plugin for oXygen

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#1574]
As of the end of January 2017, new installations of TEI P5 Framework updates from http://www.tei-c.org/release/oxygen/updateSite.oxygen now are blocked due to  “handshake-failure.” oXygen Support observes that "the TEI update site from www.tei-c.org links to sourceforge.net. sourceforge.net is enforcing SSL security measures that are not supported by default by Java 8 (Java actually supports them but explicitly limits the support due to US cryptography export laws)."

Seems like we need to alert someone at sourceforge? This problem may be confined to people like me in the benighted US.

Here's a way oXygen support suggests for people to repair until sourceforge changes its SSL measures:
"The only way I have found to avoid this is to download and deploy the Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files for the Java 8 runtime used by Oxygen.
You can find the JCE files here:
http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html
The two jars found there should be placed (replacing the existing files) in:
- Oxygen/jre/lib/security - Windows/Linux
- Oxygen/.install4j/jre.bundle/Contents/Home/jre/lib/security - Mac

Directories starting with . are invisible in "Finder", so you may have to use the Terminal.
e.g
open -a Finder /Applications/Oxygen\ XML\ Editor/.install4j/jre.bundle/Contents/Home/jre/lib/security
"

**Comment by ebeshero** [comment]
I haven't tried the fix yet--perhaps can mess with it in Prague!

**Comment by martindholmes** [comment]
The obvious solution would be to serve the plugin from tei-c rather than SF, but actually the tei-c site does not have a trustworthy cert; it appears to have been issued to Wild Apricot Inc.

**Comment by jamescummings** [comment]
Presumably that is to do with http://members.tei-c.org/ which is hosted at wild apricot.  Ask the sysadmin if we can get a certificate for tei-c.org?

**Comment by martindholmes** [comment]
@jamescummings good point -- I'd not twigged that I was outside the main site. The main site doesn't seem to offer https at all.

**Comment by hcayless** [comment]
As a quick-and-dirty solution, could we switch to GitHub?

**Comment by jamescummings** [comment]
Surely better to do so properly and switch to making our releases on github officially? I.e. stop using sourceforge at all? But yes, just changing the updateSite.oxygen to point to another place... seems easiest.

**Comment by jamescummings** [comment]
Someone asked me why they couldn't update oXygen in the recommended way any more. We should solve this soon.  Where is the right place to put the oxygen-tei framework on github? In a 'releases' directory in https://github.com/TEIC/oxygen-tei/tree/master/oxygen-tei ?  Or is there a more githuby way to do this properly?

**Comment by martindholmes** [comment]
There are releases up there already:

https://github.com/TEIC/oxygen-tei/releases

It looks like you made the last one. Do we just need to change the updatesSite.oxygen file?

**Comment by hcayless** [comment]
I think that's all we'd need to do.

**Comment by martindholmes** [comment]
I don't seem to have ssh access to tei-c.org any more, so someone else will have to change the file in-place. If we replace the URL in the existing file, and US users confirm that they can now update successfully, I'll change the bits that generate the file in the repo.

**Comment by jamescummings** [comment]
I've changed the 6.1.1 URL to point to github.  I'll ask someone who was mentioning it to test. But if someone else can as well, that'd be good.

**Comment by jamescummings** [comment]
I can confirm that Iv'e upgraded an old version 16 oXygen to version 6.1.1 of the framework.

**Comment by martindholmes** [comment]
I think the problem was only afflicting US residents, wasn't it?

**Comment by lb42** [comment]
I'm confused by these version numbers.  6.1.1 presumably identifies the framework, but when I do a "manage add ons" in oXygen it tells me I am running development build number 2017-02-07-104531 which is using TEI P5 version 3.1.83  and says nothing about the framework number. So how do I know?

**Comment by martindholmes** [comment]
I think you're running the "bleeding edge" plugin (which we really do want Council members and ex-Council members to be running, because it's our real test of the dev trees). This problem doesn't seem to apply there, because the plugin package is coming from Jenkins. The version numbering on the "stable" package, which most people use, has been the subject of much discussion in the past, and we arrived at a formula which we've been using.

**Comment by lb42** [comment]
So we use an entirely different numbering scheme for "development" and "stable" versions of the same framework? There's a word for that, and it rhymes with "conkers".

**Comment by jamescummings** [comment]
The problem was affecting someone here in the UK as well. 

@lb42 If you want to tell what version you have you should be able to go to  Help -> Manage Add-ons and click on the 'Manage' tab.  The version column there has 6.1.1 for me if I'm using the updateSite.oxygen from tei-c.org rather than the bleeding edge from jenkins.

**Comment by lb42** [comment]
@jamescummings yes,  but you're not getting my point. Why does the bleedin edge not give some indication what it's the edge of? Why isn't it the next version number followed by some date information?

**Comment by lb42** [comment]
And what on earth is the version number 3.1.83 ?

**Comment by martindholmes** [comment]
@lb42: We needed a formal numbering scheme for the stable version of the plugin because it needs to make sense to ordinary users, and it needs to move forward in a predictable way based on the release version increments of P5 and the Stylesheets. Since the bleeding-edge version is only for us, it's not numbered based on releases because it's not built from releases. Instead, it has a helpful bit in its description message:

Jenkins build number: 2017-02-07-104531

**Comment by lb42** [comment]
In what sense is the bleedinedge not "built from releases"? Surely it's built from the ashes of one release and becomes another release itself eventually?  Also, if it doesn't have a release number, what is the "3.1.83" ?

**Comment by martindholmes** [comment]
It's not built from releases, it's built from the latest Jenkins builds of the two dev trees (and its own tree).

**Comment by martindholmes** [comment]
If you'd like to propose an algorithm for numbering the bleeding-edge version, please do. It's never seemed important to me. It's built every time either oxygen-tei changes, the Stylesheets changes and gets built, or P5 changes and gets built. Bear in mind that since Jenkinses may rotate or be rebuilt, the Jenkins build number for any of these is not reliable; and GitHub gives us only hashes.

**Comment by hcayless** [comment]
Think this one is done.
