### ISSUE TITLE
Appendix C: Element Spec Reference Pages could have navigation through all elements

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1577]
In Appendix C the element spec reference pages could have a navigation to go to the 'next'/'previous' element alphabetically.  While I realise it is a very small use case of those who want to browse through the element reference pages going to the 'next' element it might lead to more serendipitous exploration of this appendix by some users.   This would be similar to the links to go to the next and previous sections in a Guidelines chapters.

I don't think this is wonderfully useful, but might be minorly so, and isn't harmful.  Potentially an easy change for those looking to understand the Stylesheets which generate these pages.

**Comment by cmsmcq** [comment]
On the slightly more general topic of improving hypertextual navigation, the next/prev links now given at the top of each chapter could usefully be repeated at the bottom, so that a(n imaginary) reader who is reading the Guidelines from start to finish can move to the next chapter from the end of the preceding chapter, without having to scroll back up to the top of the page to find the expletive deleted link.

**Comment by hcayless** [comment]
I think these are both good suggestions. I'll open them as FRs on the Stylesheets.
