### ISSUE TITLE
Are class modifications really required to make extension elements reachable?  I think not

### ISSUE THREAD

**Issue by cmsmcq** [TEIC/TEI#1590]
In 23.3.1.6 Addition of New Elements, P5 says:

> To add a completely new element into a schema involves providing a complete element specification for it, the classes element of which includes a reference to at least one TEI model class. Without such a reference, the new element will not be referenced by the content model of any other TEI element, and will therefore be inaccessible within a TEI document.

This seems to suggest that it's not possible to make a new element available by writing it into the content model of some other element.   But 23.3.1.3 Modification of Content Models seems to say that one can in fact modify content models.  

I think what may have been meant is that in the large majority of cases, new elements will have a reference to at least one TEI model class, since that is the easiest way to ensure that it is reachable from the `TEI` or `teiCorpus` element.  (It is not enough for a new element to be referred to by some content model in the schema; the element to which that content model belongs must itself be referred to, and so on recursively until one hits the root element.)  But as stated, the claim made here is too strong.  If I redefine the content model of `text` to be `(front?, body, back?, blort*)`, then `blort` will be reachable in the grammar, and usable in valid document instances, even if the definition of `blort` does not assign it membership in any classes.

**Comment by lb42** [comment]
Interesting. If you change the content model of an existing element to permit a new non-TEI element child is that a clean modification? We certainly do it  (see for example TEI with MathML exemplar) so it's a desirable one.

**Comment by cmsmcq** [comment]
There is nothing so ominous in this entire series of bug reports about chapter 23 as your asking that question as one to which the answer is uncertain.

**Comment by lb42** [comment]
To make it a clean modification by my simple-minded definition you'd have to put the redefined &lt;text> element into a different namespace. Fortunately &lt;text> is no longer mandatory inside &lt;TEI> so the damage stops there...

**Comment by jamescummings** [comment]
I agree that the statement might be too strong, what was probably intended is that it is recommended that one uses the class system to do this, as you note it isn't strictly necessary  Doesn't its cleanliness depend on whether `blort` is define in a new namespace?  I've always been of the impression that adding new elements in other namespaces doesn't dirty the customization with respect to the abstract model. (But I think another issue was submitted about the precise meaning of that.) As long as the content model of TEI elements is unchanged (or is a subset of full TEI possibilities for this content model), then that seems clean to me.  What would make it really dirty is if new TEI elements are allowed here.  But maybe I've been misunderstanding this.

**Comment by lb42** [comment]
I think the issue here is how to resolve the contradiction between (a) 23.1.6's apparent requirement that the only way of getting a new non-TEI element into a TEI document is to make it a member of a TEI model class  (b) the fact that any content model can be modified to include a non-TEI element. The contradiction is easily solved by changing the wording to make it clearer that method (a) (inclusion via an existing TEI model class) is recommended, though method (b) is also possible. The implications for conformance of doing either are another (much debated) issue, but are unaffected by the method adopted.

**Comment by cmsmcq** [comment]
@lb42 considers

> how to resolve the contradiction between (a) 23.1.6's apparent requirement that the only way of getting a new non-TEI element into a TEI document is to make it a member of a TEI model class (b) the fact that any content model can be modified to include a non-TEI element.

This sheds a slightly different light on things.  I had read 23.1.6 as making a statement of fact, which I take to be erroneous; the possibility of reading it as imposing a conformance requirement of some kind had not crossed my mind, since none of the words used in specs to describe rules for distinguishing conformance from non-conformance (_must_,. _shall_, _required_, ...) appear (and the Guidelines don't in any case seem to define those words as having conformance implications).

But Lou's proposal will address both analyses of the current text (erroneous statement of fact or undesirable conformance requirement), so it would resolve the issue regardless.

**Comment by lb42** [comment]
To be precise, I propose to change this
~~~~
  <p>To add a completely new element into a schema involves providing a complete element specification for it, the <gi>classes</gi> element of which includes a reference to at least one TEI model class. Without such a reference, the new element will not be
referenced by the content model of any other TEI element, and will therefore be inaccessible within a TEI document. </p>
~~~~
to
~~~~
  <p>To add a completely new element into a schema involves providing a 
complete element   specification for it. It is recommended that  the 
<gi>classes</gi> element of this new declaration should include a reference
to at  least one TEI model class. Without such a reference, the new element
 would not  otherwise be referenced by the content model of any other 
TEI element, and would therefore be  inaccessible within a TEI document.  
It is also possible to modify the content models  of one or more existing 
elements to refer to the new element explicitly, as discussed 
in <ptr target="#MDMDCM"/> <!-- 23.3.1.3-->  but this will generally be 
less convenient. </p>
~~~~

**Comment by jamescummings** [comment]
That prose seems clearer to me.

**Comment by emylonas** [comment]
Seems clear to me as well. +1

**Comment by martinascholger** [comment]
Agreed +1

**Comment by lb42** [comment]
Text revised as proposed at 2123dd554c0c166421d550e571a619c6783f9406
