### ISSUE TITLE
msIdentifier, district in wrong location

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1594]
The content model of msIdentifier http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-msIdentifier.html specifies an order of geo-political elements to enforce an order from largest granularity to smallest granularity. However, the district element is in the wrong place in this order hierarchy.

````
 (
      (
         placeName?,
         bloc?,
         country?,
         region?,
         district?,
         settlement?,
         geogName?,
         institution?,
         repository?,
         collection*,
         idno?
      ),
      ( msName | altIdentifier )*
   )
````

As you'll see from the definition of district http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-district.html it is a subdivision of a settlement (part of a city for example), thus it should be *after* settlement not before it.

I find it amazing that I've never noticed this before, however district is one of those which I rarely use inside manuscript descriptions. However, there is a potentiality for breaking existing document instances which do use it if we swap the order of district and settlement.

Proposed solution: Allow the geo-political names (or indeed any msIdentifier child?) in any order.  Although the ordering for geopolitical names was done with the best of intentions, and people could choose to model their msIdentifiers this way, there is no real reason for having country above region or vice versa in an XML structure.  Encoders could still choose to use this ordering if they wish, and then would be able to put district in the right order (or not at all).  This proposed solution would not break any existing document instances.

**Comment by lb42** [comment]
Actually this is more complicated than it seems. The sequence in which components of msIdentifier can appear is determined by the order of declaration of the various members of model.placeNamepart, since the content model now begins &lt;classRef key="model.placeNamePart"     expand="sequenceOptional"/>. My guess is that &lt;district>was added to the class later than the others (it doesn't appear at all in early versions of P5) perhaps without consideration of this particular wrinkle. Or maybe it happened when the content model was changed to use the classRef rather than explicitly named elements. Either way,  the fix is simply to move the declaration at line 927 of ND-NamesDates.xml down one.

**Comment by jamescummings** [comment]
@lb42 as you note this says expand="sequenceOptional" ... that means that it is in a sequence but any member is optional... right?  I would still argue that sequence need not be applied in msIdentifier since anything processing it should be able to re-sequence things at will.  Oh well.

As @lb42 suggests, this is a trivial fix, I'm going to assume it is a corrigible error and just do it by moving things as suggested at https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/ND-NamesDates.xml#L926 

Ok, I've now done so as of commit 376e3e2e14f32f653cc6163be26bddfe6a32b69e  I'll leave the ticket open for awhile in case anyone wants to revert that change because of some unpredicted side-effect.
