### ISSUE TITLE
Status of Schematron rules in TEI

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1621]
Based on this discussion on TEI-L:

https://listserv.brown.edu/archives/cgi-bin/wa?A1=ind1703&L=TEI-L#32

the status of the Schematron rules in relation to TEI conformance needs to be clarified and articulated. I think it's fair to say that there are three positions:

1: Strong position (mine): Schematron rules are an intrinsic part of validation and a document which validates against the RNG in tei_all.rng but not against the Schematron in tei_all.rng is not conformant. This position allows for some special cases (deprecation is the obvious one) where schematron rules with `@role='nonfatal'` are used for warning or advisory purposes only. That value of `@role` should not be used (as it currently is in the case of dating attribute co-occurrence constraints) in conjunction with language such as "cannot" or "must".

2: Middle position: Some Schematron rules should have the force of conformance-level constraints, but other should be specified as `@role='nonfatal'` specifically because they are merely advisory or good-practice recommendations.

3: Weak position: Schematron rules are optional adjuncts to the normal validation process, and any file which validates against the RNG in tei_all.rng but not against the Schematron is fully conformant.

**Comment by lb42** [comment]
"used for purposes of only."  words missing?

**Comment by martindholmes** [comment]
Fixed -- ta.

**Comment by martinmueller39** [comment]
I have a use case that may be helpful. Quite a few years ago, John Norstad, a very brilliant and outspoken programmter at Northwestern, was driven crazy (or so he said) by TEI encodings that createde deeply nested chains in which <p> elements appeared unpredictably as descendants of <p> elements. The cases came from the TCP archive and involved Q/TEXT/BODY/DIV paths whose content was typically letters or other documents. They were nearly always the last child of <P> but they were encoded as child elements of <P> because the text of <P> did not end with a full stop.   One can argue about the wisdom or fidelity of that encoding. I was eager to keep John happy and also remembered the Zen of Python #5 "Flat is better than nested." So I persuaded Brian Pytlik Zillig to add a "lastchild2rightsibling" routine. 
I can see the utility of the middle or weak position, which uses Schematron warnings to alert encoders to questionable practices. Do you really want to make a three page table the last childof a three sentence paragraph? Or a floatingText with two divs and lots of paragraphs? If a Schematron rule urges you ponder that question, that seems to me a good thing. If on reflection you decide that the long table or paragraph were integral parts of the paragraph that's OK

**Comment by martindholmes** [comment]
Now I think about it, it seems to me that the difference between positions 1 and 2 is that 1 (my position) would prefer it to be rare for advisory rules to be added at all; in fact I think they should be limited to cases of deprecation. The main reason is that when validation throws up lots of warning messages, people simply tune them out or stop validating their documents, so the ones that really matter get lost in the shuffle. I'm not against there being some kind of additional process you could submit your document to which would attempt to give you helpful advice about all sorts of questionable constructs or co-occurrences you might have, but I think that sort of thing should not dilute the formal validation/conformance issue.

@martinmueller39 I see the value of project-level Schematron rules of all kinds -- all my projects have dozens of them. But I think "Flat is better than nested" is a dogma that's ill-matched with the world of TEI XML encoding.

**Comment by martinmueller39** [comment]
I wouldn't say that "flat is better than nested" is a dogma.  It's useful advice and especially useful if you're dealing with inherently complex environments.  A minimal encoding of Mary had a little Lamb is a surprisingly complex thing. At the margins, do you add complexity or keep it as simple as possible? Richard Strauss' advice to young conductors was "never smile at the brass"

**Comment by martindholmes** [comment]
The equation of nesting with complexity is just wrong or at least simplistic, surely?

**Comment by cmsmcq** [comment]
> The equation of nesting with complexity is just wrong or at least simplistic, surely?

Sure; what rule simple enough to be worth remembering is not a little simplistic?  

The particular case to which MM applies it is not just nested structure vs flat structure but an asymmetric nested structure likely to have been the result of a flawed auto-tagging algorithm.  But, you know, if you're writing a piece on the Zen of [Programming Language], your copy editor is not going to be happy with "Flat is better than asymmetrically nested owing to faulty upstream processing."

**Comment by jamescummings** [comment]
Flat is not better than nested in an XML world.

**Comment by martinmueller39** [comment]
Well, no.  My favourite political slogan--albeit from the very conservative CSU in Germany-- is "so ortsnah wie möglich, so ortsfremd wie nötig," which in XML speak translates into as "flat as possible and as nested as necesssary".  Nesting is crucial to XML, but beyond the second or third turn it becomes tricky for most humans, certainly for me, and a very strong version of the Goldilocks principle comes into play.

**Comment by ebeshero** [comment]
F2F (Victoria 2017): recommendation to modify Ch. 23 to make Schematron's importance explicit.

**Comment by jamescummings** [comment]
@martinmueller39 I don't think nesting really is pertinent to this ticket in general. And that said, regardless of its human readability nesting (in an xml world) is better. At each level you get greater annotation, more expressivity, and "das Ganze ist größer als die Summe der Teile".

**Comment by ebeshero** [comment]
I'm finally working on this ticket, and I started by surveying all the Schematron constraints in our specs, including the 9 that have `@role="nonfatal"` attached.  Except in the case of the series of rules to do with dating attribute co-occurrence (`@to`, `@notBefore`, `@when`, etc) these are deprecation warnings. @martindholmes rightly points out that those dating co-occurrence constraint messages sound like fatal errors when triggered and I suspect that's because that's how they were intended to sound...I'm going to open / reopen a ticket about that. If we want this to be fatal, we should remove the `@role="nonfatal"`, but if we want it to sound like a warning, we should say so. 

What I'm seeing is that in the 70 `<constraintSpec>` elements currently in the Guidelines, the language is overwhelmingly on the side of the "Strong position" articulated by @martindholmes : that is, our Schematron constraints aren't typically just warnings or guidance, but seriously to do with ensuring conformance with the TEI. I'll start work on describing that state of affairs in Ch. 23...

**Comment by ebeshero** [comment]
With this commit in a branch, https://github.com/TEIC/TEI/commit/533d896a98e54972b437f6baa1208c6a37f97aad  , I've written something more explicit about Schematron, as well as a couple of other small suggestions for clarification in Ch. 23--I'd like to review this with Council as soon as we can.

**Comment by sydb** [comment]
@ebeshero: The example is clearly overall correct, so I changed it to `valid="true"`.

However, that example **may** have been indicated as invalid because it is missing the child elements for `<datatype>`, which are required. If that is the case, I should have used `valid="feasible"` or (better IMHO) made it complete, e.g.:
~~~~~xml
<elementSpec ident="p" mode="change">
 <attList>
  <attDef ident="topic" mode="add"
   ns="http://www.example.org/ns/nonTEI">
   <desc>indicates the topic of a TEI paragraph</desc>
   <datatype>
     <dataRef key="teidata.word"/>
   </datatype>
   <remarks>
     <p>The encoder should use up to 3 <soCalled>tags</soCalled> (word
     tokens) of her choosing, with no controlled vocabulary.</p>
   </remarks>
  </attDef>
 </attList>
</elementSpec>
~~~~~
(P.S. Apologies for checking-in to your branch; just seemed like a faster & easier way to communicate this, and I'll be talking to you in 10 mins, anyway. :-)

**Comment by ebeshero** [comment]
As per F2F Tokyo Minutes from ticket triage: I am merging my branch into the "dev" branch, but leaving ticket open since it's on the meeting agenda.

**Comment by ebeshero** [comment]
Branch is gone and pruned away. Commits here are merged into dev.

**Comment by ebeshero** [comment]
Uh oh, when I merged to dev, something broke Jenkins. Investigating...

**Comment by ebeshero** [comment]
I've just rebased my branch and I think it's okay now. I'm going to do a pull request to make sure and ask someone to review it + get Jenkins / Travis to validate it around the Council meeting tomorrow.

**Comment by ebeshero** [comment]
Noted a comment I never addressed on this commit: https://github.com/TEIC/TEI/commit/533d896a98e54972b437f6baa1208c6a37f97aad
 F2F meeting: Change "contextual" to "conditional". Edit "scheme" to "schema". Check into dev.

So, I'm doing that...

**Comment by bwbohl** [comment]
Apparently `role="nonfatal"` made it back to the specs, e.g., in the constraintSpecs for `@validUntil`.

https://github.com/TEIC/TEI/blob/30d1125ac7551c45cf15686027ded833ed758bd1/P5/Source/Specs/att.deprecated.xml#L35-L39

Is there a reason why `@role` of the second assertion is not set to another value that might be supported by some schematron validation processors (Cf. https://schematron.com/document/141.html)?

Moreover decision had been taken to follow the SynchroSoft vocabulary: 

 >Council decides to use Syncro vocab. Non-fatal error msg should be changed to Warning or Error as needed. Update TCW20 to reflect this decision.

_Originally posted by @martinascholger in https://github.com/TEIC/TEI/issues/1795#issuecomment-490152275_

**Comment by ebeshero** [comment]
@bwbohl Thanks for your vigilance! Most likely this setting was just "force of habit". We'll change it to `role= "warning"` and check if there are more such issues.

**Comment by ebeshero** [comment]
@bwbohl I think I've just resolved the problem (at least for this spec page) with this commit: https://github.com/TEIC/TEI/commit/a686829989ce55aac9d9c33e125f9dc0e25fbd8c 
We'll look later to see if non-conformant `@role` values are showing up anywhere else, but please let us know if you see them before we do!
