### ISSUE TITLE
@who and @resp are both available on  <change>

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1631]
Now that @resp is global, it is available for use on the &lt;change> element : does it mean something different from the existing @who attribute? if so, what? and if not, should @who be heading for deprecation in favour of @resp ? Either way, some clarification is needed.

**Comment by martindholmes** [comment]
Change made by research assistant on instructions from editor.

**Comment by lb42** [comment]
A very ingenious example, but which is @who and which is @resp? And where does it say that in the Guidelines?

**Comment by martindholmes** [comment]
`@who` = who made the change = the research assistant; `@resp` = who is responsible for it = the editor. `@who` is "speech or action that can be ascribed to a specific individual"; here I'd say it's making the change which is the action. `@resp` is "the agency responsible for the intervention or interpretation, for example an editor or transcriber." It seems fairly straightforward to me, but an example of the use of both together might be helpful, we can add it.

I fairly frequently carry out actions which fit this model; the editor will tell me for instance that we need make an encoding or a wording change covering many documents from a corpus, and I'll write an identity transform to do it. I usually add an automated `<change>` element with myself as the `@who`. I don't tend to use `@resp` to specify the authority requesting the change, but I should; it's a very effective way to do it.

**Comment by jamescummings** [comment]
I don't think that having both is a bug.... but only because in `@resp` being now global I think we opened a can of worms.

That said, the other place I use `@who` is on `<sp>` and I would be surprised if anyone confused them there where they are clearly different things.

**Comment by bansp** [comment]
`@resp` is great to have all over the place e.g. in dictionary encoding. And it seems like, indeed, the only place of potential clash is where it coexists with `@who`, and two of them look like they may be considered under control, with the former one, on `<change>`, requiring a bit more documentation now. So maybe we needn't fear worms, after all.

**Comment by martindholmes** [comment]
@jamescummings Your comment about `<sp>` caused me to imagine encoding the performance of a ventriloquist:

~~~~~
<sp who="#dummyLordCharles" resp="#humanRayAlan">You silly arse!</sp>
~~~~~

**Comment by jamescummings** [comment]
It seems like the outcome of this issue is that `@who` and `@resp` are fine on the change element.  The other places where att.ascribed provides `@who` are:

annotationBlock change incident kinesic move pause q said setting shift sp spGrp stage u vocal writing

From my point of view there is a clear distinction on all of those of `@resp` being the one responsible for its encoding or editorial aspects and `@who` being the one either referred to or part of the action referred to by encoded elements (e.g. they give the speech, hole up the writing, made the change).

`<change>` is indeed the one where this is the most problematic, but I think the distinction holds here as well.  I might put a `@resp` on a `<change>` to indicate who was responsible for encoding it, with a `@who` for who actually carried out the change, which is slightly different from martin's usage, which seems equally valid.

Unless strong argument comes for why these should be different and `@who` removed then I'll close this issue.
