### ISSUE TITLE
add listBibl to model.profileDescPart

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1636]
Where should one include a bibliography of items not used as source for a TEI document or corpus, but which are nevertheless associated with or referenced by it? This seems to me analogous to a personography or placeography, either of which can be supplied within the profileDesc of a corpus header. Hence I would like to be able to put a listBibl in the same place, and hence my suggestion that listBibl should be added to the class of things that can appear inside the profileDesc. I need this for a real project, so my ODD (visible at https://github.com/lb42/difdepo/blob/master/difdepo.odd) currently does it, but this is dubiously conformant, depending on your definition of conformant.

**Comment by martindholmes** [comment]
Don't we have a long-standing feature request for an element to contain this stuff?

**Comment by martindholmes** [comment]
Looking at the discussion here:

https://github.com/TEIC/TEI/issues/374

I think the `<standoff>` element has been considered as an option for containing exactly this sort of material, but it seems that over the lifetime of the discussion it's become more specialized. We need a general linked-data-block element (we considered `<ldb>`, IIRC) for this, if `<standoff>` is not the place for it.

**Comment by lb42** [comment]
Well, that's as may be, but this is not standoff annotation. It's exactly analogous to a listPerson,with person elements being pointed to by persName@ref attributes. Since we provide that for persons and for places within profileDesc, why not for bibls?

**Comment by martindholmes** [comment]
I think we should finish what we started and solve the more general problem through `<standoff>` rather than complicate things with interim solutions that will ultimately add more confusion. If we add this to profileDesc and then document it as the place to put listBibls, then later we add `<standoff>` and say that's where you should put stuff like this, we just increase confusion. I don't know what the status of `<standoff>` is, but it's been on the table since 2012 so it must be getting close, surely?

**Comment by lb42** [comment]
Except that we already have "interim solutions". And in my experience, an interim solution in the hand is worth a dozen in the bush, or "on the table since 2012".

**Comment by jamescummings** [comment]
I'd probably have put it in sourceDesc anyway. I know it isn't the source for the file but some encoders also put authority lists here as related content. i.e. listPerson and listPlace sometimes end up here for users who are merely providing authority lists (e.g. to standardise spelling) rather than personography/placeography lists (particDesc/settingDesc).

I'm not saying that is right and proper. But either there or 'back' (which I think should be used more for digital edition associated material) or indeed a separate file.

**Comment by laurentromary** [comment]
I have been using sourceDesc exactly in that manner for various types of background objects that have various degree of relation to the current document: background databases, previous versions of a document, as well as authorities. I think I'd rather see the scope of a coherent element such as sourceDesc be fine tuned to cover these cases then spread such object at heterogeneous places in the header (or else)

**Comment by martindholmes** [comment]
`<sourceDesc>` is about the source document, surely? If your lists of people, places, etc. are extra editorial material not originating in the source, I don't think it belongs there.

It seems to me we've had this argument over and over again. You can't just put this stuff in `<back>` because your original source document may have a `<back>` itself, and in any case you don't necessarily want to be making a claim that it's part of the `<text>`. Some bits of it (eg <`listPerson>`) seem to fit in `<profileDesc>`, but not others. We need a place which is unambiguously the location for stuff which is not metadata, and not part of the original text.

**Comment by laurentromary** [comment]
There is a continuum in real life concerning those things. Sure you can mention examples which are far far away, but in many cases, especially in born digital document, which are often a recomposition of other digital objects, this is not that easy.
And no, `<back>` is not the answer when one really deals with meta-data and not something that belongs to the content of the document.
Maybe we should think of `sourceDesc` as representing the "sources" of a document and shape the element a little bit more to fit (sorry, I repeat myself) the non digitally born case, where there isn't a real physical source.

**Comment by martindholmes** [comment]
If we're shaping an existing header element for this purpose, I think it should be `<profileDesc>`. But neither `<sourceDesc>` nor `<profileDesc>` really makes sense to me; and since we're supposed to be getting `<standoff>` anyway, surely it should be that?

**Comment by laurentromary** [comment]
A bit in a rush to argue, but it is at least clear to me that what we seem to be speaking about has nothing to do with annotation, thus with `<standOff>`. It seems we need to clarify the nature of the various information chunks we associate to a textual content, as background/source, documentation/profile, or supplemental/annotation/standOff. Does this classification make sense?

**Comment by lb42** [comment]
I agree that there is some sort of three way distinction. sourceDesc is defined as providing metadata describing the source from which a digital resource is derived; it makes little sense for it to contain biographical or bibliographical data about real world entities referenced in the source. I continue to think the place for those bits of metadata is profileDesc  the purpose of which is precisely to gather "other metadata"  -- notes about the work rather than its exemplar for example. Certainly I can live with putting that information into the third "standoff" camp, if that ever materializes, better than putting it into the sourceDesc. But last time I remember this being discussed, there was some question mark over whether the shiny new `<standoff>` element belonged in the header at all.

**Comment by martindholmes** [comment]
IIRC the `<standoff>` element was not supposed to be in the header; it's supposed to be a direct child of `<TEI>`. There are also two competing definitions of "annotation" in play here, one very specifically related to the annotatedU proposal and all that, and another which encompasses all editorial content which enriches a text. My view is that:

 - Editorial content such as notes, biographies of people mentioned, GIS info about places mentioned, interp stuff etc. is not metadata, and doesn't belong in the header.

 - Neither does it belong anywhere in `<text>`, UNLESS your purpose is to create a digital artifact which is explicitly a synthesis of multiple sources; in the "traditional" sort of TEI encoding project, where a primary source manuscript or print document is transcribed, encoded and annotated, what belongs in `<text>` is only the primary source transcription.

 - We need an element -- for which `<standoff>` is a reasonably good name -- whose purpose is to hold all that extra editorial content, so that the header is only real metadata, and the text is not cluttered with editorial content which can only be distinguished from the primary source by ad-hoc encoding strategies (`<note type="editorial">`).

**Comment by bansp** [comment]
A full suggestion for the content of the `<standOff>` element is in preparation at https://github.com/laurentromary/stdfSpec. If its use can be extended to the purpose that Martin mentions then everyone is going to be happy (though for the reasons mentioned by Laurent, that does not seem to be the case). If not, we'd be grateful in the name didn't end up hijacked ;-)

**Comment by martindholmes** [comment]
The proposal includes model.listLike and listBibl as part of its content model, doesn't it?

**Comment by laurentromary** [comment]
See the slides from Vienna: https://hal.inria.fr/hal-01374102 to have the latest state of reflexion from the group. The nest stage si for us to write a JTEI paper that can elicit the various choices. The core of what needs to be refined is actually the content model of `<annotationBlock>`, that has been already inserted for the sake of the ISO standard transcription of spoken language but is planned to be the basic container of elementary annotation units. I am not opening the debate here (remember in which ticket we are ;-)) but me need to have a model-class based content model to have all the necessary adaptability to any and of annotation vocabulary (bibliography may be one, but could also be named entities (person etc.), mathematical formula, or even decent (and structured) chunk of texts.

**Comment by bansp** [comment]
Being able to use that element for non-linguistic content, in the spirit of Open Annotation (something I have yet to come to grips with) would actually strengthen the overall proposal. When I mentioned hijacking the name I referred to putting standOff somewhere in the header, with by necessity a different definition. I don't think I have a problem with where Martin is going.

**Comment by martindholmes** [comment]
I've always been a bit unhappy about the standoff element being too narrowly-conceived (as being about linguistic annotation and tied up with transcription) when it has such a general name. I think we'd all benefit if its documentation (in the Guidelines) could also point out how it can be used for more general purposes, as a container for lists of people, places, publications, and so on. Topic schmopic. :-)

**Comment by lb42** [comment]
If I've understood the proposal correctly, `<standoff>` has to be a direct child of `<TEI>`, with its own `<teiHeader>`. I have no particular problem with that. However, in the context in which I raised this issue (providing bibliography and personography for a `<teiCorpus>`) it's hard to see what added value I get from using it rather than simply adding a new TEI/text to hold my lists of people etc.

**Comment by martindholmes** [comment]
True, if you're already in a `<teiCorpus>`. What if you're in a standalone `<TEI>`?

**Comment by lb42** [comment]
Then I have to add an additional `<text>` inside my TEI. Is valid according to TEI All, so it must be conformant!

**Comment by martindholmes** [comment]
That's an interesting approach I had never thought of, and I think it's worth considering as a recommended approach to separating editorial from primary source content.

**Comment by hcayless** [comment]
I'll confess that I'm a lot less religious about what goes in my `<text>`s than some here, since I tend to regard my TEI documents as editions, meaning the editor can put whatever they like in the text. Why shouldn't this go in the text as additional bibliography? We have `@resp` and `@source` to label it as not part of the original, if the possibility for confusion exists.

**Comment by laurentromary** [comment]
I think we have to deal with situations where such information are delivered or managed as meta-data and as such are seen as part of the header by the editors of the document.

**Comment by hcayless** [comment]
I'm going to give this to @peterstadler to progress as it sounds like it may be part of the whole package of `<standoff>` stuff.

**Comment by emylonas** [comment]
@peterstadler will work with @laurentromary to make progress on the `<standoff>` or `<ldb>` or whatever it will be called element.
#374 is the ticket to implement that.
For now, best to use `<sourceDesc>` or other elements that currently allow `<listBibl>`
