### ISSUE TITLE
persName example Malibran factually poor

### ISSUE THREAD

**Issue by Dominique-M** [TEIC/TEI#1656]
`<persName>
 <forename>García</forename>
 <forename>María-Felicità </forename>
 <surname type="linked">la Malibran</surname>, <roleName>Desdemona </roleName>
</persName>`
May be conforming TEI but a poor example, especially confusing forename example, because contrary to the facts. (See Wikipedia in Spanish.) It should read:
`<persName>
 <forename type="first">María</forename>
 <forename type="second">Felicita</forename>
 <surname type="first">García</surname>
 <surname type="second">Sitches</surname>
 <surname type="linked">la Malibran</surname>, <roleName>Desdemona </roleName>
</persName>`
These are two separate forenames, not one double with hyphen. García is the first surname (from her father), not a forename. It is usual in Spain to be known by two forenames and two surnames (father and mother).

**Comment by jamescummings** [comment]
Just to note that this is at http://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-persName.html 

Isn't that a really bad use of `<roleName>` by the way?  'Desdemona' is not a ' a name component which indicates that the referent has a particular role or position in society, such as an official title or rank.'  Desdemona is a `<role>` http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-role.html not a `roleName`.

I'd suggest if someone has a better example of `<roleName>` that really shows an official title or rank then this example should be replaced entirely.

**Comment by lb42** [comment]
This example is misleading in ways other than those Dominique points out. "La Malibran" for example is not a surname (nom de famille) but a "surnom" in the French sense, i.e. an &lt;addName> . And if &lt;roleName> is included as content of &lt;persName> (rather than as content of &lt;person>) it ought to be plausibly something that might form part of name. So here's a slightly less awful example:
~~~~
<persName> 
<surname>Poncet</surname> 
<forename>Olivier</forename> 
<roleName>professeur d'archivistique et diplomatique moderne</roleName> </persName>
~~~~
and here's one without a roleName
~~~~
<persName>
<forename>Joseph<forename>
<addName type="stagename">Le Pétomane</addName>
<surname>Pujol</surname>
</persName>
~~~~
And there is also this much better example in the tagdoc for addName 
~~~~
<persName>
 <forename>Catherine</forename>
 <genName>II</genName>, <addName type="epithet"> la
   Grande</addName>, <roleName>impératrice de Russie</roleName>
</persName>
~~~~

**Comment by jamescummings** [comment]
Preferring more examples than less I added these to the spec in https://github.com/TEIC/TEI/commit/591e9a89075d6a6e474f838d3ebf3e62b9dfe87c (subsequently correcting the typo in the second one.
