### ISSUE TITLE
Add listRef to model.ptrLike (and expand its description slightly)

### ISSUE THREAD

**Issue by laurentromary** [TEIC/TEI#1667]
For all the case where one want to group pointers or references together, it would be practical to use listRef in a wider range of circumstances than just its current application in tagDoc. Technically this would just mean adding it to model.ptrLike. The prose description could be changed so that its meaning is generalized to any group of pointers or references.

**Comment by lb42** [comment]
How would the uses you envisage for this differ from those supported by the existing &lt;linkGrp> element? It's necessary to provide clear guidance on when to use which  -- or to deprecate one or the other.

**Comment by laurentromary** [comment]
Well `<linkGrp>` is intended to group... links and although it can contain `<ptr>`, it does not contain `<ref>` . `<listRef>` would be a good candidate (and already conceived as such, although for a restricted scope) for gathering `<ref>`'s. It would be a little change for the guidelines but a big step for more coherence in some of its elements (having `<listRef>` wherever `<ref>` can occur). I agree so that clearer guidance be given.

**Comment by lb42** [comment]
It has also been suggested that either ptr or ref should be removed, since they both do the same job. What is ptr doing in the content model of linkGrp if it's supposed to contain only links? And why is ptr there but not ref? All very mysterious.

**Comment by laurentromary** [comment]
Agree. And if my ticket can lead to even more improvement in the guidelines, I would of course be delighted.

**Comment by sydb** [comment]
A `<ptr>` is just a `<ref>` that does not have content. In some sense a `<link>` is the same as a `<ptr>` except that it has to have at least 2 pointers in its `@target` (which is why that attribute should be named `@targets`). So having a `<ptr>` in a `<linkGrp>` doesn’t really bother me, it’s just the degenerate case of a `<link>`. And `<ptr>` has been allowed in `<linkGrp>` since P2. A `<ref>`, on the other hand, can have _content_, which neither `<link>` nor `<ptr>` can have, which would open up another ball of wax, to mix metaphors.

I don’t really see any reason **not** to do this.

**Comment by lb42** [comment]
Why is ptr allowed inside linkGrp ? It's been there a long time, but so has the Republican Party, 
What do you mean by "degenerate case of a link"?
 @target can supply multiple values,  ao are the following two different ways of doing the same thing:
~~~~
<link target="#p1 #p2"/>
<ptr target="#p1 #p2"/>
~~~~
If not, why not? 
I'm aware of the difference between ref and ptr; I was just noting that some have suggested we don't need both since ref is not required to have any content. 
I agree that listRef looks plausible. My concern is that it also seems to overlap with linkGrp as currently defined.

**Comment by sydb** [comment]
Yes, the `@target` of both `<link>` and `<ptr>` can hold multiple values. But the semantics of
~~~~~xml
<link target="#LT1 #LT2"/>
~~~~~
are that elements LT1 and LT2 have a relationship to one another, which relationship is indicated by the `@type` (and perhaps `@subtype`) of the `<link>` element (perhaps inherited from its parent `<linkGrp>`, but in any case not shown above).

With a `<ptr>`, on the other hand, the semantics of `@target` is “each of these things is related to me”, **not** that they are related to one another (which may also be true, of course). Thus
~~~~~xml
<ptr target="#PT1 #PT2"/>
~~~~~
means that both elements PT1 and PT2 are related to the spot in the text at which the `<ptr>` appears which relationship is indicated by the `@type` (and perhaps `@subtype`) of the `<ptr>` itself.

I do not know (you’d have to ask the chaps who were editors back when P2 was being written), but I guess that `<ptr>` is allowed in `<linkGrp>` exactly so as to avoid needing to specify a pointer to “here” if you put the `<linkGrp>` at a spot that at one end of the relationship being expressed.

As for why we need both `<ref>` and `<ptr>`, obviously in some sense we don’t. But the advantage of having both is that it lets the user decide whether an empty `<ref>` is to be treated just like a `<ptr>` or is an error.

So I think the writers of P2 had it right: `<ptr>` should be allowed in `<linkGrp>`, and there is some advantage to having both `<ptr>` and `<ref>`. (I also think they had it right that the name of the pointing attribute of `<link>` should be “targets”, not “target”.)

But in the end, I agree with you completely: `<listRef>` is plausible, and does overlap somewhat with `<linkGrp>`. I think if we were designing a new system from scratch, we would probably want a single “holder of a sequence (or set) of pointing elements” element whose content would be roughly `( desc?, ( ptr | ref | link | relation )* )` or some such.

But what we already have is `<linkGrp>`, which is “sequence (or set) of empty elements that express relationships either between here & there, or between two (or more) other places”, and `<listRef>`, which is “sequence (or set) of elements that establish a relationship between here and one (or more) other places”. We could certainly think about combining those. But if we don’t combine them, it’s hard to see why `<listRef>` should be limited to tagdocs.

**Comment by cmsmcq** [comment]
This seems like a plausible idea to me; I think it bears noting, however, that this proposal seems to instantiate precisely the opening of the floodgates feared in one response to #1449.

**Comment by laurentromary** [comment]
Which would not be a big flood while providing a more coherent landscape for listXX elements.

**Comment by lb42** [comment]
Several issues are raised in this thread, which maybe need disentangling.

1. The currently content model of listRef does seem a bit fascist. It is probably a consequence of the idea that listRef was primarily for use in ODD processing, specifically P5 ODD processing, in which arbitrary &lt;ref> elements with no @target value would be unwelcome. Hence, the content model permits but ghetto-izes that. If we want to make listRef more general, there's certainly no reason not to adopt MSM's suggestion, provided someone can tweak the stylesheets to cope reasonably with the consequence of having to deal with macro.paraContent and @craddoke 

2. Dealing with macro.paracontent means, for example, deciding which wins in the case that both content and @target are supplied. Should &lt;ref target="#sec1">Ye olde section wunne&lt;/ref> produce an auto-generated string  (as it would if this were a <ptr>) or should it produce one containing just the content of the &lt;ref>? or both?

3. Dealing with the availability of @cRef might be more problematic, but we have to do it for &lt;ptr anyway so...

4. Do we need both &lt;ptr> and &lt;ref> ? Why should we not say explicitly that a &lt;ref> with no content (or one containing just whitespace) is exactly the same as a &lt;ptr> ? Yes, we might need to enforce the presence of @target (or presumably @cRef) in this case, or decide what its absence means, but the same applies to &lt;ptr> for which we already use a schematron rule.

5. Syd notes that it would make more sense if the @target attribute of &lt;link> were (as it used once to be) called @targets.  I suspect this homogenization occurred during one of the minor skirmishes in the War on Attributes; I can't remember which side I was on at the time, but I thinkI  am now inclined to agree with Syd, if only because it removes one ambiguity in how to interpret a multivalued @target attribute

**Comment by laurentromary** [comment]
It is also nice to see this ticket has become a fruitful discussion place, but you summary seems to forget the initial (simple) request I had made. Il ne faudrait pas noyer le poisson :-}

**Comment by cref** [comment]
please don't enforce my presence

**Comment by sydb** [comment]
OK, @cref, I’ve taken you off the hook for now.

@lb42: I don’t follow what suggestion of @cmsmcq’s you are referring to here. In #1674 he suggests making the content model of `<listRef>` be `( model.ptrLike+ )`, but that has nothing to do with `@cRef` (let alone poor @cref) or `model.paraContent`, does it? Remember, just because `elementSpec/listRef` is allowed to have both `<ptr>` and `<ref>`, which it already is, does **not** mean that the TEI Stylesheets have to handle all the possible scenarios; just as likely we add a constraint in our own ODD file for writing P5 that disallows `<ref>`, `@cRef`, or anything else we don’t want in there.

**Comment by lb42** [comment]
I was referring to MSM's proposal to revise the content model of listRef to permit a promiscuity of ptr, ref, link as children, which being permitted I think we would need to address the questions I raised above. However I agree that this doesn't affect the question of where listRef itself should be permitted. It's not a member of any class at present because it was invented for a more specific role than the general "bunch of pointers of some kind" role proposed by Laurent, for which I continue to think that &lt;linkGrp> would be equally appropriate. Or maybe we should call it &lt;ptrGrp> to invite confusion with EAD?

**Comment by sydb** [comment]
OK. But @cmsmcq’s suggestion (in #1674) was to change the content model of `<listRef>` from `( ptr+ | ref+ )` to `( ptr | ref )+`. I.e., from “either a bunch of `<ptr>` or a bunch of `<ref>`, but not both” to “some combination of `<ptr>` and `<ref>`”. So it is not that much more promiscuous — no new elements. On the other hand, if we were to do both that and (per this ticket) add `<listRef>` to `model.ptrLike` then indeed, all of a sudden a `<listRef>` could nest inside a `<listRef>`.

The point you raise, that `<listRef>` was originally intended for a very specific purpose and none other, is a good one. It sounds like what @laurentromary wants is a way to group `<ref>`s. Instead of allowing `<listRef>` to float most anywhere in a TEI document, we could change the content model of `<linkGrp>` to include `<ref>`. (I.e., from the current `( link | ptr )+` to `( link | model.ptrLike )+`.) But then the next week someone will point out that `<relation>` does almost the same thing as `<link>`, and suggest it be in there, too.

@laurentromary — would that (allowing `<ref>` in `<linkGrp>`) work for your use case?


In our current state, we have 2 elements:

1) `<linkGrp>` — allowed almost anywhere; contains _empty_ elements that express links (either between here and there **or** among multiple theres)

2) `<listRef>` — allowed in or between paragraphs or in ODD elements; contains elements that express links from here to there

**Comment by cmsmcq** [comment]
> On Jul 28, 2017, at 8:51 AM, Syd Bauman <notifications@github.com> wrote:
> 
> OK. But @cmsmcq’s suggestion (in #1674) was to change the content model of <listRef> from ( ptr+ | ref+ ) to ( ptr | ref )+. I.e., from “either a bunch of <ptr> or a bunch of <ref>, but not both” to “some combination of <ptr> and <ref>”.

I have written the content model (ptr | ref)+ at least once in the last few days, but I think it’s not what I proposed in #1674.

********************************************
C. M. Sperberg-McQueen
Black Mesa Technologies LLC
cmsmcq@blackmesatech.com
http://www.blackmesatech.com
********************************************

**Comment by laurentromary** [comment]
@sydb if we follow your suggestion of using adding ref to linkGrp, we should then get rid of listRef. Having such a specific element for just one using is a bit of an overkill.

**Comment by sydb** [comment]
@cmsmcq: Well, right; to be precise you proposed “(model.ptrLike+)”. But since the only two current members of model.ptrLike are `<ptr>` and `<ref>` …

@laurentromary: Exactly. We would want to (deprecate then) remove `<listRef>`, and add a constraint for writing P5 itself that says “when `<linkGrp>` is in an ODD element, it should have nothing but 1+ `<ptr>` child(ren)”. (I’m not convinced that this is _the_ way to go, but it is _a_ reasonable solution.)

**Comment by scstanley7** [comment]
Hi all, I’m going to attempt to summarize the possible options for closing this ticket so @laurentromary can get the change he needs. I’ll be adding this to a discussion at a council meeting, but I’d like to get a sense of people’s preferences for the current options:

1. Original suggestion: Add `<listRef>` to `model.ptrLike`, no change to the content model of `<linkGrp>` (but implement the change in #1647).
2. Collapse `<listRef>` and `<linkGrp>` (deprecating `<listRef>`). This essentially would entail adding `<ref>` to the content model of `<linkGrp>` (per Syd’s suggestion, make the content model `( link | model.ptrLike )+`). Add constraints that contrain `<linkGrp>` when it is contained within an ODD element.

There were related proposals brought up during the course of this discussion, which I’m going to make some record of, and perhaps we can turn those into discrete discussion items (e.g. the `@targets` proposal or collapsing `<ptr/>`, `<ref/>`, `<link/>` in some capacity).

Let me know which of these proposals you prefer or if I missed an option that was proposed, and I can kick this over to the council at the next meeting.

**Comment by laurentromary** [comment]
My gut feeling would be to keep both elements and thus implement 1. In any case a nice add-on would be to have the corresponding element (linkGrp or listRef) made recursive so that we could have some structure when grouping references.

**Comment by lb42** [comment]
My guts have no feelings. But I am puzzled by your reference to #1647: which seems entirely unrelated.
I assume you meant #1674? (thetamesis rules...)
I am happy to go with a modified listRef (a) adding it to model.ptrLike (b) changing its content model to one-or-more model.ptrLike and (c) schematronically constraining it to contain only one-or-more ref when it appears as child of a *Spec element . Which I think is your option 1.

**Comment by scstanley7** [comment]
Yes, apologies. The above post has been edited to refer to the correct ticket :)

**Comment by raffazizzi** [comment]
F2F subgroup thinks @scstanley7 's solution (1) should be implemented.

**Comment by sydb** [comment]
So Council goes w/ @lb42 suggestion of [Sep 13](https://github.com/TEIC/TEI/issues/1667#issuecomment-329248706), noting that by “ref” he means `<ptr>`. However, we can’t actually constrain the content of `*Spec/listRef` to `<ptr>`s because we use `<ref>`s in compiled ODDs. However, we can (and should) constrain it to have only `<ptr>`s or `<ref>`s that have only a text node child.

**Comment by scstanley7** [comment]
How does the group feel about this language change for the `<desc>`?

> supplies a list of pointers or references, in the current document or elsewhere. `<listRef>` can be used to supply a list of significant references to places where an element is discussed, or it can be utilized to supply a more generic list of pointers and references.

And this added `<remarks>` bit:

> When used inside `model.oddDecl` elements like `<elementSpec>` or `<classSpec>`, `<listRef>` may only contain one or more `<ptr/>` or `<ref>` elements. When using `<ref>`, in these cases, the `<ref>` elements may only contain text.</p>
```
I wasn't sure about the best way to talk about `*Spec`, so if there's a better way to do that than talking about `model.oddDecl`, let me know.

**Comment by laurentromary** [comment]
I see I have not presented my use case. In legal documents (law, case law, treaties etc.), you often have cross references within or across the legal  which may come as bundles of similar objects (thus [listRef/@type](https://github.com/TEIC/TEI/issues/1803)). See [EPC - article 54](https://www.epo.org/law-practice/legal-texts/html/epc/2016/e/ar54.html) for a typical example.

**Comment by ebeshero** [comment]
Noting here that we'll resolve this issue with #2209. See https://github.com/TEIC/TEI/issues/2209#issuecomment-1065259060

**Comment by ebeshero** [comment]
Council decided that we'll add `<listRef>` to model.ptrLike as requested here, and broaden the language in its `<desc>` as proposed here. We'll include some more specific constraints on its use in `<model.oddDecl>` partly introduced in this ticket:  So, in `<model.oddDecl>` only (and not elswewhere):
* `<listRef>` is not permitted to nest
* must contain `@target`
* `@target` must not contain a space. 

I'm closing this ticket to consolidate work on `<listRef>` in #2209.
