### ISSUE TITLE
`@placement` definition not clear

### ISSUE THREAD

**Issue by emylonas** [TEIC/TEI#1669]
Follow on to #379 

The prose definition of the `@placement` attribute that belongs to `<punctuation>` is unclear. Currently, this is how it reads: 
``
@placement	indicates whether punctation marks have been captured inside or outside of an adjacent element.
Status | Optional
Datatype | teidata.enumerated
Legal values are: 
internal    punctuation marks are captured inside adjacent elements
external   punctuation marks are captured outside adjacent elements
``
The allowed values are `inside` and `outside`.

If the word `element` were changed to `tag`, then the sentences would make more sense. The sentence can be recast in a very complicated way: 
"...inside or outside the element which contains the text with which the punctuation mark is asssociated." ...

**Comment by lb42** [comment]
I don't think changing "element" to "tag" helps with this problem, if problem there be. We don't put punctuation marks inside a tag ! I think the issue is the use of "adjacent" which needs clarifying to something like "adjacent to the tag defining the start or end of the element containing the punctuation"
maybe revise like this:
@placement indicates whether punctuation marks found at the start or end of the textual content of an element are included before or after the tags marking it

internal : punctuation marks found at the start or end of the text content of an element are included within the element defining it;
external : punctuation marks found at the start or end of the text content of an element are included before or after the element defining it

an example would make this much clearer, obviously.

**Comment by emylonas** [comment]
`@placement` indicates the positioning of punctuation marks that are associated with marked up text as appearing within the element or immediately before or after the element.

internal : punctuation marks found at the start or end of marked up text are included within the element defining it;
external : punctuation marks found at the start or end of marked up text appear immediately before the element's start tag or immediately after the element's end tag.

an example would make this much clearer, obviously.

**Comment by emylonas** [comment]
modified prose and added examples. close with d5f31df

**Comment by lb42** [comment]
That doesnt seem to be the right commit link!

**Comment by emylonas** [comment]
closed with correct commit  9687289
