### ISSUE TITLE
Content model of choice is too permissive

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1690]
At present all of the following meaningless encodings are considered valid 
~~~~
<choice/>
<choice><choice/></choice>
<choice><reg>foo</reg></choice>
~~~~
This is because the content model says
~~~~
<content>
 <alternate minOccurs="0"
  maxOccurs="unbounded">
  <classRef key="model.choicePart"/>
  <elementRef key="choice"/>
 </alternate>
</content>
~~~~
I think it should say
~~~~
<content>
<sequence>
<alternate>
  <classRef key="model.choicePart"/>
  <elementRef key="choice"/>
</alternate>
 <alternate minOccurs="1"
  maxOccurs="unbounded">
  <classRef key="model.choicePart"/>
  <elementRef key="choice"/>
 </alternate>
</sequence>
</content>
~~~~
shirley?

**Comment by jamescummings** [comment]
Seems completely reasonable to me.  Am I reading that right, that this would force choice to have a minimum of two children? Only marking as 'Needs Discussion' to see if others have any objections

**Comment by sydb** [comment]
I agree completely w/ @lb42 that the content model he proposes is much better than the current one. Two further thoughts.

First, shouldn't it just be
~~~~~xml
<content>
  <alternate minOccurs="2" maxOccurs="unbounded">
    <classRef key="model.choicePart"/>
    <elementRef key="choice"/>
  </alternate>
</content>
~~~~~
? I submit that the PureODD above accepts and rejects exactly the same set of `<choice>`s, but is easier to read and, well, more pure. :-)

Second, I'd be in favor of tightening up this content model even more. Since I think
~~~~~xml
<choice>
  <sic>...</sic>
  <abbr>...</abbr>
</choice>
~~~~~
makes no sense, I think it probably should be disallowed.

**Comment by lb42** [comment]
I agree that the reformulation using  @minOccurs=2 makes better sense. 
However, I've no idea how to formulate all and only the meaningful possible  combinations of members of model.choicePart and think we should probably resist the urge to try. At least for the moment.

**Comment by jamescummings** [comment]
So the @sydb modification of the @lb42 proposal currently is:

~~~~~xml
<content>
  <alternate minOccurs="2" maxOccurs="unbounded">
    <classRef key="model.choicePart"/>
    <elementRef key="choice"/>
  </alternate>
</content>
~~~~~
Anyone disagree with that?

**Comment by lb42** [comment]
Make it so, Mr Spock.
