### ISSUE TITLE
ODD modelling global attribute as required on certain element

### ISSUE THREAD

**Issue by bwbohl** [TEIC/TEI#1699]
Hi!

I was wondering how  I could define in ODD an element as being member of a certain attribute class, and override the usage="opt" with a usage="req" for this element only. In my special case I was trying to require @xml:id from att.global on my custom element criticalNote.

I've tried:
```xml
<elementSpec ident="criticalNote" mode="add" module="my.module">
   <desc>Critical note.</desc>
   <classes>
      <memberOf key="criticalApparatus.part"/>
   </classes>
   <content>
      <classRef key="criticalNote.part" expand="sequence"/>
   </content>
   <attList>
      <attRef class="att.global" name="xml:id"/>
   </attList>
</elementSpec>
```
but @usage="req" is not possible on `<attRef>`. Likewise I was wondering if this could be done in `classes/memberOf` somehow?

Any suggestions?

Thanks!

**Comment by sydb** [comment]
Indeed, you need to use `<attDef>` rather than `<attRef>` in order to redefine an attribute as required. In the following example I‘ve made up a content model and put `<bwb:criticalNote>` into model.noteLike just ’cause it had to somewhere in order for me to test it.

~~~~~xml
	<elementSpec ident="criticalNote"
		     ns="http://www.exmpale.org/bwbohl"
		     mode="add">
	  <desc>Critical note.</desc>
	  <classes>
	    <memberOf key="model.noteLike"/>
	    <memberOf key="att.global"/>
	  </classes>
	  <content>
	    <elementRef key="epigraph"/>
	  </content>
	  <attList>
	    <attDef ident="xml:id" usage="req" mode="change"/>
	  </attList>
	</elementSpec>
~~~~~~

Note that you will typically get a faster response to questions like this if they are posted to TEI-L rather than here.

**Comment by bwbohl** [comment]
Dear Syd,

many thanks for the quick reply at least much quicker than my thanks!
You're definitely right about callback times on GitHub vs TEI-L ;-)
