### ISSUE TITLE
Clarify description of att.combinable's "mode"

### ISSUE THREAD

**Issue by raffazizzi** [TEIC/TEI#1715]
The definition of `@mode`'s values needs clarification. Here are a few notes from the Victoria F2F and my own understanding of the values' meaning. I tried to simplify terminology (e.g. changed "name" to "identifier") and clarify behavior. Changes in italics.

References: [att.combinable](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.combinable.html) and [Chapter 22.8.1](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TD.html#TDbuild)

## add
**Description**: this declaration is added to the current definitions.
**Note**: the object should be created (processing any children in add mode); raise an error if an object with the same identifier already exists
**Suggested changes (note)**:  the object should be created (processing any children in add mode); raise an error if the object *has an identifier and an object with the same identifier (and namespace in case of elements and attributes) already exists.*

## replace
**Description**:  this declaration replaces the declaration of the same name in the current definition
**Note**: use this object in preference to any existing object with the same identifier, and ignore any children of that object; process any new children in replace mode
**Suggested changes (description)**: this declaration replaces the *object* with the same *identifier (and namespace in case of elements and attributes)* in the current definition.
**Suggested changes (note)**: use this object in preference to any existing object with the same identifier *(and namespace in case of elements and attributes)*, and ignore any children of that object; process any new children in replace mode

## delete
**Description**:  if present already, the whole of the declaration for this object is removed from the current setup
**Note**: do not process this object or any existing object with the same identifier; raise an error if any new children supplied
**Suggested changes (description)**: *remove the object with the same identifier (and namespace in case of elements and attributes) as the current one.*
**Suggested changes (note)**: do not process this object or any existing object with the same identifier *(and namespace in case of elements and attributes)*; raise an error if any new children supplied

## change
**Description**: this declaration changes the declaration of the same name in the current definition
**Note**:  process this object, and process its children, and those of any existing object with the same identifier, in change mode
**Suggested changes (description)**: this declaration changes the *object* of the same *identifier (and namespace in case of elements and attributes)* in the current definition.
**Suggested changes (note)**: process this object, and process its children, and those of any existing object with the same identifier *(and namespace in case of elements and attributes). This will replace only those children elements that appear both in the original specification and in the new specification. Other children from the original specification will be preserved.*

**Comment by raffazizzi** [comment]
Related to https://github.com/TEIC/Stylesheets/issues/272. Pinging @sydb and @martindholmes for feedback.

**Comment by raffazizzi** [comment]
I'd like @sydb and @martindholmes to chime in about the proposed changes above because of https://github.com/TEIC/Stylesheets/issues/272.

**Comment by sydb** [comment]
Bravo, Raff. A few thoughts and suggested tweaks.

## all seven cases, specific
I’d prefer “(and namespace in the case of an element or attribute)” since the rest of the clauses these occur within are in the singular.

## general
Is it sufficient to refer to already existing objects by just their `@ident` and namespace? Doesn’t this imply that an ODD processor that comes across `<constraintSpec ident="blort" mode="delete">` should delete `<macroSpec ident="blort">`? So how about “if this object has an identifier, and an object of the same type already exists that has the same identifier (and the same namespace in the case of an element of attribute), then …” or some such?
I also don’t wonder if we shouldn’t be precise about those `@mode` combinations an ODD processor should consider an error vs warning. E.g., that if you come across something with an `@mode` of "change" or "delete" while you are processing an addition or replacement, should that be an error or a warning (or neither)?

## add
> … raise an error if _the object has an identifier and_ an object with the same identifier (and namespace in case of elements and attributes) already exists.

Interesting. I’m pondering about the ”if the object has an identifier” part of the last clause. Every element that has `@mode` also has a required `@ident` except `<valDesc>` and `<valList>`. So what this snippet changes is that previously an ODD processor wasn’t really sure if a `<valDesc mode=add>` or a `<valList mode=add>` should raise an error if a `<valDesc>` or `<valList>`, respectively, was already present. (It should not, because there are no `@ident`s to compare; or it should, because the values of the two `@ident`s are the same: namely, missing.) Now an ODD processor knows it should not raise an error in this case. I think I’m OK with that, as `<valDesc>` is explicitly allowed to repeat, and `<valList>` is nothing but a grouping element for a bunch of `<valItem>s`.

## replace
Hmmm…
Still seems a little confusing and weird to me, but may be unavoidable. How about “use this object in preference to any existing object of the same type that has the same identifier (and the same namespace in the case of an element or attribute), and ignore any children of that existing object; process the children of this element in replace mode”? Or perhaps “Remove any existing specification of the same type that has the same identifier (and the same namespace in the case of an element or attribute) entirely (i.e., including its children), and add this specification, processing its children in add mode”. (Note that processing the children of this specification in add mode has the exact same effect as processing them in replace mode, except it it more efficient as the processor doesn’t keep checking for a construct to delete, and makes more sense, at least IMHO.)

## delete
> raise an error if any new children supplied

What does that mean? Does it mean raise an error if the current element has a child element, or does it mean raise an error if the current element has a child that is in add, change, or replace mode? I.e., which, if any, of the following are errors?
~~~~~xml
<constraintSpec ident="quack" mode="delete" scheme="schematron">
  <desc>[prose here that may or may not match the existing description of "quack"]</desc> 
</constraintSpec>
~~~~~
~~~~~xml
  <elementSpec ident="foo" mode="delete">
    <constraintSpec ident="bar" scheme="schematron" mode="change">
      <constraint>
        <sch:assert test="true()">Huh?</sch:assert>
      </constraint>
    </constraintSpec>
  </elementSpec>
~~~~~
~~~~~xml
  <elementSpec ident="foo" mode="delete">
    <constraintSpec ident="bar" scheme="schematron" mode="delete"/>
  </elementSpec>
~~~~~
(This also makes me think of my age old question “why do I have to specify the `@scheme` of a constraint I am deleting?”, but I suspect that’s a conversation for another time. :-)

## change
Why not make it clear that it is the current children (i.e., those children being processed in mode "change") that replace the existing constructs? Also, the values of attributes (like `@usage`) get processed similarly. So perhaps something like “process this object and its children, replacing only those components of an existing object of the same type with the same identifier (and namespace in case of an element or attribute) that are explicitly specified. This will replace only those existing attribute values and child elements that appear both in the original specification and in the new specification. Other children from the original specification will be preserved.” Neither wording makes clear that a child element which has an `@mode` other than change is not processed in change mode. I hope that is made clear elsewhere.

**Comment by scstanley7** [comment]
F2F subgroup suggests moving away from using processing-focused language in the descriptions (and towards language that describes the *effects*). We suggest utilizing language like "is part of," instead of "is added to." Subgroup thinks notes look good.

**Comment by raffazizzi** [comment]
Note to self: go ahead and try to create definitions as suggested by F2F subgroup and submit for further discussion.

**Comment by raffazizzi** [comment]
Made changes as suggested by @sydb and Köln subgroup. Please read over again.

## add
**Description**: this declaration is added to the current definitions.
**Note**: the object should be created (processing any children in add mode); raise an error if an object with the same identifier already exists
**Suggested changes (description)**: this declaration *is part of* the current definitions.
**Suggested changes (note)**:  the object should be created (processing any children in add mode); raise an error if the object *has an identifier and an object with the same identifier (and namespace in the case of an element or attribute) already exists.*

## replace
**Description**:  this declaration replaces the declaration of the same name in the current definition
**Note**: use this object in preference to any existing object with the same identifier, and ignore any children of that object; process any new children in replace mode
**Suggested changes (description)**: this declaration replaces the *object* with the same *identifier (and namespace in the case of an element or attribute)* in the current definition.
**Suggested changes (note)**: use this object in preference to any existing object with the same identifier *(and namespace in the case of an element or attribute)*, and ignore any children of that object; process any new children in replace mode

## delete
**Description**:  if present already, the whole of the declaration for this object is removed from the current setup
**Note**: do not process this object or any existing object with the same identifier; raise an error if any new children supplied
**Suggested changes (description)**: *the object with the same identifier (and namespace in the case of an element or attribute) as the current one is no longer part of the current definitions.*
**Suggested changes (note)**: do not process this object or any existing object with the same identifier *(and namespace in the case of an element or attribute)*; *the element carrying this attribute must be empty: raise an error if there are any children*

## change
**Description**: this declaration changes the declaration of the same name in the current definition
**Note**:  process this object, and process its children, and those of any existing object with the same identifier, in change mode
**Suggested changes (description)**: this declaration changes the *object* of the same *identifier (and namespace in the case of an element or attribute)* in the current definition.
**Suggested changes (note)**: *process this object and its children, replacing only those components of an existing object of the same type with the same identifier (and namespace in case of an element or attribute) that are explicitly specified. This will change only those existing attribute values and child elements that appear both in the original specification and in the new specification. Other children from the original specification will be preserved.*

**Comment by raffazizzi** [comment]
I wonder if it's time to return to this. I think I was pushing for these adjustments as I worked on Roma, but I think they are still important. What do you think of the latest definitions? @sydb do the changed definitions above match your expectations of what the mode values mean?

**Comment by martinascholger** [comment]
@sydb, @ebeshero please comment on @raffazizzi's updates.

**Comment by ebeshero** [comment]
@raffazizzi I've just taken a long moment to review the latest descriptions you've provided here. I think the language is a lot clearer on the differences between add and replace and replace and change (which is what I was looking for in reviewing this). I think it's good.

**Comment by ebeshero** [comment]
@raffazizzi Do you want to try to get this into the upcoming release, or punt to the next one maybe if we should all review the wording again in a Council session?

**Comment by raffazizzi** [comment]
@ebeshero  I would like to see this in the new release. However, I see the ticket still has the Needs Discussion label, so I'm not sure if I can just go ahead and make the change directly. I have created a PR https://github.com/TEIC/TEI/pull/2269 and it would be great if we could merge it during this week, but if you or @sydb think the Needs Discussion label is there for a good reason, we should delay until we can discuss

**Comment by raffazizzi** [comment]
Bump. @ebeshero and/or @sydb if either of you think the Needs Discussion label was unnecessary, I will merge the PR  :)

**Comment by ebeshero** [comment]
@raffazizzi I have read the new language in your branch and it is significantly clearer than the current Guidelines language. I think we should merge this to include in this release. Inevitably we could continue discussing, but I think if we merge this now, we can start a new discussion of how to continue improving on what you’ve formulated.
