### ISSUE TITLE
make hyph/stress/syll members of att.notated

### ISSUE THREAD

**Issue by scstanley7** [TEIC/TEI#1734]
This was brought up by @laurentromary in a [comment](https://github.com/TEIC/TEI/issues/1510#issuecomment-331879152) on #1510, but I didn't implement it as a part of that ticket. If anyone has examples of the usage of `@notation` on `<hyph>`, `<stress>`, or `<syll>`, they would be appreciated!

**Comment by martinascholger** [comment]
If there are no objections, I'll set this to green and implement it.

**Comment by laurentromary** [comment]
No objection at all :-}. It is important that we have some coherence within the child of `form`.

**Comment by sydb** [comment]
I think I agree w/ @laurentromary, but it would be good to have an example or two. And we are in refrigeration, so proceed with caution. (You’d be breaking the rules which are designed to give us some time to test things and protect the release tech. But since you _are_ the release tech, and this is a pretty small schema change, I think it’s OK.)

**Comment by laurentromary** [comment]
I am spoken with Toma Tasovac on this and we do need to gather examples, but not in the short term (we need this for a TEI related exercice we are doing), so please implement this (no backward compatibility breaking, more coherence in the guidelines etc.) and keep the ticket open so that we have a nudge to produce examples.

**Comment by martinascholger** [comment]
The elements are member of att.notated now, commit bf620b1. I leave the ticket open for more examples from @laurentromary and Toma Tasovac (also for att.notated on other linguistic markup, see also #1514)

**Comment by susannehaaf** [comment]
In a joint attempt of Peter Stadler and me to work through some LingSIG issues this one came up as well. @laurentromary and @ttasovac: Are there already news concerning the examples?

**Comment by laurentromary** [comment]
@ttasovac : we should put this on the agenda of our forthcoming TEI lex meeting.

**Comment by martinascholger** [comment]
@laurentromary and @ttasovac : do you already have examples for this?

**Comment by martinascholger** [comment]
pinging @laurentromary and @ttasovac

**Comment by martinascholger** [comment]
The original request has been implemented - I'm closing this ticket. Feel free to reopen if you have an example for att.notated, @laurentromary and @ttasovac
