### ISSUE TITLE
Deprecate macroSpec/@type

### ISSUE THREAD

**Issue by raffazizzi** [TEIC/TEI#1737]
Since the introduction of pureODD, `macroSpec[@type='dt']` has been replaced by `dataSpec`. We should deprecate `macroSpec[@type='dt']`, which would make `macroSpec[@type='pe']` redundant. So we could deprecate both `@type` values and simply use `macroSpec` for paremeter entities (such as macro.paraContent, etc.)

**Comment by lb42** [comment]
I agree that @type is probly no longer needed on macrospec, but its misleading to say that macrospec is used for parameter entities. Its used for specifying macros ie abbreviations of other odd components typically conten t models. The abbreviation gets turned into a pe in dtdland, or a pattern in rng country, but in odd speak its just a macro.

**Comment by sydb** [comment]
F2F says to:
 * check for (and remove) code that depends on `macroSpec/@type`.
 * remove prose that implies `<macroSpec>` is for parameter entities.
 * nuke it.

**Comment by sydb** [comment]
This is just about the first bullet point, “check for (and remove) code that depends on `macroSpec/@type`.” Non-trivial.

1. Searched for the string "macroSpec" in all files named `*.sh`, `*.bash`, or `Make*` in both the Stylesheets/ and TEI/ directories, found none.

1. Used a commandline XPath search to look for `//@*[contains(.,'macroSpec')][..//@*[contains(.,'type')]]` in those same two directories, and for each hit print out the filename and element name of the parent of the attribute found.
1. My first try at this took **forever** because first I did not use an ultimante slash in the directory name on `find`, and then somehow I had a symlink in my Stylesheets/ directory that pointed to the Stylesheets/ directory. But after deleting that, it worked in ~0.5 s for each directory (i.e., a total of ~1 s).
1. Got 28 hits.
1. Deleted all hits that were for the element `<xsl:strip-space>` (which, BTW, probably occur because both the element macroSpec and typeDesc are in the value of `@elements`), leaving 19.
1. Removed TEI/P5/Utilities/TEI-to-tei_customization.xslt — I wrote that one, and know it’s not a problem — leaving 18.
1. Removed TEI/P5/Exemplars/tei_customization.xsl — it’s a generated file left over from Schematron execution — leaving 16 hits in 6 files:

filepath | GI | comment
---------|----|--------
Stylesheets/common/common_tagdocs.xsl | xsl:template | not `@type` of the `<macroSpec>`
Stylesheets/common/common_tagdocs.xsl | xsl:template | changed `test="@type = 'pe' or @type = 'dt'"` to `test="@type eq 'pe'"`
Stylesheets/odds/odd2dtd.xsl | xsl:if | changed `tei:dataSpec\|tei:macroSpec[@type='dt']` to `tei:dataSpec`
Stylesheets/odds/odd2dtd.xsl | xsl:apply-templates | changed `tei:dataSpec\|tei:macroSpec[@type='dt']` to `tei:dataSpec`
Stylesheets/odds/odd2dtd.xsl | xsl:if | changed `tei:macroSpec[not(@type='dt' or @predeclare='true')]` to `tei:macroSpec[ not( @predeclare eq 'true' ) ]`
Stylesheets/odds/odd2dtd.xsl | xsl:apply-templates | changed `tei:macroSpec[not(@type='dt' or @predeclare='true')]` to `tei:macroSpec[ not( @predeclare eq 'true' ) ]`
Stylesheets/odds/odd2dtd.xsl | xsl:when | changed `parent::tei:content/parent::tei:macroSpec[@type='dt']` to `parent::tei:content/parent::tei:dataSpec`
Stylesheets/odds/odd2dtd.xsl | xsl:template | see (a), below
Stylesheets/odds/odd2dtd.xsl | xsl:template | tests for 'epe', not 'dt'
Stylesheets/odds/odd2dtd.xsl | xsl:template | changed match for `tei:macroSpec[@type='dt']/tei:content/rng:choice` to `tei:dataSpec/tei:content/rng:choice`
Stylesheets/odds/odd2dtd.xsl | xsl:when | deleted `<xsl:when test="parent::tei:content/parent::tei:macroSpec[@type='dt']">` clause (another clause already tests for dataSpec)
Stylesheets/odds/odd2dtd.xsl | xsl:when | tests for 'pe', not 'dt'
Stylesheets/odds/teiodds.xsl | xsl:key | removed addition of `tei:macroSpec[@type='dt']` to the `<xsl:key>` named “DataMacroModule”
Stylesheets/odds/teiodds.xsl | xsl:template | not a test of `macroSpec/@type`
TEI-GitHub/P5/Scripts/purifyDataSpecs.xsl | xsl:template | seems to me should remain
TEI-GitHub/P5/Utilities/expand.xsl | xsl:for-each | tests for 'pe', not 'dt'

**a)** Folded template for `tei:macroSpec[@type='dt']/tei:content/rng:text` and `tei:dataSpec/tei:content/tei:textNode` into one that matches `tei:dataSpec/tei:content/tei:textNode \| tei:dataSpec/tei:content/rng:text`, as they did exactly the same thing.

8. Found 2 tests in odd2dtd.xsl which my search had failed to find: `test="not(@type) or @type='defaultpe' or @type='pe' or @type='epe' or @type='dt'">` in a pair of called templates. Changed them to `test="not(@type) or @type=('defaultpe','pe','epe')"`

9. Found a test in odd2dtd.xsl which my search had failed to find: `<xsl:if test="not(@type='dt')">`. I removed the conditional, as it now should *always* be true.

10. Issued a search for the string 'dt' surrounded by characters other than word chars, `<` or `>`, and filtered the results by filename. (`time egrep -R "[^a-zA-Z0-9<>]dt[^a-zA-Z0-9<>]" Stylesheets TEI | egrep -v '\.git/|Binary |\.(html|processed|rn[cg]|dtd|xsd):|\.compiled|/ChangeLog|p5subse|/p5.xml|/Source|/xhtml\.' | tee /tmp/erase.me | wc`.)

11. Result is 23 hits in 18 files, of which only 5 seem relevant (the rest all look to be the HTML `<dt>` element or a shorthand for a RELAX NG datatype library):

filepath | match | comment 
---------|-------|--------
TEI/Documents/pureODD/pureODDtutorial.xml | `type="dt") and a new <gi>dataRef</gi> element is used to select one as content for the` | should be left as is
TEI/I18N/extras-it.xml | `<valItem ident="dt">` | idunno what to do
TEI/I18N/teinames.xml | `<value ident="dt">` | idunno what to do
TEI/P5/Query/datatypes.xql: | `for $t in collection("/db/TEI")/tei:macroSpec[@type='dt']` | changed to just …/tei:dataSpec
TEI/P5/Scripts/purifyDataSpecs.xsl | `<xsl:template match="tei:macroSpec[@type='dt']">` | should be left as is

All these changes have been checked in at f61c48d here, and [Stylesheets f9b58f4](https://github.com/TEIC/Stylesheets/commit/f9b58f495ae28b3706b5f14669a4055a275c4d96)

**Comment by sydb** [comment]
In [Stylesheets commit 6ec1fd1](https://github.com/TEIC/Stylesheets/commit/6ec1fd1) I have further removed the dependencies on `@type` of "pe" (listed above) in Stylesheets/common/common_tagdocs.xsl and odds/odd2dtd.xsl, **except** that I am not sure what to make of the 3 tests in the latter that test for "pe", "epe", or "defaultpe". These values are not permitted as values of `@type` no `<macroSpec>` by the P5 schema. Are they fossils of previous versions, or generated as some sort of intermediate step?
I have not done historical research yet, in the hopes that someone (perhaps @lb42 or @jamescummings) knows off the top of his or her head. I have searched the entire Stylesheets/ and TEI/ directories for "defaultpe", and found none other than the two tests in odd2dtd.

**Comment by sydb** [comment]
I found no prose that implies `<macroSpec>` was for parameter entities. (I searched for both ">macroSpec" and "parameter.*ent".) 

In fc82edc I have removed `@type` attributes from our own `<macroSpec>`s, both in P5 and in examples. (Although not in the data.XXX macros, as they are to be removed at the same time.)

**Comment by sydb** [comment]
Actual deprecation just committed at d758c6c.
