### ISSUE TITLE
Schema problem with (msPart | msFrag)

### ISSUE THREAD

**Issue by schassan** [TEIC/TEI#1747]
Hi,

as we started using the relatively new element `<msFrag>` alongside `<msPart>`s, we constantly come across an error message saying, that instead of one of these elements the other one was expected.

I guess that the definition of the content model of `<msDesc>` is erroneous and that instead of

( msPart* | msFrag* )

the definition should be

( msPart | msFrag )*

cf. ( msName | altIdentifier )*

If I change the generated schemata manually, the "error" disappears.

Best, Torsten

**Comment by hcayless** [comment]
I think it was assumed at the time that you’d either be dealing with a document that is assembled from different parts (msPart), or that you’d be making a virtual reconstruction of a fragmented document (msFrag). If you’ve got a good example that needs both, I’m sure Council would be willing to adjust accordingly.

**Comment by schassan** [comment]
I don't really see the "either ... or" but an "as well as" here: We often have fragments attached to the binding or in other places. Those fragments don't belong to the book block but they don't constitute a composed manuscript either. Thus we sometimes have a manuscript that is both composed from different parts as well as it contains fragments which we would like to describe using msFrag.
Thus, the use of msFrag shouldn't be limited for reconstructions only? Even the wording in the Guidelines right now doesn't suggest this, does it: "... or bound into a larger manuscript"?

**Comment by hcayless** [comment]
The point of the wording is that a virtually reconstructed document might draw on pieces now bound in separate documents. MsFrag isn't intended for describing a "fragment" that's been bound into a codex—that's still an msPart. MsPart is for describing pieces of an assembled whole, whatever the nature of those pieces is, and msFrag is for describing pieces of something that was once unitary, but has been broken up into bits. So the distinction is between parts of a physical whole, and fragments that used to be part of a physical whole. 

That doesn't mean there can't be a situation where you'd want to do both, and if you've got an example, we'd love to hear it. Can you show us what you want to do?

**Comment by PietroLiuzzo** [comment]
Thanks @schassan for pointing me here from the mailing list. I have to make sure I get notifications from this repo. I have this example. 
BNF _et_ 45 and BNF _et_ 165, which contains leaves detached from BNF _et_ 45. 

BNF _et_ 45 is not a reconstructed manuscript, is there, just it does not have any more those leaves, which constitute a fragment of it. 

So, for the encoding of BNF _et_ 165 we are all set on msPart, but I would not want to have two manuscript descriptions e.g., 
 - one for stage 1 of BNF _et_ 45 using msFrag pointing to the current BNF _et_ 45 and to the leaves in BNF _et_ 165; 
- and one for stage 2 being the current BNF _et_ 45 with a msPart corresponding to what is left after deprivation.  

It would be much easier (and this is what we are currently doing) to have in the description of BNF _et_ 45  msPart and a msFrag in the msDesc.

We are then working on formalising the relations between these parts as in the book "La Synthax du Codex", using an ontology based on that book, which will describe formally what happens.

**Comment by schassan** [comment]
As I stated on the list: Even after I realised that I failed to read ch. 10.11 in order to understand `<msFrag>` completely,

I think that the usage of msFrag for everything that once was unitary (and what we call a "fragment" today!) isn't bad, only that it should be allowed in any given manuscript description, even if one describes "an assebled whole". Because there's a whole lot of manuscripts out there that are both composite *and* have fragments.

I understand that your idea of the usage of `<msFrag>` is to have in a `<msDesc>` at least two `<msFrag>`s with the requirement for both of them to have a different `<msIdentifier>`, at least with a different shelfmark? Only then this `<msDesc>` would suffice to be a virtual reconstruction.

Whereas I would like to see `<msPart>` and `<msFrag>` be allowed side-by-side and even share the msIdentifier, meaning that all parts (or fragments) can be found in the same "manuscript".

And as I pointed out on the list, Pietro's and my request have different origin but result in the same change of the schema.

**Comment by Jean-Baptiste-Camps** [comment]
Having seen the debate on the list, and being a user of the `msFrag` element, I'll allow myself an opinion here:
on my part, I think it is very good to allow for use of either `msFrag` or `msPart`, because, in your `msDesc`, you are either describing a virtual reconstructed manuscript (then `msFrag`), that is you are acting critically as an expert and offering a reconstruction hypothesis; or you are describing an actual volume on a library shelf, with a shelfmark, etc., and then you use `msPart` if it is composite.

In fact, I'm a bit afraid that the possibility of using both would create mixed manuscript descriptions, describing in the same time an existing volume and a reconstructed manuscript, which are very different thing. To be a bit schematic, if you are writing a library catalogue, you'll use `msPart` , and if you are describing the witnesses of your text in your critical edition, or reconstructing an ancient library of  _membra disjecta_, for instance, you'll use `msFrag`. I can't think of use case where I would need to use both.

  | Hide Latest Messages
-- | --
 

you'll probably use `msFrag`

**Comment by schassan** [comment]
I just realise that this "issue" addresses the same thing as https://github.com/TEIC/TEI/issues/1680. (Thanks to @hcayless I finally understood what the issue is all about.)

**Comment by holfordm** [comment]
As I argued on the list, my preference would be (like @Jean-Baptiste-Camps ) to keep `msFrag` for reconstructed manuscripts and to use `msPart` for describing composite manuscripts (however defined, and including binding fragments in otherwise non-composite manuscripts). `@type` can be use on `msPart` to clarify the nature of the fragment. Attributes from att.global.linking (e.g `@sameAs` ? could be used to point to `msPart `from `msFrag` in the event that a description of part of a reconstructed ms already existed in TEI.
One cannot always know (can one?) if part of a composite manuscript is a fragment of another manuscript, or not - that is, in Torsten's terms, whether it is msFrag or msPart
(maybe this isn't the right place, but I would be interested incidentally to hear how other projects describe endleaves - whether endleaf - main ms - endleaf are all put in `msPart` or some other solution (e.g `msPart` in `accMat`?)

**Comment by jamescummings** [comment]
Council decided to clarify the definition of msFrag via issue #1832 and close this one.
