### ISSUE TITLE
Make <q> a member of att.fragmentable

### ISSUE THREAD

**Issue by mccaskey** [TEIC/TEI#1750]
As suggested here: https://listserv.brown.edu/archives/cgi-bin/wa?A2=tei-l;71ecda83.1710)

**Comment by sydb** [comment]
If `<q>` were a member of att.fragmentable, why wouldn’t `<hi>`, `<quote>`, `<said>`, etc., also?

In the general case (not necessarily the OP’s actual case), `@part` is not helpful, or at least can be confusing, on an element that can self-nest. Is there something wrong with `@next` and `@prev` for this?

**Comment by ebeshero** [comment]
@sydb I agree about the confusion potentially generated by adding `<q>` and related elements to `att.fragmentable`, since we often need to self-nest these kinds of elements. But the elements belonging to `att.fragmentable` are either `att.divLike` or `att.segLike--and we *do* commonly self-nest `<div>` elements, so I'm wondering whether the situations might be similar after all. 

The examples we have for uses of `att.fragmentable` seem to apply it for a couple of distinct and rather different purposes on structural elements, and the second one here seems most pertinent to this discussion about `<q>` (and `<said>` and others like these to do with cues of speaking or quoting). 
1) Indicating that something is only partial, and *not completely represented* in a TEI encoding:  See this example of `@part` on div in http://www.tei-c.org/release/doc/tei-p5-doc/en/html/DS.html#DSDIV3X

That indicates that `@part` should be used to indicate whether a `<div>` is an isolated portion of something--either an initial, medial, or final portion of a larger structure that isn't going to be represented in the TEI document. 

2) Spoken expressions When used on `<l>`, (in an example from http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COVE ) we see it applied to indicate that a verse line in a play is interrupted by a stage direction: 
```
<l part="I">A Workeman in't.</l>
<stage>Enter an Armed Soldier.</stage>
<l part="F">Good morrow to thee, welcome.</l>
```
Perhaps both of these uses are consistent with one another. There is another example in this section (from the poem _Rime of the Ancient Mariner_ , no less, and one that's even *discussing* cutting something apart around an obstacle and re-uniting it again later) showing a group of lines fragmented around indications of a change in speaker: 
```
<sp>
 <speaker>First Voice</speaker>
 <lg type="stanza" part="I">
  <l>But why drives on that ship so fast</l>
  <l>Withouten wave or wind?</l>
 </lg>
</sp>
<sp>
 <speaker>Second Voice</speaker>
 <lg type="stanza" part="F">
  <l>The air is cut away before,</l>
  <l>And closes from behind.</l>
 </lg>
</sp>
```
One more point: The Guidlines in this chapter show examples of *nested* `<lg>` elements for a sonnet stanza, showing groupings of sestets and quatrains within a larger grouping. Putting the pieces together, we can expect to be able to mark when these are fragmented by an obstacle such as an indicator of a new speaker.

Conceptually, based on this review of examples, I think we do see grounds for applying `att.fragmentable` in the opposite way, to indicate when portions of a spoken passage are interrupted by lines or stanzas or other structural elements. So, how do we currently deal with ambiguities posed by nested sub-levels in elements marked as fragmentary?

**Comment by sydb** [comment]
Wow, @ebeshero, your analysis is quite impressive. (Although I don’t know which of the three examples of `<div>` in DSDIV3X you mean; and I think your (1) is really describing `@sample`.) But it boils down to “that’s the way the Guidelines have always allowed it”. And although that’s true, it is a problematic methodology when applied to `<said>` or `<div>` (but not to `<l>`, which cannot self-nest, except in crazy circumstances). I think the Guidelines either have to take a position on what something like
~~~~~xml
<said part="I">One <said part="I">two</said></said> <said part="F">three</said> <said part="F">four</said>
~~~~~
means, or suggest that people avoid using `@part` in this sort of situation. Until we’ve got that right, I’m not sure it makes sense to add another case of undefined semantics to the Guidelines.

**Comment by sydb** [comment]
Council discussed this ticket and believes (almost, but not quite, unanimously) that the proper encoding for the original use case (as we understand it) is to use `@next` or `@prev` (or both). E.g.
~~~xml
<lg>
  <l>At the beginning of class, Chris said,</l>
  <l><said>Encoders must learn this</said>, I've read.</l>
  <l>So that they can then say</l>
  <l>That <said next="#ds07">Encoding this way,</said></l>
  <l><said xml:id="ds07">Overlap does not fill me with dread.</said></l>
</lg>
~~~
An out-of-line `<join>` element could obviously be used instead, but our sense of community practice is that this is much rarer.
The suggestion raised on this issue, to use the `@part` of att.fragmentable instead, would lead to somewhat simpler encoding, but has the significant drawback of ambiguity in some cases of self-nested elements. And the argument that TEI already has cases of self-nesting elements in att.fragmentable is an argument for taking those elements out of att.fragmentable, not putting more self-nesting elements in.

Additional comment by me (i.e., not sanctioned by Council) …

The original request actually used the `<q>` element, not the `<said>` element. This leaves me puzzled. The `<q>` element is for passages which are "distinguished from the surrounding text using quotation marks or a similar method". If you were to use `<q part="I">Confusing,</q> she said <q part="F">to encode them as one thing.</q>` or `<q next="#mn45">Confusing,</q> she said <q xml:id="#mn45">to encode them as one thing.</q>`, I (or more importantly, my software) might infer that there was only one pair of quotation marks in the source text.
