### ISSUE TITLE
jTEI constraint "jtei.sch-rangeHyphen" is too strict

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1759]
The constraint `jtei.sch-rangeHyphen` in the jTEI schema is intended to flag numeric ranges encoded with a hyphen instead of an en dash:
~~~~~xml
      <sch:rule context="
text()
[ not( ancestor::tei:eg | ancestor::eg:egXML | ancestor::tei:code | ancestor::tei:tag | ancestor::tei:idno | ancestor::tei:date) ]
[ not( . = parent::*/@* ) ]  ">
        <sch:assert test="not(matches(., '\d-\d'))">
          Numeric ranges should not be indicated with a hyphen. Please use 
          the EN Dash (U+2013 or –) character instead.
        </sch:assert>
      </sch:rule>
~~~~~
While I appreciate the cleverness of the `not( . = parent::*/@* )` clause, which prevents this rule from firing on, e.g., `<date when="2018-04-01">2018-04-01</date>`, it would not fire on this anyway, because of the `not( … ancestor::tei:date )` bit. More importantly, this rule would complain about many ISBNs (“0-19-853737-9”), US and Canadian phone numbers (“202-224-2541”), or any US Social Security Number, which take the form 000-00-0000.
I have not tested it thoroughly, but I have tested it a bit, and I think the following represents a significant improvement.
~~~~~xml
      <sch:report test="matches(., '[^\d-]\d+\s*-\s*\d+[^\d-]|^\d+\s*-\s*\d+[^\d-]|[^\d-]\d+\s*-\s*\d+$')"> …
~~~~~

**Comment by rvdb** [comment]
@sydb I agree that the current regex is probably too simplistic. I'm wondering, though, whether information like ISBN codes, social security numbers shouldn't be encoded in `<idno>` (though I don't know if `<idno type="phone">202-224-2541</idno>` would make any sense). If so, it would technically not be necessary to change the regex, although it might be more user-friendly to either allow for more nuanced hyphen/digit combinations in "bare" text, or add a suggestion to use the appropriate tag for formal identifiers. 

But still, your regex suggestion probably improves on detecting true numeric ranges. Yet, wouldn't this be a more concise version:

    (^|[^\d-])\d+\s*-\s*\d+([^\d-]|$)

?

**Comment by rvdb** [comment]
I've been giving this some more thought, and think the regex can be refined further to:

    (^|[\W-[-]])\d+-\d+([\W-[-]]|$)

This will isolate the matching strings more precisely to only 2 series of consecutive digits, separated by a hyphen. The class subtraction `[\W-[-]]` will match anything that is a word boundary, except the hyphen. This also excludes (pseudo-)numeric ranges that occur inside consecutive strings with other non-digits, as may happen in URLs, e.g. `http://just.a.test?q=1-2&amp;so+on`. While this matches the previous version of the regex, it doesn't match the version above. I guess the `[ not( . = parent::*/@* ) ]` predicate was a way to catch and exclude URLs from this Schematron check (since they would typically have the same text value as their parent's `@target` attribute).

Of course, it would be nice to use this specific regex in a Schematron Quick Fix, offering a replacement of the hyphen with the EN dash. The only problem is that in cases where two different numeric ranges are separated by a single space as in `0-9 0-9`, this regex only catches the first one. OTOH, there _is_ a match, and if a SQF replacement still leaves the second one untouched, the Schematron rule will be triggered a second time, so I think it still is an improvement.

**Comment by rvdb** [comment]
(sigh, Git...) https://github.com/TEIC/TEI/pull/1762 had nothing to do with this, so I've reopened the issue for closing when https://github.com/TEIC/TEI/pull/1761 is merged
