### ISSUE TITLE
<desc> as child of model.listLike

### ISSUE THREAD

**Issue by joeytakeda** [TEIC/TEI#1771]
Is there a reason why `<desc>` (`model.descLike`) isn't allowed as a child to the elements in `model.listLike`? 

It think it would be helpful to be able to provide descriptions on lists, particularly if you have different lists for different reasons (say a `<listPerson>` for all historical people and a `<listPerson>` for all contributors to a project).

**Comment by martinascholger** [comment]
@joeytakeda: I can relate to what you mean. 
These are the affected elements: list (note allowed) listApp listEvent listNym listOrg listPerson listPlace listRelation listWit table (note allowed). Does anything speak against allowing `<desc>`?

**Comment by joeytakeda** [comment]
If this is uncontentious, then I would be happy to implement this. What needs to happen, I think, is:
* In most cases (all affected elements other than `<list>` and `<table>`) `<desc>` (or, more appropriately, `model.descLike`) would be an optional element after `model.headLike`. 
* For `<list>` and `<table>`, `<desc>` should be added after the sequence of `model.headLike` and `model.global`. It does seem odd, however, that for `<table>`, you can have 0 or more `model.headLike`; surely, there is no reason for having more than 1 `<head>` in a `<table>`?

The guidelines would have to remind that `<desc>` functions as a documentation element .

**Comment by jamescummings** [comment]
The use of `<desc>` has semantically loosened since it was first used purely for documentary elements (e.g. elementSpec). This is why the desc of `<desc>` is "contains a brief description of the object documented by its parent element, typically a documentation element or an entity." And why its cross reference from the element reference page in the Guidelines is to chapter 22 http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TD.html#TDcrystalsCEdc 

Since that definition is now not 'typical'... maybe that should change slightly as well? Something that made it clear that it is documentary with reference to the parent, not just a random note, is always important to include.

**Comment by sydb** [comment]
Council greenlights this as a go.

**Comment by jamescummings** [comment]
To clarify, Council meeting at Folger on 2019-05-07 agrees to add desc to member of model.listLike (table already has it).

**Comment by martinascholger** [comment]
@jamescummings, I am closing this. It already seems to have been done on May 8.
