### ISSUE TITLE
location of model.ptrLike elements within biblStruct

### ISSUE THREAD

**Issue by kshawkin** [TEIC/TEI#1788]
According to https://github.com/TEIC/TEI/issues/385 , Council once decided that `idno` should not be used as a child of `biblStruct` but should instead only be used as a child of `analytic`, `monogr`, or `series`.

However, I've just discovered an instance where `ref` is given as a child of `biblStruct`: see the Coombs, Renear, and DeRose example at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COBICOL .  In this example, it seems that the `ref` should be moved to be a child of `analytic` since the URL relates to the article, not the journal issue.

If we accept that a `ref` should only be a child of that to which it most closely relates, that the Sukovic example at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COBIXR should also be revised to move the `ref` from under `monogr` to under `analytic`.

The rest of P5, especially the bibliography, should be reviewed as well for consistency.

**Comment by kshawkin** [comment]
I should add that it's worth considering whether to deprecate `model.ptrLike` as a child of `biblStruct`, as was done for `idno` ( https://github.com/TEIC/TEI/issues/385 ).

**Comment by ebeshero** [comment]
I'm assigning this to @jamescummings to see if he agrees with @sydb and @kshawkin . The description of `biblStruct`does seem to preclude anything that isn't a "bibliographic sub-element"...

**Comment by jamescummings** [comment]
1. I agree that both these examples should be changed to have the ref under analytic.
2. I'm wary of deprecating model.ptrLike as a child of biblStruct just in case it has been used en masse by anyone. Have you encountered people doing this at all?

**Comment by laurentromary** [comment]
Since it breaks backward compatibility we should deprecate the construct enough in advance rather than changing the content model on the fly. This would prevent discontent.

**Comment by emchateau** [comment]
I’m heavilly using idno as child of biblStruct and find it very convenient to give references for the record separately from the analytic or the monogr elements.
For exemple I’ve got a bibliographic list of all printed books for a given title in my corpus. Each BiblStruct is derived from a catalog record wich have in id and is available as linked open data. So I refer to this record through an idno :
```
<biblStruct xml:id="brice1717" type="manifestation">
               <monogr>
                  <author> <persName ref="#briceGermain"> <forename>Germain</forename>
                     <surname>Brice</surname> </persName> </author>
                  <title level="m"
                     >Description de la ville de Paris et de tout ce qu’elle contient de plus remarquable, par Germain Brice ; enrichie d’un nouveau plan et de figures dessinées et gravées correctement. 7e édition, revue et augmentée par l’auteur</title>
                  <imprint>
                     <date when="1717">1717</date>
                     <pubPlace>Paris</pubPlace>
                     <publisher>F. Fournier</publisher>
                  </imprint>
                  <extent>In-12</extent>
               </monogr>
               <idno type="catBnf">http://catalogue.bnf.fr/ark:/12148/cb30160624f/</idno>
            </biblStruct>
```
The idno is not the one of the book, neither the one of the exemplar, but the one of the record.
In the french national library catalog, p.e., there are multiple record for one single exemplar. And sometimes, one record for multiple exemplar wich are identified by their "cote".

**Comment by emchateau** [comment]
Yes, it’s a matter of semantic because it is not describing the same thing ! I think, that’s really important, especially in the perspective of the semantic web.

The `idno` child of a `monogr` is describing the `monogr` element. Currently my `idno` is describing the bibliographical description, that’s why it is child of the `biblStruct`. All the more, the fact that `idno` doesn’t allow other attributes than @type to categorize them, makes it difficult to distinct them if we are not using the TEI hierarchy of elements.

What do you mean by not changing the schema ? that it wouldn‘t be allowed by default, at least that we customise it with ODD ? How would this use of idno as child of biblStruct would then be conformant with TEI-all ? (currently it seems that it is not allowed anymore with TEI-all)

By the way, in `monogr` and `analytic`, I don’t see any reason why the order of `idno` is prescribed in the childs sequence.

And an other matter about idno, there are cases when we need to use it with various king of identifiants. For exemple, ISNI have ISNI numbers and ISNI uris, the same for ORCID, etc. In library catalogs, you often have an id for a record which is sometime different from the permalink URI or handle, purl, and so on. Curently, the fact that you can’t categorize by other mean the `idno` element that by @type, doesn’t allo to say this is an URI or an ID and is from xxx source.

```
<listBibl>
  <!-- ... -->
  <biblStruct xml:id="brice1717" type="manifestation">
    <monogr>
      <author>
        <persName ref="#briceGermain"> 
          <forename>Germain</forename>
          <surname>Brice</surname>
       </persName>
      </author>
      <title level="m">Description de la ville de Paris et de tout ce qu’elle contient de plus remarquable, par Germain Brice ; enrichie d’un nouveau plan et de figures dessinées et gravées correctement. 7e édition, revue et augmentée par l’auteur</title>
    <imprint>
      <date when="1717">1717</date>
      <pubPlace>Paris</pubPlace>
      <publisher>F. Fournier</publisher>
    </imprint>
    <extent>3 vol. ; In-12</extent>
    <idno type="bnf">8-LK7-6002 (A,1)</idno>
    <idno type="bnf">8-LK7-6002 (A,2)</idno>
    <idno type="bnf">8-LK7-6002 (A,3)</idno>
    <!-- <idno type="frenchNationalBibliography">if I had one</idno> -->
  </monogr>
  <idno type="catBnf">http://catalogue.bnf.fr/ark:/12148/cb30160624f/</idno>
</biblStruct>
</listBibl>```

**Comment by kshawkin** [comment]
See below ...

> What do you mean by not changing the schema ? that it wouldn‘t be allowed by default, at least that we customise it with ODD ? How would this use of idno as child of biblStruct would then be conformant with TEI-all ? (currently it seems that it is not allowed anymore with TEI-all)

I was referring to the discussion above on this issue, which Syd summarized as item (b) in his list of things to implement: [deprecating](http://teic.github.io/TCW/tcw27.html) use of all model.ptrLike elements as a child of `<biblStruct>`, instead only allowing them as children of `<analytic>`, `<monogr>`, or `<series>`.

But now I realize that you are discussing use of `<idno>` in these locations, not model.ptrLike elements!  That, in turn, refers back to #385, where `<idno>` was deprecated as a child of `<biblStruct>` and in fact has been removed entirely as an allowed child of `<biblStruct>`:

https://github.com/TEIC/TEI/commit/c9279125b98c125502be42ed740c546409927c32#diff-e971f879792ed08d3991da2c0cb08bf9

As you'll see in the comment on lines 49-51 at the link above, Council had decided that you should use `<ptr/>` or `<ref>` for identifiers.  Thus your example would better be:

```
<biblStruct xml:id="brice1717" type="manifestation">
    <monogr>
      <author>
        <persName ref="#briceGermain"> 
          <forename>Germain</forename>
          <surname>Brice</surname>
       </persName>
      </author>
      <title level="m">Description de la ville de Paris et de tout ce qu’elle contient de plus remarquable, par Germain Brice ; enrichie d’un nouveau plan et de figures dessinées et gravées correctement. 7e édition, revue et augmentée par l’auteur</title>
    <imprint>
      <date when="1717">1717</date>
      <pubPlace>Paris</pubPlace>
      <publisher>F. Fournier</publisher>
    </imprint>
    <extent>3 vol. ; In-12</extent>
    <idno type="bnf">8-LK7-6002 (A,1)</idno>
    <idno type="bnf">8-LK7-6002 (A,2)</idno>
    <idno type="bnf">8-LK7-6002 (A,3)</idno>
    <!-- <idno type="frenchNationalBibliography">if I had one</idno> -->
  </monogr>
  <ptr type="catBnf" target="http://catalogue.bnf.fr/ark:/12148/cb30160624f/"/>
</biblStruct>
```

(or replace `<ptr/>` with `<ref>` if you prefer).

If you don't think this is appropriate for your need, I suggest creating a new issue here in GitHub, proposing that `<idno>` be added back as a child of `<biblStruct>`.

> By the way, in monogr and analytic, I don’t see any reason why the order of idno is prescribed in the childs sequence.

If I understand correctly, you are saying that do not see any particular reason for `<idno>` to occur in a particular order among the child elements of `<biblStruct>`.  As you can see from [the content model of `<biblStruct>`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-biblStruct.html), the order of child elements is flexible following `<series>`.

> And an other matter about idno, there are cases when we need to use it with various king of identifiants. For exemple, ISNI have ISNI numbers and ISNI uris, the same for ORCID, etc. In library catalogs, you often have an id for a record which is sometime different from the permalink URI or handle, purl, and so on. Curently, the fact that you can’t categorize by other mean the idno element that by @type, doesn’t allo to say this is an URI or an ID and is from xxx source.
> <listBibl>
>   
>   <biblStruct xml:id="brice1717" type="manifestation">
>     <monogr>
>       <author>
>         <persName ref="#briceGermain"> 
>           <forename>Germain</forename>
>           <surname>Brice</surname>
>        </persName>
>       </author>
>       <title level="m">Description de la ville de Paris et de tout ce qu’elle contient de plus remarquable, par Germain Brice ; enrichie d’un nouveau plan et de figures dessinées et gravées correctement. 7e édition, revue et augmentée par l’auteur</title>
>     <imprint>
>       <date when="1717">1717</date>
>       <pubPlace>Paris</pubPlace>
>       <publisher>F. Fournier</publisher>
>     </imprint>
>     <extent>3 vol. ; In-12</extent>
>     <idno type="bnf">8-LK7-6002 (A,1)</idno>
>     <idno type="bnf">8-LK7-6002 (A,2)</idno>
>     <idno type="bnf">8-LK7-6002 (A,3)</idno>
>     
>   </monogr>
>   <idno type="catBnf">http://catalogue.bnf.fr/ark:/12148/cb30160624f/</idno>
> </biblStruct>
> </listBibl>```

Remember that you should use `<ptr/>` or `<ref>` rather than `<idno>` for URIs rather.  Also keep in mind that `@subtype` is available on `<idno>` in addition to `@type`.

**Comment by emchateau** [comment]
Thanks a lot for your reply. It‘s my mistake because I’ve confond te two issue. I’m really concerned by the suppression of idno from biblStruct and I don’t understand why it have been done. Thanks also for @subtype, didn’t knew about it, it solve the issue for links.

**Comment by sydb** [comment]
Right, @emchateau is clearly talking about `<idno>` child of `<biblStruct>`, and thus should re-open (or otherwise re-raise) #385.

## on @emchateau’s question

That ticket was opened in 2012 and resolved in 2014, so I would not hold my breath for it to change, especially given that the use case you’re talking about probably calls for `<ptr>`, not `<idno>`.

Note, BTW, @emchateau, that `<ptr>` also has
- both `@type` and `@subtype`
- `@mimeType` for saying what kind of thingy you should get back from `@targert`
- `@targetLang` for saying in what natural language the thingy is written
- `@evaluate` for saying what you (the processor) should do if the thingy is itself a pointer 

It does not, however, have all the dating attributes that `<idno>` has. It (`<ptr>`) does have `@cRef` (intended as an alternate to `@target`), but I think it is better to use a locally abbreviated URI and a `<prefixDef>` these days.

## on the real point of this ticket

So … does the discussion of `<idno>`, above, make us think we should **not** deprecate the use of model.ptrLike as a direct child of `<biblStruct>`? (I.e., negating my (b), [above](#issuecomment-412987160), as @kshawkin pointed out [12 days ago](#issuecomment-414092011)

**Comment by kshawkin** [comment]
That's right, I believe the consensus is to do just the following:

1. Adjust the Coombs, Renear, and DeRose example to move the `<ref>` under `<analytic>`.
2. Add Emmanuel's first example to P5 except change `<idno type="catBnf">http://catalogue.bnf.fr/ark:/12148/cb30160624f/</idno>` to `<ptr type="catBnf" target="http://catalogue.bnf.fr/ark:/12148/cb30160624f/"/>`.

No schema changes needed.

**Comment by martinascholger** [comment]
Do you mind if I steal this from you, @jamescummings?

In addition to the Coombs, Renear, and DeRose example, the Sukovic example at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COBIXR should also be adjusted (make ref a child of analytic instead of monogr), right? @kshawkin mentioned it at the beginning.   

I would add Emmanuel's example at the end of http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COBIXR and propose this description
 
"The `<ptr>` element may be used as a child element of `<biblStruct>` to refer to a bibliographic description itself, such as a catalog record:"

Can we mark this green?

**Comment by jamescummings** [comment]
Feel free. Thanks! I concur with your plan.

**Comment by martinascholger** [comment]
At F2F Washington, Council agreed with this rewording: 
"The `<ptr>` element may be used as a child element of `<biblStruct>` to refer to the online catalog record of this bibliographic item:"

**Comment by emchateau** [comment]
Thanks a lot for the follow up.
I’ll correct my encoding with this solution.
Best regards,
Emmanuel

**Comment by martinascholger** [comment]
Close, 00615f2

**Comment by glorieux-f** [comment]
I’m working on the TEI translator for Zotero, thanks for this interesting discussion. The translator should be corrected, the output of URL of an item is odd (?? <note type="url">), but there is a nice idea for @emchateau, a @corresp attribute for the URL of the record.

```  
<biblStruct type="journalArticle" xml:id="de_Rougemont2010" corresp="http://zotero.org/users/8989645/items/DITJYYQ3">
    <analytic>
      <title level="a">Le théâtre en France sous l'Ancien Régime : à l'origine de l'exception culturelle française.</title>
      <idno type="DOI">10.3917/rip.252.0199</idno>
      <title type="short">Le théâtre en France sous l'Ancien Régime</title>
      <author><forename>Martine</forename><surname>de Rougemont</surname></author>
    </analytic>
    <monogr>
      <title level="j">Revue internationale de philosophie</title>
      <idno type="ISSN">0048-8143</idno>
      <imprint>
        <biblScope unit="volume">252</biblScope>
        <biblScope unit="issue">2</biblScope>
        <biblScope unit="page">199-206</biblScope>
        <date>2010</date>
        <note type="accessed">2023-06-13T15:09:31Z</note>

        <note type="url">https://www.cairn.info/revue-internationale-de-philosophie-2010-2-page-199.htm</note>

      </imprint>
    </monogr>
  </biblStruct>
```
