### ISSUE TITLE
How to solve "IllegalStateException - cannot validate without schema"

### ISSUE THREAD

**Issue by kev1807** [TEIC/TEI#1799]
Hi there once again, 

I am sure, this is quite the beginner question, however it stops me from working ... 
I have created my own TEI.ODD and created a new project with OxygenXML, connected to my exist-db

As I understand, I need to validate the schema, isn't that what the O(ne D(ocument) D(oes it all) file is for? 
I'm pretty sure it is here :
`<?xml-model href="/db/apps/Wager/resources/odd/tei_boo.odd" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?><TEI xmlns="http://www.tei-c.org/ns/1.0">`

Another problem: 
I attempt a facsimile-edition  (for training purposes mainly, so that before I start I have more experience using tei, exist-db and Oxygen):

Edit: Somehow github does not allow huge secitons of code to be posted ... I am talking about the <facsimile> </facsimile> part and the following <text> </text> which can be found in the pastebin at the bottom of this post!

It's more pictures but I doubt that's relevant: the text "the text must go here" should be displayed, even using standard-css from Oxygen, am I right? 

If I am completely off, I'd sure appreciate a hint! 
(Tei by example was not of too much help, neither was googling it ... I have worked through the DARIAH examples and many more, still I do not get the results I want/need)

In case I forgot something essential: 
the ODD I am working on as a paste: 
https://pastebin.com/vSY9tWWQ

I hope you can help me quickly, although surely I'm missing something important (and probably very basic) 

further edit: 
my file structure: 
![grafik](https://user-images.githubusercontent.com/15955790/43318016-7b2e8c68-919f-11e8-84a1-16068e394451.png)
so you see, the Unbenannt.xml (just an example file) is in the same place the pictures are, which cannot be displayed as they are "corrupt or not supported"

**Comment by hcayless** [comment]
You're missing a step. And it's a step that's possibly not as well-documented as it should be, because it crosses out of TEI's domain into the domain of XML validation. An ODD is meant to be converted to some flavor of XML schema before you can validate a TEI document against it. Your choices are XML Schema, Relax NG (the usual favorite), or DTD (don't use DTDs!).

You can use http://oxgarage.tei-c.org/ to convert your ODD to a schema. Choose "ODD Document" and then one of "Relax NG compact schema", "Relax NG schema", or "XSD schema", Select your ODD file, and hit "Convert". The resulting file is what you should put in your xml-model declaration.

The point of ODD is that it provides a single place to put both your project documentation and schema constraints, but it has to be converted to HTML or something readable to properly display the documentation, and to a schema to deal with validation. Hope this answers your question!

**Comment by kev1807** [comment]
aaah yes thanks! 
I probably read that and forgot about it as soon as I opened Oxygen.
However, the jpgs still cannot be opened in Author Mode nor are they exported when I transform the file to whatever file-format I wish ... 

I think it's weird, they can be opened in preview mode

![grafik](https://user-images.githubusercontent.com/15955790/43323752-cca3fd68-91b2-11e8-8fc3-7dcaf6beb860.png)

![grafik](https://user-images.githubusercontent.com/15955790/43323896-2b774fa2-91b3-11e8-9eff-022332f2ecca.png)
