### ISSUE TITLE
p5/repodate.xml gitignorable?

### ISSUE THREAD

**Issue by duncdrum** [TEIC/TEI#1802]
Apologies if this is mentioned somewhere in the docs, but if so i couldn't find it. I m using the teidev-docker image to run the jenkins tests. It seams that running `make clean` is creating a `repodate.xml`.

Since `local.mk` is on the gitignore i was just wondering if i shouldn't do the same with `repodate.xml`, or should this be submitted with a PR?

**Comment by duncdrum** [comment]
while i m at it there are another 13 files not cleaned up by the current make target, but overwritten on each new run (i hope):
-   6 `*.jar` files in `P5/Exemplars/oNVDL/bin`, 
-   6 more files of the same name in `P5/oNVDL/bin`, and 
-   `P5/exemplars/isofs.xsl` 

should they get cleaned up as well?

**Comment by duncdrum** [comment]
looking at the same file, gitignore seems to be the wtg.

**Comment by peterstadler** [comment]
we should have a proper lib folder (where needed software components are stored which are not kept in the repo itself) and a proper build folder (which can be nuked in toto). The current structure is a mess.

just saying …

**Comment by martindholmes** [comment]
I've recently been setting up my project builds so that all sorts of external jars (vnu.jar, epubcheck.jar, saxon) are only downloaded a) if they're not there, or b) if there's a more recent version released on github. I have working ant code for that, so if we'd like to make all the bulky jars only download themselves where needed, that would be a starting point.

**Comment by duncdrum** [comment]
sounds like a good start, that doesn't rhyme with raven
