### ISSUE TITLE
make listRef member of att.typed

### ISSUE THREAD

**Issue by laurentromary** [TEIC/TEI#1803]
I am using `<listRef>` to group together references from various articles in legal texts to other ones (typically, at the beginning of an article, there is a list of relevant references that one may consider as background or applications of the current one). These texts are of various types (reference convention, guidelines, case law etc.) and I would like to group the corresponding references accordingly. Since it seems standard for listXXX elements to be members of `att.typed`, could we extend this to `<listRef>`?

**Comment by jamescummings** [comment]
Hi laurent,

The two tests for whether something should get att.typed when someone requests it, if memory serves, are:
1) Is it repeatable? i.e. can you have more than one listRef in a row?
2) Is it sensible to classify them in some way?

I believe the answer to both of these is yes. In principle, I have no objection to adding att.typed to the list of classes of which listRef claims membership.

**However**, from your description of why you are asking, are you sure that listRef is the appropriate element? The definition of listRef is:

>  supplies a list of significant references to places where **this element** is discussed, in the current document or elsewhere.

It comes from the documentation elements module and is intended for use in ODD writing.
I'm not saying you shouldn't be doing this, but perhaps listRef is not the right thing to be doing it with?
I'd be tempted to say that you should be using listBibl (and then allow ptr and ref directly in listBibl). ;-)

**Comment by martindholmes** [comment]
I'm in favour of generalizing the use of listRef as suggested, but I think there will be implications for the Stylesheets, which are expecting to find it only in tagdocs contexts.

**Comment by jamescummings** [comment]
I'm not adverse to widening the definition. (But I'm also not that adverse to adding ptr/ref inside listBibl. But other tickets have shown I seem to have a minority view on how to use bibliographic things. ;-) 

I think widening the definition will certainly take more work. Is your feeling that it is the right element to use based on its name? If it was called listOfElementRefs would you think it as suitable?  Perhaps it was poorly named to begin with. But I guess this all hinges on whether there is a semantic difference between listRef being used for pointing to sections of the Guidelines where elements are discussed and pointing to items in a bibliography or previous cases etc. Note that the content model of listRef is not at all like the other list* elements as well. It only allows ptr and ref. I'm guessing another argument against using it for this would be something like "why not just use list/item/ref since its semantics are clearer?"

Just thinking through some of the issues.

**Comment by jamescummings** [comment]
Any updates on this issue? Is it still needed?

**Comment by laurentromary** [comment]
Apart from the fact that I did not completely grasp what you where trying to say on 28 Aug 2018, I do need this.... since listRef exists and it would be a tiny change to implement what I was asking for, maybe the best way would be to proceed with the implementation.

**Comment by jamescummings** [comment]
Hi @laurentromary,

It is that what you are trying to do doesn't seem to be what listRef is defined for. It was created specifically for ODD writing, and it is a much more major change to generalise that. For example:  would we have to move it out of the tagdocs module? To which module? We'd need to write new guidelines prose in that chapter?  I think you are entirely being mis-led by its name and gloss. listRef is not a list of general references but a list of references-to-element-discussions. To make it into the former I really think we'd need to deprecate and create something entirely new (or just make something entirely new and be clear about how it is different). 

Again, I've no problem adding att.typed to listRef in principle.

**Comment by laurentromary** [comment]
And @martindholmes seemed to be in phase as well. So let us add att.typed and take some time to think about whether it makes sense or not to adapt listRef to what I think it should be :-}

**Comment by martinascholger** [comment]
Council has no objection on att.typed for `listRef`, but agrees with @jamescummings that allowing `ref` as direct child of `listBibl` is preferable to abusing `listRef`.

**Comment by jakub-simek** [comment]
I had posted a question about the use of `<listRef>` on the TEI mailing list a few weeks ago. Now I've discovered this issue. Here is the link to my question in the mailing list:

https://listserv.brown.edu/cgi-bin/wa?A2=ind2110&L=TEI-L&P=R6280&X=O844CA838D75D476204

One point I tried to make is: The TEI specs make `<listRef>` member of "model.oddDecl" which is used by "model.inter" so that `<listRef>` can indeed appear as a child of many elements which have nothing to do with schema specifications. Or do I read it the wrong way?

But apart from this technical point, do you really think that the use of `<listRef>` should remain constrained to the ODD context and would you consider its use e.g. in prosopographical elements like `<person>` an abuse?

Sorry for posting this comment in a closed issue.

**Comment by sydb** [comment]
No worries. Thanks for reminder. Will try to respond in a few hours on the list.
