### ISSUE TITLE
Deprecations should include explanations of alternative encoding strategies

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1815]
In the East Asian/Japanese SIG this morning, a researcher who had been using `<oVar>` was dismayed to discover that it was removed from the TEI in 2013. The discussions around the reasons for the removal, and suggestions for what to do instead of using it, were not really accessible. Since we're working now on deprecations (issue #1657), should we formalize an approach to helping people migrate away from deprecated features, to be provided as part of the deprecation process?

**Comment by dariok** [comment]
It may be a good idea to have a special page, most likely as an appendix to the GL, that contains an abstract of the discussion why to deprecate and what to use instead. A Schematron rule should contain a link to this page so that it is immediately clear where to finde more information. For easy changes, providing a Schematron Quick Fix may be a useful service.
The link to the appendix of the GL might have a highlighted “last changed“ date so that it immediately draws attention to it. This might help notifying users who do not regularly update to the most recent version of follow the mailing list.

Those who don't upgrade, don't read the mailing list and don't visit the GL will still be left behind – but then they will be hard to reach anyway.

**Comment by martindholmes** [comment]
@sydb has already completed this bit.
