### ISSUE TITLE
migrate to travis.com

### ISSUE THREAD

**Issue by duncdrum** [TEIC/TEI#1826]
travis.org's interface with github has been deprecated as of 0ct. 01. Travis.com is where all the fun is nowadays, i.e. users can see more easily see the state of the CI when working on branches or opening PRs. 

https://docs.travis-ci.com/user/open-source-on-travis-ci-com/

**Comment by martindholmes** [comment]
Since accounts are required on travis.com, I'd like us to create some solid documentation on how the TEIC projects on GitHub are going to be managed on travis.com, who's responsible for managing settings etc., how much we should trust travis over our own Jenkins, and how much of our build requirements can actually be handled on travis.com. I'd be happy to relinquish the requirement to run a Jenkins server, but the idea of putting ourselves in a position where we're wholly dependent on travis.com is a little worrying. What's their business case for providing free builds for open-source projects?

**Comment by martindholmes** [comment]
Thanks Peter. I do see a lot of value in automatic tests of all branches.

**Comment by martindholmes** [comment]
PS did the migration today. We just need to watch to see that everything goes OK. Close the ticket if the builds and notifications run well.

**Comment by peterstadler** [comment]
everything ok. Migration done, notifications turned on, build tested
