### ISSUE TITLE
Clarifying the definition of <msFrag> in Guidelines

### ISSUE THREAD

**Issue by djbpitt** [TEIC/TEI#1832]
The definition given for `<msFrag>` at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-msFrag.html reads:

>`<msFrag>` (manuscript fragment) contains information about a fragment of a scattered manuscript now held as a single unit or bound into a larger manuscript. [10.11 Manuscript Fragments]

The scope of reference for “now held ...” is easy to misread. It refers to “fragment”, that is, the fragment is now held separately or bound into a convolute, but within my work team some taggers initially misread it as meaning that the scattered manuscript is now held as a single unit—which is the opposite of the intended meaning. Can we clarify the wording to discourage this type of misunderstanding? Perhaps we might try something like:

> `<msFrag>` (manuscript fragment) contains information about a portion (of any size) of what was once a single manuscript, where the pieces are now physically dispersed and catalogued separately, but they are being reunited as `<msFrag>` children of a single `<msDesc>` parent. [10.11 Manuscript Fragments]

I specify “of any size” because the term “fragment”, at least as typically used in the Slavistic philological tradition, refers to a small piece of a manuscript, and not to any and all of the pieces, and this terminological difference led to initial misunderstandings within my team, as well. If, for example, 2 folios have been removed from a manuscript of 100 folios and are now catalogued separately, the 2 folios would be called a fragment but the remaining 98 would not. And if only the 2 folios were known, and the 98 were not, Slavists would call the 2 folios a fragment. But if only the 98 were known, they would be called a manuscript (not fragment) that was missing 2 (or an unknown number of) folios. There is no firm quantitative understanding of how small a fragment has to be in order to be considered a fragment, but I think the difference is clear at the extremes. From a TEI perspective, on the other hand, each piece, regardless of size, is an `<msFrag>`. And if only one piece were known, regardless of the size, it would be an `<msDesc>`, and `<msFrag>` would probably not be used (although, for what it’s worth, I don’t see anything that prohibits an `<msDesc>` that contains only one `<msFrag>`).

**Comment by holfordm** [comment]
Additionally, if there is consensus on this in the community, it would be useful to offer clearer guidance at this point in the Guidelines about when `<msFrag>` should be used, and when `<msPart>`

**Comment by ebeshero** [comment]
@holfordm The distinction between `msPart` and `msFrag` is a little clearer in 10.10 of the Guidelines (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/MS.html#mspt)  than on its element Spec page. In 10.10 we have: 

> The msPart element may be used in cases where manuscripts or parts of manuscripts that were originally physically separate have been bound together and/or share the same call number.

That seems to be a good basis for distinction from Ch. 10's description of `<msFrag>`: 

> The msFrag element may be used inside msDesc when encoding one or more fragments of a scattered or fragmented manuscript. The fragment(s) described in a single msDesc element may be held either at several institutions or at a single institution, so different call numbers may be attached to the fragments. Inside the msFrag element, information about the single fragment or each dispersed part is provided: e.g. the current shelfmark or call number, the labels of the range of folios concerned if the fragment currently forms part of a larger manuscript, dimensions, extent, title, author, annotations, illuminations and so on.

It seems we're distinguishing the two based on whether they're cataloged and compiled together at the same institution or spread apart in different places and in different catalogs. I think the element spec pages might make this distinction a little clearer, though.

**Comment by ebeshero** [comment]
@holfordm Is there something more you'd like to see revised in the Guidelines Ch. 10 on this? Or am I right in thinking we really need some more precise description on the element spec pages: 
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-msFrag.html

and 
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-msPart.html
?

**Comment by PietroLiuzzo** [comment]
I think this is related also to  #1747 and I agree that the use could be clarified. 
However I think here the issue is much deeper then just in the element names and guidance on how to use them. The vague concept of Fragment in manuscripts cataloguing simply fails to be helpful in all vague contexts where it can be used, whereas we have much more precise definitions of Units of Production and Units of Circulation (see _La Syntaxe du Codex_ ) which allow to properly describe each of the many and different ways a 'Fragment' can be, distinguishing each Unit in relation to the events (transformations) which can be observed and identified also in a TEI description. However, `msFrag` and `msPart` have in my opinion all the potential needed to make a good description, without further elements, and it is instead only a problem (see issue linked above) that they cannot be alternative in `msDesc` so that I have to use msFrag for the 98 as well as the 2 in a reconstructed description.
In the proposed new definition I would personally feel that 
- 'of any size' might lead to include more than it should and lead to identify e.g. two Units of Circulation, which once were a single one as 'Fragment' of the first only. this size argument is easily broken by thinking of cases in which a manuscript is divided in parts of similar size.
- the choice of portion instead of fragment, which in both cases assumes some physical support is moved, is probably ok, but we are still on the vague, so why add a further vague term? 
- Also the ability to say that a fragment was a part of a single manuscript is not that obvious or generalisable and would restrict the use of `msFrag` unnecessarily IMHO.  In the current definition the reference is to the repository where a fragment is held, and this I think is fine, because that is the only thing which makes the distinction, if it was not somewhere _else_ 'held as a single unit or bound in a larger manuscript' it would not be a fragment. 
- Also I would not think that restricting the use to catalogued fragments would help, especially in those context where this is not the case, i.e. those fragments are not catalogued at all, we simply know that there is a fragment somewhere. 
- I disagree unfortunately also with the last part of the new proposition, which I believe belongs to the guidelines perhaps, but not to the element definition. 
This said my vote is for the current definition, and I think a more exact usage should be defined within each project with examples taken from that manuscript  tradition and the chosen cataloguing methodology.

**Comment by djbpitt** [comment]
@PietroLiuzzo OP here. Thank you, Pietro, for the helpful pointer to the terminology explored in greater detail in _La Syntaxe du Codex_. Your response alerts us to the opportunity to distinguish how the Guidelines explain the intended semantics of `<msPart>` and `<msFrag>` as TEI elements, on the one hand, and how manuscript scholars should understand the concept of “fragment” or “part”, on the other. My original posting was primarily about the former, and, as you’ve explained, waded into the latter without sufficient nuance.

With that said, as I wrote originally, the wording of the current definition of `<msFrag>` _is_ open to misunderstanding, and retaining the current definition means leaving it open to misunderstanding. I would, therefore, respectfully repeat my suggestion that we can remove an opportunity for misunderstanding by making the scope of reference of “now held” in the Guidelines clearer. Whether we should also attempt to define what constitutes a fragment is, I now recognize, a more complex issue, and one that, I would agree, might more properly be addressed in the context of a project or tradition, rather than as part of the Guidelines.

**Comment by ebeshero** [comment]
@PietroLiuzzo @djbpitt Pietro, you are reminding me of something that seems wrong of off in our Guidelines explanations of “part” and “fragment”. The Guidelines make an unspoken assumption that at the time of encoding, all parts of a composite are either bound together or cataloged by an institution that assigns them a location identifier, or known to be dispersed, with all fragments assigned multiple identifiers by different holding institutions. The Guidelines presumes an ideal of holistic unified knowledge on this point that seems even in my limited experience of “holding institutions” very rarely the case in Real Life. How quickly does the Guidelines explanation of “part” become problematic as soon as a piece we didn’t know about at the time of coding turns up elsewhere?

**Comment by PietroLiuzzo** [comment]
perhaps one could remove _of a scattered manuscript_ from the msFrag definition and make it clearer by making it shorter instead of longer?

> How quickly does the Guidelines explanation of “part” become problematic

As far as I know both eCodices and our project use msPart to refer to a Unit of Production. This is distinguished on the basis of observation. It is never obvious what a Unit of Production is, the observation should identify converging discontinuities which allow to identify a Unit of Production which has a unique production intent. But I believe this belongs with codicological methodology, not with TEI once one is clear on what it is encoding and the msPart definition is fine on that. Also, the methodology of _La Syntaxe du Codex_ is not the only methodology used out there (IMHO, unfortunately) and I do believe that for the purposes of the TEI it would be detrimental to pick one or the other. Thus the Guidelines have a hard time here trying not to refer to any methodology and still providing guidance to encode. Where the guidelines say 

> Since each component of such a composite manuscript will in all likelihood have its own content, physical description, history, and so on, 

perhaps this is unnecessary, what matters really is what follows immediately, that msPart can have the same content of `msDesc`. I would also say that this is not something for the end of the chapter but for the beginning of it. The Fragment definition is also variable depending on the point of view or beginning of the description, as in the example I have provided for #1747, a common case of material from one manuscript used to increase another manuscript (_La Syntaxe du Codex_ MA1 transformation): what is a `msPart` of BNF165, is a `msFrag` of BNF45. Those folios in BNF165 

> contains information about an originally distinct manuscript or part of a manuscript, which is now part of a composite manuscript. 

but at the same time when looking from BNF45, the definition of msFrag is fine, because those folios are a fragment of a scattered manuscript now bound in a larger manuscript.

I do not think however that this is a decision for the Guidelines to guide, but for the codicologist. The Guidelines giving us both `msFrag` and `msPart` (and possibly as alternatives in msDesc) already provide IMHO all what one needs for an interchangeable encoding of a manuscript description, reconstructed or not, and what ends up in those elements according to their definitions depends really on what the codicologists will decide to put in there according to their methodology.

**Comment by holfordm** [comment]
Possible wording:
`msFrag` element spec: "msFrag contains information about a codicological unit described in relation to its _original_ codicological context, typically as part of a virtual reconstruction of a manuscript of which fragments are now held in several different repositories"
`msPart` element spec: "msPart contains information about a codicological unit described in relation to its _current_ codicological context, as part of a description of a manuscript currently held by a repository"

**Comment by hcayless** [comment]
I will timidly raise my hand to point out that msFrag is used by people like papyrologists, who don't *have* codices, but do have fragments that they want to describe (and that may have distinct curation histories, inventory numbers, etc.). MsDesc was created for codex-like things, but other people with other types of document use it, and in fact msFrag originated in part because there were objections to the use of msPart to describe document fragments that are being virtually reassembled for publication.

**Comment by PietroLiuzzo** [comment]
I like the proposal of @holfordm ! but I think it might also be too close to the type of example I provided above. using codicological units with the meaning that Gumbert in 2004 proposed for this concept (if that is what is intended) eventually really cuts out the papyrologist and possibly also those whose manuscripts are autographs because Gumbert's definition of Codicological unit is very much for the codex, based on quires (which in turn have a very specific definition) etc. also the distinctive emphasis on current or original might turn out to be misleading as soon as the history of the manuscript has more than two known stages and the number of possible originals grows. 

I thus still think that the current definition by not referring to any technical methodological terminology specific to a field of research serves more people better than a more precise one and is also for this reason better in TEI, if we agree that it does not mean any of the things we further specify in each project, but a more generic useful and practical concept.

**Comment by martinascholger** [comment]
Council decides at F2F to rephrase msFrag:

> msFrag contains information about a fragment described in relation to a prior context, typically as a description of a virtual reconstruction of a manuscript or other object of which fragments are now catalogued separately

**Comment by scstanley7** [comment]
Council recommends rephrasing `<msFrag>` desc as:

> `<msFrag>` contains information about a fragment described in relation to a prior context, typically as a description of a virtual reconstruction of a manuscript or other object of which fragments are now catalogued separately
