### ISSUE TITLE
allow <g> in <zone>/<line>

### ISSUE THREAD

**Issue by GVogeler** [TEIC/TEI#1838]
In a TEI-L discussion in 2014 there was agreement that the a glyph `<g>` can be part of a sourceDoc-transcription and @lb42 even volunteered to add this to the model ( http://tei-l.970651.n3.nabble.com/zone-g-tp4025940p4025942.html ). I cannot see that this has happend yet (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-g.html). Maybe it has just slipped attention?

**Comment by lb42** [comment]
I didn't do it because I was waiting for you to submit it as a bug report! But now you have.

**Comment by lb42** [comment]
I think the right way to fix this would be to change the content model of zone and line so that they refer to macro.xtext rather than to text i.e. change `<textnode>` to `<macroRef key="macro.xtext"/>`.  Other ways are not hard to identify. Possibly there are other places currently using `<textNode>` which would benefit from the same change.

**Comment by sydb** [comment]
Yes, `<textNode>` should probably be `<macroRef key="macro.xtext"/>`.

**Comment by martinascholger** [comment]
I just want to mention that `<g>` is already allowed in `<line>`, with `<classRef key="model.gLike">`. This has to be considered when changing `<textNode/>` to `<macroRef key="macro.xtext" />`.

See current content model of `<line>`: 
 
```
<content>
 <alternate minOccurs="0"
  maxOccurs="unbounded">
  <textNode/>
  <classRef key="model.global"/>
  <classRef key="model.gLike"/>
  <classRef key="model.linePart"/>
 </alternate>
</content>
```
