### ISSUE TITLE
Add more discussion of editorial practice to TC chapter

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1849]
#1801 highlights the need for some nuanced discussion of how editorial theory and practice applies to TEI encoding of text critical information. For example, does the editor mean to provide a positive (all witnesses recorded) or negative (only variant witnesses recorded) apparatus? Are all variants recorded, or only those the editor thinks significant? I'd like to write some introductory prose that discusses these questions and how to deal with them.

**Comment by raffazizzi** [comment]
F2F subgroup thinks something like this would be very useful, however we would suggest to make sure that the different approaches are provided solely as examples (rather than as a limited set of options) so that the elements described in the TC chapter can remain a tool for encoding one's own theory of the text.

We suggest to green light it and then review Hugh's prose.

**Comment by martinascholger** [comment]
@hcayless can we close this?

**Comment by hcayless** [comment]
Yes
