### ISSUE TITLE
Define semantics of witDetail without @target

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1852]
The `@target` attribute on `<witDetail>` (just like with `<note>`) indicates the `<lem>` or `<rdg>` that the `<witDetail>` applies to. Apparatus encoding could be simplified if we adopted the convention that `<witDetail>` without `@target` applies to the first preceding `<lem>` or `<rdg>` sibling. `@target` Is already optional, so this would amount practically to adding some prose explaining the convention. Cf. 
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.scoping.html, where an element without `@target` and `@match` is assumed to apply to its parent.

**Comment by sydb** [comment]
1. At first blush seems reasonable, although:
  * It is a bit odd to have the default for `<witDetail>` be different than the default for att.scoping elements, and perhaps from `<note>`.
  * You would also have to change the 2nd para of the `<remarks>` for `<witDetail>` — but it looks like you have entirely removed it (well, commented it out) already.
  * As a member of att.pointing, `<witDetail>` has a `@targetLang` attribute which specifies the natural language of the content of that which is pointed to be `@target`. So some tweaks might have to be made to the semantics of `@targetLang`, too.
  * We don’t have to worry about `@evaluate`, I don’t think, because the element pointed at by default cannot be a pointing element itself. (Which is odd — you can put a `<link>`, `<alt>`, or `<join>` almost anywhere else, why not in an `<app>`?)

2. Nit-pick: you mean “… an element with neither `@target` nor `@match` is assumed …”, as a `<certainty>` with one of `@target` or `@match` is not assumed to apply to its parent.

**Comment by hcayless** [comment]
It’s any member of att.scoping, surely? I don’t think that’s unclear in what I said. 

Since `<witDetail>` is not a member of att.scoping, I don’t see why att.scoping’s defaults are relevant. It’s more like the convention that a `<note>` without a `@target` applies to the content immediately preceding it. `@targetLang` is only valid when there’s a `@target`, so I’m not sure it’s a problem.

**Comment by sydb** [comment]
Ummm … you’ve lost me. What’s att.scoping got to do with it?

`<witDetail>` is a member of att.pointing, and thus has `@target`, `@targetLang`, and `@evaluate` (all of which are optional, but you are right, `@targetLang` can only be used if `@target` is present; strangely, we do not have such a restriction on `@evaluate`). So I’m wondering if `@target` gets default semantics on `<witDetail>`, do we have to loosen the constraint that limits `@targetLang` to only cases where `@target` is present,[1] or do we say “If you want to specify the target language with `@targetLang`, then you actually have to provide the `@target` of the `<witDetail>`, even if points to the immediately preceding sibling `<lem>` or `<rdg>`.”?

[1] I.e., change the Schematron context to `tei:*[not( self::tei:elementSpec | self::tei:witDetail )][@targetLang]`. (Too bad you can’t use `tei:* except ( tei:elementSpec | tei:witDetail )[@targetLang]`)-:

**Comment by hcayless** [comment]
I was responding to your nitpick re the behavior of `@target` and `@match`, which I didn’t understand on first read.

I don’t see how either `@targetLang` or `@evaluate` make sense in the absence of `@target`. But I don’t think `@targetLang` would make sense on `<witDetail>` anyway, as the thing `<witDetail>` annotates is an attribute value in `@wit` on the referenced reading, which is itself a fragment identifier and so has no language. Anyway, that’s all horrible, but the upshot is that I don’t think we’d ever need to worry about anyone using `@targetLang` in this context at all. It would be weird.

I would be open to the notion that `@target` on `<witDetail>` is not the `@target` in att.pointing at all, but a locally defined attribute.

**Comment by hcayless** [comment]
Want to tag in @sjhuskey to see what you think of this, as a user of `<witDetail>`.

**Comment by sjhuskey** [comment]
I think that I am following the issues here. I like the idea that `<witDetail>` without `@target` applies to the first preceding `<lem>` or `<rdg>` sibling. That makes good sense to me and would simplify some things, at least for the DLL project.

**Comment by martindholmes** [comment]
Council subgroup thinks this looks like a project-level convention rather than something the Guidelines should recommend.

**Comment by hcayless** [comment]
I appear to have completed this and neglected to close it.
