### ISSUE TITLE
isocat.org links should be updated

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1866]
The specs for `att.datcat` and `<gram>` contain links to the repository that used to be at isocat.org, but that is now obsolete. It may be sufficient to replace most of them with links to http://www.datcatinfo.net, but some of them are supposed to be links to ISO 12620, which might be better directed to https://www.iso.org/standard/37243.html.

**Comment by martinascholger** [comment]
I think no discussion is needed, so I'm marking this green

**Comment by martinascholger** [comment]
@martindholmes I found some more references in various examples: http://www.isocat.org/datcat/DC-1345, http://www.isocat.org/datcat/DC-1230, http://www.isocat.org/datcat/DC-1256, and the namespace http://www.isocat.org/ns/dcr. Do you have any advice what I should do with these references?

**Comment by martindholmes** [comment]
@martinascholger The only thing I can suggest would be:

1. Search archive.org for a page for the concept -- so DC-1345 goes here:
https://web.archive.org/web/20160304120102/http://www.isocat.org/rest/dc/1345
2. Search datcatinfo (https://datcatinfo.termweb.se/termweb/app) for the same term. The page you find won't have a useful URL, but it does provide a PID that looks like a URL: http://datcatinfo.termweb.se/datcat/DC-1345. It doesn't work as URL, though.

This is the eternal problem with linked open data.

**Comment by martinascholger** [comment]
Thanks, I'll do! And yes, what I found was and URL that we cannot use for the example: https://datcatinfo.termweb.se/termweb/app;jsessionid=C8459D2C714F00504EEB02AB1808D608?service=direct/1/SearchView/termList.link&sp=Sl2qs6

**Comment by bansp** [comment]
How about this for 'part of speech': http://hdl.handle.net/11459/CCR_C-5524_d8864ad4-1bdf-ee56-594e-784312129ea7
This comes from the CLARIN Concept Registry, which filled in for ISOCat.

**Comment by martindholmes** [comment]
That works, but the question is how long the CLARIN Concept Registry will last; it may run out of funding and disappear just like the ISOCat registry did. :-(

**Comment by martinascholger** [comment]
As a central hostet Clarin Service, I think it is a reliable ressource. But would that mean that we should consider to change not only the links in the examples?

**Comment by martindholmes** [comment]
Are there other isocat links not in the examples?

**Comment by martinascholger** [comment]
http://www.isocat.org/ (-> http://www.datcatinfo.net) and http://www.isocat.org/12620/ (https://www.iso.org/standard/37243.html) is linked in the chapters DI and FS and in the specs `att.datcat` and `<gram>`

**Comment by bansp** [comment]
> That works, but the question is how long the CLARIN Concept Registry will last; it may run out of funding and disappear just like the ISOCat registry did. :-(

That is true (modulo what Martina rightly observes), but, since the ISOCat URLs were (meant to be, haha) permanent, they act as URIs, so the fact that the links are dead (well, zombified in the Wayback Machine) does not remove their uniquely identifying function, it merely removes the convenience of being able to retrieve the end point when following them. Brutally speaking, as long as &lt;pos>, &lt;gram type="pos"> or  &lt;gram type="Kat"> use `dcr:datcat=http://www.isocat.org/datcat/DC-1345`, they model the same container category.

Casuistry aside, a project may use these mechanisms to point at any shared taxonomy/ontology, so any concrete links used in the documentation should be taken primarily as illustration of a special case, BUT it's also very true that dead resources should not be used as they are in the current https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-gram.html
```
classifies the grammatical information given according to some convenient typology—in the case 
of terminological information, preferably the dictionary of data element types specified in ISO 12620.
```
and
```
A  much fuller list of values for the type attribute may be generated from the data category 
registry accessible from http://www.isocat.org and maintained by ISO technical committee 37.
```
... because both the advice and the ISO TC reference are outdated.

Instead, it might be a good idea to point to 
https://dariah-eric.github.io/lexicalresources/pages/TEILex0/TEILex0.html#typology-of-gram
for a semi-closed list of suggested values for `@type` on &lt;gram>.

**Comment by martinascholger** [comment]
Adressed in PR https://github.com/TEIC/TEI/pull/2359. As soon as we have merged the PR, the issue can be closed.

**Comment by martinascholger** [comment]
Implemented with pull request https://github.com/TEIC/TEI/pull/2359
