### ISSUE TITLE
listWit should also allow msDesc and object

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1868]
In addition to `<witness>` I am suggesting that the `<listWit>` element also allow `<msDesc>` and `<object>` elements. This would enable those working with a variety of witnesses for which there are manuscript descriptions for some and only `<witness>` like identifying strings for others to store them in the same place. (And it is conceivable that the witness could indeed be an `<object>`, one supposes.)  

This would be a straightforward change to the `<listWit>` content model but the relevant section in chapter 12 (crit app) that discusses listWit would need to be updated.

**Comment by tuurma** [comment]
Quick summary for the listWit and its extant and proposed children:

`<listWit>` lists definitions for all the witnesses referred to by a critical apparatus, optionally grouped hierarchically. May contain `witness` (or nested `listWit` and `head`)

`<witness>`  contains either a description of a single witness referred to within the critical apparatus, or a list of witnesses which is to be referred to by a single sigil

Proposal suggests adding `msDesc` and `object` directly to the content model, which implies they are equivalent on some level. I would like to point out that both `msDesc` and `object` are valid children for `witness` thus I wonder if there is anything wrong with wrapping them into `witness` for use in `listWit`.

`<msDesc>` (manuscript description) contains a description of a single identifiable manuscript or other text-bearing object

`<object>` contains a description of a single identifiable physical object

**Comment by larkvi** [comment]
Since <witness> used with msdescription is largely just a container for nodes in a stemma, would the intent be to get rid of witnesss altogether, such that listWit/witness/bibl, listWit/witness/msDesc, and listWit/witness/object would be reduced to listWit/bibl, listWit/msDesc, and listWit/object respectively?

If not, what is the benefit? If yes, what do we do with witnesses that are not easily categorizable as one of those three? ("supposed witness based upon the stemma of Dr Smith, who proposed a shared ur-text for A and B")

**Comment by scstanley7** [comment]
Council discussed this at F2F, and we decided that everything should be nested within `<witness>`, rather than as a direct child of `<listWit>`. Currently, `<bibl>` and `<msDesc>` are allowed there, but `<object>` is not, so we just need to add `<object>` to be allowed directly within `<witness>`
