### ISSUE TITLE
why cant i define a PM in terms of model classes rather than individual elements?

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1889]
The element &lt;model> defining a bit of PM (and likewise &lt;modelGrp> &lt;modelSequence>) is permitted only as child of &lt;elementSpec>. I am sure there was a good reason for this, but I can't remember what it is. Why can I not define a processing model for a whole class of elements at once?

**Comment by sydb** [comment]
I don’t know. But my guess would be because at the time no one knew (and still no one knows) how to process a whole class at once. Or at least, thought it better to get processing working one element at a time first before trying to handle a disparate set of elements.

**Comment by jamescummings** [comment]
My recollection was that SPQR thought it'd be too difficult to implement in time we had for simple print project. That said,  it does seem natural that members of some classes should all be processed the same.

**Comment by tuurma** [comment]
I think that PM even at the very beginning was considered as a concept not limited to the TEI vocabulary. Keeping processing of the model specifications independent of the conceptual constructs behind the vocabulary (like TEIs element classes) makes it just more general.

From practical perspective I can say that the need to specify processing model for a whole class to make things more concise or avoid redundancy didn't surface yet in multiple project I worked on. There are other areas where it did, happy to elaborate in another issue.

Summarizing: before allowing `<model>`s specification for whole classes of elements I'd like to see a concrete use case.

**Comment by lb42** [comment]
But @tuurma  the model spec cannot be "independent of the conceptual constructs" of ODD as long as it's required to have an &lt;elementSpec> parent. Allowing it to be dependent on an element class is surely a step towards making "more general"? 
As a concrete use case: I might want to set up some fairly specific processing models for all members of att.canonical (to do the @ref or @key stuff for example)

**Comment by tuurma** [comment]
What I meant is currently you don't need to be aware of the schema when applying processing model rules. TEI PM is perfectly applicable (and already applied) to XML vocabularies that do not share TEI's 'conceptual constructs' of modules, attribute classes etc. Allowing for models to be associated with these would require processing engine to be aware of that. Besides, some rules would have to be established for deciding which model would be matched when there are candidates coming from different places. I see quite some pain handling this and not much gain since it's extremely unlikely you would really treat identically all elements that share certain attribute (kindly reminding that models are not additive, just one is matched for an element instance so you cannot specify via attribute class how to handle @ref or @key but differentiate say output rendition on the basis of something else).

**Comment by lb42** [comment]
I had forgotten/failed to realise that only one model spec is ever chosen for a given element occurence: this  seems rather a serious shortcoming in the design. Would it help with my suggestion if I said that a processor could just consider a model attached to a class as a kind of macro, which would need to be expanded to provide identical models for all members of the class?

**Comment by tuurma** [comment]
It would be possible though your proposal would need clear specification of merging rules (is the model from a class to be added on top or as last available model for an element, what happens if an element is a member of more than one class and both specify default models).

I still object to adding this into spec on two grounds:
* tying PM to TEI concept of classes, thus requiring special treatment of TEI vocabulary
* I still see it as purely hypothetical use case ("extremely unlikely you would really treat identically all elements that share certain attribute" as already said above), bringing quite a complication for no practical gain

> I had forgotten/failed to realise that only one model spec is ever chosen for a given element occurence: this seems rather a serious shortcoming in the design.

I think you might have forgotten or failed to realise what `modelSequence` is meant for.

**Comment by lb42** [comment]
Thanks for the reminder, but I think a modelSequence is different from the problem of deciding how to handle multiple models for the same element. Maybe my brain has been rotted by too much exposure to things like CSS or ODD which thrive on their ability to merge partial specifications. 

I think your objections are a bit unfair: if you're using TEI it's natural to think of using classes as a means of simplifying the complexity of a specification. Nothing to imply that you *must* do so! as to how useful it might be, well, the world is not exactly awash with users of the PM in its current form either... But  feel free to close this ticket, if no-one wants to consider the issue further.

**Comment by tuurma** [comment]
As I see it, choosing a single model for element instance is in essence the same as matching a single template by XSLT. Exact rules for choosing a model differ from XSLT template matching but basic design - select one match - is the same.

> world is not exactly awash with users of the PM in its current form either...

Not awash maybe, but I know at least couple dozens of projects that use it by now and many have nothing to do with me or my work colleagues. Thus I do get to hear various complaints and requests and just saying that the need to treat TEIs model or attribute classes in bulk has not surfaced so far and I have doubts it will. Looking at many TEI classes, they put into single bag quite different beasts, eg. lists and list entries (like person & listPerson) so not too likely these would really be treated the same. If you add to it the fact that concrete projects usually use smallish subsets of TEI elements and there are some defaults in place (like unadorned inline behaviour for all elements unless specified otherwise), the gains in reducing complexity seem very small to me.

On the grounds me being not entirely objective, how about I will raise this ticket during next Council call or f2f and ask for other opinions.

**Comment by jamescummings** [comment]
Council Face to face in Graz decides to close this having been convinced that the amount of effort and complexity this would introduce would not give enough benefit. (Partly because of our own vague use of classes in TEI, but also issues of precedence when belonging to multiple model classes, local modifications to classes, and other cans of worms that would need to be solved before a clear specification for this would make sense.)
