### ISSUE TITLE
repositories and manuscripts in multiple locations

### ISSUE THREAD

**Issue by holfordm** [TEIC/TEI#1906]
The current content model of msIdentifier makes it difficult to encode (1) repositories in multiple settlements (e.g., the Schøyen  collection in Oslo and London; the university library of Friedrich–Alexander University Erlangen–Nürnberg) (2) manuscripts dispersed between more than one repository (e.g the 'Codex Mediceus' of Virgil which has the 'shelfmark' Florence, Laur. 39.1 + Vatican lat. 3225, f.76)

The changes suggested in #1836 may make some of this easier, but it is possible that the guidelines and or content model should also be revised. For (1) it might be necessary to for example to allow the `placeName` element to repeat and to recommend that the `country`, `region`, `settlement` etc. elements should be enclosed in a `placeName` element
`<placeName><country>Norway</country><settlement>Oslo</settlement></placeName>
<placeName><country>United Kingdom</country><settlement>London</settlement></placeName>
<repository>Schøyen  collection</repository>`
For (2) it might be necessary to allow the `msIdentifier` element to repeat.

**Comment by jamescummings** [comment]
Hi Matthew,

So that I can understand this more clearly is it the case that a manuscript might be listed as being in multiple repositories simultaneously? I've always assumed that we considered these separate manuscripts. So I've some (honest) questions which prod at this need a bit for doing due diligence to try to tease out precisely what might be needed.

So let me ask about your:

1. Repositories in multiple settlements. Is it the case that a manuscript might be in a particular repository but that repository has, erm, 'branches' (like some libraries do) in multiple locations. So that while the repository is X, this X really consists of A, B, C physical places. And while we would usually recommend cataloguing the precise place, in this case it might not be known, in which case the repository location is sort of a Schrödinger's Repository, where it is not known that this particular MS is in place A, B, or C until we visit them?  I'm less convinced by a collection that spans multiple locations like Oslo and London, because surely the msDesc would record the known usual repository location for this manuscript? Remember, we're not describing the many locations of the collection/repository, only the location of this specific physical object, which has to be in one of the locations. This 

2, Manuscripts dispersed between more than one repository. Aren't these usually catalogued separately?     Where wanting to create a virtual reconstruction manuscript description, that is precisely what msFrag is intended for (clarified even more, we hope by its updated description). One would have an msDesc with an msIdentifier for the virtual reconstruction msDesc (i.e. naming it) and an msFrag for each the physical parts of it. Where there is just a shelfmark that lists multiple shelfmarks (but there is only one physical copy) then that sounds like an altIdentifier. Or is it that you want the msDesc/msIdentifier to reflect each of the msDesc/msFrag/msIdentifier's?

Hope those questions make sense?

**Comment by holfordm** [comment]
I am all for due diligence!

To take 2. first - yes, it may well be that I am just misunderstanding the content model of msIdentifier here, and what elements it does / doesn't require, and that some of the guidance in msFrag could be amplified. 
The element definition https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-msIdentifier.html has a schematron rule stating that an msIdentifier must contain a repository or a location, but are there in fact occasions when this is not true? (e.g. when msFrag is used?)
Also, what would one do when when the 'reconstruction ms' doesn't have a name, or other recognized identifier?  Recommend that the cataloguer assigns one?

**Comment by jamescummings** [comment]
Hi @holfordm 

If you are arguing that the content model of `<msIdentifier>` needs to be loosened then I'm all with you there. You'll see that when I created `<objectIdentifier>` I removed all those pesky constraints of order and schematron rules (except requiring it has _one_ child element). The point about an msDesc with several msFrags which doesn't have a repository or single location is a good case I think. But yes, if creating such a hypothetical reconstructed msDesc then it would make sense to me that the cataloguer proposing that the fragments belonged together in such a way would provide the name or identifier if it didn't already have one.

**Comment by jamescummings** [comment]
Council Face to Face meeting in Graz 2019 decides to close this issue, feeling there are mechanisms to deal with the original use cases. It is possible that msIdentifier and associated schematron rules might need to be loosened, but this should be subject of a different issue.  (c.f. objectIdentifier not imposing order or requirement for a repository, just any child element.)
