### ISSUE TITLE
What is a paragraph, really?

### ISSUE THREAD

**Issue by dariok** [TEIC/TEI#1929]
Discussing between ourselves #1856 – more precisely, we wanted to see what the “semantic baggage” of `p` actually is –, @ebeshero and I stumbled across the prose definition of “paragraph” in the GL because we wanted to see what the actual difference between `ab` and `p` really is (being the radical *advocatus diaboli* I usually am in these discussions, I proposed we should get rid of `ab`).

The definition of `p` starts:
> The paragraph is the fundamental organizational unit for all prose texts, being the smallest regular unit into which prose can be divided.

While you could argue that this smallest unit may actually be the sentence, this definition already poses problems. Either
- headings, lists, etc. are not prose, or
- they are actually paragraphs (so we ditch `head` for `p type="heading"`...), or
- they are to be considered sth. that is below the chunk level and hence should be a child of a paragraph (which then makes `p` the only possible child of `div` – or rather `p` is the smallest `div` and the only difference is that i may contain text).

We felt rather uneasy about that.

So the problem is: How to spot and delimit a paragraph? Where does it start and end?
The GL state that
> Since paragraphs are usually explicitly marked in Western texts, typically by indentation, the application of the p tag usually presents few problems.

Well...
We admit that for non-Western texts this will be a problem. Actually, pre-modern Western texts have the same set of problems, be that in classical or medieval manuscripts or 16th century prints. Often, a lot of the text is one blob spanning many different pages and the idea of a subdivision is merely hinted at by, e.g., a ⸿ – but then again what is delimited by these would as often as not rather be a sub-chunk level division.
But even in modern texts the idea of delimiting paragraphs by purely typographical features such as indentation will break down: consider a novel with a lot of (unprefixed) direct speech. Is every utterance a paragraph in its own right? It is, after all, typographically distinct...

---

Far from being perfect, we could describe a paragraph as

- a collection of one ore more phrase-like bits of text (e.g., general purpose “sentences” (whatever that might be) or more specific descriptions),
- that may be considered as sharing a common (more or less complex) statement,
- that can (but need not) be typographically separated from each other (esp., they may actually comprise e.g. `q`s that all start on their own line),
- is a building block for larger, abstract dissections of a larger text (thus being one possible content for `div`, which, while possibly being explicitly marked by several levels of numbering in a heading, itself is basically an abstract segmentation of a larger whole)
- and does not have any grouping function other than that of combining phrase-like content (thus, in a way defining it as a combination of text that is non-heading, non-list, non-table)

With this, saying what a paragraph really is remains up to the editor but giving ideas on where to draw the line (and leaving enough lee way for typography and just content) and should hopefully be open enough for other languages.

As regards the distinction of `p` and `ab`, an `ab` would not be governed by the *common statement* rule, thus giving more options to group content together e.g. on purely typographical grounds. Given my thoughts above, I'd argue that if you have headings conveying ideas and text grouped below them, these are `p`, while headings e.g. simply stating a date (as, e.g., in a diary) may be followed by `ab`s as the grouping may be quite random.

This is, of course, far from perfect and leaves many angles of attack itself but it will hopefully serve as a basis for discussion.

**Comment by martindholmes** [comment]
I think you end up choosing between two equally questionable positions:

1. Relying on some kind of intuition, you say that you know a paragraph when you see one, and that's all there is to it.

2. A paragraph is a thing which has one or more pieces of text in it, which is typographically segregated from sibling components, and which is not any of the other things which are similarly distinct but more clearly describable (list items, headings, blockquotes, etc.).

**Comment by jamescummings** [comment]
There is centuries of textual theory concerning the nature of paragraphs that we should not just ignore. More recently theory about paragraphs is more related to contents for composition with a skewing to American undergraduate teaching. I wouldn't get bogged down by the latter but distinctions like prescriptive, descriptive and cognitive as discussed here https://www.jstor.org/stable/25472231 might be a useful way to break us out of our very datacentric view on it. I can look up some real textual theory on paragraphs if people want. But their non-nestability is not the semantics which are removed when it is made 'anonymous' IMHO.

**Comment by lb42** [comment]
I like Martin's proposal #1 best.

**Comment by PFSchaffner** [comment]
I sense a deep well of despair opening up under our feet. Because the truth is that many if not most of the basic units elude definition. Try defining 'list' , 'table' , or even 'verse line' and 'line group' .  These things jostle amongst themselves in a common space, defined (in the space of one book or one kind of book) more or less as convenient and by means of contrast with the others. Isn't there a famous description of relative dates in pre-history? something about not being securely fixed at any one spot, but like a pair of drunks wandering arm-in-arm down the street, holding each other up and each located only by reference to his companion. I have certainly called identical things 'paragraphs' and (alternately) list 'items' when the context made that sensible and convenient.  I'm not sure there's any real difference between Martin's (1) and (2); (2) just attempts to supply some rationale for the intuitions of (1).  A paragraph is a unit of prose, pretty much full stop.

**Comment by duncdrum** [comment]
@jamescummings i d rather we stick with a datacentric view given the context of this discussion, but ditch the anglocentric part. 

for a  start take something like [Bamboo Manuscript](https://www.academia.edu/7518436/Strategies_of_Meaning_Construction_in_Early_Chinese_Philosophical_Discourse).

Note the interpunction and indentation in this article is done by the Author, in the manuscript we have a continuous stream of characters, no punctuation, whitespaces, indentation, sentence or word boundaries, etc. 

If someone wanted to present a teI edition of said manuscript that both captures the physical structures (start and end of fragments, slip sequence, hands and so on) as well as the content structures based on parallelism and rhyme schemes that the author describes. Then we miss the point by demanding `p` s. There are no paragraphs, there are however nested structures. I don't see how  abandoning *the semantic baggage of, a paragraph* is actually happening if we keep insisting on deep parallels between `ab` and `p` based on english language examples from the last 200 years give or take. 

It seems entirely reasonable and in line with the GL to want to use `seg` to delimit material units (slips, and segments), `div` for larger structures (like chapter analoges) and (nested) `ab` *to mark any component-level elements in a text for which no other more specific appropriate markup is defined*

Needless to say the best way to read this kind of text, if a character belongs to the previous sentence as object, or as subject of the next; If a sentence group begins a topical start of a larger group, or is a conclusion to the previous groups is the content of scholarly debate among Chinese linguists since forever.

**Comment by martindholmes** [comment]
As the JSTOR article points out, a lot of the confusion arises out of the conflict between the prescriptive needs of instructors and the realities revealed by empirical investigation. People teaching writing want a paragraph to be a particular kind of thing with particular structural and rhetorical features, but real texts routinely violate all the prescriptions. I think ultimately I agree with Paul that #1 and #2 are scarcely distinct, and perhaps `<p>` is actually just the generic prose block, with things like `<head>` being syntactic sugar for `<p type="heading">`. In which case `<p>` is just `<ab>` really. The "semantic baggage" is largely the piffle loaded onto it by a misguided pedagogues or pedants. 

This is a paragraph.

This too.

?

**Comment by lb42** [comment]
Except that a verse line is probably not a <p type=verse

**Comment by sydb** [comment]
Actually, while my intuition tells me no, a `<head>` is **not** a `<p type=head>`, but actually an `<l>` **is** a `<p type=verse>`, at least in some sense.

I _think_ I agree w/ @lb42 that @martindholmes ’s #1 is correct, but that may be me just being ignorant of years of textual theory, and reasoning that the TEI has had this floppy definition of `<p>` for over two decades, and it hasn’t really been a problem.

**Comment by martindholmes** [comment]
It hasn't been a problem because we've mostly been working in the same fairly narrow tradition within which we can (mostly) rely on our instincts  and assume we have the same intuitions. But as the TEI is increasingly used for texts from very different traditions, the flimsy nature of our categories is increasingly apparent. I would say that if we can't adequately articulate what a paragraph is, and we find ourselves falling back to the old "I know one when I see one" defence, then we've been thoroughly caught out.
I know @PFSchaffner will say that the same is true for all manner of other things including headings and list items and tables. But I think that's pushing it a bit too far; any of us could come up with a pretty clear definition of what a table is, for instance -- "a set of islands of content, typically rectangular, laid out in a grid pattern," off the top of my head. A list item might be "one of a sequence of text segments, typically with parallel structure, forming an enumeration." We might well quibble over details and edge cases, but it's not too difficult to get started. But paragraphs are a different kettle of fish.

**Comment by ebeshero** [comment]
I think we can at least try to do a little better with describing a `<p>` in the Guidelines. And we can even describe the very problem of attempting to define it in terms of cultural expectations of present vs. past. Text encoders can decide if they want the "semantic baggage" of a paragraph or not. For example, we could differentiate the "generic prose block" of a paragraph from that of a descriptive header or caption by indicating that usually paragraphs appear in sequences with one another, that often we expect to find them as low-level block units in documents divided into chapters or sections, though they are not confined to such usage. That in most cases, we expect paragraphs to contain more than one sentence, though there are paragraphs of just one sentence. 

As I type this I'm reviewing my students' encoding of some documents that I think have paragraphs, but they evidently don't think the paragraphing matters. They're sometimes happy to encode something like a newspaper article for things like people and places and concepts, and not worry about the structural stuff. That looks wrong to me, but as they're learning to code it's not necessarily an error. Hmm. But it reminds me that paragraphing is usually about dividing up ideas, showing some kind of sequence from one to the next in a document, and that the paragraph contains prose text, whereas we think of sections and chapters as themselves containing paragraphs.

**Comment by ebeshero** [comment]
Oh--can we have paragraphs in documents that don't have what we'd call a sentence?

**Comment by martindholmes** [comment]
@ebeshero `<p>Absolutely.</p>`

**Comment by npcole** [comment]
Just as an aside.  One can have a paragraph inside another paragraph in many printing conventions -- such as a nested block quote inside a paragraph.

**Comment by jamescummings** [comment]
@npcole Some might argue that this is a block quote rather than a paragraph. It might be the conflation of presentational rendering on the page and intellectual understanding of that block's semantics. But people disagree about this.

**Comment by PFSchaffner** [comment]
Given (1) that the vagueness of `<q>` covers block inserts of all kinds; and (2) that we usually avoid creating a new way of doing something for which a valid way already exists; and (3) `<p><q><p>` is perfectly valid (and much used) -- there is no need for `<p><p>`.  (?)

**Comment by PFSchaffner** [comment]
As for `<p>` vs. `<ab>` I suppose I've roughly followed the rule that `<p>` is a semantic unit with typographic implications, `<ab>` a typographic unit with semantic implications, and that one should privilege `<p>`  when typography and layout align, unless `<ab>` is more convenient!

**Comment by lb42** [comment]
Another simple rule of thumb is that if a block of text is prose, then I tag it as `<p>`; if it is verse as `<l>`; and when I am not sure because it could be either,  I tag it as `<ab>` .

**Comment by PFSchaffner** [comment]
I'm thinking as usual of Bibles (and similar texts with more-or-less arbitrary chunks of text). It is conventional to tag the 'verses' as `<ab>`, unless it is a 'paragraphing' Bible that attempts to format the Biblical prose into modern paragraphs independent of the verses, in which case those paragraphs go in to `<p>` and the verses get relegated to milestones ('cause otherwise you'd have to put the `<ab>`s within `<p>`s. )  The same applies to Bibles that attempt to render the verse and semi-verse in lines: once they do that, you have to abandon `<ab>` for verses and turn them into milestones instead. I think this procedure follows both of our rules.

**Comment by PFSchaffner** [comment]
(It is very annoying, however, to talk about Bibles because of the ambiguity of the word 'verse')

**Comment by lb42** [comment]
Indeed, treatment of biblical verses was the primary use case for ab when it was first mooted.

**Comment by sydb** [comment]
Council VF2F subgroup thinks that if @ebeshero can describe `<p>` a bit better, she should go for it. Otherwise is there any concrete recommendation for a change to the _Guidelines_ herein? We also like @martindholmes (1), the [pornography definition](https://en.wikipedia.org/wiki/I_know_it_when_I_see_it), as it were.

**Comment by ebeshero** [comment]
2020-10-24 Council Face to Face discussion:  We should consider that putting `<ab>` in core would resolve some issues: `<ab>` should be able to be encoded like `<p>`. `<p>` is an artefact of Western culture, and perhaps we should now be treating it as a subset of the larger category of things that are `<ab>`.  Thus, `<ab>` could really be primary, with `<p>` as a special instance.

**Comment by martinascholger** [comment]
Council meeting 2021-10-14: try a PR with `<ab>` in core, and modify prose to remove the phrase, "semantic baggage."

**Comment by ebeshero** [comment]
Completed requested revision in branch: https://github.com/TEIC/TEI/compare/dev...ab_in_ab_issue-1856

**Comment by ebeshero** [comment]
I am thinking I completed work on this ticket with #1856 .
