### ISSUE TITLE
Incorrect restriction for teidata.word?

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1930]
The restriction for https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-teidata.word.html is
```xml
<content>
 <dataRef name="token"
  restriction="(\p{L}|\p{N}|\p{P}|\p{S})+"/>
</content>
```
This excludes combining marks (`\p{M}`), meaning certain types of accentuation, etc. are illegal in, e.g. `@type`. This seems like a corrigible error, but would it be better to rewrite the expression to just exclude any sort of spacing character? So `\P{Z}`. For reference, see the [General Category Properties](http://unicode.org/reports/tr18/#General_Category_Property).

**Comment by lb42** [comment]
The proposed simplification also has the advantage of being clearly motivated.

**Comment by sydb** [comment]
The intent of the current restriction is that the characters be “word” characters from natural languages. Thus, @hcayless  is correct, something should be done so that accented characters are allowed regardless of normalization form. But characters like U+001C (FILE SEPARATOR) should not be allowed. Personally, I’m not fond of allowing '{' and '@', either, but they’re already in there.

**Comment by hcayless** [comment]
Excluding control characters (`\P{Cc}`) would probably also be sensible. Not sure about the other stuff in `\p{C}`, which includes the PUA, but we could, conservatively, decide to exclude it too  (since it already is and no-one has complained).

**Comment by sydb** [comment]
Agreed, especially about PUA characters, which by definition should not be in a TEI file.

**Comment by duncdrum** [comment]
> Agreed, especially about PUA characters, which arguably by definition should not be in a TEI file.

well I for one want PUA in tei, and lots of them. But not as attribute value, which seems to be the only use of `teidata.word`

`must contain a single ‘word’ which contains only letters, digits, punctuation characters, or symbols`
nothing in the above description however, tell users that we don't PUA, so maybe the *GL* should mention that.

**Comment by sydb** [comment]
We don’t use PUA simply because PUA and Guidelines for _interchange_ are diametrically opposed concepts. If you want to use a PUA character locally, that’s your problem. If you want to use the TEI Guidelines for interchange, you should encode such characters with `<g>`.
But I agree, just “it is desirable that any relevant additional information about the [PUA characters] should be recorded … as further discussed under 5 Characters, Glyphs, and Writing Modes” is probably not enough guidance in this area.

**Comment by duncdrum** [comment]
`<g>` is tei xml, the Guidelines already contain examples for how to use this with PUA inside them, more coming. Since PUA are inside `<g>`, and `<g>` are tei-xml, PUA are in tei files.  

It ll be the day when TEI can do without PUA, if ever.

**Comment by hcayless** [comment]
Implemented, excluding all of `\p{Z}` and `\p{C}`, and seems to work fine.
