### ISSUE TITLE
FSD purposes non-sentence

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1952]
In [FD](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/FS.html#FD) there is a list of the three purposes an FSD serves. The second one is quite problematic:

> It provides a mechanism by which the encoder can define constraints not only what it means to be a well-formed feature structure, but also `<hi>`valid`</hi>` feature structure, relative to a given theory stated in typed feature logic. These constraints may involve constraints on the range of a feature value, constraints on what features are valid within certain types of feature structures, or constraints that prevent the co-occurrence of certain feature-value pairs.

The first “sentence” is not even a sentence, I don’t think; and the second sentence is poorly worded.

My first thought at rewording is the minimalist approach: “It provides a mechanism by which the encoder can define constraints not only **on** what it means to be a well-formed feature structure, but also **over a** `<hi>`valid`</hi>` feature structure, relative to a given theory stated in typed feature logic. These <strike>constraints</strike> may involve constraints on the range of a feature value, constraints on what features are valid within certain types of feature structures, or constraints that prevent the co-occurrence of certain feature-value pairs.”

My second thought at rewording would be more like “It provides a mechanism by which the encoder can define not only what it means to be a well-formed feature structure, but also provide constraints which may be used to determine whether a particular feature structure is `<term>`valid`</term>` relative to a given theory stated in typed feature logic. The FSD may provide constraints on the range of a feature value, constraints on what features are valid within certain types of feature structures, and constraints that prevent the co-occurrence of certain feature-value pairs.”

But that rewording was written without the benefit of careful review of FSDs to make sure it is correct. (I haven’t written an FSD in over a decade.)

**Comment by lb42** [comment]
On the less is  more principle, I much prefer your first revision/ correction

**Comment by MegJBrown** [comment]
Can someone explain the 'less is more' principle relative to this sentence? The first revision proposed involves less intervention, but it also seems less clear to me. I think Syd's second version is easier to parse, because its more explicit that the constraints can be used to determine whether something is valid. 

 I'm coming to it cold, though, and largely out of context. If there's solid consensus behind the first, I can go ahead and make the change, I'm just checking.

**Comment by lb42** [comment]
Well, if you prefer the second version, here's an even clearer revision: change 

"the encoder can define not only what it means to be a well-formed feature structure, but also provide constraints which may be used to determine whether a particular feature structure is <term>valid</term>... "
to 
"!the encoder can define what it means to be a well-formed feature structure and can also provide constraints which  determine whether a particular feature structure is considered to be  <term>valid</term>... "

My reluctance to change anything is largely because the last time this chapter was reviewed the group concerned was unable to come up with any revision that everyone agreed to, though they were pretty unanimous in not liking the current draft much. That was years ago, and I am not aware that anyone has ever really looked at it since, so would really not advise spending much time on it.

**Comment by ebeshero** [comment]
I think the first revision @sydb offers is pretty difficult to read, and the emphasis plus highlighting on **over a** `<hi>valid</hi>` is not making things better. I think the second formulation is smoother reading and says the same thing with less of an obstacle course for the reader.

**Comment by ebeshero** [comment]
I just now saw @lb42 ‘s alternative revision, but I think I still prefer @sydb ‘s second revision for flow. Really this ticket is not about overhauling the FSD chapter, but simply correcting an unclear passage, and I think we’ve got a good revision in Syd’s post.

**Comment by ebeshero** [comment]
Okay, @lb42’s rephrasing boils down to removing a “not only ... but also” construction, which simplifies a bit, but loses something too. 

If we stay with the “not only...but also” construction, I’d modify @sydb’s phrasing in his option 2 slightly for parallelism, like so, to move “not only” before the word “define”.

“can not only define what it means to be a well-formed feature structure, but also provide “

**Comment by MegJBrown** [comment]
Ok, just tried fixing the language in FD about FSD. This was my first independent git fix, so hopefully I did this right. All three bullet points in this used the same structure, bullet point 2 (under discussion here) just tried to vary it up by flipping around a few elements. I hope simplifying it has increased clarity.
