### ISSUE TITLE
FR: Declarative Citation Structure

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1957]
The TEI element [`<cRefPattern>`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-cRefPattern.html) defines a mechanism for resolving "canonical" references into machine-actionable URIs. While it permits automated resolution of these references, it does not provide for the automated *construction* of references. So while TEI documents can declare how citations should be treated, they can't actually declare how those citations should be made. This means systems that might want automatically to do things with a document's citation structure, like chunk a large document into smaller pieces or generate a table of contents are at a disadvantage.

We (@PonteIneptique and myself) are proposing two new elements to allow documents to declare their citation structure and to specify how structural information may be extracted from them:

`<citeStructure>` permits an application to address and extract parts of the TEI document declaring its structure,
and can provide hints on how to construct canonical references. Instead of telling an application how to
resolve  references, as `<cRefPattern>` does, this tells the application how to *build* them using
the TEI document as a data source.
        
`<citeStructure>` has three required attributes, `@unit`, a label specifying what kind of unit this level
of structure refers to, e.g., "book", "line", or "section"; `@match`, an XPath that tells you how to
find each unit in of the given type in the document; `@use`, an XPath, relative to the element(s) matched
by `@match` that gives a mechanism for uniquely identifying the element(s) referenced by `@match`. This could
be an `@xml:id`, or a labeling attribute like `@n`, or even a positional reference like `position()`. It should
be possible to construct an XPath that will retrieve an element referenced by `<citeStructure>` by constructing
a predicate on the XPath in `@match` using the value for a given element of the XPath in `@use`.
             
`<citeStructure>` also has an optional attribute, `@delim`, which can be used as a hint for the construction of 
canonical references, e.g. "1.2" for the poem `<div n="1">` and the `<l n="2">`. In those references,
the value of `@delim` should be assumed to come before the referenced unit. So, in example 2 (again, assuming a 
reference style like "1.2"), the line `<citeStructure>` is the one that has a `@delim`.
             
`<citeStructure>`s may nest, and a relative XPath in `@match` is assumed to start from the element(s) matched
by the parent `<citeStructure>`. See example 2 below. 
             
`<citeData>` provides a way for a document to declare how certain types of data can be extracted from the
structures mapped out by `<citeStructure>`. In examples 1 and 2, a Dublin Core Title can be obtained for each
front section or poem by getting the `<head>` element from each.
             
`<citeData>` has two required attributes, `@property` (analogous to `@property` in RDFa), a URI, and `@use`,
a relative XPath exactly like `@use` on `<citeStructure>`. 

```xml
<encodingDesc>
    <refsDecl>
        <!-- Example 1: Units of the introductory front matter may be cited, e.g. "Intro. 1" -->
        <citeStructure unit="front"
            match="//front/div[@type='introduction']/div[@type='section']" 
            use="@n" delim="Intro. "> 
            <!-- The thing(s) matched by ../@match have titles at the location ./head. 
                 Assume the prefix "dc" has been declared using a <prefixDef> elsewhere.
                 Multiple <head>s in the matched <div> would mean multiple dc:titles being
                 extracted for that div.-->
            <citeData property="dc:title" use="head" /> 
        </citeStructure>
        <!-- Example 2: Poems may be cited as, e.g. "1", lines as, e.g. "1.5" -->
        <citeStructure unit="poem"
            match="//body/div[@type='edition']/div[@type='textpart']" use="@n">
            <citeData property="dc:title" use="head" />
            <citeStructure unit="line" 
                match=".//l[parent::div or parent::lem]" use="@n" delim=".">
            </citeStructure>
        </citeStructure>
    </refsDecl>
</encodingDesc>
```
The following example is the equivalent of the one given for `<cRefPattern>` in https://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SACR and could be used (with a different algorithm) both to resolve citations of the type "Matt 5:7" and/or to generate a set of resolvable citations at any level.
```xml
<encodingDesc>
  <refsDecl>
    <citeStructure unit="book" match="//body/div" use="@n">
      <citeStructure unit="chapter" match="div" use="position()" delim=" ">
        <citeStructure unit="verse" match="div" use="position()" delim=":"/>
      </citeStructure>
    </citeStructure>
  </refsDecl>
</encodingDesc>
```

**Comment by martindholmes** [comment]
This looks really interesting, and is nicely worked out. I'm not absolutely clear on how I'd use it, though; would it be used by an external processor that is pulling out a particular fragment of the document and needs to construct a citation for it?

**Comment by PonteIneptique** [comment]
This would be particulary helpful to build application that serves texts and chunks of text on demand, particularly in situation such as DTS API ( www.w3id.org/dts ) which was one of our usecase.

Another usecase was to provide a way for tool provider in general to parse texts easily in declared chunks. For Capitains.org, we are looking forward to leave cRefPattern behind for something that, in between other things, allows for more flexibility and ease of parsing in regards to Table of Content building *and* citation retrieval. This allows for quickly presenting big corpora based on citation scheme, and display chunks such as groups of 30 lines when in a book->line scheme or poems when in a book->poem->line one.

Finally, the ability to declare automaticaly citation level metadata would definitely make sense, eg. for charters in cartularies, poems title when applicable and poems author when dealing with multi-author anthology, letters in correspondences :)

@hcayless will probably explain some stuff in a better way, but I hope this helped clear things up.

**Comment by lb42** [comment]
I may be missing the point here, but why wouldn't you use cRefPattern to express the structure of your document? What does this proposed feature add to what cRefPattern already provides, other than different syntax?

**Comment by hcayless** [comment]
cRefPattern looks like maybe it should let you do this, but in fact it can’t. You can kind of, sort of, maybe sometimes do it by parsing the regexes in `@matchPattern`, but I don’t think that’s reliable, and certainly not easy.

**Comment by PonteIneptique** [comment]
Regarding technical difficulties and parsing, lets take one example:

```xml
<cRefPattern matchPattern="([1-9A-Za-z]+)\s+([0-9]+):([0-9]+)"
 replacementPattern="#xpath(//div[@type='book'][@n='$1']/div[@type='chap'][@n='$2']/div[@type='verse'][@n='$3'])"/>
```

Is easy to use to translate `1 1:5` to an xpath `//div[@type='book'][@n='1']/div[@type='chap'][@n='1']/div[@type='verse'][@n='5']` as it is a matter to replace potentially `$` by language specific regexp group identifiers. However, building the XPath from this information to list available citation is a bit more complexe, as it requires us to find what is `=$1`: reconstructing the search for `//div[@type='book']/@n` from `//div[@type='book'][@n='1']` is not an easy task. And we are lucky here that the document did not state the filter `[@type='book']` after `[@n=$1]` as it would require to really parse the xPath, and not the string only, to build this kind of identifier.

However, if you take ` <citeStructure unit="book" match="//body/div" use="@n">` both resolving `1` and finding it will be easy as much as string collation is : `//body/div[@n=?]` and `//body/div/@n`.

This is not the only good thing about citeStructure : citeStructure is hierarchical, which means we can design citation tree structure which is currently impossible in cRefPattern, except by having a look at a built ToC. The relationship between books and verse in the example over is not only clear while reading for human, it's much more easy to interpret for the machine than : 

```xml
<cRefPattern matchPattern="([1-9A-Za-z]+)"
 replacementPattern="#xpath(//div[@type='book'][@n='$1']"/>
<cRefPattern matchPattern="([1-9A-Za-z]+)\s+([0-9]+)"
 replacementPattern="#xpath(//div[@type='book'][@n='$1']/div[@type='chap'][@n='$2']"/>
```
as the relationship between the two is derived from the matchPattern and its reuse in replacementPattern.

On another note, while I base a lot of my work on these cRefPattern, I wonder if they are less used mostly because their reuse is complexe.

**Comment by sydb** [comment]
My instinct is similar to @martindholmes’. But I want to add my concern of security. If I am writing an XQuery or XSLT program to process a generic TEI document that uses `<citeStructure>` or `<citeData>`, I suspect there will be a strong incentive to evaluate an XPath that is constructed from the values of `@match` and `@use`. But I can’t do that safely without scrubbing the XPath first, a task which is notoriously difficult.
This is not a deal-breaker, but it is an argument against. The arguments in favor may outweigh it, or not.

**Comment by hcayless** [comment]
@sydb What's your safety concern? I wasn't aware that XPath had side effects. Wouldn't the same concern hold for evaluating `@replacementPattern`?

**Comment by sydb** [comment]
Haven’t thought about `@replacementPattern`, but XPath injection attacks are discussed in the literature, as it were.[1] In our case, think of the nasty anti-humanitarian who wants to take down [TAPAS](http://tapasproject.org/) after this has taken effect. He or she submits a file that has as the value of `@match` (or whatever attribute is going to be evaluated) that has, instead of something like `//div/head`, something that loads a 48 GiB KML file: `doc('http://bad.example.org/huge.kml')//div/head` or some such.

[1]
1. https://www.balisage.net/Proceedings/vol7/html/Vlist02/BalisageVol7-Vlist02.html
1. https://owasp.org/www-community/attacks/XPATH_Injection
1. https://www.thesecuritybuddy.com/vulnerabilities/what-is-xpath-injection-attack/
1. https://rhinosecuritylabs.com/penetration-testing/xpath-injection-attack-defense-techniques/
1. https://ws-attacks.org/Xpath_Injection
1. https://monovm.com/blog/xpath-injection-attacks-and-prevention/

Caveat: I have not read most of these.

**Comment by hcayless** [comment]
@sydb My response is that it isn’t the responsibility of a document in a system to sanitize inputs into that system. It’s the system’s (and the implementer’s) responsibility to do that. Probably something we should note in the documentation of the element if it’s accepted, but I don’t see how it’s a reason not to accept it. Bear in mind that we use URIs all over the place, and _any_ URI might point to something malicious.

**Comment by sydb** [comment]
I agree completely, @hcayless, that it is the implementer’s responsibility. But as one of those implementers, I’d just as soon have fewer places to worry about. And yes, if we do this, we definitely need a health warning. (Perhaps the warning in [teidata.xpath](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-teidata.xpath.html) is sufficient, but perhaps not.)
But no, it is not the same level of problem for URIs — _pointing_ to something malicious is not the same is _being_ something malicious. Only a URI that has an “xpath()” (or “xpath1()” or “xpath2())” scheme _and_ is being evaluated (rather than just passed along) poses a significant threat, no? (Or am I missing something?)

**Comment by martindholmes** [comment]
@sydb Let's look at this from the point of view of a malicious hacker. What exactly would I have to do to take advantage of this?

I presume it would go something like this:

1. Notice that TAPAS has an XSLT or XQuery module that's evaluating XPath in an attribute like this without sanitizing it (because how could you)?
2. Notice that anyone can upload TEI documents into TAPAS and get them presented to the world.
3. Carefully craft one of these XPath structures such that it does something malicious when the document is rendered into HTML.
4. Upload the document into TAPAS.

Now, in order to make the nasty thing happen, someone just needs to visit the HTML rendering of the document. Easy. However, what I'm having trouble figuring out is exactly what it is that the XPath could do. It could potentially read a document on the filesystem and present its contents in the HTML page, so if you had left risky files containing passwords or whatever accessible to the XSLT processor, that's definitely a risk, but the fault there would surely be on the part of the server admin. I don't think you could write anything to disk, or overwrite anything, could you? (I realize this would be possible using the EXSLT file extensions in a commercial version of Saxon, but I don't think a project like TAPAS would be using a commercial version of Saxon behind its public site.)

You could put something unwanted into the output HTML document with (perhaps) less chance of detection than in the case of other mechanisms, but I think the risk there is along the lines of that posed by allowing a graphic element pointing to a JPEG somewhere external to be converted into an HTML img tag. Can anyone imagine plausible exploit scenarios for this?

**Comment by hcayless** [comment]
Two things here: the first is that attacks of the sort I imagine @sydb fears are already perfectly possible. Anything that uses teidata.xpath is potentially vulnerable. This proposal does not make those attacks especially more likely in itself–it's especially no more a vulnerability than [model/@predicate](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-model.html), e.g. 

Second, if you're arguing that the Guidelines themselves need to be more vocal about how to block these sorts of attacks, we'd presumably advise filtering out functions that access external information (e.g. https://www.w3.org/TR/xpath-functions-31/#fns-on-docs, https://www.w3.org/TR/xslt20/#document, https://www.w3.org/TR/xslt20/#unparsed-text, https://www.w3.org/TR/xslt20/#system-property, https://www.w3.org/TR/xslt-30/#func-document, https://www.w3.org/TR/xslt-30/#func-system-property, and https://www.w3.org/TR/xslt-30/#func-available-system-properties) plus any externally defined functions. We could write a Schematron rule for that...

But I don't see how any of this is a good reason to block the FR. If it is a reason, then it would also be a reason to go back and rip out a bunch of existing functionality immediately.

**Comment by peterstadler** [comment]
I wonder whether such "processing instructions" rather belong into the ODD than into each TEI file? As I see that the TEI Publisher also supports the DTS API maybe @tuurma has some thoughts on this?

**Comment by hcayless** [comment]
@peterstadler What use would they be in the ODD? And why would I want to try in my ODD to model every possible structural variant rather than do it in the document where I can be specific about what that document does?

**Comment by peterstadler** [comment]
Well, I assumed this was mostly about making a *collection* of documents available not about a single item. And I assumed that some effort would be made to (structurally) harmonise those documents within that collection for data interchange (by creating an ODD based schema). Hence my conclusion that the majority of rules would be repeated in every document. 
But you're right, one would want a mechanism to locally override those generic rules (from the ODD) within the document instance.

**Comment by PonteIneptique** [comment]
I would just add that files can be lost, updated, etc. Having such information directly in the file, without the need for parsing an ODD, is definitely a bonus. In context like DTS and generally APIs, it also allows for passing information to the client (with the security reserve mentioned before in the thread) with a single http request.
For example, Perseus corpora with Capitains have such mechanism using the cRefPattern, but it definitely showed limits in terms of both flexibility and readability :)

**Comment by martinascholger** [comment]
ping @peterstadler, @ebeshero, and @martinascholger to review @hcayless' pull request https://github.com/TEIC/TEI/pull/1983
