### ISSUE TITLE
Add more elements to att.spanning with schematron constraint

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#197]
Many structural and transcriptional elements should be added to att.spanning with a schematron rule enforcing the following conditions:

1) if the element is empty it must have a `@spanTo` attribute
2) the `@spanTo` attribute must point to an `@xml`:id in the document (starts-with(`@spanTo`, '#'))
3) the `@spanTo` attribute must point to an `@xml`:id attribute which follows the current element.

Many elements could be added to this.  I would argue that any element which has a foo and fooSpan equivalent should be added (i.e. add the non-Span versions of all of the current members) and the alternative slowly deprecated.  Structural elements like div, p, ab, lg, l, and similar elements should be added and transcriptional elements like add/del/subst/abbr/sic/orig, and a general purpose element like seg.

This would, for example, solve many of the overlap problems people have, and be useful for those undertaking to create genetic editions.

Original comment by: @jamescummings

**Comment by lb42** [comment]
As an example of the "difficult theoretical issues" consider the following markup

<p> blah <del spanTo="#endSpan">boppity boo</p>
<p>bippity boppity <anchor xml:id="endSpan"/> boo </p>

we may infer that the text after deletion should read "blah boo".
How many paragraphs though?

**Comment by ebeshero** [comment]
This looks like a lot of my projects lately... I think you mean to close that `<del/>` here, right?
~~~~
<p> blah <del spanTo="#endSpan"/>boppity boo</p>
<p>bippity boppity <anchor xml:id="endSpan"/> boo </p>
~~~~


 Well, in practice shouldn't we use this to include as many paragraphs as were part of a single instance of deletion? 

I guess one issue is simply human recognition of what text was deleted--do we need a reminder inside lots of lines that they are each part of a deletion? Or is it a convenience to the human coder not to have to set del elements inside every `<p>` that was deleted?

**Comment by lb42** [comment]
Sorry, yes, I did mean to make the `<del>` empty (or, better, make it a `<delSpan>`). But I thin you may be missing my point. Is the markup being deleted as well as the text (so we have one `<p>` afterwards) or not  (so we have two)? Either seems to me perfectly plausible and there's no obvious way of saying which is intended. 

And it's not just about deletion: suppose we invented saidSpan:
~~~~
<l> blah <saidSpan spanTo="#endSpan"/>boppity boo</l>
<l>bippity boppity <anchor xml:id="endSpan"/> boo </l>
~~~~
If I do a search for `<l>` elements containing "boppity", should I get zero, one, or two?

**Comment by ebeshero** [comment]
Reopening this in the larger context introduced on the TEI listserv in early October 2017, regarding element behavior in the context of overlapping hierarchy in poetry encoding. See https://listserv.brown.edu/archives/cgi-bin/wa?A2=TEI-L;ae5e4e1f.1710  .

**Comment by ebeshero** [comment]
@lb42 Oh! interesting point about the **deletion** in particular, but presuming entire paragraphs are included in an act of a massive strikethrough, we're in the weeds of genetic editing anyway--it's going to have to be a call we **mark** in the indication of resuming an act. 

I think we want a mechanism to indicate interruptions within an act of something-that-spans (whether speech or deletion). We need a means of identifying and grouping related elements that span, and indicating where these pause a moment and resume (pretty frequent with the representation of spoken expression, she said.)

Anyway, to your example, of course if you search for `<l>` elements containing "boppity" you should and will get two with this markup. Perhaps you'd be asking how to locate "boppity" only when it's part of something spoken...and for that we're going to have to look at the text nodes in between the saidSpan and the anchor on the `following::` axis. And we wouldn't be doing this unless we had a darned good reason to--that is--because we've got an overlapping hierarchy issue.

**Comment by ebeshero** [comment]
@lb42 I'm thinking about your example with `<saidSpan/>`: is the issue you're raising a question of whether the spoken portion ought to be considered part of the lines of verse?  In a speech act inside a poem, we see this quite a lot--the spoken expression is part of the regular lineation and meter, so the poetry lines would properly be considered to be spoken expression and part of the structural hierarchy of the poem. That's why we'd want this to span and, as I read it, the presence of markup within the range of the span is presumed to be *part* of the spanning event. We'd need to designate otherwise, mark a different way, if we didn't want to presume that.

**Comment by sydb** [comment]
Lovely and informative discussion, but unless there’s a proposal, it’s not much of a ticket. So Council sub-group is closing this ticket. If @ebeshero , @lb42 or others have a definitive proposal, please open a new ticket rather than re-open this (unless it aligns very closely with the original issue raised 2009-08-09.
