### ISSUE TITLE
Finalize the content model of standOff

### ISSUE THREAD

**Issue by laurentromary** [TEIC/TEI#1977]
We are not completely finished with  `<standOff>`: following the decisions taken at the September 2019 meeting in Graz (see minutes: https://tei-c.org/activities/council/meetings/tei-technical-council-f2f-graz-2019-09-14-16/) we need to have at least `<listAnnotation>` (typed, recursive, child of standOff, with `<annotationBlock>` and `<annotation>` as children) and `<annotation>` (typed, child of listAnnotation, possibly directly  of standOff), implementing the Web Annotation Data Model (three components: target (spans, surfaces), annotation (interps) and body (we need a class, maybe pre-filled but where we can plug anything that would be a nice body - persons, notes, lexical entries etc.). Quite  some stuff is available from https://github.com/laurentromary/stdfSpec/blob/AnnArbor/Scenarios/StandOffScenarios.xml

**Comment by ebeshero** [comment]
See conversation at https://github.com/TEIC/TEI/issues/1976#event-3038465938

**Comment by sydb** [comment]
You are (of course) completely correct, @laurentromary. `<listAnnotation>` along with `<extraTextual>` (or whatever it ends up being called) are slated for next release.

**Comment by sydb** [comment]
Correction: `<listAnnotation>` is what is slated for the next release, and I fully hope we can get `<annotation>` in, too. It would be optimistic to think `<extraTextual>` will be ready that soon, but it is not at all out of the question.

**Comment by sydb** [comment]
Speaking of `<listAnnotation>`, what should the content model be? Council is leaning towards a content model that boils down to either
~~~~~
model.annotationLike = ( note | annotation | annotationBlock )
listAnnotation = model.headLike*, model.labelLike*, ( model.annotationLike | listAnnotation )+
~~~~~
or, equivalently to the end user,
~~~~~
model.annotationLike = ( note | annotation | annotationBlock | listAnnotation )
listAnnotation = model.headLike*, model.labelLike*, model.annotationLike+
~~~~~

**Comment by laurentromary** [comment]
I tend to prefer the second version (only class-based). I would also see listAnnotation as member of att.typed (e.g. to implement the notion of "tier", i.e. an annotation layer (cf. ELAN, etc.)) and att.notated (to elicit that a specific annotation framework or vocabulary is being used, e.g. a tags in POS annotation).

**Comment by sydb** [comment]
Yes, `<listAnnotation>` (as I envision it) is a member of att.typed and att.notated, as well as a few others to which we can add model.annotationLike. (Unless there are objections :-) 
~~~~~xml
    <memberOf key="att.global"/>
    <memberOf key="att.typed"/>
    <memberOf key="att.notated"/>
    <memberOf key="att.declaring"/>
    <memberOf key="model.listLike"/>
    <!-- and likely also: -->
    <memberOf key="model.annotationLike"/>
~~~~~

**Comment by sydb** [comment]
So, here is something I missed when I wrote my previous comment. (And thank goodness for automated validation during the build process!)

`<listAnnotation>` cannot be a member of both model.listLike and model.annotationLike because both are themselves members of model.standOffPart. Thus if an element were a member of both model classes, non-deterministic content models would result.

My proposed fix is to remove `<listAnnotation>` from model.listLike. Yes, it is like a `<list>` in _structure_, but I do not see any reason a `<listAnnotation>` needs to go in the normal places a `<list>` can go. (This particular class, model.listLike, is one of the worst abuses of the class system — it allows, e.g., a list of witnesses to be put inside an `<sp>`!)

So anyone who thinks it important that `<listAnnotation>` be allowed in the content of the elements listed below should speak up.

-----

#### elements which have model.listLike as content (either directly or indirectly, and not including `<standOff>` itself, of course)

`<ab>`, `<abstract>`, `<accMat>`, `<acquisition>`, `<add>`, `<additions>`, `<argument>`, `<back>`, `<body>`, `<camera>`, `<caption>`, `<case>`, `<castList>`, `<cell>`, `<change>`, `<collation>`, `<colloc>`, `<condition>`, `<corr>`, `<custEvent>`, `<damage>`, `<decoNote>`, `<def>`, `<del>`, `<desc>`, `<dictScrap>`, `<div>`, `<div1>`, `<div2>`, `<div3>`, `<div4>`, `<div5>`, `<div6>`, `<div7>`, `<docEdition>`, `<emph>`, `<entryFree>`, `<epigraph>`, `<epilogue>`, `<etym>`, `<fDescr>`, `<figDesc>`, `<figure>`, `<filiation>`, `<foliation>`, `<form>`, `<fsDescr>`, `<gen>`, `<gram>`, `<gramGrp>`, `<handNote>`, `<head>`, `<hi>`, `<hyph>`, `<iType>`, `<imprimatur>`, `<item>`, `<l>`, `<lang>`, `<layout>`, `<lbl>`, `<lem>`, `<licence>`, `<meeting>`, `<metamark>`, `<mod>`, `<mood>`, `<musicNotation>`, `<note>`, `<number>`, `<occupation>`, `<orig>`, `<origin>`, `<orth>`, `<p>`, `<per>`, `<performance>`, `<pos>`, `<postscript>`, `<prologue>`, `<pron>`, `<provenance>`, `<q>`, `<quote>`, `<rdg>`, `<rdg>`, `<ref>`, `<reg>`, `<rendition>`, `<restore>`, `<retrace>`, `<rhyme>`, `<said>`, `<salute>`, `<scriptNote>`, `<secl>`, `<seg>`, `<set>`, `<sic>`, `<signatures>`, `<signed>`, `<sound>`, `<source>`, `<sourceDesc>`, `<sp>`, `<stage>`, `<stress>`, `<subc>`, `<summary>`, `<supplied>`, `<support>`, `<surplus>`, `<surrogates>`, `<syll>`, `<tagUsage>`, `<tech>`, `<title>`, `<titlePart>`, `<tns>`, `<trailer>`, `<trailer>`, `<typeNote>`, `<u>`, `<unclear>`, `<usg>`, `<view>`, `<witness>`, `<witness>`, `<writing>`, `<xr>`, and `<xr>`

**Comment by laurentromary** [comment]
No clear and spontaneous objection to this!

**Comment by bansp** [comment]
Request for confirmation: is the branch https://github.com/TEIC/TEI/tree/sydb-standOff the official Council workplace for standoff? I'd like to set up tracking on my side, so I'm just double-checking. Cheers!

**Comment by sydb** [comment]
I don’t think “official” is quite correct, but I suspect it is what you want to track.

**Comment by sydb** [comment]
We believe this was done in 4.1.0, and thus are closing.
