### ISSUE TITLE
idno: different desc for English and other languages

### ISSUE THREAD

**Issue by mattlev2** [TEIC/TEI#1989]
Hi, 

It seems there is a problem with the description of the idno element. 

The English description reads: 
`` <desc versionDate="2010-04-30" xml:lang="en">supplies any form of identifier used to identify some object,
  such as a bibliographic item, a person, a title, an organization,
  etc. in a standardized way.</desc>``

The French, Spanish or Italian translations are slightly different: 
- ``<desc versionDate="2009-01-05" xml:lang="fr">donne un numéro normalisé ou non qui peut être utilisé
    pour identifier une référence bibliographique.</desc>``
- ``<desc versionDate="2007-05-04" xml:lang="es">proporciona un número, estándard o no, usado para la identificación de un elemento bibliográfico.</desc>``
- ``<desc versionDate="2007-01-21" xml:lang="it">fornisce un identificatore, standard o meno, usato per identificare un'unità bibliografica</desc>``

I don't read the other languages, so I can't tell. 

The expression "such as" is omitted in Spanish, Italian and French, which leads to a restriction of the uses for this element in those three languages to bibliographic contexts. 

## Solution
- French translation: ``donne un numéro normalisé ou non qui peut être utilisé pour identifier une référence bibliographique, une personne, le titre d'un ouvrage ou une organisation``
- Spanish translation: ``proporciona un número, estándar o no, usado para la identificación de un elemento bibliográfico, una persona, un título o una organización``
- Italian translation: no skills to provide a translation

Matthias

**Comment by ebeshero** [comment]
Thanks for noticing this discrepancy, @mattlev2 ! I have a further question about a phrasing in the English version that seems to be handled differently in the French, Spanish, and Italian. The English version indicates “any form of identifier” (so not necessarily a number as indicated in the French and Spanish), and it ends with the phrase, “in a standardized way.” The Italian version uses the phrase “un identificatore” which I think(?) does not imply a number.

The French, Spanish, and Italian versions contain a phrasing that I think doesn’t agree with the English “in a standardized way.” French has “normalisé ou non”, Spanish: “estándar o no”, and Italian: “standard o meno”. I am not sure, but I think those are all saying the identifier need not be standardized so that looks like a serious discrepancy. Or am I misinterpreting something?

**Comment by mattlev2** [comment]
I think you're right. 

|  English version | **any identifier**    | to identify  | **bibliographic items, persons, organizations or title**  | + **standard way**      |
|------------------|-----------------------|--------------|-----------------------------------------------------------|-------------------------|
| Spanish version  | **number**             | to identify  | **bibliographic item**                                    | + **standard or not**   |
| French version   | **number**            | to identify  | **bibliographic item**                                    | + **normalized or not** |
| Italian version  | **identifier**        | to identify  | **bibilographic item**                                    | + **standard or not**   |


Maybe the reason for this discrepancy is the english ''any form" that can lead to a misinterpretation. 
I suppose the reference version is the english one ?

**Comment by lb42** [comment]
If you look at the source file (on github at https://github.com/TEIC/TEI/tree/dev/P5/Source/Specs/idno.xml) you will see that each descriptive element (`<desc>` or `<gloss>` for example) has a date stamp, indicating when it was last updated. In the case of idno, the English description was last updated in 2010, which is much more recent than the others.  Hence, we can infer that the change in scope of application of this element reflected in the English text, but not the others, is probably the result of a conscious change rather than an accident.  

There is also a long-standing discussion on the TEI issue tracker (see https://github.com/TEIC/Stylesheets/issues/138) as to how readers of the Guidelines should best be warned if a translated text is superannuated. Like many others, this issue has yet to be decided, alas.   

As the OP notes, it is the English text which should be considered definitive, since English is the language in which the Guidelines are written and edited, though not all of those involved are necessarily English speakers.

**Comment by sydb** [comment]
Assigning to @raffazizzi for the italian, @vbigot-juloux for the French, and (as soon as he has access to the repo) @alex-bia for the Spanish.

(BTW, I think @lb42 is completely correct, this is just the natural state after updates have been made but translations have not; however, since OP and @ebeshero have already put work in on this, I think we may as well capitalize on it. :-)

**Comment by martinascholger** [comment]
Updates on Italian, French, Spanish, and Japanese. Closing issue.
