### ISSUE TITLE
FR GH milestones with dates for upcoming releases

### ISSUE THREAD

**Issue by duncdrum** [TEIC/TEI#1995]
As a contributor, it would be handy to see when releases are planned. So maybe we can add dates to the GitHub milestones, so folks can plan around the release schedule more easily

**Comment by bansp** [comment]
+1 to that. The cyclic bursts of Council activity are always a welcome sign, but I have noticed that they usually tend to happen while my hands are tied with running commitments. And even if it weren't so, I'm a bit afraid that these bursts mean that it's too late already to reshuffle your plans and prioritize something TEI-related, because the time to submit is already up and the Council is in the finish phase for the current cycle.
Having a clearly announced schedule, with partial and complete freeze dates, would be helpful indeed. Dated milestones may be a good GitHub-internal way of signalling that. (And no one demands perfect precision and gut spillage when it comes to holding onto a specific release date, I'm sure.)

**Comment by peterstadler** [comment]
Thanks for the heads up. I just added the dates to both the next TEI and Stylesheets milestones. And for the record: we decided on these dates just on Friday.

I think we also need to update our [TCW22](http://teic.github.io/TCW/tcw22.html) to include procedures for adding and closing milestones. Will do …
