### ISSUE TITLE
revamp att.interpLike

### ISSUE THREAD

**Issue by laurentromary** [TEIC/TEI#2012]
This class is one reason for still having a couple of elements (interp interpGrp span spanGrp) just having `@type` and not being members of `att.typed`. Could we make a quick fix:

- delete `@type` from att.interpLike
- make `<interp>`, `<interpGrp>`, `<span>` and `<spanGrp>` members of att.typed

**Comment by bansp** [comment]
Oh, +1 to that, great catch!

**Comment by ebeshero** [comment]
This looks remarkably unproblematic...Can anyone think of problems we might encounter in changing this? @sydb ? @hcayless ?

**Comment by sydb** [comment]
This one was (deliberately) not addressed by #386, as it is not free-standing. But @emylonas and I noted in our work on that ticket that there are 3 classes that should be looked at:

1. att.entryLike
1. att.interpLike (this one)
3. att.textCritical

We did not, at the time, actually look at them, IIRC.

At least in this case, making the change would require either that

- the `@type` of att.interpLike lose its special semantics; OR
- each of the 4 members of att.interpLike override the definition of `@type`; OR
- att.interpLike becomes a member of att.typed (thus getting both `@type` and `@subtype`), and the definition of `@type` gets overridden once, in the definition of att.interpLike.

At the moment I like the last one the best, although I may have missed something.

**Comment by laurentromary** [comment]
I also like proposal 3. above. This is simple and easy to maintain in the long run.

**Comment by ebeshero** [comment]
Council VF2F agrees we should proceed with option 3, namely that: 
`att.interpLike` becomes a member of `att.typed` (thus getting both `@type` and `@subtype`), and the definition of `@type` gets overridden once, in the definition of `att.interpLike`.

**Comment by sydb** [comment]
Sigh. All well and good that we decided on option 3. However, a known [bug](https://github.com/TEIC/Stylesheets/issues/370) in the Stylesheets prevents us from doing that.

For now I have made att.interpLike a member of att.typed, but the local over-riding definition of `@type` in each of the four `<elementSpec>`s for the memberes of att.interpLike (namely, `<interp>`, `<interpGrp>`, `<span>`, and `<spanGrp>`).

I have put comments in all 4 source files explaining what was done. Please see PR #2053.

**Comment by sydb** [comment]
P.S. As per a suggestion from @martindholmes, I tried using XInclude instead. I.e., putting the `<attDef>` for `@type` in the interp.xml file with an `@xml:id` of "type_should_be_from_att.interpLike", and having 
~~~xml
<xi:include href="interp.xml" xpointer="element(type_should_be_from_att.interpLike)"/>
~~~
in interpGrp.xml, span.xml, and spanGrp.xml. The XInclude processor I use (xmllint version “using libxml version 20903”, compiled with (among other things) “XPath XPointer XInclude”) handles that just fine. But apparently whatever the P5 build process is using does not know how to handle that `@xpointer`, because the entirety of the `<interp>` `<elementSpec>` gets stuck into the `<attList>` of `<interpGrp>`.  As you might guess, that does not go over well.

**Comment by martindholmes** [comment]
@sydb I was about to suggest that you could just put an xml:id on the valList and do the XInclude with that, but then the penny dropped. :-) That's another reason I use PIs instead of XInclude.
