### ISSUE TITLE
versionDate attribute needs more constraint

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2036]
@hcayless’ recent fix (commit 97195e21f3ad5200929cc6cc3bdbc2ffd70fb6f6) makes it clear that we should constraint the values of `@versionDate` further than just att.temporal.w3.
My instinct is that the value should have to be an xs:date or an xs:dateTime with a year from 2008 (the year P5 was released) to, say, 2108 or 2208; or perhaps “before the day after tomorrow” (to account for time zones).

**Comment by ebeshero** [comment]
Council VF2F: @sydb and @MegJBrown should come up with a good plan for combining a datatype + Schematron check and we'll discuss further.

**Comment by MegJBrown** [comment]
See pull request #2068

**Comment by peterstadler** [comment]
European subgroup was looking at this issue and the proposed PR and while we like the implementation (very elegant :) we wonder how to prevent confusion about this new datatype `teidata.temporal.working`.
Maybe we should move the class `att.translatable` (from the tei module) to the tagdocs module to make it more explicit that this class "provides attributes used to indicate the status of a translatable portion of an **ODD document**." ([Specs](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.translatable.html))

Especially since `<desc>` is (for some time already) available in various places outside tagdocs elements this would prevent unnecessary misuse of `@versionDate`,  e.g. 
```xml
<notatedMusic>
   <desc versionDate="1476-03-02">The 1476 version of this famous tune</desc>
</notatedMusic>
```

**Comment by sydb** [comment]
Commit 9d8122417 moves att.translatable from ST to TD (directly on dev branch). If Mr. Jenkins approves, this ticket can be closed.

**Comment by sydb** [comment]
No, there are quite a few problems with moving att.translatable from ST to TD. But since @ebeshero has opened another ticket for that, I will discuss the problems there and close this ticket, as the original request (more constraint on `@versionDate`) is fine.
