### ISSUE TITLE
tei-install.sh does not release the Oxygen plugin if only the Stylesheets are released

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#2038]
@sydb and I were checking out the release process ahead of next week's planned Stylesheets hotfix release, and we noticed a slight problem: 

The P5/Utilities/tei-install.sh script only releases the Oxygen plugin if P5 is being released. Lines 39 and 40 of the script do the work of releasing the plugin, and they are only run if P5 is being released. A simple fix would be to duplicate those lines in the Stylesheets case.

**Comment by sydb** [comment]
@martindholmes (and everyone else) —

This is not as simple as we thought yesterday. The complication is that the release of the oXygen stuff is inextricably tied to the release of P5 (i.e., use of --package=TEIP5) because the oXygen stuff comes from the directory that uses the $version of the P5 release, not the $version of the Stylesheets release.

Thus I am leaning (back) towards saying the usual install process should have to call this routine 3 times, once for TEIP5, once for oXygen, and once for Stylesheets. (Yes, I know that we call it 3 times for each package, --install, --makecurrent, and --upload; but we _could_ call it only once with --all, which is equivalent to those 3 in a row. We don’t just to have better understanding of where errors come from. If one were completely certain there would be no errors, one would just use --all, I think.)

Thoughts?

**Comment by martindholmes** [comment]
@sydb One option would be to "release" P5 again anyway; nothing would change, I don't think, but the Oxygen plugin would get updated. But I do agree that we need to be able to release stable versions of the Oxygen plugin too, distinct from both P5 and the Stylesheets, so these three things should be done in separate routines in the file.

**Comment by martindholmes** [comment]
Looks like we were wrong about this; the plugin release takes place as part of step 22 in TCW22, and tei-install.sh has little to do with it. The step in that file to copy the updateSite.oxygen file over should indeed only happen when releasing P5, because its only purpose is to make that file available in the new release folder of P5.
