### ISSUE TITLE
Make file points at non-existent files

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#2070]
With @sydb: The P5 build tries to retrieve the VERSION files from all previous versions of TEI (in the dist-doc.stamp target, which ends up invoking a Stylesheets file Stylesheets/profiles/readme/html/to.xsl), pointing to paths such as:

https://www.tei-c.org/Vault/P5/4.1.0/VERSION

for every single version of P5. However, those files are now in a different location:

https://www.tei-c.org/Vault/P5/4.1.0/doc/tei-p5-doc/VERSION

So the fix needs to be made in the Stylesheets, but this affects only the P5 build (as far as we know).

**Comment by sydb** [comment]
Note to @npcole or anyone else trying to tackle this: seems to me the problematic part of file `Stylesheets/profiles/readme/html/to.xsl` is roughly line 66.

**Comment by sydb** [comment]
@martindholmes (and @npcole) —
Once we fix this (which I believe I am on the verge of doing), how do we test it?

**Comment by martindholmes** [comment]
@sydb I think the only test would be to make a local build of P5 and see if the readmes are retrieved or not.

**Comment by ebeshero** [comment]
@martindholmes @sydb Just did a local build to see if I could test this...and I'm not sure which file to check for the URLs?

**Comment by martindholmes** [comment]
@ebeshero I'm not sure either now. @martinascholger how do you produce the readmes for each of the releases? The ones linked here: 

https://tei-c.org/guidelines/p5/

**Comment by peterstadler** [comment]
@ebeshero , @martindholmes the issue is just about the warning
```
BUILD: Make web pages for release notes
for i in ReleaseNotes/readme*xml; do \
ANT_OPTS="-Xss2m -Xmx752m -Djava.awt.headless=true" ant -q -f /var/jenkins_home/jobs/Stylesheets-dev/lastSuccessful/archive/dist/xml/tei/stylesheet/html/build-to.xml -lib Utilities/lib/saxon10he.jar -Dprofiledir=/var/jenkins_home/jobs/Stylesheets-dev/lastSuccessful/archive/dist/xml/tei/stylesheet/profiles -Dprofile=readme \
-DinputFile=`pwd`/$i -DoutputFile=`pwd`/release/tei-p5-doc/share/doc/tei-p5-doc/`basename $i .xml`.html; \
done
     [echo] XSLT generate HTML files (language ${lang})
Warning: XML resolver not found; external catalogs will be ignored
     [xslt] WARNING: file https://www.tei-c.org/Vault/P5/0.3.1/VERSION cannot be read, so links will probably be broken
```
(see https://jenkins.tei-c.org/job/TEIP5-dev/680/consoleText)

This is produced by those lines: 
https://github.com/TEIC/Stylesheets/blob/dbb661df3470229d978a523bbedf66ce66de24c9/profiles/readme/html/to.xsl#L72-L84
While the following code https://github.com/TEIC/Stylesheets/blob/dbb661df3470229d978a523bbedf66ce66de24c9/profiles/readme/html/to.xsl#L85-L90 for creating the links (for `<gi>` elements) does work.
I wonder if we do need the initial check (when we noticed only now)?

**Comment by martinascholger** [comment]
@martindholmes I only add a TEI file to the ReleaseNotes folder: https://github.com/TEIC/TEI/tree/dev/P5/ReleaseNotes

**Comment by sydb** [comment]
So I spent quite a bit of yesterday on this ticket. It is quite a tangled web of confusion, IMHO. A large part of me wants to say @peterstadler is right, there is just no need for this check. But then again, links from the README files _should_ work, and to ensure that they work they should be tested somehow.

So here is some preliminary research results.

The list of files used as input, and thus the set of version numbers we need deal with, is [1]. It is, of course, ever-expanding, but I am hopeful that in the future it will always expand consistently: the file will be named `readme-Ma.Mi.PaL.xml`, where _Ma_, _Mi_, and _Pa_ (major, minor, patch) are all nonNegativeIntegers, and _L_ is an optional letter, one of 'a', 'α', 'b', or 'β'. I am also hopeful that the path to any future version of the _Guidelines_ will remain the same (`https://www.tei-c.org/Vault/P5/Ma.Mi.Pa/doc/tei-p5-doc/en/html/index.html`) heretofore. 

I tested most of the readme-X.Y.Z.html files, spot-checking the links. For detailed results, see [2].

Suggested plan of action:
1. Change code in Stylesheets/profiles/readme/html/to.xsl so that:
   1. No attempt is made to generate links before release 1.0.0
   1. Look for `<name>`, not `<ident>` for classes[3]
   1. Generate correct absolute URIs for `<gi>` & `<name type=class>`,
      even if filename omits ultimate “.0”
2. Change XML files so that:
   1. References to classes are consistently encoded with `<name>`
   2. Specific bugs noted in [2] are fixed wherever the fix is easy & fast
3. Change build procedure to add a full-blown link-check to HTML output

I do not mind doing 1 & 2, but would need help with 3, as I know almost nothing about link-checkers.


#### Notes
[1] In dir P5/ReleaseNotes/:
~~~bash
readme-0.3.1.xml
readme-0.4.1.xml
readme-0.5.xml
readme-0.6.xml
readme-1.0.1.xml
readme-1.0.xml
readme-1.1.xml
readme-1.2.xml
readme-1.3.xml
readme-1.4.xml
readme-1.5.xml
readme-1.6.xml
readme-1.7.xml
readme-1.8.xml
readme-1.9.1.xml
readme-1.9.xml
readme-2.0.1.xml
readme-2.0.2.xml
readme-2.0.xml
readme-2.1.0.xml
readme-2.2.0.xml
readme-2.3.0.xml
readme-2.4.0.xml
readme-2.5.0.xml
readme-2.6.0.xml
readme-2.7.0.xml
readme-2.8.0.xml
readme-2.9.0.xml
readme-2.9.1.xml
readme-3.0.0.xml
readme-3.1.0.xml
readme-3.2.0.xml
readme-3.3.0.xml
readme-3.4.0.xml
readme-3.5.0.xml
readme-3.6.0.xml
readme-4.0.0.xml
readme-4.1.0.xml
readme-4.2.0.xml
readme-4.2.1.xml
readme-4.2.2.xml
readme-4.3.0.xml
~~~
Note that the README for 0.1.9 is called readme-2005-06.txt, and thus is not processed and we don’t have to check the links.

[2] Detailed results:
- **readme-0.3.1.html**: Every link in the file (except the “Feedback” and maybe “Home” at the bottom) is broken. The GI links are of the form `https://www.tei-c.org/Vault/P5/0.3.1/doc/tei-p5-doc/en/html/ref-GI.html`.
- **readme-0.4.1.html**: Same (except format of links has “0.4.1” instead).
- **readme-0.5.html**: Same (except format of links has “0.5” instead).
- **readme-0.6.html**: Same (except format of links has “0.6” instead). In addition, at least 2 of the links are deliberately to elements that no longer exist (mentioning the elements that were removed).
- **readme-1.0.html**: The one and only link (other than “Home” and “Feedback” at the bottom) is broken; it is not a GI link.
- **readme-1.0.1.html**: All links work (except maybe “Home” at the bottom). The GI links have the same format (`https://www.tei-c.org/Vault/P5/1.0.1/doc/tei-p5-doc/en/html/ref-GI.html`), but in this case it works because there is a page there.
- **readme-1.1.html**: Every link in the file (except the “Feedback” and maybe “Home” at the bottom) is broken. The GI links are of the form `https://www.tei-c.org/Vault/P5/1.1/doc/tei-p5-doc/en/html/ref-GI.html`; when changed to `https://www.tei-c.org/Vault/P5/1.1.0/doc/tei-p5-doc/en/html/ref-GI.html` they work.
- **readme-1.2.html**: Same (except for “1.1” read “1.2”).
- **readme-1.3.html**: Same (except for “1.1” read “1.3”).
- **readme-1.4.html**: Same (except for “1.1” read “1.4”).
- **readme-1.5.html**: Same (except for “1.1” read “1.5”).
- **readme-1.6.html**: Same (except for “1.1” read “1.6”).
- **readme-1.7.html**: Same (except for “1.1” read “1.7”).
- **readme-1.8.html**: Same (except for “1.1” read “1.8”).
- **readme-1.9.html**: Same (except for “1.1” read “1.9”). Interestingly the 2 links to Sourceforge still work.
- **readme-1.9.1.html**: No links (other than “Home” and “Feedback” at the bottom).
- **readme-2.0.html**: Link to Genetic SIG works, but the link to the Music SIG is horribly wrong because it is missing the “https://” part. GI links, which have the same format as other “X.Y” cases are broken, and work when converted to “2.0.0”.
- **readme-2.0.1.html**: Essentially a copy of the 2.0 notes. Same problem with Music SIG link. GI links work (because they are already in “2.0.1” form).
- **readme-2.0.2.html**: Same, but also the only reference to a class does not have a `@type` attribute in the source XML, so is not a link here.
- **readme-2.1.0.html**: There are 2 URLs in the 3rd paragraph of the XML that are not encoded, but would be broken if they were. There is 1 URL in the last paragraph that is not encoded but that would work (because of a re-direct) if it were. The GI links (and a class link) work.
- **readme-2.2.0.html**: The direct links to Sourceforge tickets seem to work, but to the Sourceforge search is broken. GIs and class names are not encoded in the XML, and thus are not links.
- **readme-2.3.0.html**: All links are encoded as `<ref>`, not `<gi>` or `<ident>`. Those to the _Guidelines 2.3.0_ work, those to PURLs to Sourceforge do not.
- **readme-2.4.0.html**: Links generated from `<gi>` and `<ident>` seem to work; vast majority of Sourceforge links, too.
- **readme-2.5.0.html**: Mostly everything works, but really interesting bug that repeats “closed bugs and” near end, possibly due to space in `@target`.
- **readme-2.6.0.html**: Classes are not encoded, so are not linked; GIs are, and work; most other links work, but link to Chapter 2.2.4 fails.
- **readme-2.7.0.html**: Classes are encoded as `<name>`, not `<ident>`, and thus are not links; GIs work; other links work.
- **readme-2.8.0.html**: Same.
- **readme-2.9.0.html**: Link to lists of closed bugs & closed FRs (on gitHub) fail. Other links (GIs, classes, issues) work.
- **readme-2.9.1.html**: Same.
- **readme-3.0.0.html**: The link to “this release” is relative, and thus fails my test but works on website; others seem to work
- **readme-3.1.0.html**: All links checked work. One of the (many) `<att>`s is encoded inside a `<ref>`, and its link works.
- **readme-3.2.0.html**: References to the prose are not links, but all the links that are present seem to work except the link to OxGarage.
- **readme-3.3.0.html**: 
- **readme-3.4.0.html**: 
- **readme-3.5.0.html**: 
- **readme-3.6.0.html**: 
- **readme-4.0.0.html**: 
- **readme-4.1.0.html**: 
- **readme-4.2.0.html**: 
- **readme-4.2.1.html**: 
- **readme-4.2.2.html**: Link to FR#2128 is to wrong repo. All others spot-checked (including OxGarage) work.
- **readme-4.3.0.html**: 

[3] Or vice-versa. I prefer `<name>` because we are, it seems to me, using the name of the class to refer to it. Same way we use the name of an element or the name of an attribute. (Heck, it is even called an “attribute name” in the XML Spec.) Yes, the name also appears on the `@ident` attribute of its definition, but we are not referring to it by its identifier, which would include either release-specific information or the commit number and the XPath to the `<classSec>` or some such.
