### ISSUE TITLE
change the content model of exemplum

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#2072]
This is a continuation from #1933 : Now that we have experimented with outputting all exempla from tagdocs (agnostic of language) at https://bauman.zapto.org/~syd/temp/4TEICouncil/html_GLs_all_eg_en/  , we want to try to group examples that are duplicates of each other but described in different languages. We're opening this ticket to work on changing the content model of `<exemplum>` to permit this.

**Comment by jamescummings** [comment]
Great idea.  2 output thoughts:

1. Should there be a language identifier supplied in order to indicate what language the example is in (for all languages)
2. Should there be a way to toggle or express interest in seeing examples in all languages vs the current language? (And if sophisticated this could be sticky via a cookie so a user selects once and then all tagdocs pages display all examples unless they change their mind.)

**Comment by ebeshero** [comment]
Closing because this ticket is outdated because Council decided to introduce an `<exemplumGrp>` element on ticket #1933.

**Comment by ebeshero** [comment]
Closing because this ticket is outdated because Council decided to introduce an `<exemplumGrp>` element on ticket #1933, rather than try to allow multiple `<egXML>` in a single `<exemplum>`.
