### ISSUE TITLE
unused files?

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2080]
The file P5/p5sch.xsl does not appear to be used at all. I have searched both the entire TEI and Stylesheets repos. The only place the string “p5sch.xsl” is found is in the P5/Makefile, which copies it into release/tei-p5-source/share/xml/tei/odd/.

It has not been changed since @sebastianrahtz checked it in almost 16 years ago. I am not at all sure what it does.

Unless someone can propose a reasonable reason to keep it, I think we just try deleting it.

**Comment by sydb** [comment]
Roughly the same goes for P5/Query/datatypes.xml and P5/Test/xml.xsd.w3c. The former is not mentioned at all; the latter is mentioned once in a change log file. The entry says that @sebastianrahtz added it (a “clean copy of xml.xsd from W3C”) back on Sun 27 Nov 05.

**Comment by sydb** [comment]
Add P5/fasc-head.xml to the list; only mentioned, in a Changelog, as being moved.

**Comment by lb42** [comment]
Well, p5sch.xsl appears to be generating an additional schematron constraint for a (nonexistent) @src attribute on `<choice>` I suspect it may be a "proof of concept" example showing how to generate such constraints in xslt. 
By the looks of it, the "fasc-head.xml" file was used to generate SGML versions of P5 chapters  ("fascicules"): no point keeping it since it references files (e.g. "external-entities.dtd") long since gone to the bit bucket in the sky.
The other two files  predate current methods of controlling datatypes and are equally of historical interest only.

**Comment by sydb** [comment]
To be re-opened if Mr. Jenkins objects.

**Comment by sydb** [comment]
Thanks, @lb42 !
