### ISSUE TITLE
moderately problematic issues in SATS

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2084]
Re: section 16.2.4, TEI XPointer Schemes

- [x] Portions of the various discussions are written as if these XPointer schemes were functions, i.e. as if they _returned_ or _captured_ a value. They don’t, they just point at things. (Yes, a program processing one of these will likely return to its caller whatever is pointed at, but it is still just a pointer.)
- [x] Shouldn’t the example (SATSXP-ex) be in 16.2.4.1, not 16.2.4.2? (HC: no)
- [x] The REGEX parameter to the `match()` scheme is described as necessarily inside straight single quotes. But in general, in XML, I can use straight single quotes to delimit the attribute value itself. If that is the case, how does one delimit the REGEX? (HC: use `&apos;`, as one does. I don't especially want to add any documentation to that effect)
- [x] The 1st sentence of "SATSXP" incorrectly says “locates a node”; an XPath locates 0 or more nodes.
- [x] The reference to _XQuery 1.0 and XPath 2.0 Data Model (Second Edition)_ in the definitions of “Node” and then “Sequence” should probably be updated to _XQuery and XPath Data Model 3.0_.
- [x] In “A TEI Pointer that referenced the "normalized" form in …”, the word “normalized” should not be in straight quotes. I am not sure it should be in anything at all. I also wonder if it should be the word “regularized” instead, or for that matter read “A TEI Pointer that referenced the &lt;reg> element in …”. Also should this be in past tense? Why not “A TEI Pointer that references the &lt;reg> element in …”?
- [x] `For example, a range() might select text beginning before an <gi>app</gi>, encompassing the content of a single <gi>rdg</gi> and continuing after the <gi>app</gi>.` would be better as something like `For example, a <name type="xpscheme">range()</rs> might select text from somewhere before an <gi>app</gi>, include only the content of one of several <gi>rdg</gi> children of the <gi>app</gi>, to somewhere after the <gi>app</gi>.` (HC: this seems less clear to me, but also, if you hate it, change it)
- [x] In para 1 of 16.2.4.6 ("SATSRN") we are told “A range() locates a (possibly non-contiguous) sequence beginning at the first POINTER parameter and ending at the last.” Sequence of what? Some of the possible POINTERs return a sequence of nodes, others return points. Seems to me the prose here has to explain what is pointed at when a pair of POINTERs is “point, point” (probably a string), “node*, point”, “node*, point”, and “node*, node*” (probably a sequence of nodes). (HC: Sequence is defined in 16.2.4.1)
- [x] In “If a sequence addressed by a range pointer …” the “range pointer” seems ambiguous to me: does that mean a POINTER parameter to a range() scheme or a range() scheme used as a POINTER parameter (or something else)?
- [x] Either way, the whole sentence (“If a sequence addressed by a range pointer overlaps, but does not wholly contain, an element (i.e. it contains only the start but not the end tag or vice-versa), then that element is not part of the sequence.”) is confusing at best. Leaving aside that I cannot tell if this sentence is talking about the sequence addressed by a pair of POINTERs or the (possibly discontiguous) sequence addressed by an entire range(), what does it mean for an element not to be part of the sequence addressed? Technically I suspect that should mean that the entire element (expressed in serialized XML as a start tag, possibly attributes, possibly content (which may include other elements, PIs, comments, and text nodes), and an end tag) is not in the sequence. But it might mean that while the XML structure is lost, the character string content (either child content or descendant content) that is inside the range is retained. That is, does `#range( string-index( xpath( //supplied[1] ), 1 ), string-index( xpath( //reg[1] ), 2 ) )` select “i non ha” or just “ non ” or something else? I see that the 2nd example following implies that the contents of an element partially included are retained for the returned sequence.
- [x] The “… the whole of line 4 from the …” should pretty clearly be the whole of line 3, no?
- [x] `#range(right(//lb[@n='3']),string-index(//lb[@n='3'],15)) indicates the sequence <unclear>s</unclear>emp<unclear>er</unclear> in mente.`: We should say _what_ is pointed at, no? (Just to be clear, that is a sequence of element(), text(), element(), text(), right?)
- [x] In the discussion of string-range() we say “[a]s with range(), the addressed sequence may contain text nodes and/or elements”. We don’t actually explicitly say that in the discussion of range(). (HC: 🤷🏻‍♂️)
- [x] I believe that comments and PIs are invisible to string-range() much the way tags are are. We should say so. (HC: I don't understand what 'invisible' means. But to the extent that the text stream is defined as the concatenation of text nodes in a document, then no. But if your XPath referenced a comment, I suppose the text inside could be addressed,)
- [x] In the discussion of match() “If omitted, the first match in the text stream will be used.” should be something like “If omitted, the match() refers to the first match in the text stream.”

**Comment by martindholmes** [comment]
One more item: based on my own misunderstanding and others', discussed today on TEI-L, I believe the XPath section should explicitly state that the context of an xpath pointer is the document, not the node hosting the pointer.

**Comment by Arithmeticus** [comment]
I'd like to add to the awesome list drawn up by @sydb  

The entire section lacks discussion of what implementations are assumed for an XPATH. I would have expected at least a mention of conformance expected for different implementations / processors. (If I want to write a parser for TEI Pointers in XSLT, how will I know if my algorithm meets conformance, esp. if I rely upon <xsl:evaluate>?)

Why not allow the element hosting the attribute to be the context node, and support relative XPaths if one wishes? Isn't that the declarative way? We all know how inefficient // is. If TEI XPATHs must take the document node as the context, we should instill best practices and avoid the // in the examples.

At https://tei-c.org/release/doc/tei-p5-doc/de/html/SA.html#SATSR the text... 
the pointer #left(//gap[1]) indicates the point between the first lb and the first gap in the example above.
...has problems. The first XPath expression might match nodes not seen in the example. And in the example there are many points between the first lb and the fist gap, b/c they're not next siblings.

In TEI don't IDREFS have a # prepended? Shouldn't #left(line1) be #left(#line1)? (Otherwise, one is saying locate a root element named <tei:line1>)

At https://tei-c.org/release/doc/tei-p5-doc/de/html/SA.html#SATSMA the text...
 "locates a sequence based on matching the REGEX parameter against a text stream relative to the reference node"
should probably be something like
 "returns from the text stream immediately following the reference node the Nth substring (where N = INDEX) that the REGEX parameter matches"
or
 "returns from the sequence immediately following the reference node the Nth sequence (where N = INDEX) whose string value the REGEX parameter matches"
or
 "returns the sequence that corresponds to the Nth substring (where N = INDEX) from the text stream immediately following the reference node that the REGEX parameter matches"

After all, a match on a text stream, being a concatenation (taking "concatenation" in its XPath meaning as entailing a single string), is not a candidate for a sequence, right? Or have I misread the definitions? Maybe "A Text Stream is the concatenation of the text nodes in a document..." should read "A Text Stream is the sequence of the text nodes in a document..."?

Related, if a text stream has by definition no elements then how can the <unclear> in the first example be returned? The second example implies that the first example does capture the unclear. And is "capture" the right verb? It's ambiguous enough to imply extract/return, not point/refer.

Good luck, Jedi Council.

**Comment by hcayless** [comment]
@Arithmeticus some of these issues are simply due to the age of the section, and should be updated, though I should note that the Guidelines tend to steer clear of discussions of implementation, for a variety of good reasons.

The relative XPath issue is an interesting one, but we are somewhat restricted by the definition of datatype of the attributes involved ([teidata.pointer](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-teidata.pointer.html)). Because they are xs:anyURI, they can't be relative to a particular part of the document, only to the document itself. So changing that would mean a pretty fundamental re-thinking. 

An IDREF can't be `#<ID>`. '#' isn't a legal ID character. The '#' is prepended because it's a URI fragment identifier. The lexical space of IDREF is the same as ID.

"Returns" didn't seem appropriate because these are not functions.

"Text stream" here is a theoretical concept, but it means the text content of a document treated as though it were a single string (hence "concatenated"). The stream itself doesn't know about nodes, but a node can correspond to a string index, so you can say "start at a particular element and read the text stream from there."

No doubt much of this can be explained better :-).

**Comment by hcayless** [comment]
Closing after review.
