### ISSUE TITLE
re-defining Node in SATS?

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2085]
Re: section 16.2.4, TEI XPointer Schemes

- [x] The definition of “Node” says that only “Text Nodes, Element Nodes, and Attribute nodes” are of interest. Besides the inconsistent capitalization (which might match the spec, idunno), why are we not potentially interested in other nodes? In particular, I often find it useful to address a (subset of) a particular comment node: `/comment()[ matches( ., '\p{Sc}Id:\$')]` (because `#xpath( tokenize( /comment()[ matches( ., '\p{Sc}Id:\$') ] )[3]` is the Subversion revision number of my file, although to be fair, I have never addressed it using TEI pointer schemes, only using XPath in Schematron, in XSLT, or on the commandline. BTW, the use of “\p{Sc}” instead of ‘\$’ is only necessary if you are writing the XPath in a file that is under Subversion control, lest Subversion perform keyword substitution on the Xpath :-).
- [x] The last sentence of the definition of “Node” (“XPath expressions that address attribute nodes are only advisable in the xpath() scheme.” is ambiguous, even to me. Does it mean that XPath expressions that address a sequence that **(** includes an attribute node **|** may include an attribute node **|** consists of nothing but attribute nodes **)** are **(** inadvisable in schemes other than xpath() **|** the only thing advised in xpath() **)**?

**Comment by hcayless** [comment]
I didn't want to address comments because it seemed more trouble than it was worth, but I suppose if you want them, we can include them.

You wouldn't want to address an attribute node in most cases because they don't have locations in the same way elements do. `left(<some attribute>)` doesn't have any obvious meaning, because attributes lack intrinsic order. So it's fine to point at an attribute node using `xpath()`, but mostly not otherwise (I suppose you could have a `string-range()` on the contents of an attribute).

**Comment by hcayless** [comment]
I've rewritten the language about it not being sensible to reference attribute nodes in schemes other than `xpath()` in a32d80f7bc51374ede677716427ad01114001a68.

**Comment by raffazizzi** [comment]
F2F@Guelph subgroup asks: @hcayless does https://github.com/TEIC/TEI/commit/a32d80f7bc51374ede677716427ad01114001a68 sufficiently address this ticket to close it?
