### ISSUE TITLE
Inconsistent prohibition of the use of <p> directly under <div1>

### ISSUE THREAD

**Issue by wyoichiro1125** [TEIC/TEI#2089]
When using \<div1\>, \<div2\>, and \<p\> tags at the same time, there seems to be inconsistency where one \<p\> is allowed and another \<p\> is not, even though they exist in the same hierarchy.

```
 <text>
      <body>
         <div1>
            <p>para1</p>
            <div2><p> ... </p></div2>
            <p>para2</p>
         </div1>
      </body>
 </text>
```

Both of these \<p\>s should be directly under \<div1\>, but only the former \<p\>para1 \</p\> is allowed to be used, while the latter \<p\>para2 \</p\> is not. As long as the former \<p\> is allowed to be used, I would like the former \<p\> is allowed to be used as well. Otherwise, if there would be an explicit explanation for the reason for the restriction, please let me know the pointer.

**Comment by gimsieke** [comment]
This is a widespread (not only in the TEI, but also in DocBook, JATS, and many other vocabularies) content model in which no paragraphs or other block-like items are allowed after a section has ended. 
It is called “[tessellation](https://wiki.tei-c.org/index.php/TEI-Council-FAQ#What_does_it_mean_to_say_that_elements_tessellate.3F)” or “end-to-end segmentation”.
The historical background for this, I think, is that the beginning of a hierarchic section is often well detectable because of a heading, while there may be optical ambiguities in the rendered text whether a trailing paragraph, in your example `<p>para2</p>`, belongs to `div1` or to `div2`. 
Other vocabularies, such as JATS that has `boxed-text`, offer dedicated elements for interspersed content in the middle of a section. In TEI, there is [`floatingText`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-floatingText.html) that is a bit more heavy-weight:
```xml
<text>
  <body>
    <div1>
      <p>para1</p>
      <floatingText>
        <body>
          <div>
            <p> ... </p>
          </div>
        </body>
      </floatingText>
      <p>para2</p>
    </div1>
  </body>
</text>
```

**Comment by sydb** [comment]
So since @wyoichiro1125 has not responded, we (Council SVF2F subgroup) are presuming @gimsieke’s response is sufficient. If it is not, @wyoichiro1125, please bring up the issue on [TEI-L](https://listserv.brown.edu/cgi-bin/wa?A0=TEI-L) or in a [GitHub discussion](https://github.com/TEIC/TEI/discussions).
