### ISSUE TITLE
bookmark links in examples pages have no mouse-over text 

### ISSUE THREAD

**Issue by stuartyeates** [TEIC/TEI#2137]
On pages such as https://tei-c.org/release/doc/tei-p5-doc/en/html/examples-p.html the bookmark link has no alt text and the unicode character used is obscure and non-obvious on the platforms that I have access to.

Also the name of the link is bookmarklink and the character is an anchor, but there are two perfectly good bookmark unicode characters: "BOOKMARK TABS" and "BOOKMARK"

**Comment by ebeshero** [comment]
@stuartyeates Thanks for this. The symbol we've been using is an anchor, which has some visual association with the element on which it's placed:`<a class="bookmarklink">` (the HTML anchor element). We should discuss which is best: the ship's anchor ( ⚓ ) or the bookmark (🔖 ) or the bookmark tabs (📑).  As for alt text, that may be a little more difficult--a good discussion for our Stylesheets group!

**Comment by lb42** [comment]
Also, the "bibliography" pop-up links still don't work for non-English examples

**Comment by martindholmes** [comment]
@lb42 Good point on the bibliography links; I didn't know that. It should be relatively easy to fix. The links in the English version of the Guidelines always point to the English bibliography page, but there are examples in the specs pages which are only reffed in the French bibliography. This is an example:

https://www.tei-c.org/release/doc/tei-p5-doc/en/html/examples-title.html#index-egXML-d39e47171

The example does not appear in the main spec page in the English Guidelines, so its source doesn't appear in the English bibliography, but it is harvested into the complete examples page in the English Guidelines, and from there the link fails, because it's pointing to the English bibliography. But if you're reading the French spec page and you click on Bibliography, it works:

https://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-title.html

This needs its own ticket, since it's not related to the icon/alt text issue.

**Comment by martindholmes** [comment]
Moved the non-English bibliography links issue to a new issue #2138.

**Comment by martinascholger** [comment]
Council F2F: mouseover of anchors in examples pending.

**Comment by HelenaSabel** [comment]
Stylesheets Group meeting on 2023-07-27 added the missing `@title` attribute in examples. See commit [1e9090f](https://github.com/TEIC/Stylesheets/commit/1e9090f) ([Stylesheets repo](https://github.com/TEIC/Stylesheets))
