### ISSUE TITLE
am should allow lb

### ISSUE THREAD

**Issue by sarcanon** [TEIC/TEI#2164]
It is accepted practice to use `<am>` to mark-up Latin abbreviations such as DDDNNN or AVGGG, e.g. 

```
<w lemma="dominus"><expan><abbr>D<am>DD</am></abbr><ex>ominorum</ex></expan></w> <w lemma="noster"><expan><abbr>N<am>NN</am></abbr><ex>ostrorum</ex></expan></w>

<w lemma="Augustus"><expan><abbr>Aug<am>ggg</am></abbr><ex>ustorum</ex></expan></w>
```

Sometimes these abbreviations occur with intervening line breaks, e.g.,

```
DD
DN
NN

```
or

```
AVGG
G

```
However, for some reason, `<am>` does not support spanning line breaks. I propose that this be changed.

Thank you.

**Comment by sydb** [comment]
Indeed, the content model for `<am>` is pretty simplistic:
~~~
( text | model.gLike | model.pPart.transcriptional )*
~~~
The fact that it does not include model.global immediately makes me wonder if this was just an oversight, or did the designers of `<am>` think there was a reason to discourage or avoid having `<lb>`, `<note>`, or `<gap>` _inside_ an abbreviation marker?

**Comment by jamescummings** [comment]
Personally I would never mark up the examples you have above as you have done so -- the idea of embedding an `<abbr>` inside an `<expan>` is anathema to me. The Guidelines do not imagine or ever exemplify this usage, stating that " content of the abbr element should usually include the whole of the abbreviated word, while the expan element should include the whole of its expansion". Alas, I understand some people (e.g. EpiDoc) dislike the redundancy of properly using separate `<abbr>` and `<expan>` inside a `<choice>` element because it causes the repeated text, however it makes it much more human readable when dealing with multiple abbreviations in a single word, IMHO.  

My recollection is that since `<am>` is viewed as just storing the individual marker it was felt unlikely that an individual abbreviation marker character might span lines. If part of an abbreviation marker is on a separate line then the line break could be put between the `<am>` elements used to record each of the abbreviation markers. The fact that they are on separate lines, to me, makes them separate markers even if as a whole they are replaced by the same text 'ustorum'.  

So your: 

```
AVGG 
G
```
I would markup as 

```xml

<w lemma="Augustus">
  <choice>
    <abbr>AUG<am>G</am><lb/><am>G</am></abbr>
    <expan type="normalised">Aug<ex>ustorum</ex></expan>
  </choice>
</w>
```  
But I recognise opinions on this might differ. There was definitely a desire to keep `<am>` and `<ex>` as unpolluted as possible.

**Comment by lb42** [comment]
👍

**Comment by hcayless** [comment]
I think @jamescummings is basically right about the placement of `<lb/>` inside `<am>`, though I don't agree with his argument for using `<choice>`, nor his hyperbole :-). The question is whether the line beginning is _part_ of the abbreviation marker or simply occurs in the midst of the characters which signal an abbreviation. It seems to me that the latter is what's happening here, so the correct markup for 
```
AUGG
G
```
would be 
```xml
<w lemma="Augustus"><expan><abbr>Aug<am>g</am><lb break="no"/><am>g</am></abbr><ex>ustorum</ex></expan></w>
```
The reason being that if you were to drop the abbreviation marker (in creating an alternative display, for example), you would lose the fact of the line beginning in the middle of the word. The line beginning isn't itself an abbreviation marker, it just happens to occur in the midst of one. The clincher for me is that I don't think you'd put the `<lb/>` inside the `<am>` if it occurred adjacent to it. You'd do
```xml
<w lemma="Augustus"><expan><abbr>Aug<lb break="no"/><am>ggg</am></abbr><ex>ustorum</ex></expan></w>
```
rather than
```xml
<w lemma="Augustus"><expan><abbr>Aug<am><lb break="no"/>ggg</am></abbr><ex>ustorum</ex></expan></w>
```
I think to get `<lb/>` included in the content model of `<am>` you'd need an example where it really was an abbreviation marker. That seems not completely impossible, but at the same time would tend to work against the usual function of abbreviations—saving space.
