### ISSUE TITLE
Problem to download DTD

### ISSUE THREAD

**Issue by Papofobico** [TEIC/TEI#2166]
I tried to download tei_all.dtd but when I open this link https://tei-c.org/Vault/P4/Lite/DTD/ i've found nothing, can you help me

**Comment by martindholmes** [comment]
It seems you're looking for a P4 DTD, rather than the current P5. Is that right? If you want the current P5 tei_all.dtd, it's here:

https://tei-c.org/Vault/P5/current/xml/tei/custom/schema/dtd/tei_all.dtd

If you want P4, then it's a modular system, and all the files are here:

https://tei-c.org/Vault/P4/xml/schema/dtd/

**Comment by sydb** [comment]
@Papofobico — find what you were looking for?

**Comment by Papofobico** [comment]
Yes, thank you so much

**Comment by martindholmes** [comment]
Closing, since this seems resolved.
