### ISSUE TITLE
detail vs. sub-headings?

### ISSUE THREAD

**Issue by nakagawanatuko** [TEIC/TEI#2170]
I am translating the TEI document (Chapter 4) into Japanese and got a question on 4.2.1.
In explaining types of headings in newspapers, the text says "for example as ‘main’ headings, or ‘detail’ headings". In the coding example right below the text, however, 'main' and 'sub' headings are used.
I am wondering whether there is a difference between 'detail' and 'sub' headings.
This affects my translation because if 'main' and 'detail' headings are relevant in the coding example, I will leave the 'main' and 'detail' as it is in English; otherwise I will translate them into Japanese.

Thanks in advance.
Best,

-Natsuko

**Comment by sydb** [comment]
# Inappropriate Answer

## Sigh…
_[I posted the lovely response below thinking @nakagawanatuko was asking about how to encode, not how to translate. (I had missed the first sentence.) Sorry. Thanks to @ebeshero for quickly pointing out my mistake.]_

## previous post itself
I think both "detail" and "sub" (short for “subordinate”) are just suggestions for categorization of headings in _any_ kind of document, including newspapers. I do not have ready access to _[NYTM](https://en.wikipedia.org/wiki/The_New_York_Times_Manual_of_Style_and_Usage)_ (which, of course, is an English, not Japanese guide) or [other newspaper style guide](https://en.wikipedia.org/wiki/List_of_style_guides#For_journalism_2), but suspect those would be the best places to look for the “proper” categorization of headlines.

That said, I do not really think the actual value used should make a significant semantic difference; rather, it is how those values are _defined_ in your local ODD that matters. That is,
~~~xml
  <valItem ident="sub">
    <gloss xml:lang="en">subordinate</gloss>
    <desc xml:lang="en">Any kind of heading other than the main heading</desc>
  </valItem>
~~~ 
is essentially the same as either
~~~xml
  <valItem ident="detail">
    <desc xml:lang="en">Any kind of heading other than the main heading</desc>
  </valItem>
~~~
or
~~~xml
  <valItem ident="委細">
    <desc xml:lang="ja">メインの見出し以外のあらゆる種類の見出し</desc>
  </valItem>
~~~
or
~~~xml
  <valItem ident="委細">
    <gloss xml:lang="en">detail</gloss>
    <desc xml:lang="ja">メインの見出し以外のあらゆる種類の見出し</desc>
    <desc xml:lang="en">Any kind of heading other than the main heading</desc>
  </valItem>
~~~
(presuming Google Translate did a good job — my Japanese is limited to counting and a few nouns, and only in romanized text, not in kanji or kana), and is very different from 
~~~xml
  <attDef ident="type" mode="replace" usage="opt">
    <datatype minOccurs="1" maxOccurs="1">
      <dataRef key="teidata.enumerated"/>
    </datatype>
    <valList type="closed">
      <valItem ident="alt">
        <gloss xml:lang="en">alternate</gloss>
        <desc xml:lang="en">alternate heading, preceded by a conjunction</desc>
      </valItem>
      <valItem ident="sub">
        <gloss xml:lang="en">subordinate</gloss>
        <desc xml:lang="en">heading that is separated from the main heading with a colon</desc>
      </valItem>
      <valItem ident="det">
        <gloss xml:lang="en">detail</gloss>
        <desc xml:lang="en">secondary heading that repeats the information of the main heading more precisely</desc>
      </valItem>
    </valList>
    <remarks>
      <p>If it is appropriate, use <val>det</val> whether preceded by
      colon or conjunction or both. Use <val>alt</val> only when there
      is a colon but not a conjunction.</p>
    </remarks>
  </attDef>
~~~
(BTW, those are not suggestions for actual encoding, I just made those up off the top of my head to make a point — it is probably not a good idea to differentiate headings based on syntax like that, at least not in the early modern period. :-)

All that said, as long as you are absolutely consistent about the application of the value "sub" or "detail" (or Japanese equivalent), this is a very low-stakes decision, because it is trivial to change from one to the other later. E.g., `xmlstarlet ed --ps -N t=http://www.tei-c.org/ns/1.0 --update "//t:head/@type[.='sub']" --value 'detail' IN.xml > ERASEME.xml` does it as a shell 1-liner. Any decent XML editor (including, of course, OXygen) can do this, too.

**Comment by sydb** [comment]
My instinct is that “main” and “detail” as they appear in the main text (encoded with `<soCalled>`) are descriptive words that should be translated into Japanese, rather than suggested attribute values (which should be encoded with `<val>`) which should be left as pseudo-English.
Whether “detail” should be translated into something closer to “subordinate” is an interesting question.

**Comment by nakagawanatuko** [comment]
Thank you for your answer. I will translate "main" and "detailed" headings into some words reminiscent of "main" and "sub" in codings. I was wondering whether they might be technical terms for newspapers or TEI or something else.

Thanks again.

**Comment by sydb** [comment]
OK. Does that mean we can close this issue?

**Comment by nakagawanatuko** [comment]
Yes please, thanks!

**Comment by sydb** [comment]
😀
