### ISSUE TITLE
content model of line

### ISSUE THREAD

**Issue by HelenaSabel** [TEIC/TEI#2171]
The element `<line>` doesn’t allow `<subst>`  elements. It does allow `<substJoin>` so at the moment it would be possible to semantically link a series of `<del>` and `<add>` elements anyway, but I wonder if the content model of `<line>` shouldn’t include something equivalent to `model.pPart.editorial`.

**Comment by lb42** [comment]
This is up there with "why can't we have global @type"  on the tei faq. The answer is because the workgroup wanted to avoid introducing interpretive tags. Deciding that this is a substitution is a editorial judgment and hence is not appropriate for physical description.

**Comment by HelenaSabel** [comment]
I think I would make a difference between editorial intervention and editorial interpretation. I agree that in a physical description there is little place for editorial interventions, but I am not sure if the same can be said for editorial interpretations. The identification of the different hands, for example, is a highly interpretative endeavor. The editors use physical cues to encode their hypotheses, and I think we can agree that the use of `@hand` is very pertinent in any diplomatic transcription (even in one that focuses on the description of the layout and thus uses `<line>`). In cases in which an addition is physically linked to a deletion (e.g. a fragment in a parchment written over scraped characters), I don’t see why the use of `<subst>` would not be recommendable.

**Comment by lb42** [comment]
It's not a question of distinguishing intervention from interpretation, but  of disallowing the encoding of interpretations which might be construed as assuming some particular reading of the physical evidence rather than simply recording that evidence.  The work group, or some of its more vocal members, definitely felt that encodings such as "correction" or "substitution" went beyond simply recording the presence of (in your example) a passage scraped out, and a passage added at a later date,. Likewise, the *identification* of hands (as in "this is the hand of Shakespeare") is not the same as the *distinguishing* of hands (this hand uses a particular combination of letter forms, or a particular colour of ink: this passage seems to have been written by someone other than the person who wrote this other passage) . If I understand them correctly, the proponents of genetic edition are all about the latter and eschew the former.

I am simply bearing witness to the historical arguments about this issue, of course; I have no particular opinion, and no editorial qualifications, other than a disinclination to revisit old disagreements!

**Comment by HelenaSabel** [comment]
Thank you for providing this perspective, @lb42 . I am also inclined to not revisit old disagreements, so I will close the ticket (although I wonder if a ticket should be open to make sure that the constraints of the use of `<substJoin>` and `<subst>` are consistent because one shouldn’t be allowed when the other isn’t).

**Comment by lb42** [comment]
I quite agree that allowing substJoin but not subst is inconsistent. A corrigible error, imho.
