### ISSUE TITLE
both equally valid ways of encoding the same argument?

### ISSUE THREAD

**Issue by knagasaki** [TEIC/TEI#2182]
During our translation work of the chapter 4, we faced a question in **4.2.3 Arguments, Epigraphs, and Postscripts.**

The division notes "The following are thus both equally valid ways of encoding the same argument". However, it is a little ambiguous for us to regards the following two examples as "equally valid ways". The first example uses `<p>` and the second uses `<list>`. Both are valid as TEI, but it seems to me that the sentence needs a little more words to explain the meaning of "equally".

**Comment by hcayless** [comment]
I think by "valid" here, the writer meant "correct". So you could do it either way and one is not obviously better than the other.

**Comment by knagasaki** [comment]
Dear Hugh, thank you for your comment. In that meaning, "equally" would be a little difficult to be interpreted. The word is necessary for the meaning? Otherwise, could a phrase be added like: ", while their structures are different"?

**Comment by hcayless** [comment]
I understand "equally" to mean that there's no reason to prefer one method over the other. It's not really adding much to the meaning and it's a curious way to express it since the previous sentence strongly implies lists are better. For your purposes, I think I'd just ignore the "equally" if it makes the sentence harder to translate. You won't be losing anything important.

**Comment by sydb** [comment]
Can this be closed, @knagasaki ?

**Comment by knagasaki** [comment]
Yes, thanks.
