### ISSUE TITLE
xs:anyURI permits spaces, so we need teidata.anyURI to replace it

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#2185]
@sydb's work on TCW32 and subsequent testing has revealed a weird anomaly that affects all the TEI attributes that permit multiple space-separated xs:anyURI values: Although [RFC 2396](https://www.ietf.org/rfc/rfc2396.txt) specifies that spaces are excluded from URIs, the W3C XML Schema Part 2 spec [says that](https://www.w3.org/TR/xmlschema-2/#anyURI) they're allowed, although discouraged. That means that when we try to constrain an attribute value to a single xs:anyURI, the constraint fails because multiple values are valid as a single URI.

The Stylesheets Working Group suggests that we substitute our own datatype which does not permit unencoded spaces.

**Comment by sydb** [comment]
Problem, as @martindholmes says above, is that a processor cannot differentiate between an xs:anyURI that happens to contain a space and two xs:anyURIs separated by a space.

But the solution, it turns out, is probably simpler than creating a new datatype (which I had suggested, so not ragging on Martin, here). Probably just changing the definition of teidata.pointer to
~~~xml
          <content>
            <dataRef restriction="\S+" name="anyURI"/>
          </content>
~~~
would do the trick for most things. (The `@property` of `<citeData>` uses xs:anyURI directly — incorrectly, IMHO — so it would have to be fixed. And we would have to decide what to do with teidata.namespace — probably just do the same thing. As for teidata.namespaceOrName I am not sure what we would do, as it already uses `<dataFacet>`; maybe they can be merged.)

**Comment by sydb** [comment]
Note-to-self: PR #2204 should fix this. (Isn’t GitHub supposed to automatically link these two?)

**Comment by sydb** [comment]
Please see [comment about problem](https://github.com/TEIC/TEI/pull/2204#issuecomment-981709846) (with spaces in the fragment identifier portion, in this case in arguments passed to an XPointer scheme; same could occur in query portion of URI, though) on the PR.

**Comment by sydb** [comment]
Note also that although RFC 2396 forbids spaces, that spec is obsoleted by [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#appendix-A).
