### ISSUE TITLE
Information about Richard Crashaw in the guideline (Ch4)

### ISSUE THREAD

**Issue by nakagawanatuko** [TEIC/TEI#2203]
I and other members are translating the TEI guideline (Ch4) into Japanese and got a question.
In 4.3.1., you can find the following description "three collections published in Crashaw's lifetime". According to Wikipedia, Crashaw is dead in 1649, while the book entitled "Carmen deo Nostro" published in **1652** is included in the "collections published in Crashaw's lifetime" in the guideline.
Also according to Wikipedia, the book "Steps to the Temple" was first published in 1646, whereas the guideline says it is "a collection of verse first published in **1648**" (underline added).
https://en.wikipedia.org/wiki/Richard_Crashaw

Are these descriptions in the guideline correct?
I'm sorry for referring only to Wikipedia since Crashaw is not famous in Japan. I did not know better ways to learn about him.

**Comment by lb42** [comment]
Thanks for reporting this mistake in the text, which has been lurking unnoticed since it first appeared in  TEI P2 !
I suggest that the text "first published in 1648" should read "as published in 1648", and the sentence beginning "Each of the three collections published in Crashaw's lifetime has a...  " should read "The first three of these collections each has a..." 

If you''re curious about how this error came about, I blame J R Tutin, from whose 1888 edition the Muses Library edition being transcribed is derived. Tutin liked to re-arrange the order of the poems in each edition according to his own preferences, and structuring them more faithfully to resemble the original source texts was of low priority to him. This is particularly the case for the 1646 Steps to the Temple, which he ignored completely in favour of the 1648 edition. Tutin is also responsible for applying the term "posthumous" edition to the later collections, which misled me into assuming that the earlier collections must have been ... I was going to say "pre-humous" but there is no such word.

P.S. No need to apologise for using Wikipedia! The article on Crashaw is, like many others, well-written and entirely credible, in my view. And a lot more accessible than other reference works.

**Comment by sydb** [comment]
Assigning to @sabineseifert, as soon as she is eligible.

**Comment by nakagawanatuko** [comment]
Thank you! I will fix the translation.
