### ISSUE TITLE
description of `<listRef>` mildly misleading

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2209]
As @jakub-simek [pointed out](https://listserv.brown.edu/cgi-bin/wa?A2=ind2110&L=TEI-L&P=R6280) in an [ongoing thread](https://listserv.brown.edu/cgi-bin/wa?A2=ind2111&L=TEI-L&P=4705) on TEI-L, the definition of `<listRef>` says “where this element is discussed”, but of course the thing being discussed may be a class, macro, or datatype.

**Comment by ebeshero** [comment]
The discussion on the TEI listserv also moves for wider application of `listRef` as in prosopography entries. We should be considering this, too. Rather than simply updating the description, we may want to connect this ticket with https://github.com/TEIC/TEI/issues/1667 .

**Comment by ebeshero** [comment]
Council decision 11 March 2022: 
* Add `<listRef>` to model.ptrLike
* Add constraints so that within P5 ODDs tagDocs, `<listRef>` should not be permitted to nest, and must contain `@target`. Also, `@target` must not contain a space. 
* Review the remark on listRef and update it as needed.
This is linked to #1667 
https://github.com/TEIC/TEI/issues/1667#issuecomment-345482914

**Comment by ebeshero** [comment]
Also linked to Stylesheets https://github.com/TEIC/Stylesheets/issues/333
