### ISSUE TITLE
`<handShift/>` should be a member of `model.global`

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#2247]
It seems obvious to me that this sort of structure must be common:

~~~~~
<div>
   <p>...</p>
   <handShift/>
   <p>...</p>
</div>
~~~~~

Other elements with similar semantics are allowed as children of `<div>`, including `<shift>`, `<milestone>`, and `<incident>`. It seems to me that `<handShift/>` really should be a member of model.global.

**Comment by sydb** [comment]
Assigning to @lb42 for a brief history lesson in how `<handShift>` currently works and why it was set up that way. (We will then move to the discussion as to whether or not it should stay like that.)

**Comment by lb42** [comment]
Not sure why a history lesson is needed, but fwiw, `<handShift>` was defined as a phrase class element in TEI P3, rather than as a global inclusion (like pb and other mileStoneLike elements). When the wg on source-based editing took it in hand, dusted it down, and generally made it useful, they added it to the new pPart.transcription class, rather than to model.milestoneLike,  presumably following the same logic: that a handshift was meaningless outside the context of some written stuff. It does look like a milestone though, I  agree, but it has the peculiarity there has to be some text before and after it. So I think Martin's imaginary example has to be
~~~~
<div>   <p> ....
   <handShift/>
   </p>
<p>...</p>
</div>
~~~~

**Comment by sydb** [comment]
Or, presumably
~~~xml
<div>
  <p> ... </p>
  <p><handShift/> ... </p>
</div>
~~~

In the years since `<handShift>` was originally conceived as a phrase-level element rather than a global inclusion, the `@hand` attribute has become much more prevalent.  So in fact the snippet could be encoded with
~~~xml
<div>
  <p hand="#MDH"> ... </p>
  <p hand="#LDB"> ... </p>
</div>
~~~

But it does strike me as inconsistent that `<shift>` (which does the same soft of thing for transcriptions of spoken word that `<handShift>` does for handwritten text) is part of model.global and `<handShift>` is phrase level.

In any case, thanks, @lb42!

**Comment by lb42** [comment]
Well, not quite. There is an important difference between the use of `<handShift>` and the use of `@hand`. The former is a milestone element: its effect applies until the next `<handShift>` comes along. The latter asserts something about the content of its enclosing element. So the latter is no use if you want to signal that the scribe suddenly changed pens in the middle of writing a line. And using the former you have to explicitly signal where it stops being applicable. As far as I can remember, there is no other case where the TEI provides for both scoped and non-scoped tagging of the same phenomenon in this way. 

As to `<shift>` yes, I agree it's inconsistent. But a better way of removing the inconsistency might be to make it a phrase level element too (I suspect it isn't simply because we didnt have a phrase class to add it to at the time). After all, what on earth does it mean for `<shift>` to occur *between* two `<u>` elements?

**Comment by sydb** [comment]
> … make [`<shift>`] a phrase level element too. … After all, what on earth does it mean for <shift> to occur between two <u> elements?

Agreed.

**Comment by sydb** [comment]
Having discussed at Council meeting w/ @martindholmes, decided no change in order.

**Comment by martinascholger** [comment]
Council F2F thinks `@hand` should suffice, and possibly that att.written might be expanded if someone needs more elements to be included.
