### ISSUE TITLE
Constrain translatable elements in TEI ODDs

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#2279]
To make it easier to build and maintain a translation interface for the TEI documentation, a few additional constraints would help:

1. Require that the English version of a desc, gloss, or remarks come first. This is a convention followed everywhere in the Specs as far as I can tell, but I don't think it is enforced. It is easier to look at preceding siblings for the "main" version than to have to look around.
2. Prevent multiple glosses and descs in the same language. I found a single case where a Japanese translation was added when an existing one was already there. There is already a rule like this in place for remarks.

**Comment by sydb** [comment]
I submit that these are changes that should be made to p5odds.odd (where, BTW, the "only-one-remark-per-lang" constraint comes from), not to the _Guidelines_ themselves, in which case I am 100% in favor.

I get the duplicate in same language constraint, makes perfect sense. However, need to define “same language”. One (easy)  way to do so is to say “the values of `@xml:lang` match”, which I think makes sense. But if someone wants to make an argument that different variants or extensions should be considered the same, speak now …

While I have no objection to the “English first” constraint, I don’t get it — I thought translators were using an interface, not reading the tagdocs directly. In which case,
~~~xml
<xsl:apply-templates select="*[@xml:lang eq 'en']"/>
<xsl:apply-templates select="*[@xml:lang ne 'en']"/>
~~~
seems a pretty easy way to go.

**Comment by hcayless** [comment]
@sydb imagine you have a desc in German, and you want to know if it's out of date. It's easier if you can just look back at the preceding English desc rather than have to look at both preceding siblings and following siblings.

And yes, I agree about where to make the changes.

**Comment by sydb** [comment]
I have implemented this in branch sydb_2279. I found that there were 10 errors our new constraints found, and was able to fix 6 of them myself quite easily. HOWEVER we have trouble in this here paradise. In the following cases, there **is no** English `<desc>`, `<gloss>`, or `<remarks>`, thus it _cannot_ come first, and the constraint that the English must come first fails, and the build will break.

- the `<remarks>` for the element specification of `<extent>`
- the `<desc>` for the value item "foreign" of attribute definition for `@type` of `<q>`
- the `<remarks>` for the element specification of `<speaker>`

Also
 - the element specification for `<availability>` has two (slightly different) French glosses. (I would bet the 2021 version is to be preferred over the 2007 version, but as I do not speak French, and GoolgeTranslate says both mean “availability” …)

Of these four remaining errors the first three are all of the same general sort. They could be handled by

1. Adding English versions. (Someone who speaks one of the languages already present would back-generate an English version, methinks.)
2. The error could be converted to a warning. (Thus the build would not break.)
3. I could re-write the constraint so it only insists that English be first if there _is_ an English version.

My vague recollection is our rule is that there should _always_ be an English version, thus (3) is not the right way to go. I personally lean towards doing both (1) and (2).

The fourth error listed above needs be fixed before it is merged into dev, because it would _break the build_. Could someone from **il8** who speaks French please take a look at and fix the `<availability>` tagdoc on branch sydb_2279? (Note that detest_odd_schematron.log has already been updated _without_ the four errors above, so you will not have to fix that, too.)

**Comment by sydb** [comment]
Council decides we are going with solution (1) only, not (2) (it should remain an error). Green to finish up, asking for I18N help as needed.

**Comment by sydb** [comment]
Attn: @peterstadler, @sabineseifert, @raffazizzi, @martinascholger, @HelenaSabel —

Looks like @hcayless fixed the French in availability.xml (in branch sydb_2279) back in September. So what is needed now:

- A **German** speaker to add `<remarks xml:lang="en">` to extent.xml (or delete the `<remarks xml:lang="de">`);
- Someone who speaks at least one of (and preferably 2+ of) **Spanish**, **French**, **Italian** to add `<desc xml:lang="en">` to the `<valItem ident="foreign">` in q.xml (approximately line 131); and
- A **French** speaker to add  `<remarks xml:lang="en">` to speaker.xml (or delete the `<remarks xml:lang="fr">`).

Change should be made in the sydb_2279 branch, or in dev and then merge dev into sydb_2279.

**Comment by HelenaSabel** [comment]
Update: 

- [x]  A **German** speaker to add `<remarks xml:lang="en">` to extent.xml (or delete the `<remarks xml:lang="de">`);
- [x] Someone who speaks at least one of (and preferably 2+ of) **Spanish**, **French**, **Italian** to add `<desc xml:lang="en">` to the `<valItem ident="foreign">` in q.xml (approximately line 131); and
- [x] A **French** speaker to add  `<remarks xml:lang="en">` to speaker.xml (or delete the `<remarks xml:lang="fr">`).
- [x] A **English** speaker to review the  `<remarks xml:lang="en">` of speaker.xml.

**Comment by sydb** [comment]
I tweaked the wording of `<remarks xml:lang="en">` of speaker.xml, but think someone else should still review it.

**Comment by sydb** [comment]
(Although as soon as we get a translation of the German remarks in extent.xml, I think we can make a PR of this.)

**Comment by sydb** [comment]
This was fixed 9 months ago, just forgot to close the ticket. But in response to @hcayless’s [explanation](#issuecomment-1102587993), seems to me `../desc[ lang('en') ]` is just as easy as `preceding-sibling::desc[ lang('en') ]`. (Actually easier, since I can never spell “preceding” :-)
