### ISSUE TITLE
restrict embedded transcription to sourceDoc / exclude text in zone and line as part of facsimile

### ISSUE THREAD

**Issue by GVogeler** [TEIC/TEI#2300]
The specs state "`facsimile` contains a representation of some written source in the form of a set of images rather than as transcribed or encoded text." https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-facsimile.html
The current content model of `zone` and `line` is identical in `facsimile` and in `sourceDoc` which makes it possible for users to add text to these elements in a `facsimile` structure and by this contradicting the specs. Would it be an idea to align the schema with the specs by adding a schematron constraint on `(zone|line)[ancestor::facsimile]` exluding non-whitespace content?

**Comment by lb42** [comment]
+1 from me

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: GVogeler ***@***.***>
Sent: Tuesday, May 31, 2022 10:02:03 AM
To: TEIC/TEI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TEIC/TEI] restrict embedded transcription to sourceDoc / exclude text in zone and line as part of facsimile (Issue #2300)


The specs state "facsimile contains a representation of some written source in the form of a set of images rather than as transcribed or encoded text." https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-facsimile.html
The current content model of zone and line is identical in facsimile and in sourceDoc which makes it possible for users to add text to these elements in a facsimile structure and by this contradicting the specs. Would it be an idea to align the schema with the specs by adding a schematron constraint on (zone|line)[ancestor::facsimile] exluding non-whitespace content?

**Comment by sydb** [comment]
See [PR 2360](https://github.com/TEIC/TEI/pull/2360).
