### ISSUE TITLE
`<docDate>` should be in att.datable and lose its bespoke `@when`

### ISSUE THREAD

**Issue by joeytakeda** [TEIC/TEI#2432]
In reviewing #2045, @ebeshero, @trishaoconnor, and I were surprised by (and thankful for) @martindholmes ' [comment](https://github.com/TEIC/TEI/issues/2045#issuecomment-731271583) that `<docDate>` has its own `@when` and is not part of `att.datable`.  This seems like an error that can be fairly easily resolved.

**Comment by JanelleJenstad** [comment]
`<docDate>` also needs a `@calendar` attribute. It needs to move to the new `att.calendarSystem`

**Comment by JanelleJenstad** [comment]
Example: All early modern books have a year (if they have a date at all). If you want to be able to process any data from encoded title pages, you would need a `@notBefore` and `@notAfter` date in order to capture the period between March 25 YYYY and March 24 YYYY+1. You also need to be able to capture the `@calendar` used in the text node (e.g., Julian).

**Comment by raffazizzi** [comment]
Another example with `18--`: https://digitalcollections.nypl.org/items/510d47e2-c586-a3d9-e040-e00a18064a99
![index](https://github.com/TEIC/TEI/assets/144770/9df82f69-8fbe-4ffe-9d45-cfd8ac058cf0)

**Comment by JanelleJenstad** [comment]
Another example:[https://digitalcollections.nypl.org/items/510d47e2-c586-a3d9-e040-e00a18064a99]( https://digitalcollections.nypl.org/items/510d47e2-c586-a3d9-e040-e00a18064a99)
The date one would transcribe and then tag with `<date>` and `@notBefore` and `@notAfter` is 18--
