### ISSUE TITLE
Update prose definition of surface to reflect contents constraints

### ISSUE THREAD

**Issue by Martin-de-la-Iglesia** [TEIC/TEI#2476]
As per Release 4.5.0 / Issue #2300, the content that is allowed in `<surface>` depends on its context: if it's a descendant of `<sourceDoc>`, it may contain transcriptions, but not within `<facsimile>`. We discussed that at this year's SIG Text & Graphics meeting, and found that the defitinition of `<surface>` doesn't reflect this; it currently reads:

> defines a written surface as a two-dimensional coordinate space, optionally grouping one or more graphic representations of that space, zones of interest within that space, and transcriptions of the writing within them.

We propose to change the last part to something along the lines of, "and - when using an [Embedded Transcription](https://tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#PHZLAB) approach - transcriptions of the writing within them."

**Comment by sydb** [comment]
Overall makes sense to me. But we have no precedent for a `<desc>` to refer directly to some other portion of the _Guidelines_ like that.[1] And since a link to 11.2.2 Embedded Transcription is already included in the `<listRef>` (and thus shows up on the tagdoc page immediately after the description being re-worded) it seems redundant. So I think I would be in favor of

> defines a written surface as a two-dimensional coordinate space, optionally grouping one or more graphic representations of that space, zones of interest within that space, and, when using an embedded transcription approach, transcriptions of the writing within them.

**Note**
[1] There are 9 cases of a pointer to elsewhere inside `<desc>`: 8 to W3C specs (some via the bibliography), and 1 to ISOCAT; note that 2 of the 9 are from non-English descriptions.

**Comment by sabineseifert** [comment]
Thanks, @sydb, for your suggestions. I am fine with it - and I don't think it needs discussion any longer and can be implemented?!
