### ISSUE TITLE
margin notes vs. line numbers

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#252]
Tite discusses margin notes but does not give guidance on distinguishing margin notes from other information that might appear in the margin, such as line numbers \(which presumably would just be encoded using `@n`\).

Original comment by: @kshawkin

**Comment by hcayless** [comment]
Absent a proposal, there's nothing to do, and this is 6 years old. Closing.

**Comment by kshawkin** [comment]
Oh gosh, I just haven't gotten made time to look at how the TEI does this and see how to accommodate in Tite.  This, along with other tickets, was on hold till I reconciled DTDs with Apex in December 2014 (see [history](http://wiki.tei-c.org/index.php/User:Kshawkin/My_Council_obligations/Plan_for_TEI_Tite)), so in a sense it's only a year and a half old.

**Comment by PFSchaffner** [comment]
I think discussions over the years have pointed to many (I won't say innumerable, but many) sorts of things that can appear in margins, many of which are susceptible to various kinds of capture and encoding: references to other reference systems (milestones?), line numbers, running date or time references, running summaries, section labels or heads, &c. &c. I'm not sure that a one-size-fits-all solution is even possible, much less desirable... This is a matter I return to frequently, since it affects so many early books -- which loved to put things in margins, and loved to find new uses for them.

**Comment by lb42** [comment]
Feel free to reopen when you have been able to get to it.
