### ISSUE TITLE
allow `<quote>` in `<bibl>`

### ISSUE THREAD

**Issue by cthomasdta** [TEIC/TEI#2544]
Since no-one objected to [my mail to TEI-L from Fri, 22 Mar 2024](https://listserv.brown.edu/cgi-bin/wa?A2=TEI-L;b7b66dfc.2403), I open this issue, asking to allow `<quote>` in `<bibl>`.

Background, as explained in the mail, is
> while encoding Goethe's letters for https://goethe-biographica.de/ we are putting information about sth that was sent together with the letter in `//teiHeader/physDesc/accMat/bibl[@type="attachment"]`. For example:
>
> ```XML
> <physDesc>
>      <accMat>
>             <bibl type="attachment">S.s Bemerkungen über den <quote>Umfang alter und neuer Architektur.</quote></bibl>
>       </accMat>
> </physDesc>
> ```
>
> This is not valid, since `<quote>` is not allowed in `<bibl>`, cf. https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-bibl.html.
I can't see any reason why not (plus there is `<q>` which is  allowed in `<bibl>`).

One could even argue, that there is no reason why `<quote>` should be verboten in any structure, but for now, we only ask to allow `<quote>` in `<bibl>`.

**Comment by jamescummings** [comment]
Hi @cthomasdta, 

I'm not disputing the need for `<quote>` inside `<bibl>` and I can imagine some scenarios where this happens. In this instance, I just want to check is 'Umfang alter und neuer Architektur' not the title of a publication? If so, wouldn't `<title>` be more appropriate? 

I guess one avenue of objection might be that `<bibl>` (used for bibliographic citations) should be used for the bibliographic object and whether the quoted material really is part of that. One could wonder if the text isn't in quotation marks of some sort, is it really the allusion one thinks? Or, is it really part of the title? And if so, `<title>` already allows `<quote>` inside it.  

However, I think some of those objections have fairly obvious holes. 

For an anglo example, to make it easier for non-German speakers, If we look at  [https://search.worldcat.org/title/949698766](https://search.worldcat.org/title/949698766 ) we see that the title is "To be or not to be? : the verbum substantivum from synchronic, diachronic and typological perspectives". I've chosen this example precisely because it is impossible to know (just from the metadata record) whether the allusion to Shakespeare's _Hamlet_ is just that. (If I had chosen something that was obviously about Shakespeare, that would be less problematic.) In this case the "volume describes and interprets the to be-verbs and constructions in the broad context of contemporary linguistic research", so is really about the linguistic formulation. 
However, if we were encoding this and wanted to express our interpretation that this is indeed a quotation, how would we do it? It doesn't have quotation marks, so `<q>` is inappropriate. To me the appropriate way to mark this up is: 
~~~~xml
<bibl> 
<title><quote source="#Hamlet">To be or not to be?</quote> : the verbum 
substantivum from synchronic, diachronic and typological perspectives</title>, 
edited by <editor>Michail Kotin</editor> and <editor>Richard J. Whitt</editor>, 
<publisher>Cambridge Scholars Publishing</publisher>, <pubPlace>Newcastle 
upon Tyne</pubPlace>, <date>2015</date>
</bibl>
~~~~
However, that is because I use a fairly completist model of `<bibl>`, which is supposed to also allow more free text citations. Thus encoding as: 

~~~~xml
<bibl> 
<quote source="#Hamlet">To be or not to be?</quote> : the verbum 
substantivum from synchronic, diachronic and typological perspectives, 
edited by Michail Kotin and Richard J. Whitt, Cambridge Scholars Publishing, 
Newcastle upon Tyne, <date>2015</date>
</bibl>
~~~~

should be perfectly feasible. 
(I've left the date encoded because in this putative bibliography I want to be able to order by date. ;-) ) 

So +1 in favour.

**Comment by cthomasdta** [comment]
> So +1 in favour.

Thank you @jamescummings ! I hope others will agree in principle.

I will also get back to you re: your question "is 'Umfang alter und neuer Architektur' not the title of a publication?", I have passed it on to the editors who can answer it (I can't). This may take a moment due to holiday season here in Germany.

**Comment by cthomasdta** [comment]
Dear James, here's finally the answer to your question:

> In this instance, I just want to check is 'Umfang alter und neuer Architektur' not the title of a publication? If so, wouldn't `<title>` be more appropriate?

The quoted phrase  "Umfang alter und neuer Architektur" is _not_ a (bibliographic) title. It is a quotation intended to identify the underlying manuscript. 

So, even more, I would stress that there is

> the need for `<quote>` inside `<bibl>` and I can imagine some scenarios where this happens. 

Thanks all, I hope to see this in the next release!

**Comment by ebeshero** [comment]
Hi Christian and James,Thanks for this helpful discussion. I’m persuaded that there’s good reason to apply `<quote>` in `<bibl>`, but not sure I understand why we could not use `<title>` for your example, Christian. Mainly I am wondering how one determines a title string to be such a thing when it is absent from or unstated in a document. If a manuscript has no title but is well known, and people reference it by a phrase found inside it, one might argue for that phrase to be meaningfully and functionally working in library catalogs as a title for the purpose of identifying and locating the document. 

I suppose I am more comfortable with the encoding of `<quote>` inside the `<title>` element, but uncertain of its semantics in the looser construction. But `<bibl>` is certainly intended for flexible application—I am okay with the proposal to include `<quote>` in `<bibl>.` 

I think I would like to see a better definition of `<title>` itself in the Guidelines. Ours is pretty underwhelming: we just say a title is a title. (What is a title, really?)

**Comment by cthomasdta** [comment]
Hi Elisa,

> I’m persuaded that there’s good reason to apply `<quote>` in `<bibl>`, 

thanks, that's another +1 ;) Concerning your (and James') slight discomfort, I hope I can clear things up a little more:

> but not sure I understand why we could not use `<title>` for your example, Christian.

the manuscript, the archival unit encompassing the pages from which the quotation "Umfang alter und neuer Architektur" originates has no title in the legacy collection (and is not well known, but that's beside the point). It is identified merely by a "Signatur", a reference or call number. Our colleagues wish to quote the phrase since it happens to characterise its content – or at least these parts of it that are relevant to the correspondence context edited here –, the topic, which this handy quote provides without the editors having to make one up or to write more elaborate text here. I have to say, I would also refrain from using `<title>` here, thereby suggesting that this is (from now on) the title of said document(s), or should have been, i.e. was supposedly intended by the scribe to be the title, or should be. We do not use the title here, since there is none and we do not want to determine one, we only quote text from it and therefore we need `<quote>`. Maybe the analogy holds and helps: an incipit is also not a title, although both sharing some functions for using, which is why we have different elements for that, i.e. `<title>` and [`<incipit>`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-incipit.html). 

So, I would stick to my request to allow `<quote>` in `<bibl>` (repeating my initial additional argument that `<q>` is already allowed there, so it would be only consistent).

**Comment by ebeshero** [comment]
The one question I would raise here (before opening a new ticket about the Guidelines' understanding of `<title>`) is just this: How often in the history of our libraries and collections have documents been given titles that their authors never intended? How often are titles just applied by convention, by practice, by application in reference?  I was thinking of the *Beowulf* manuscript, but I'm sure there are a lot of interesting examples. 

I do not think we should limit the concept of a bibliographic title to the intention of an author or scribe.

**Comment by cthomasdta** [comment]
Thanks Elisa, I agree with your concerns regarding the definition of title, but I also and more strongly agree that this is another issue. For our purpose here, let's keep the focus on my initial request: please [allow `<quote>` in `<bibl>`](https://github.com/TEIC/TEI/issues/2544#top).

**Comment by sydb** [comment]
I find the “it is not a title” argument uncompelling; I find the “I should not have to encode it as a title” argument very compelling (even though I would not personally do that). So +1 from me, too.

**Comment by sabineseifert** [comment]
European subgroup at VF2F April 27:
- If we allow `<q>` should we also allow `<quote>`? 
- difference between `<q>` and  `<quote>`: `<q>` may have graphical markers, e.g. quotation marks, so it can be applicable for terms as well as actual quotations, whereas `<quote>` is specifically for quotations
- `<q>` is superset which can contain quotations contained by  `<quote>`
- EU subgroup agrees on allowing `<quote>` in `<bibl>`

**Comment by sabineseifert** [comment]
Issue can be closed as [PR 2557](https://github.com/TEIC/TEI/pull/2557) is already merged.
