### ISSUE TITLE
ISO 8601 retitled

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#2575]
Kazuhiro Okada points out that the title of ISO 8601 changed with the 2019 release; it's now called "Date and time — Representations for information interchange". I was thinking this would be a quick fix, but we explicitly reference ISO 8601:2004 throughout the Guidelines, so at the very least we would need to:

1. Decide whether we want to update all our references to 2019; if so
2. Check that all our quotes, assertions, and encoding structures based on :2004 still work in :2019; if so
3. Update all section references etc.

**Comment by sydb** [comment]
Unless the reference is _specifically_ to ISO 8601:2019, please do not.
(We currently do not support 8601:2019, but only 8601:2004, so should name the one we do support. In truth, though, our “support” is so lame, it probably does not matter.)

**Comment by laurentromary** [comment]
As a matter of fact, it would even be better to point to the two parts now: https://www.iso.org/iso-8601-date-and-time-format.html

**Comment by sydb** [comment]
Personally, I would prefer to stick with the original plan, although I understand if other folks get too frustrated and just want to update bits right now.
The current plan is essentially to overhaul teidata.temporal.iso so that it documents and to some extent supports use of 8601:2019. (Whenever i say that, @laurentromary, I mean both parts 1 & 2.) I am expecting that re-write to be based on _Dates and Times in DH: An annotated application profile of ISO 8601:2019 for use with TEI and other DH systems_, which is about ⅓ done, but is likely to take another year for me to finish, given how slow I have been going.

**Comment by rettinghaus** [comment]
relates to #2249

**Comment by martindholmes** [comment]
I think, having looked at issue #2249, that we should do nothing now, and in fact close this ticket; there's no point in updating the Guidelines to point to a standard we don't (yet) implement. I'm going to punt this to the 4.10 milestone, but @sydb do you think we should just close it to avoid confusion with #2249?

**Comment by sydb** [comment]
Not “won’t fix”, but rather will fix on #2249 .
