### ISSUE TITLE
Encoding RDF relationships in TEI

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#311]
Hi, I was looking at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-relation.html today, and realized that it comes very close to being able to represent RDF-style triples.  Actually, I think it could do so now, but there are a couple of things I'd suggest TEI do:

Example:

&lt;placeName ref="http://sws.geonames.org/361059"&gt;Alexandria&lt;/placeName&gt;
&lt;placeName ref="http://sws.geonames.org/357994"&gt;Egypt&lt;/placeName&gt;

...

&lt;relation xmlns:gn="http://www.geonames.org/ontology\#" ref="gn:parentFeature" active="http://sws.geonames.org/361059" passive="http://sws.geonames.org/357994"/&gt;

could be a way to encode the triple Alexandria is a child feature of Egypt.  My first recommendation would be that the Guidelines say explicitly that using `@ref` on &lt;relation&gt; enables the encoding of RDF-style triples.

My second recommendation is that the attributes `@active` and `@passive` be deprecated and renamed.  The names are *extremely* confusing, unintuitive, and fail to describe the attributes' actual function.  Better would be `@subject` and `@object` (as in "subject, predicate, object"), which is a standard way of describing RDF triples.  The relations are directed graphs, so names drawn from graph theory terminology, like `@head` and `@tail` would be acceptable also.  Likewise `@symmetric` might be a better name than `@mutual`, but the latter is less bad than `@active` and `@passive`.  

It could be argued that `@mutual` is redundant, but I see the attraction of a single attribute that can express symmetric relationships.

My last recommendation is that the guidelines make it clear that &lt;relation&gt; is not just for persons, but can be used for relationships between places, objects, organizations, etc.  I wonder too whether elements like &lt;affiliation&gt; ought not to be considered refinements of &lt;relation&gt;.

Original comment by: @hcayless

**Comment by chiarcos** [comment]
Note that the relation/RDF example in the TEI guidelines (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-relation.html, example 4) violates the TEI schema because it describes the link to a CTS URN rather than a named entity. Although <relation> is sufficiently generic ("any kind of relationship or linkage amongst a specified group of places, events, persons, objects or other items."), it must be contained in core: listBibl, namesdates: listEvent listNym listObject listOrg listPerson listPlace listRelation. Every single of these refer to a (named) entity, which does not include references to other pieces of text (and in particular, canonical references, which can abstract from a concrete manifestation of a given text). Also note that the SAWS ontology (where this example comes from) therefore permits <relation> to be contained in <ab> and <seg>. I suggest to deprecate the current use of <relation> for RDF triples and to introduce unambiguous vocabulary elements for that (and will open a new issue on that).

**Comment by lb42** [comment]
Coming from a position of almost total ignorance, I am necessarily agnostic about whether or not using &lt;relation> is the way to go, but I don't think it's accurate to say that this example "violates the TEI schema": the TEi schema requires only that the value of these attributes be a URI. There is a presumption in the TEI conceptual model that the URIs here will resolve to information about a named entity, and so your comment is appropriate only if you don't consider such things as "the third line of act 2 of Hamlet" to be named entities (though some scholars, in particular those behind the definition of the CTS, would disagree). On the question of the contexts in which &lt;relation> is permitted, I agree with you that the job of introducing it into TEI P5 has not really been thought through adequately. Why not make it a member of model.global, for example? Or permit it explicitly within the content of &lt;note> (which is pretty much globally available)?  There is precedent (a little) for TEI elements having different semantics depending on their context.

**Comment by chiarcos** [comment]
Am .03.2019, 15:20 Uhr, schrieb Lou <notifications@github.com>:
>
> Coming from a position of almost total ignorance, I am necessarily  
> agnostic about whether or not using <relation> is the way to go, but I  
> don't think it's >accurate to say that this example "violates the TEI  
> schema": the TEi schema requires only that the value of these attributes  
> be a URI. There is a presumption >in the TEI conceptual model that the  
> URIs here will resolve to information about a named entity, and so your  
> comment is appropriate only if you don't >consider such things as "the  
> third line of act 2 of Hamlet" to be named entities (though some  
> scholars, in particular those behind the definition of the CTS, >would  
> disagree).
In fact, I would not consider "the third line of act 2 of Hamlet" a named  
entity. Not because I fail to see how anyone could, but because with such  
a broad definition, named entity becomes basically indistinguishable from  
URI. I'm pretty sure this is not intended. And I'm pretty sure this was  
exactly why SAWS (where this example seems to come from) extended the  
contexts of <relation> to <seg> and <ab>.
>
> On the question of the contexts in which <relation> is permitted, I  
> agree with you that the job of introducing it into TEI P5 has not really  
> been thought >through adequately. Why not make it a member of  
> model.global, for example?
I think this would be a nice alternative (and I mentioned that in the  
accompanying email). I'm just afraid this would be an even greater  
disruption as it can cause problems with current uses of <relation> that  
may require the named entity reading.
>
> Or permit it explicitly within the content of <note> (which is pretty  
> much globally available)?
I'd prefer <ab> or <seg> because these were the contexts that SAWS  
required and where we have an antecedent for this modeling choice.
>
> There is precedent (a little) for TEI elements having different  
> semantics depending on their context.
Best,
Christian

**Comment by PietroLiuzzo** [comment]
in our local ODD we made `listRelation` part of model.global . but perhaps this is a bit of an abuse of <listRelation> on our side because actually we use the <relation> elements in there for a number of other things, so I would be happy to improve on this.

**Comment by hcayless** [comment]
Work on the new `<standoff>` proposal will include a place to put `<listRelation>` as well as other types of list (persons, places, etc.). `<standoff>` will be a model.resourceLike element. Standoff annotations may be an alternative to `<relation>` used in this way. See #1745.

I am deeply sympathetic to the desire to deprecate `<relation>` as a mechanism for expressing RDF-style assertions, but I fear that ship has sailed. A CTS URN referencing a piece of text as the target or subject of an assertion is perfectly legal, regardless of whether you think it's a good idea. Since we have #1860 as a focus for discussion, I'm going to close this issue again.
