### ISSUE TITLE
New attribute @keepHyphen

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#361]
As a result of the discussion on TEI-L \(Re: `@break`, April 11-20\), I'd like to propose a new attribute, `@keepHyphen`, as a member of att.breaking. \(The definition of att.breaking needs to be changed accordingly.\)

`@keepHyphen` indicates whether or not a hyphen preceding the element bearing this attribute is preserved when the line break is removed due to re-rendering of the document.
Status: optional
Datatype: data.enumerated
Sample values include: yes - a hyphen preceding the element bearing this attribute is preserved when the line break is removed due to re-rendering of the document.
no - a hyphen preceding the element bearing this attribute is omitted when the line break is removed due to re-rendering of the document.

Original comment by: @Martin-de-la-Iglesia

**Comment by lb42** [comment]
I've asked @PFSchaffner if we can use an image along with one of the examples above., Presumably the example should go into http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COPU somewhere.

**Comment by PFSchaffner** [comment]
With apologies for the hasty arrangment and awful html, I've dropped some images on the web and linked to them from [THIS LIST](http://www-personal.umich.edu/~pfs/tei/hyphens/readme.html)

**Comment by PFSchaffner** [comment]
If those won't serve, or should be moved, etc., will gladly do whatever, tomorrow. Have to go catch a bus now.

**Comment by PFSchaffner** [comment]
(Just added a few more examples to the list above, though not yet one of the sort I was looking for -- those that use a hyphen to bridge a divide of some sort that is not reflected in the markup at all -- no page break, no column break, etc.  The ones I added this time are all from George Herbert's Temple: one in which a 'wraparound' word at the end of a verse line is hyphenated (how you handle that will depend on how you handle that feature to begin with: we silently move the wraparound bit to the verse line from which it is detached, but keep the contingent hyphen.) Another features a catchword that represents the first half of a hyphenated compound ("Church-" pointing to "Church-rents" on the next page). And a third that features a similarly hyphenated catchword, fragment, but the full word on the next page is NOT hyphenated ("Judge-" pointing to "Judgement" on the next page). I imagine that represented as g elements, these would be contingent, real, and contingent hyphens respectively.

**Comment by hcayless** [comment]
Subgroup recommends assigning someone to pick one of Paul's examples and turn it into an example for the GLs.

**Comment by sydb** [comment]
If I may, I’d also like to suggest we consider `<pc>` in place of `<g>`. While the latter is *technically* correct (because there is no character in Unicode to represent “there was a contingent hyphen here in the source”), the former is semantically more informative. Thus:

~~~~~
<lb/>This is a typo<pc function="soft">-</pc>
<lb break="no"/>graphically introduced hyphen.
<lb/>The next one, introduced by a wood-
<lb/>cutter, is not.
~~~~~

**Comment by raffazizzi** [comment]
Add examples here: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COPU

**Comment by raffazizzi** [comment]
This is already very explicitly remarked in the guidelines (in [CO#COPU](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COPU)):

> If the hyphen is included in the character data of the TEI document, it might be marked up using the pc (punctuation character) tag, which allows the encoder to express information about its function as a separator, through the force attribute (see 17.1.2 Below the Word Level).

So the correct encoding is:

```xml
<lb/>This is a typo<pc force="weak">-</pc>
<lb break="no"/>graphycally introduced hyphen.
</p>
```

The Guidelines are sufficiently clear and no further action is needed.

**Comment by kshawkin** [comment]
The force= attribute is one that I was not previously aware of, and which I find an intriguing way to deal with this.

However, http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COPU merely suggests using `@force` and says to see section 17.1.2 ( http://www.tei-c.org/release/doc/tei-p5-doc/en/html/AI.html#AIPC ).  When you get to that section, there's only a brief discussion of `@force`, with no explanation of the allowed attribute values and how they would apply to the various cases of punctuation.  You have to visit the element spec for `<pc>` to find this.

I'd like to suggest any of the following as a way to improve the situation:

a) Remove the cross-reference to section 17.1.2 from http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COPU so as not to send readers to a dead end.  Instead, we'll rely on them to follow the link earlier in that sentence to the element spec for `<pc>`.

b) Add some discussion of values of `@force` for various types of hyphens to http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COPU (where we already discuss hyphenation more extensively than elsewhere in the Guidelines).

c) Say something about allowed values of `@force` in 17.1.2 since the one example given is opaque for those who don't know about the use of this symbol in manuscripts.

I realize it may seem unnecessary to add such information to the Guidelines when the reader could figure this out if the reader digs enough.  However, I plead for an exception here since hyphenation occurs so often in manuscripts and text, and consistent handling is required in order to do a number of basic functions with texts, including word counts and reformatting without preserving existing line breaks.

**Comment by raffazizzi** [comment]
Thanks @kshawkin, I'll look into writing something either as you suggest in b) or c).
