### ISSUE TITLE
Improve guidance and restrict usage of biblScope

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#377]
There are a few problems with section 3.11.2.3 and the content models of associated elements:

1) Not much guidance is given on when to put &lt;biblScope&gt; in which parent element.

2) When guidance is given, it's for journal articles (to put volume and issue number in &lt;biblScope&gt;s &lt;imprint&gt;), but the information there doesn't "relat[e] to the publication or distribution of a bibliographic item", as &lt;imprint&gt; is currently defined.

To address (1), we propose to explain more explicitly in the Guidelines that &lt;biblScope&gt; be used to constrain the scope (within the parent element of the biblScope) of the item cited in the next lowermost "level", where "level" is used as in section 3.11.2.1. Take this example:

&lt;biblStruct&gt;
&lt;analytic&gt;
&lt;author&gt;Albert Schachter&lt;/author&gt;
&lt;title&gt;Iolaos&lt;/title&gt;
&lt;/analytic&gt;
&lt;monogr&gt;
&lt;title&gt;Herakles to Poseidon&lt;/title&gt;
&lt;imprint&gt;&lt;date&gt;1986&lt;/date&gt;&lt;/imprint&gt;
&lt;biblScope type="pp"&gt;64-70&lt;/biblScope&gt;
&lt;/monogr&gt;
&lt;monogr&gt;
&lt;title&gt;Cults of Boiotia&lt;/title&gt;
&lt;imprint&gt;&lt;pubPlace&gt;London&lt;/pubPlace&gt;&lt;/imprint&gt;
&lt;extent&gt;4 vols.&lt;/extent&gt;
&lt;biblScope type="part"&gt;2&lt;/biblScope&gt;
&lt;/monogr&gt;
&lt;series&gt;
&lt;title&gt;Bulletin of the Institute of Classical Studies
Supplements&lt;/title&gt;
&lt;biblScope type="vol"&gt;38&lt;/biblScope&gt;
&lt;/series&gt;
&lt;/biblStruct&gt;

There are four "levels": the lowest "level" is the &lt;analytic&gt;, the next is the first &lt;monogr&gt;, then the second &lt;monogr&gt;, and finally the highest "level" is &lt;series&gt;.  The article "Iolaos" appears on pp. 64-70 of *Herakles to Poseidon*, which is part 2 of *Cults of Boiotia*, which is vol. 38 of *BICS  Supplements*.

Each &lt;biblScope&gt; describes where (within its parent element) to find the thing in the previous level.

To address (2), we would remove the current recommendation in 3.11.2.3 to use monogr/imprint/biblScope for journal articles and instead say to encode information like volume, issue, and date of a given journal issue as a child of &lt;monogr&gt;.  We would modify examples accordingly, and we would deprecate use of &lt;biblScope&gt; inside of &lt;imprint&gt;.

There would be no change to the definition or examples of &lt;extent&gt;: it would still be used not for mentions of particular pages or volumes but for a statement like "4 vols." and "325 pages".

Original comment by: @gabrielbodard

**Comment by kshawkin** [comment]
While implementation of this ticket led to an update of the Chesnutt encoding example found at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-monogr.html , that example also appears at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-analytic.html , where we forgot to update it.  The example in ref-analytic should be updated there to correspond to ref-monogr.

**Comment by lb42** [comment]
I've made the examples consistent at least. But it seems we ought to be considering formal deprecation of biblScope as a child (rather than a sibling) of imprint as well. Thus breaking a gazillion exports from zotero and annoying old timers accustomed to considering it legal there.

**Comment by kshawkin** [comment]
For the record, Lou's update is here: https://github.com/TEIC/TEI/commit/c23bb14257372b74892f7e43d5f7225cb4fd067a .

**Comment by kshawkin** [comment]
Even if the Council does not deprecate according to http://www.tei-c.org/Activities/Council/Working/tcw27.xml , we should still add some text to `<remarks>` on the biblScope spec to indicate that the placement of `<biblScope>` within `<imprint>` is no longer recommended.

**Comment by lb42** [comment]
I've added this remark to the  spec for biblScope:
~~~~
<p>It is now considered good practice to supply this element as a sibling (rather than a child)   of <gi>imprint</gi>,cd since it supplies information which does not constitute part of the  imprint. </p>
~~~~
Leaving the ticket open so that Council may decide whether or not it wishes to proceed to deprecate this.  I'd recommend not to, or if we do, to give at least a year's notice.

**Comment by hcayless** [comment]
Should we file a bug with Zotero if their TEI export isn't using the recommended structure? Otherwise recommend close.

**Comment by jamescummings** [comment]
They get it from us: http://wiki.tei-c.org/index.php/ZoteroToTEI 
As documented here: https://www.zotero.org/support/kb/tei

**Comment by ebeshero** [comment]
Council says @lb42 should fix this stylesheet.

**Comment by jamescummings** [comment]
Council decides, @lb42 to fix the stylesheet, and @emylonas to tell Zotero when he's done so.

**Comment by kshawkin** [comment]
But according to https://www.zotero.org/support/kb/tei , Zotero includes not http://wiki.tei-c.org/index.php/ZoteroToTEI but rather http://wiki.tei-c.org/index.php/TEIZoteroTranslator , which is stored in Google Code.  The wiki page for http://wiki.tei-c.org/index.php/TEIZoteroTranslator claims that you can get in touch through Google Code, but I don't see contact information there, and in any case Google Code was made read-only by Google in 2015.  So we need a new home for http://wiki.tei-c.org/index.php/TEIZoteroTranslator .  I believe that @smjwsk developed it, so you might check with him to see if he has any intention of updating it before forking the code (and then notifying Zotero of the new location).

**Comment by emylonas** [comment]
pinged @smjwsk via email

**Comment by emylonas** [comment]
Zotero uses the translator https://github.com/zotero/translators/blob/master/TEI.js
@martindholmes submitted a patch on Jan 19, 2017 to Zotero which was accepted, to handle `@idno` properly, exporting it as a child of `<monogr>` and `<analytic>`. See discussion here: https://forums.zotero.org/discussion/comment/268352

For the record, original (archived) google code tei-zotero-translator source, dating from 2011, is here: https://code.google.com/archive/p/tei-zotero-translator/downloads

There is also a modification to the tei-zotero-translator code made by Franziska Horn in 2015, https://groups.google.com/forum/#!topic/zotero-dev/TdsRZjQbkvs - 
This modification exports the Zotero key in addition to the author+date id that is generated, a short title and some formatting within titles (but which has a glitch in that it is forced to use `&lt; &gt;` instead of angle brackets. The code is available, but hasn't been submitted as a pull request. I think we should discuss it with Zotero anyway, or just ask them to have it as an alternative translator. I like the Zotero key export.

So: do we deprecate `<biblScope>` inside `<imprint>`? 
Do we make Zotero export in the recommended fashion? If so, we can modify https://github.com/zotero/translators/blob/master/TEI.js and issue a pull request.

**Comment by emylonas** [comment]
btw, Zotero doc  has a page on Zotero and the TEI - https://www.zotero.org/support/kb/tei
Worth reviewing. It's not pernicious, but the introductory paragraph is not totally accurate. For ex. some of the wording "curates and international standard for the XML markup of texts" "Web-based TEI-compliant documents are found in increasing numbers online." We could review and suggest some changes.

**Comment by lb42** [comment]
Assuming that the stylesheet I'm supposed to be fixing is the "zoterototei" one originally written by Paul Caton, I note that this contains several other defects, which seem to have been  fixed in the TEItozoteroTranslator. And since neither of these is the one actually being used by Zotero I believe the wiki should be updated to point to  https://github.com/zotero/translators/blob/master/TEI.js anyway. So I think  I've done all that needs doing on this topic, so I have unassigned myself from it. Leaving open in case someone else (with JS skills) wants to improve the current Zotero translator.

**Comment by martindholmes** [comment]
I made some fixes to the TEI.js file already:

https://github.com/zotero/translators/pull/1229

There's room for more improvement, of course.

**Comment by lb42** [comment]
Yes, I had noticed that... and was hoping you'd  volunteer yourself to fix this one (biblScope as sibling rather than child of imprint) too!

**Comment by martindholmes** [comment]
No time right now, but if you raise a TEI ticket pointing to it and assign it to me I'll get to it eventually. If it's raised as a Zotero bug I'll never remember it. :-)

**Comment by kshawkin** [comment]
Lou wrote that "the wiki should be updated to point to https://wiki.tei-c.org/index.php/TEIZoteroTranslator#Synopsis anyway".  I've edited https://wiki.tei-c.org/index.php/TEIZoteroTranslator#Synopsis to point to the repository.

**Comment by emylonas** [comment]
waiting for Martin or other person who has javascript fu to modify the Zotero translator to export biblScope as child of imprint. Left myself assigned in case I locate someone before Martin is able to turn to this. Blocked due to lack of js attention.

**Comment by martindholmes** [comment]
I believe this ticket to be moribund. Council never decided to deprecate biblScope as a child of imprint, and therefore what is currently produced by Zotero is perfectly valid, and I see no reason to upset the Zotero/TEI community by suddenly changing the results of their export process to create something different from what they're used to getting. If Council does decide to deprecate biblScope as a child of imprint, then action will need to be taken.
