### ISSUE TITLE
make explicit difference between tagUsage and ODD documentation

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#457]
Per Lou's comment on TEI-L:

http://listserv.brown.edu/archives/cgi-bin/wa?A2=TEI-L;819d9fe2.1305

it seems that tagUsage is only useful when describing use of an element, but if you want to describe more complex usage, you need to use an ODD.  However, I am having trouble finding this stated explicitly in the Guidelines.

The introduction to section 2.3.4 (#HD57) implies that more detailed information might be elsewhere in the header, and section 2.3.4.2 (#HD57-2) does not mention any other location where you might put such information.

I might also expect to find a mention of this use of an ODD in section 1.2 (#STIN) and section 23.3 (#MD).  I confess to not having time right now to re-read these sections closely, so I might have missed a reference.  But I would also expect this use to be stated somewhere obvious, near the beginning of these sections.

Original comment by: @kshawkin

**Comment by lb42** [comment]
Added the following text to #HD57:
~~~~
<p>The <gi>tagsDecl</gi> element is descriptive, rather than prescriptive: if used, it simply documents
practice in the TEI document containing it. The elements constituting a TEI customization file (discussed in chapter <ptr target="#TD"/>) by contrast document expected practice in a number of documents, and may thus be used prescriptively. If there is an inconsistency between 
the actual state of a document and what is documented by its <gi>tagsDecl</gi>, then the latter should be corrected. If there is an inconsistency between a document and what is required by the customization file, or a schema derived from it, then it will usually be the document that requires correction.</p>
~~~~
