### ISSUE TITLE
att.measurement and att.dimensions overlap

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#470]
&lt;measure> and &lt;measureGrp> are the only members of att.measurement ("provides attributes to represent a regularized or normalized measurement") which supplies attributes `@unit` `@quantity` and `@commodity`. Most things which are measurements are members of att.dimensions ("provides attributes for describing the size of physical objects") which supplies its own definitions for `@unit` and `@quantity`, doesn't have `@commodity`, but does have others (`@extent`, `@precision`, `@scope`)

This should be regularised. I think the original idea was that `@unit` in att.measured should allow only an SI unit, but all the examples show that this was unworkable. We could 
- keep att.measured as is (or modify it slightly to match the current definitions in att.dimensions); make att.dimensions inherit `@unit` `@quantity` `@commodity` from it
- add `@commodity` to att.dimensions and abolish att.measured
- leave well alone
- factor out `@unit` and `@quantity` (and possibly also `@extent`) into a new class and make the other two inherit from that 
- provide a new `@SIunit` attribute somewhere, constrained to be an SI unit

Original comment by: @lb42

**Comment by sydb** [comment]
Not sure I ever saw this ticket before, and I have not read the whole thing yet. I think I agree that it can just be closed. But I’d like to vehemently correct a misinterpretation of the current situation. `@unit` of att.measurement was **never** intended to be restricted to only SI units. It was, and is, and should be, intended to a) suggest that SI units are good ones to use, and b) provide a standard set of values for those that choose to use SI units. Note that the (horribly abbreviated) list of SI units is a _suggested values include_ list, not a _legal values are_ list. From the notes on the spec page: “Wherever appropriate, a recognized SI unit name [sic] should be used …. The list above is indicative rather than exhaustive.”

(The fact that the list is horribly abbreviated means that we fail at (b) for lots of physical features that might be measured including temperature, mass, and force. Some believe, perhaps correctly, that these units will be used so rarely in the digital humanities that it is not worth including them.)

**Comment by martindholmes** [comment]
Closing this; I don't think there's anything to be acted on here.
