### ISSUE TITLE
Make @new obligatory attribute of <shift>

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#512]
In order to reduce the calamaties caused by it being a milestone element, the attribute ``@new`` should be made obligatory for `<shift>` element. This means that the current shortcut of leaving out the attribute in cases where it would read ``@new`=normal` should be disallowed.

Original comment by: sf_user_thomas_schmidt

**Comment by martindholmes** [comment]
SB and MDH discussion 2016-02-12: There doesn't seem to be @validUntil, and this ticket should stay open until August 2016 so that the process can be completed. Additionally, it seems to us that having `<shift/>` without `@feature` is meaningless; and `<shift/>` with `@new` without `@feature` seems even more so; and therefore consideration should be given to making both `@feature` and `@new` required attributes. Also, the valList for `@feature` should be semi, not closed -- why would we restrict what features people can use? Finally, the prose discussion near the end of 8.3.6, last para, of the values of `@feature` dates back before ODD, apparently, and should be updated to reflect that values for `@feature` should be documented in the ODD, not in the teiHeader.

**Comment by lb42** [comment]
I've updated the discussion to allow documentation of @feature values either in an ODD or in the header, since both are perfectly valid. I'm reluctant to make   @feature mandatory since you may want to specify changes in voice quality more generally, or without consideration of the specific features involved, as in the example given in the chapter (&lt;shift new="reading">) . I've made the list of features semi-open. The remark about deprecation in the current source does seem a bit vague, and I am not sure that I know  to fix that. This ticket's request to make  @new mandatory has already been met by the schematron constraint; removing the current defaultVal seems a bit drastic but would be required if we do make @new mandatory in the schema.

**Comment by lb42** [comment]
Closing for now.
