### ISSUE TITLE
Add profileDesc as optional child biblFull

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#533]
As per discussion on TEI-L on 2014-11-14, I suggest to add profileDesc as an optional child biblFull. There are two use cases on my side:
- documenting entries in the HAL system (see https://hal.inria.fr/hal-00762664v3/tei) with keywords and classification schemes
- documenting journal list with classification schemes
"Kevin Hawkins seemed in phase with this. I quote: I would support a proposal to add profileDesc as an optional child of biblFull.  Not only do you provide a user case for adding "various keywords and classifiers" to your bibliographic descriptions, but I can imagine descriptive and annotated bibliographies that include things like a UDC or Dewey class number or the language(s) of the work.  All of these would better fit in <profileDesc> than elsewhere in the current model of biblFull."

Original comment by: @laurentromary

**Comment by hcayless** [comment]
@sydb suggests changing the content model of biblFull to alternate either its current model or (fileDesc, profileDesc).

**Comment by sydb** [comment]
Oh dear. I started writing this reply during the Providence face-to-face, but never posted it.
Just to be explicit, I think the structure we are talking about is:
~~~~~
  (
    (
      (  titleStmt, editionStmt?, extent?, publicationStmt, seriesStmt?, notesStmt? ),
      sourceDesc*
    )
    |
    ( fileDesc, profileDesc )
  )
~~~~~
That is, an alternation between 
  a) the current contents of `<biblFull>,` and
  b) a `<fileDesc>` follwed by a `<profileDesc>`.

Note that there is a difference between the current content model of `<biblFull>` and the content model of `<fileDesc>`: the `<sourceDesc>` is required in `<fileDesc>` but not in `<biblFull>`. Thus the proposed new content puts a burden on he who wants to add a `<profileDesc>` to a `<biblFull>`: he has to add a `<sourceDesc>` (if not already there), too.

BTW, I don’t know why this discrepancy exists, but it has been around since P2, and to my knowledge is not discussed in the _Guidelines_ at all.
