### ISSUE TITLE
Give more structure to abstract

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#548]
The abstract element is particularly important for representing meta-data associated to scholarly works. Still, many disciplines have developed a tradition of reflecting the argument of a paper within a structured abstract. 

For instance see the attached screen shot where the abstract has two subsections with corresponding headings. 

We suggest to allow abstract to contain divs so that the preceding example could be represented as:

~~~~~~

<profileDesc>
   <abstract>
      <div>
         <head>Motivation:</head>
         <p>A number of available program packages determine the significant enrichments and/or depletions of GO categories among a class of genes of interest. Whereas a correct formulation of the problem leads to a single exact null distribution, these GO tools use a large variety of statistical tests whose denominations often do not clarify the underlying P-value computations.</p>
      </div> 
      <div>
         <head>Summary:</head>
         <p>We review the different formulations of the problem and the tests they lead to: the binomial, x 2 , equality of two probabilities, Fisher&apos;s exact and hypergeometric tests. We clarify the relationships existing between these tests, in particular the equivalence between the hypergeometric test and Fisher&apos;s exact test. We recall that the other tests are valid only for large samples, the test of equality of two probabilities and the x 2-test being equivalent. We discuss the appropriateness of one-and two-sided P-values, as well as some discreteness and conservatism issues.</p>
      </div> 
   </abstract>
</profileDesc>

We have two use cases for this currently: one is the back-office format for HAL, the French national open publication repository (yes, it does use the TEI for all content interchange) and the second is the Istex initiative (http://www.inist.fr/?ISTEX-51&lang=en) where data from publishers are ingested ni the context of a notional licence program.

Original comment by: @laurentromary

**Comment by lb42** [comment]
Council reviewed this and also question of what belongs inside &lt;front> 
Agreed that &lt;front> can contain &lt;div>s of any provenance i.e. both from original source and from elsewhere, irrespective of whether source is born digital.
Not agreed how to handle structure, or lack of it, within &lt;abstract> We could introduce new metadata-only division-like and block-level elements ("section", "para") with content models of (head?, (para|division)* ) and (model.restricted.phrase)* respectively. If it wasn;t for mixed-content problems, we could do without &lt;para>
We could add schematron rules to minimize impact of introducing &lt;div, or &lt;section.
We did not reach a firm conclusion.

**Comment by rloth** [comment]
Hello all.
In that case i'd suggest adding abstracts to the exemples of the guidelines' description for <front> element :
"(front matter) contains any prefatory matter (headers, ++abstracts++, title page, prefaces, dedications, etc.) found at the start of a document, before the main body"

More controversial suggestion: also perhaps consider renaming renaming the element "<abstract>" to "<metadescription>" or something like this.

Motivation: when i was trying to encode a scientific paper's abstract in TEI i naturally tried to type "TEI abstract" in the search engine (which is a perhaps dumb but probably very common guidelines browsing strategy)... of course it sent me directly to the abstract element, and not <front>...  
Reading this issue's history I now understand the explained difference between <abstract> tag as an encoder's addition in TEI council's perspective and "abstract" as a common sense word. It makes sense :+1:  but because of the tag's denomination it is (once again) slightly cryptic when coming from the librarian's world with a search engine query like "how to encode my abstract in TEI". Hence the suggested changes.

**Comment by laurentromary** [comment]
To answer Lou's comment, I like the idea of controlling the presence of div, p etc. in abstract by means of schematron rules. Since we have no other means to implement polymorphism, it looks like a reasonable choice.

**Comment by lb42** [comment]
The suggestion that we should make more explicit the idea that an abstract might appear in &lt;front> is helpful and worth following. The problem with how to help those who persist in wanting to put their highly structured abstract in the header remains: on the whole we would prefer to avoid polymorphism...

**Comment by lb42** [comment]
Have added an example of structured abstract to the front element spec, and revised wording of abstract spec in line with these suggestions. Schematron rules to be further considered, so leaving ticket open for now.

**Comment by laurentromary** [comment]
Just to answer @lb42 's previous comment. It is not a matte row persistence, but one of data pouring in from third party providers as part of their meta-data. If we want to acknowledge that the scientific article scenario is an important one, that's the way to proceed. Thanks for working on the schematron rules for controlling `<div>` and `<p>`.

**Comment by lb42** [comment]
Reviewed at FTF, and agreed to close for now.
