### ISSUE TITLE
Allow q/quote/cit in u

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#563]
In the context of the creation of a corpus of parliamentary debates, where we obviously use u for MP's statements (in UK and DE if you ask), we systematically need to encode quotes from a) other MPs and b) legal sources. The content model of u is unfortunately poor and allow none of the members of model.qLike. I could even imagining aligning u on p, but this may go too far at this stage...

Original comment by: @laurentromary

**Comment by martindholmes** [comment]
Council subgroup 2015-10-26: There seems a strong argument for making this macro.paraContent. That introduces a few questionable things, but it's simple and straightforward. It's clear that quotes appear in transcriptions of speech, and that they must be tagged. A u is closer to a p than anything lower-level.

**Comment by laurentromary** [comment]
This looks like a reasonable decision. Thanks

**Comment by martindholmes** [comment]
Council is reluctantly conceding that the requirement for `<quote>` is convincing, and will change the content model to macro.paraContent. However, some members of Council are uncomfortable with this because there is one strict understanding of the purpose of `<u>` which suggest that it should never be used for the kind of use-case on this ticket anyway; LB suggests that `<sp>` is more suitable, although others believe this is wrong.

**Comment by laurentromary** [comment]
which in turn would open a can of worms concerning the didascalic nature of sp (see http://www.theses.fr/2002PA040056)  whereas u has a more recording status. In the case of politicians, this could be debated...  ;-) I am open for an offline discussion, but thanks the council for this action taken.

**Comment by hcayless** [comment]
@emylonas to change content model of `<u>` to `macro.paraContent`.

**Comment by emylonas** [comment]
Closed with commit e71db58

**Comment by lb42** [comment]
Just for the record, I remain unconvinced of the wisdom of this change.
