### ISSUE TITLE
a grobid example

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#568]
The text of the standard does a really good job of showing examples of how to encode textually interesting pieces of text (for widely varying definitions of 'textually interesting').

What it perhaps does a less good job of is showing how to encode computationally interesting pieces of text.

I'd like to propose adding this example https://github.com/kermitt2/grobid/blob/master/grobid-trainer/resources/dataset/citation/corpus/0953-2048_24_7_075001.header-reference.xml , which is a short file from the grobid training corpus, along with a suitable covering comment to http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-listBibl.html. Maybe 

"The following <listBibl> is taken from the grobid training corpus, it shows a pair of citations to the same article in the journal Superconductor Science and Technology, illustrating the variety of order and presence of the elements within the <bibl>. Such variety is important because it avoids over-fitting the generated probabilistic model which grobid generates from the training data."

If there is general agreement, I can work up a patch.

cheers
stuart

Original comment by: @stuartyeates

**Comment by martindholmes** [comment]
There's been no response to my September 15 comment. At this point I believe we should close the ticket, because there's no benefit in taking an example from real-life if it (as it currently does) exemplifies practice we would not recommend. I must admit the value of the actual example escapes me too; exactly what is the value in showing that the same bibliography item can be encoded in slightly different ways using `<bibl>`? I'm sure if I read the grobid documentation I'll understand exactly how this works as part of the training corpus, but I don't believe it would be easy to explain in enough detail in the context of the Guidelines to make this a useful example for ordinary users. I think it would be confusing.

However, if the use of @type on `<biblScope>` can be replaced with @unit, and the page-range in the second example switched to the use of @from and @to, then I'd be happy to ask Stuart to write a short explanation (two or three sentences) and suggest where it should go in the Guidelines.

**Comment by laurentromary** [comment]
I don't have the feeling that there is a priority at this stage. We do have a lot of other things on our plate. Unless Stuart has a clear idea of what to do I would close the ticket.

**Comment by lb42** [comment]
subgroup recommends closure

**Comment by martindholmes** [comment]
Council closing wont-fix.
