### ISSUE TITLE
data.enumerated != valItem/@ident

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#624]
The value of `@ident` of ﹤valItem﹥, which is for “here is a value that belongs in an enumerated list”, is defined as xsd:NCName (via data.name). The datatype data.enumerated, which is for “put a value from an enumerated list here”, is defined as rng:string (via data.text).

It’s not clear to me what they should be (I’m leaning towards data.word), but they should match.

Original comment by: @sydb

**Comment by lb42** [comment]
The datatype of of valItem/@ident is teidata.text (thus permitting included white space); the datatype teidata.enumerated is teidata.word with some restrictions (thus not permitting included white space). This is so that you can define a valItem such as "sturm und drang"  and was a conscious design decision, afaicr. If we had wanted @ident to be the same, we'd have defined it as teidata.enumerated, but we didn't.  
(@peterstadler : valList is now permitted as a child of content; the discussion you reference above is way out of date)

Closing this, since I don't think there's any need for action and it's been sitting aroiund for over a year.  @sydb can always reopen if desired!
